### ISSUE TITLE
keep "plus" button in Script Window and show script name in tab header

### ISSUE THREAD

**Issue by kristynakitz** [AirtestProject/AirtestIDE#1]
1) we should keep "plus" button in Script Window to allow users to add more test scripts just by one click
![no_add_button](https://user-images.githubusercontent.com/35829963/35895315-dfdfc2dc-0bf1-11e8-860d-a8cf8c4565be.png)

2) tab header is not updated when creating new script with existing name and you answer "No" in pop-up dialog asking you to overwrite the file
![script tab header](https://user-images.githubusercontent.com/35829963/35895330-f3ffd61c-0bf1-11e8-819d-830eaec6f648.png)

**Comment by Meteorix** [comment]
fixed
