### ISSUE TITLE
"start_app" is not easy to find

### ISSUE THREAD

**Issue by nakhbari** [AirtestProject/AirtestIDE#10]
the first thing people want to do in a script is to launch their app. We should make this more visible.

1) Include `start_app` in the initial script
2) Like other command auto-complete the `start_app` method

**Comment by Whiteseeker** [comment]
Same for clear_app

**Comment by adolli** [comment]
We will add these 2 buttons at quick access panel with TOUCH/SWIPE together. And try to make auto-complete-list for apps which can be launched if possible.

**Comment by Whiteseeker** [comment]
I believe making a button for them is too much.
Adding them to the list of autocomplete command is probably a better user experience.

**Comment by Whiteseeker** [comment]
@nakhbari Here:
http://airtest.readthedocs.io/en/latest/all_module/airtest.core.android.android.html

**Comment by nakhbari** [comment]
@Whiteseeker This is great thanks! Maybe it's best to point them to the docs somewhere @adolli  what do you think?

**Comment by kristynakitz** [comment]
I'll put it there ...

**Comment by adolli** [comment]
In the IDE, global functions (here : http://airtest.readthedocs.io/en/latest/all_module/airtest.core.api.html) can be used directly. I think `start_app` and `stop_app` are often used just after `touch` and `swipe`.
