### ISSUE TITLE
使用夜神模拟器连接，出现了点击位置偏差

### ISSUE THREAD

**Issue by sakurua5** [AirtestProject/AirtestIDE#1002]
当模拟器设置为“平板”模式时，使用touch（）识图点击，最终被点击的位置与返回来的坐标值有不小的偏差；模拟器设置为“手机”模式则没有这个问题。是每个模拟器都会有这种情况吗？

**Comment by fyypll** [comment]
反正目前mumu模拟器会出现点击偏差，解决办法是用老版本...

**Comment by yimelia** [comment]
更新至最新版本再试试
