### ISSUE TITLE
夜神模拟器android 9 版本连接黑屏

### ISSUE THREAD

**Issue by desolution025** [AirtestProject/AirtestIDE#1003]
**详细描述问题bug：**
测试了夜神模拟器7的android 9版本和夜神模拟器9测试版连接后都黑屏，只有32位的android 7是正常的

**复现步骤：**
使用夜神多开器建立安卓9实例运行连接
![image](https://user-images.githubusercontent.com/69784210/132939107-98ed98dd-b415-402f-ae46-4927199cee5a.png)

**操作系统:** `Windows10 64bit`

**设备信息:**
 - 手机型号: 夜神模拟器9
 - Android系统版本号: Android 9.0

**其他相关信息补充**
已经尝试勾选javacap和adb orientation
- AirtestIDE版本号：1.2.11

**截屏**
![image](https://user-images.githubusercontent.com/69784210/132939238-00cfa739-7885-47bd-8853-a077923ae968.png)

**Comment by grayguest** [comment]
摸索了一下android7 64可以，和端口有关系
android7 64   62025

**Comment by yimelia** [comment]
用最新版本的IDE

**Comment by grayguest** [comment]
没适配nox。
