### ISSUE TITLE
Airtest IDE使用问题

### ISSUE THREAD

**Issue by bbll29** [AirtestProject/AirtestIDE#1005]
你好，我有两个问题请教：
1、我看到官方教程里还有一个脱离Airtest IDE使用pycharm的讲解，是只用Airtest IDE的话，会不够用吗？
2、如果使用Airtest IDE的话，本地的.air文件有办法和git仓库绑定吗？如果能绑定上传git，可以方便其它的同事开发。我目前在IDE中没有找到git相关的东西，比较疑惑
期待你的答复，谢谢

**Comment by yimelia** [comment]
1. airtest-ide只是辅助截图和辅助查看poco抓取到的UI树信息用的，如果是要写更复杂的脚本内容，推荐用pycharm这样专业的Python IDE会更好
2. AirtestIDE目前暂时是没有针对git功能做更多适配的，如果希望有更多git的深度功能的话，还是推荐用pycharm或者vscode
