### ISSUE TITLE
git绑定

### ISSUE THREAD

**Issue by bbll29** [AirtestProject/AirtestIDE#1006]
:bulb:**相关项目:** AirtestIDE

**标题:** [问题咨询]git绑定

**AirtestIDE版本:** 1.2.11

**未使用本地Pyhton环境运行脚本**

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;AirTest IDE能和git进行绑定吗？这样方便和同事进行协同开发，谢谢

**相关截图:**
无

**报错Log:**
```
无
```

**连接设备信息:**
无

**提供最小可复现此BUG的代码:**
```
无
```

**Comment by yimelia** [comment]
目前暂时没有相关的支持
