### ISSUE TITLE
airtestIDE链接mumu模拟器鼠标位置偏移 在(0,0)位置上正确

### ISSUE THREAD

**Issue by WINGSIGOD** [AirtestProject/AirtestIDE#1010]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
使用mumu模拟器链接会产生偏移

**复现步骤：**

**python 版本:airtest未指定python版本 电脑自带3.6

**操作系统:** `Windows710 64bit`

**手机设备信息:**
 - 手机型号:mumu模拟器
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.11

**截屏**
![image](https://user-images.githubusercontent.com/19849392/134795300-fb1a190d-c28b-4521-8b91-0d1015375937.png)
![image](https://user-images.githubusercontent.com/19849392/134795307-f6f636ee-8e40-4cbc-b767-2f49b68d1ffb.png)

**Comment by kslz** [comment]
我也复现这个问题了 目前退回到1.2.10版本就好了

**Comment by WINGSIGOD** [comment]
> 我也复现这个问题了 目前退回到1.2.10版本就好了

好 我试试

**Comment by yimelia** [comment]
这个是1.2.11的问题，现在更新至最新版本即可
