### ISSUE TITLE
连接多台设备时，无法指定设备执行脚本，只能在第一个连接的手机上执行脚本

### ISSUE THREAD

**Issue by 15834140568** [AirtestProject/AirtestIDE#1017]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
    连接多台设备时，无法指定设备执行脚本，只能在第一个连接的手机上执行脚本

**复现步骤：**

     1.移动设备窗口显示已连接>1台设备
     2.脚本 
       devices1=connect_device('android:///f9bcc6da')#设备为第二台连接序列号
        # 连接手机
       poco = AndroidUiautomationPoco(device=devices1,use_airtest_input=True, screenshot_each_action=False)
      init_device("Android")

    # 启动app
     start_app("com.hnquxing.crazyidiom")
    3。点击执行
    4.在第二台设备启动了pocoservice 服务，但是启动的app却是第一台设备的app
**python 版本:** `python3.8`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号: 华为 p20
 - Android系统版本号:  Android 10
 

- AirtestIDE版本号：
   1.2.12
**截屏**
   
![image](https://user-images.githubusercontent.com/55582900/138388912-6858ccd3-31e1-4272-ab78-2d8b9ecf5c39.png)

**Comment by yimelia** [comment]
查询一下api有一个set_current接口，可以在同时传入多个`--device`的前提下切换到别的手机
