### ISSUE TITLE
测试报告图片中 部分目标图片框选坐标不准。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#102]
版本：v0.0.14-v0.0.16
![default](https://user-images.githubusercontent.com/17442044/39849974-9d5056d2-5441-11e8-8b18-37ca95e0950b.png)

**Comment by zzldjkzxf** [comment]
@StandOutstar 请问这是用selenium生成的报告吗？是在mac下使用的吗？

**Comment by rockywhisper** [comment]
@StandOutstar  是使用的什么浏览器打开的报告呢？

**Comment by StandOutstar** [comment]
chrome浏览器，windows系统下，这是app的测试报告中的。

**Comment by zzldjkzxf** [comment]
@StandOutstar  可以给更详细的bug描述吗，是用的poco对吧，在什么应用下，执行的什么命令呢

**Comment by rockywhisper** [comment]
@StandOutstar  Hi，你好.
官网上 [最新版本](http://airtest.netease.com/changelog.html) 已经解决了这个问题哈。
