### ISSUE TITLE
一个bug和一个建议

### ISSUE THREAD

**Issue by bertestzhan** [AirtestProject/AirtestIDE#103]
1、bug：无法控制IDE日志的等级；
![image](https://user-images.githubusercontent.com/30916789/39864004-ed355d76-547a-11e8-9057-5475f4692607.png)

2、建议：希望在IDE中集成console，方便开发。

**Comment by yimelia** [comment]
@bertestzhan 你好，虽然在脚本中可以设置logger的级别为ERROR，但是实际上需要等代码跑到脚本的这一行时，设置才能生效，log窗口中打出来的两条adb相关的log是airtest初始化时连接设备时的log，此时脚本尚未开始运行，因此还是显示出了log内容，未来我们会考虑在log窗口中加入log级别的筛选功能，方便调试和查看。

**Comment by bertestzhan** [comment]
@yimelia  了解。

那是否方便在IDE中集成console

**Comment by yimelia** [comment]
@bertestzhan 感谢你的建议，我们目前有提供了一个鼠标右键选中代码段，单独运行这段代码的调试功能，但是比较简单。在IDE中集成console的这个建议很好，我们在后续的版本开发中根据排期考虑是否加入这个功能，感谢你的建议~

**Comment by rockywhisper** [comment]
@bertestzhan  你好，[新版IDE](http://airtest.netease.com) 内已经在log窗内可以设置输出log的筛选层级了.

这个issue暂时关闭了哈 :-)
