### ISSUE TITLE
Facing "WebDriverAgentRunner-Runner[6540:2683756] -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2823c6b00" error after iproxy connected

### ISSUE THREAD

**Issue by Christiansmlee** [AirtestProject/AirtestIDE#1039]
Remove any following parts if does not have details about

**Describe the bug**
Facing "WebDriverAgentRunner-Runner[6540:2683756] -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2823c6b00" error after iproxy connected

**Screenshots**
![image](https://user-images.githubusercontent.com/99716221/154014847-db08f213-8be1-46e5-951c-77403884ce24.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Xcode to run WebDriverAgent
![image](https://user-images.githubusercontent.com/99716221/154015462-0ebb262a-8697-4996-a93d-8d24b6a16141.png)
2. Click Product -> Destination -> iOS Device -> iPad
![image](https://user-images.githubusercontent.com/99716221/154015712-5bfbf219-757b-4615-84a4-18e98c4d905d.png)
3. Click Product -> Test
![image](https://user-images.githubusercontent.com/99716221/154016086-019e72dd-f01d-48a4-80ab-001d9f2bd92d.png)
![image](https://user-images.githubusercontent.com/99716221/154016246-db4bf764-66e3-43fb-8713-32524a3de3c1.png)
4. Open Airtest IDE
![image](https://user-images.githubusercontent.com/99716221/154016552-af0c60d5-e1a0-43d3-bbc1-a6f140a96215.png)
5. Open Terminal and input iproxy 8100 8100. Then waiting for connection.
6. Click Connect in Airtest. Then the error happened.
![image](https://user-images.githubusercontent.com/99716221/154017120-8590b251-44c3-43c1-bf65-19c35bc16f02.png)

**Expected behaviour**
Can connect to iPad without error.

**AirtestIDE version:** `1.2.13`

**Platform:** `MacOS Monterey version 12.1`

**Smartphone (please complete the following information):**
1. Device: iPad 7th generation
OS: 15.1
2. Device: iPhone 11
OS: 15.1

**Additional context**

**Comment by fishfish-yu** [comment]
ios-tagent不支持iOS15.1，可以换appium最新的wda试试
