### ISSUE TITLE
**连接手机后，设备窗显示黑屏，手机显示正常**

### ISSUE THREAD

**Issue by SkyJQ** [AirtestProject/AirtestIDE#1048]
**详细描述问题bug：**
环境：win10系统，python3.8，airtest版本1.2.12
手机连接airtest后，设备窗显示黑屏，无法进行元素定位和代码执行
（说明：在手机连接airtest时，手机端出现一个被禁用提示，该提示在之后一直未能找到）

**复现步骤：**
1、手机连接USB后，在移动设备连接 窗口中 点击connect
2、连接成功后，设备窗显示黑屏，只有下方的手机系统功能区按钮可用（锁屏、首页……），手机显示正常

**python 版本:** 
python 3.8
**操作系统:** 
win10 64

**手机设备信息:**
 - 手机型号:MI6
 - Android系统版本号: Android 9

**其他相关信息补充**

- AirtestIDE版本号：1.2.12

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![2](https://user-images.githubusercontent.com/59728398/160047347-c861e9f9-ea02-460c-a323-daccc88999a7.png)
![1](https://user-images.githubusercontent.com/59728398/160047367-0350748b-c452-4950-88b6-87fdae92cb5d.png)

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/3_android_faq/#1_2

设置完之后，可以点connect按钮下拉菜单的最后一个功能 init device初始化一下设备

**Comment by SkyJQ** [comment]
> https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/3_android_faq/#1_2
> 
> 设置完之后，可以点connect按钮下拉菜单的最后一个功能 init device初始化一下设备

搞定了，多谢。
没用过小米，丢大脸了 = =、
