### ISSUE TITLE
无法连接手机，求回复，急急急急急急急急！！！

### ISSUE THREAD

**Issue by kopk12** [AirtestProject/AirtestIDE#1052]
![image](https://user-images.githubusercontent.com/104412941/165228090-84eadc1b-16ab-4989-a9b7-2e6275fa0b05.png)

![image](https://user-images.githubusercontent.com/104412941/165228328-c1e94ef7-d856-4cf7-b0b6-1bf0eadc5f54.png)

![image](https://user-images.githubusercontent.com/104412941/165228355-1383bc4e-e950-4a0d-922b-05c93014307c.png)

![image](https://user-images.githubusercontent.com/104412941/165229364-6c947471-3c7c-44d6-8519-165c9d974a2a.png)

手机型号：OPPOReno6Pro5G
ColorOS版本：v12.1
Android版本：12
处理器：天玑1200八核

**Comment by kopk12** [comment]
python是3.8.0版本

**Comment by kopk12** [comment]
AirtestIDE版本是1.2.13

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/3_android_faq/#5oppo
