### ISSUE TITLE
在Mac上使用AirtestIDE连接Iphone真机非常的卡顿。

### ISSUE THREAD

**Issue by qskld** [AirtestProject/AirtestIDE#1055]
:bulb:**相关项目:** AirtestIDE

**标题:** [问题咨询]在Mac上使用AirtestIDE连接Iphone真机非常的卡顿。

**AirtestIDE版本:** 1.2.13

**未使用本地Pyhton环境运行脚本**

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;1.在Mac电脑上，使用AirtestIDE连接Iphone真机，在设备窗操作，非常的卡顿。
2.在Mac电脑上，使用AirtestIDE连接Iphone真机，启动任意一款游戏，由竖屏变为横屏后，到达游戏登录界面，无法在设备窗正常进行点击操作，表上非常像出现了错位。
3.同样的，在widnows电脑上，使用AirtestIDE连接Android真机，不卡顿，游戏启动后，竖屏变为横屏，设备窗的点击操作一切正常。
4.因为，该问题不是在特定设备下出现的。所以，不需要截图。

**相关截图:**
无

**报错Log:**
```
不涉及代码相关，仅是设备窗连接真机，因此没有LOG。
```

**连接设备信息:**
设备类型 | 设备型号 | 系统版本号 | apk名称/下载链接 | 使用的wda版本 | wda更新到最新
------------ | ------------- | ------------- | ------------- | -------------  | -------------
iOS | iPhone12 | iOS14.6 | 任意一款手机游戏 | iOS-Tagent | 否

**提供最小可复现此BUG的代码:**
```
不涉及代码相关，仅是设备窗连接真机。
```

**Comment by ferdyzhang** [comment]
我也有同样的问题，不知道是不是Mac的问题

**Comment by yimelia** [comment]
下载 1.2.14版本的AirtestIDE
然后根据此文档，更新到最新版本的ios-tagent https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/4_ios_connection/
新版本在ios上体验有了巨大的提升，欢迎试用

**Comment by qskld** [comment]
嗯嗯，真的非常感谢，你的回复让我有了巨大的学习动力，我也在实时关注咱们官网的公告，确实看到了这条宝贵的信息呢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 上午10:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AirtestProject/AirtestIDE] 在Mac上使用AirtestIDE连接Iphone真机非常的卡顿。 (Issue #1055)





 
下载 1.2.14版本的AirtestIDE
 然后根据此文档，更新到最新版本的ios-tagent https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/4_ios_connection/
 新版本在ios上体验有了巨大的提升，欢迎试用

**Comment by qskld** [comment]
官方已经给出了最新版本的AirtestIDE，本次更新针对这个问题有了优化，你可以试试。
下载 1.2.14版本的AirtestIDE
然后根据此文档，更新到最新版本的ios-tagent&nbsp;https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/4_ios_connection/
新版本在ios上体验有了巨大的提升




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月15日(星期三) 晚上9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AirtestProject/AirtestIDE] 在Mac上使用AirtestIDE连接Iphone真机非常的卡顿。 (Issue #1055)





 
我也有同样的问题，不知道是不是Mac的问题
