### ISSUE TITLE
连接电脑上的火狐浏览器，无法输入中文，输入过快时软件卡死

### ISSUE THREAD

**Issue by hagyao520** [AirtestProject/AirtestIDE#106]

**Comment by rockywhisper** [comment]
@hagyao520  

Hi，你好，可以使用[最新版本的IDE](http://airtest.netease.com/changelog.html)哈，验证没问题的  :-)

![airtestide-firefox_chinese_input](https://user-images.githubusercontent.com/8188879/41974894-cd4d7920-7a4b-11e8-8819-01bccdb22590.gif)
