### ISSUE TITLE
import schedule

### ISSUE THREAD

**Issue by ferasfm** [AirtestProject/AirtestIDE#1063]
Hello it is great to find this program and thank you first
I have a question if you want to add an import schedule
Does this work, and if the answer is no, how can I add this package to make it compatible with your program?
airtest
I do not want to download it from Python, but rather it should be within the internal system of the program airtestID

**Comment by ferasfm** [comment]
?????????????

**Comment by yimelia** [comment]
1. https://airtest.doc.io.netease.com/en/IDEdocs/run_script/1_useCommand_runScript/#deploy-the-python-environment run in the python environment
2. or run in AirtestIDE with the python environment https://airtest.doc.io.netease.com/en/IDEdocs/settings/1_ide_settings/#run-the-script-using-the-native-python-environment-trial

**Comment by ferasfm** [comment]
Thank you for your help.
