### ISSUE TITLE
使用macos安装好IDE，红米可以识别到设备，但连接失败

### ISSUE THREAD

**Issue by alicechen0302** [AirtestProject/AirtestIDE#107]
红米Note4和红米Note2都可以识别到设备，但是connect提示Failed to execute ADB commands, please read [Docs]无法连接

**Comment by rockywhisper** [comment]
@alicechen0302  请问是否可以看下AirtestIDE的console窗口的报错截图？
另外，可看下设备内的开发者选项内的部分设置是否勾选： [参考文档](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id9)

**Comment by rockywhisper** [comment]
@alicechen0302  你好，因为红米Note2和红米Note4都在我们的[测试列表](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/6_device_connection/5_android_support.html)内，经验证是没有问题的。

本issue就暂时关闭了哈。
