### ISSUE TITLE
AirTestIDE minicap 不支持 Android 13 (android-33)

### ISSUE THREAD

**Issue by LiuJQ** [AirtestProject/AirtestIDE#1089]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
小米13（MIUI 14） adb连接上后画面只能通过 adb screenshot 模式呈现

IDE出错日志：
```raw
[15:55:10][ERROR]<airtest.core.android.cap_methods.screen_proxy> b"adb: error: cannot stat 'D:\\AirtestIDE\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-13/arm64-v8a/minicap.so': No such file or directory\r\n"
```
通过 adb 查看 MIUI 14 的 Android 版本是 33
```shell
adb shell getprop ro.build.version.sdk
33
```

查看AirTest IDE目录，`AirtestIDE\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs`也没有android-13

查看[minicap](https://github.com/openstf/minicap)最高只编译到 android-29

**复现步骤：**
插上小米13（MIUI 14），通过AirTest IDE adb连接上

**python 版本:** `python3.11.1`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号: 小米13
 - Android系统版本号: [e.g. Android 8.1] Android 13
 - MIUI版本：14

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：v1.2.14

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/3191942/215314366-280e5d14-ceaf-4e19-a122-22574cda1d06.png)

**Comment by MarkTina** [comment]
兄弟你都发现问题了，离解决问题不就差一步了么，github 上搜索一下 code 关键词，不是能找到编译好的么。
https://github.com/varundtsfi/Android12Support_withso/tree/main/aosp/android-33

**Comment by yimelia** [comment]
直接更新最新版本airtest即可
