### ISSUE TITLE
win7下脚本编辑器显示问题

### ISSUE THREAD

**Issue by Kevinchenzero** [AirtestProject/AirtestIDE#109]
脚本编辑器部分，显示为黑屏，没有任何代码。
但是可以输入，输入结果可以在.air文件夹得.py文件中查看。
这个问题有解决方法么？

**Comment by yimelia** [comment]
@Kevinchenzero 你好，这个问题比较罕见，能不能发一张打开IDE后那个黑色命令行窗口里的log截图呢？以及你的电脑环境是否为断网等特殊状态下？

**Comment by yimelia** [comment]
最新的版本已经升级了，使用了另外一种方式来显示编辑器，可以尝试一下看是否问题依旧

**Comment by leaf-wh** [comment]
我昨天下的版本在笔记本上也是同样的问题啊
![无标题](https://user-images.githubusercontent.com/56475858/66700932-fa942b80-ed28-11e9-9136-003621b50135.png)
就是脚本编辑窗里其实有文字，但是显示不出来啊

**Comment by leaf-wh** [comment]
附命令行截图
![image](https://user-images.githubusercontent.com/56475858/66700954-3dee9a00-ed29-11e9-8e89-307dec7e8818.png)

**Comment by yimelia** [comment]
@leaf-wh 
在部分机器上可能由于显卡兼容性问题，导致无法正确启动，或脚本编辑窗口无法编辑，可以双击IDE目录下的`兼容模式启动.bat`文件来启动

**Comment by leaf-wh** [comment]
我试了下，还是一样的黑屏…我笔记本确实是集成显卡，我先去看看显卡有没有新版本驱动吧
