### ISSUE TITLE
无法给通过 airtest IDE 内置的python 环境安装【psycopg2-binary-2.9.6】，便于通过它，访问Postgresql数据库。

### ISSUE THREAD

**Issue by brianlaibaoqin** [AirtestProject/AirtestIDE#1111]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**详细描述问题bug：**

1、想用airtest IDE 内置的环境，安装psycopg2 ，便于通过它，访问Postgresql数据库。网上找了一些方法【pymysql模块，pip安装好以后直接在site-packages里：复制文件夹pymysql文件夹到airtest IDE的  XX\AirtestIDE-win-1.2.15\AirtestIDE,里就可以用来了】都不能用。

2、有什么方式在airtest IDE 内置的环境 ，访问Postgresql数据库？

**Comment by yimelia** [comment]
可以用你本地的python环境来运行，参考文档：https://airtest.doc.io.netease.com/IDEdocs/3.4run_script/0_run_script/#4
