### ISSUE TITLE
ImportError: No module named ***** apppear after running .air file from bat command

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/AirtestIDE#112]
I am using following format in .bat file
```
**********************
@echo off

C:\AirtestIDE\AirtestIDE runner "PATH OF .air FILE"  --device Android://"DEVICE ID" --log "PATH FOR LOG FILE"

C:\AirtestIDE\AirtestIDE reporter "PATH OF .air FILE" --log_root "PATH OF LOG FILE\log" --outfile "PATH OF HTML LOG FILE\log.html" --static_root "C:\AirtestIDE\airtest\report" --lang en

@pause
***************
```
for example

I added openpyxl in pip list to generate test result in excel format.
When I run my program in Airtest IDE it working fine and showing expected result but same file shows "import error "after running .air file in bat file

Tell me
How to add path for third party python libraries in airtest
with example will be great help

I already add the python path in Option >> setting >> add python sys path "[r'C:\Python27\Lib\site-packages']" in airtest

**Comment by Meteorix** [comment]
You can do it in 2 different ways:
1. add python path in your test script
```
import sys
sys.path.append("xxxx")
```

2. just use airtest python library from command line instead of AirtestIDE, reference [here](https://github.com/AirtestProject/Airtest#running-air-from-cli)

**Comment by SUDARSHANCHAUDHARI** [comment]
Hello Meteorix,

Thanl you very for much the help.

It is working (I used second link) now.

******************
@echo off

python -m airtest run "PATH OF .air DIR"  --device Android://DEVICE ID --log "LOG PATH"

python -m airtest report "PATH OF .air DIR" --log_root "LOG PATH" --outfile "PATH OF LOG HTML FILE" --static_root "C:\AirtestIDE\airtest\report" --lang en

@pause

*********************

**Comment by Meteorix** [comment]
Good to hear that :)
