### ISSUE TITLE
Need to allow to disable debug logging

### ISSUE THREAD

**Issue by TimurNurlygayanov** [AirtestProject/AirtestIDE#113]
During the tests debugging I want to insert my own "print" commands and print important variables to track their values.

But now Airtest generating a lot of very verbose debugging logs, like:
```
[04:55:15][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 713b9a280504 forward --remove tcp:18877
```
and in the result I can't find my own prints.

I want to disable default debug level of logging, to skip all debug Airtest messages from the output.

**Comment by Meteorix** [comment]
Thanks for the feedback. We will add a logging filter in IDE latter.

For now, you can set it in your script

```
import logging
logging.getLogger("airtest").setLevel(logging.WARNING)
```

**Comment by TimurNurlygayanov** [comment]
Thank you!
