### ISSUE TITLE
Script run doubts

### ISSUE THREAD

**Issue by renbardela** [AirtestProject/AirtestIDE#114]
Hi, 

I'm a QA at a games studios and AirtestIDE is really helping me, but I sitill have some doubts:

1) Is it possible to start the script from a certain step or I always must start at the first step?
2) There's a way to execute a lot of scripts in a row? For example: as soon as a script ends another one begins (diferent files).

Hope someone can help me.

Best regards,
Renato

**Comment by TimurNurlygayanov** [comment]
The way how you can do this - just open Python file in another IDE, like PyCharm, and use PyTest framework to run many tests one-by-one.

**Comment by Meteorix** [comment]
@renbardela 

1. now you can `Run selected` code with the latest version of IDE
![image](https://user-images.githubusercontent.com/3805278/40274107-82d2cfac-5c01-11e8-89ef-47f4d663a21e.png)

2. as @TimurNurlygayanov suggested, you can use any python unittest framework to do that.
Or, a simpler way, you can write a `.bat` script to to run tests without starting IDE itself. IDE provides [command line usage](http://airtest.netease.com/tutorial/Tutorial.html#Command-line-interface).

But if you're familiar with python and programming, @TimurNurlygayanov 's way is recommended. It will be more extensible. You can then use continuous integration with Jenkins.

**Comment by renbardela** [comment]
@TimurNurlygayanov and @Meteorix 

Much thanks for the answers. I'm not so familiar with python, but I'll learn in order to help me testing.

If I have any more doubts I'll ask again.
