### ISSUE TITLE
APP 输入框，输入和删除字符都响应很慢

### ISSUE THREAD

**Issue by Swady1122** [AirtestProject/AirtestIDE#116]
步骤：
输入框已有字符：123456789   现删除原有字符，输入222333
结果：
响应速度很慢
无法全选文本

**Comment by rockywhisper** [comment]
@Swady1122  你好，删除字符的指令可参考 [keyevent按键码文档说明](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/5_api_faq.html#keyevent)  。

其中，对安卓设备执行Keyevent时，`keyevent(KEY_NAME)`执行的是`adb shell input keyevent KEY_NAME`。 [KEYNAME参考链接](https://developer.android.com/reference/android/view/KeyEvent)

响应速度取决于`adb shell input keyevent xxx`的速度。

SelectAll可能需要自己调研下有没有相关指令，脚本内可以使用`device().shell("SHELL_COMMAND")`执行shell指令。

**Comment by rockywhisper** [comment]
@Swady1122  这个issue暂时关闭了哈
