### ISSUE TITLE
AMD显卡崩溃的问题什么时候能解决啊

### ISSUE THREAD

**Issue by 541347048** [AirtestProject/AirtestIDE#117]
AMD显卡崩溃的问题什么时候能解决啊

**Comment by rockywhisper** [comment]
@541347048  你好，抱歉耽误你使用了。

开发组近期在全力准备稳定大版本，预计在6月中旬放出。预计该版本将会对显卡崩溃这类系统兼容性问题统一修复。

**Comment by 541347048** [comment]
已经到中旬拉  啥时候能放出来啊

**Comment by rockywhisper** [comment]
@541347048  Hi, 新版本已经发布，下载链接详见： http://airtest.netease.com/changelog.html

如果遇到问题还请及时反馈，感谢。 : )
