### ISSUE TITLE
Win10 IDE Pico窗口选择Unity后闪退

### ISSUE THREAD

**Issue by iamlyc** [AirtestProject/AirtestIDE#118]
Win10 IDE Pico窗口选择Unity后闪退，报错如图：
![image](https://user-images.githubusercontent.com/13329407/40484012-a4ba7cf8-5f8c-11e8-831c-6bfbbcfc36d8.png)

**Comment by zzldjkzxf** [comment]
@iamlyc 请问你是连接的什么应用呢？ 这个应该是生成poco tree的时候报错了

**Comment by iamlyc** [comment]
@zzldjkzxf ,Unity手游，Unity版本5.6.5f1

**Comment by iamlyc** [comment]
@zzldjkzxf ，偶现的，但是一旦出现，需要切换游戏场景之后才不崩，不然就一直崩

**Comment by rockywhisper** [comment]
@iamlyc 大概知道哪里的问题了，下个版本会修复下哈 :-)

**Comment by rockywhisper** [comment]
@iamlyc  Hi，我们今天放出了稳定的预览版，下载链接： http://airtest.netease.com/changelog.html

这个问题应该OK了，欢迎试用。 : )
