### ISSUE TITLE
调用封装的UI元素，“poco("android.widget.ScrollView").child("android.view.ViewGroup")[6].child("android.view.ViewGroup")"”，提示“list index out of range ”

### ISSUE THREAD

**Issue by yinchunjun** [AirtestProject/AirtestIDE#119]
![image](https://user-images.githubusercontent.com/39696609/40610835-74dd5b28-62a6-11e8-9815-b4231478b462.png)
![image](https://user-images.githubusercontent.com/39696609/40610968-12ba01de-62a7-11e8-9a2f-4c7a06f684ac.png)
使用上述方法，提示出错；
![image](https://user-images.githubusercontent.com/39696609/40610996-2fe787b8-62a7-11e8-887d-2af4bfcfbafd.png)
如果调用不包含【X】格式的UI，则能正常调用

**Comment by Meteorix** [comment]
@yinchunjun 这个poco语句写的太长了，如果界面稍微出现变化就很容易出错，建议按UI层级自行改为更合理的selector

**Comment by yinchunjun** [comment]
@Meteorix 谢谢，有试过短的poco语句，但是只要poco语句里面有poco.[1],这种结构的，封装后的.py 文件在case里面import的这一步，就报list index out of range 的错；这是不是跟界面界面没什么关系呢，毕竟这只是import它，还没有正式用到；

**Comment by Meteorix** [comment]
@yinchunjun 确认了一下问题，只要用[1]这样的写法，就是会在import的时候去找，我们看看怎么解决

**Comment by Meteorix** [comment]
@yinchunjun 建议先用其他方式替换掉用`[1]`的selector，绕过这个问题。后续我们会修复`[1]`的执行时机

**Comment by yinchunjun** [comment]
好的，如果后面修复了的话，麻烦在这告诉我一下哦~

**Comment by adolli** [comment]
@yinchunjun 我们现在的下标selector是按照UI的空间排布来求值的，当使用下标selector时会立即计算同组所有UI的属性，所以在你的模块里这样写就会报错。如果你需要保存ui对象，可以用下面这种方式，在需要真正使用时才进行求值。

file1.py
```python
def my_ui():
    return poco('xxx').child('yyy')[1]
```

file2.py
```python
from file1 import my_ui
my_ui().click()
```

**Comment by rockywhisper** [comment]
@yinchunjun  Hi，这个issue暂时关闭了哈，请参照楼上同学的做法试下。

有任何问题欢迎随时反馈 :-)
