### ISSUE TITLE
cannot connect to emulator// the emulator can be discovered but cannot connect to

### ISSUE THREAD

**Issue by duanly** [AirtestProject/AirtestIDE#12]

**Comment by adolli** [comment]
Which emulator are u using?

**Comment by duanly** [comment]
The AVD is Galaxy Nexus API P; Resolution 720 * 1280.






--

祝好,
王冬华


At 2018-03-12 16:46:42, "adolli" <notifications@github.com> wrote:


Which emulator are u using?

**Comment by adolli** [comment]
The emulator is not available currently, sorry about this. Maybe future updates will support. You can treat the emulator window as a normal windows APP. Then interact with the emulator using click and swipe.

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/AirtestIDE/issues/16   duplucated here

@rockywhisper  we need to write a tutorial for android emulator.

**Comment by rockywhisper** [comment]
OK, we‘ll write provide one later.

**Comment by duanly** [comment]
Thanks！


| |
Alex(Donghua) Wang
邮箱：alex_wang@126.com
|

签名由 网易邮箱大师 定制

On 03/21/2018 12:06, 王建军 wrote:

OK, we‘ll write provide one later.

**Comment by rockywhisper** [comment]
@duanly  Hi, we have released [AirtestIDE with Emulator-support](http://airtest.netease.com/changelog.html).

[How to  connect an emulator](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html)

**Comment by Sunny1000** [comment]
There is problem connecting to Android 8.0 (API26) Emulator with Airtest IDE v0.1.4 to v0.1.6.
Return: "airtest ADB指令执行失败 ...", Emulator is shown in the Device list, but fail to connect.

But I can connect to Android 6.0 (API23) Emulator. 

Is Android 7 and 8 supported now?

**Comment by wolvenworks** [comment]
http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html

this link is dead (404). please update with functional link to how to link airtest to emulator.

**Comment by yimelia** [comment]
@wolvenworks 
https://github.com/AirtestProject/Airtest/issues/439
