### ISSUE TITLE
用命令跑脚本时，报告生成问题 bug

### ISSUE THREAD

**Issue by IvyyLu** [AirtestProject/AirtestIDE#121]
问题一、用下airtest run命令直接跑脚本，如果不指定 --log参数，无法生成log.txt文件（ps：指定LOG_DIR和脚本所在目录都没有，但，运行截图是有保存在LOG_DIR目录下的）
airtest run F:\wwddzAutoTest\src\test.air --device Android://127.0.0.1:5037/d21ac3d

![image](https://user-images.githubusercontent.com/39722697/40697705-1a889724-63fe-11e8-863c-f3fc8b86f307.png)

问题二、如果一个.air目录下放了多个脚本文件，与目录名字不一致的文件无法用 airtest run命令跑。。。。用 python yy.py倒是可以运行的，但无法生成 log.txt ，不知是否同问题一是同一缘由，没指定log目录路径导致。。。。期望解决
![image](https://user-images.githubusercontent.com/39722697/40697740-4495ef6c-63fe-11e8-911b-a8f67836ab52.png)

**Comment by IvyyLu** [comment]
自己解决了，，，，，，，在脚本中加句：

set_logdir(r"F:/wwddzAutoTest/src/test.air/log")

用python x.py方式跑也有log

**Comment by Meteorix** [comment]
@IvyyLu 厉害~

**Comment by Meteorix** [comment]
对于API有什么建议也可以在Airtest仓库中提issue
