### ISSUE TITLE
ide 如何使用自己修改后的airtest.core.cv

### ISSUE THREAD

**Issue by youguiyan** [AirtestProject/AirtestIDE#122]
尝试了设置中的pythonpath, 设置PYTHONPATH环境变量, sys.path.insert(0, xxx)都无法使用自己修改的airetest.aircv.sift
尝试在air中py中打印api.__file__, 发现是/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/api.pyc
, 这个貌似是直接使用py2app 编译到AirtestIDE中的

**Comment by Meteorix** [comment]
IDE本身依赖airtest，所以import优先级最高，你试试在脚本中动态修改对象:
```
import your_cv
from airtest import core
core.cv = your_cv
#可能还需要设置用到cv的地方
core.api.function = you_cv.function

```

**Comment by rockywhisper** [comment]
@youguiyan  你好，[最新版的IDE](http://airtest.netease.com/changelog.html) 里增加了本地python环境配置。

要使用本地修改的airtest代码：
 - 先把本地修改的airtest装入本地python环境；
 - 在IDE的配置界面内，配置本地python环境，运行即可。
