### ISSUE TITLE
使用命令行运行测试python脚本出现如下错误

### ISSUE THREAD

**Issue by tanhuaping** [AirtestProject/AirtestIDE#124]
![1527746889 1](https://user-images.githubusercontent.com/17636034/40764616-52411572-64dc-11e8-962f-a6fb18334f38.jpg)

**Comment by Meteorix** [comment]
请提供完整的命令行截图

**Comment by tanhuaping** [comment]
[01:59:47][DEBUG]<airtest.core.android.adb> C:\Python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.ex
e -P 5037 -s 127.0.0.1:62001 forward --remove tcp:16381
<LoopThread(simplerpc_update, started daemon 93020)> finished
'touch_method' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by tanhuaping** [comment]
![1527747124 1](https://user-images.githubusercontent.com/17636034/40764712-a8e8f11a-64dc-11e8-8ae3-7f33828fa4ae.png)

**Comment by Meteorix** [comment]
--device "后面一串打上引号，这是windows cmd的解析问题"

**Comment by tanhuaping** [comment]
加上引号之后解决了 ths
