### ISSUE TITLE
text输入有问题，无法正确输入

### ISSUE THREAD

**Issue by bs111** [AirtestProject/AirtestIDE#125]
![tim 20180531220909](https://user-images.githubusercontent.com/38519076/40787099-59db61f0-651f-11e8-8f9c-e34f456a8004.png)
![tim 20180531220936](https://user-images.githubusercontent.com/38519076/40787096-5935a4e0-651f-11e8-8024-5d7f6f4a323c.png)

想输入中文，结果不是我们想要的。

**Comment by bs111** [comment]
也没法输入阿拉伯语言。

**Comment by rockywhisper** [comment]
@bs111  好的，我们查证下问题，尽快修复&外放。

有同学说poco输入暂时没问题，暂时可以先尝试下pocode input哈   :-)

**Comment by bs111** [comment]
嗯 是的 tks

**Comment by rockywhisper** [comment]
@bs111  Hi，我近期在真机和模拟器上都没有重现问题，使用的是airtest的text(“xxx”)，如下：

 - Mumu模拟器：
![test-arab-lang](https://user-images.githubusercontent.com/8188879/42549743-62cf230e-8500-11e8-8895-bc87f6dd7563.gif)

 - 真机：
![test-arab-lang-2](https://user-images.githubusercontent.com/8188879/42550173-acdd03ce-8502-11e8-893f-af408eee0fe7.gif)

可以使用[最新版本的AirtestIDE](http://airtest.netease.com/) 试一下？
本issue先关闭了哈，后续有问题随时沟通~

**Comment by yuanze12345678** [comment]
怎么取消输入后自动跳转到下一行

**Comment by yuanze12345678** [comment]
@rockywhisper
