### ISSUE TITLE
无法连接wifi远程设备

### ISSUE THREAD

**Issue by suqingyue738** [AirtestProject/AirtestIDE#13]
![default](https://user-images.githubusercontent.com/12101941/37273437-cdcaf17e-2614-11e8-87de-14a00dc274cf.png)
![default](https://user-images.githubusercontent.com/12101941/37273445-d32c5aea-2614-11e8-87cc-1c4b9a28e021.png)
设备已经通过wifi连上，但是在控制台输出如图报错

**Comment by yimelia** [comment]
实测过wifi连接的设备是能正常连上IDE的，但是稳定性比较差。
这个问题跟wifi连设备无关，应该是其他原因导致的连接失败
