### ISSUE TITLE
连接夜神模拟器成功后，屏幕是黑的，导致不能图片对比

### ISSUE THREAD

**Issue by hankhua** [AirtestProject/AirtestIDE#131]
![default](https://user-images.githubusercontent.com/19551480/40962397-e91b31c4-6894-11e8-8819-7c8df4dedf31.png)

**Comment by rockywhisper** [comment]
@hankhua  点击connect之前，请把connect下拉菜单中的“Use javacap”勾选上。

详见 [连接模拟器文档](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html#id3)

**Comment by hankhua** [comment]
@rockywhisper connect下拉菜单中只有Use Emulator
