### ISSUE TITLE
在IDE中，使用Poco.scroll(), 报错误 swipe() got an unexpected keyword argument \'steps\'

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#132]
AirtestIDE v0.0.19, mac版，测试IOS, 调用 poco("Cell")[6].scroll("vertical",  percent=0.3)，得到错误，swipe() got an unexpected keyword argument \'steps\'"，不知道这个问题已知吗？

**Comment by zzldjkzxf** [comment]
最新版本中已经解决
