### ISSUE TITLE
Airtest IDE不支持设备MI 5S Plus

### ISSUE THREAD

**Issue by andrewyong87** [AirtestProject/AirtestIDE#133]
使用Airtest IDE在小米5S Plus中录制case时手机没有任何反应，log窗口提示：ADB指令执行失败，请查阅官网[FAQ](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html)获得更多信息。

**Comment by rockywhisper** [comment]
@andrewyong87  你好，连接设备时候如果遇到未知错误，可以在控制台窗口进行查看。
[如何查看IDE的详细报错信息](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/1_ide_crash.html#id2)

另外，小米设备请着重查看下设备的部分调试开关是否已经打开，[小米设备调试开关](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id9)

**Comment by rockywhisper** [comment]
@andrewyong87  你好，看了下小米 5S设备在我们的[支持列表](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/6_device_connection/5_android_support.html)内，没有复现出连接问题，请查证确认下。

本issue先关闭啦~
