### ISSUE TITLE
IDE通过selenium进行录制还是闪退

### ISSUE THREAD

**Issue by liuyang054** [AirtestProject/AirtestIDE#134]
浏览器打开后，点击录制闪退，报错如下：

![img_1742](https://user-images.githubusercontent.com/30917812/41077006-f01fa4d8-6a46-11e8-8dcf-d2b886e8ef9e.JPG)

**Comment by zzldjkzxf** [comment]
@liuyang054 你是每次都出现，还是只出现了一次…能说下具体情况吗，是点开浏览器马上点录制还是怎么操作的，能说下具体步骤吗

**Comment by zzldjkzxf** [comment]
@liuyang054 你是每次都出现，还是只出现了一次…能说下具体情况吗，是点开浏览器马上点录制还是怎么操作的，能说下具体步骤吗

**Comment by liuyang054** [comment]
我把chrome升级了，升级成 32位67.0的版本，闪退不是每次都出现了，但是偶尔还会出现，但还没找到规律，所以怀疑还是chrome版本的影响（以前版本比较老，是49.0）
公司应用前端用的是angular js开发的，发现录制时，xpath里面都是空的，是否又遇到这种情况啊？
另外对于没有id或者name的控件，录制时都是默认用xpath吗？

**Comment by zzldjkzxf** [comment]
@liuyang054  尽量提升到新的chrome版本哈…然后xpath是空的情况是因为页面里嵌套了<iframe>的情况吧，对于<iframe>内的元素确实暂时会找不到，所以xpath是空的哈，之后会争取解决这个问题。然后现在确实是除了id,name 都是用的xpath，你觉得还有那些属性会比较常见的可以用的呢？我们可以考虑加上
