### ISSUE TITLE
[IDE_Mac_0.0.19][Poco Assistant]Android原生: 双击元素id包含"text"时,IDE崩溃

### ISSUE THREAD

**Issue by oenaizha** [AirtestProject/AirtestIDE#136]
![image](https://user-images.githubusercontent.com/19545308/41083645-44b5271c-6a64-11e8-97ea-2168dc2216c9.png)
双击就会崩溃,之前版本没有这个问题

**Comment by XedGo** [comment]
老哥，我也遇见了，今天第一次尝试，受伤了

**Comment by oenaizha** [comment]
@rockywhisper 恩呢~~~18的版本不知道为什么在touch的时候截图各种崩溃~默默等待新版本~

**Comment by rockywhisper** [comment]
@oenaizha  @XedGo  
Hi, 新版本已经发布，这个问题已经解决掉了。

下载链接详见： http://airtest.netease.com/changelog.html
如果遇到问题还请及时反馈，感谢。 : )
