### ISSUE TITLE
和#136的问题应该差不多

### ISSUE THREAD

**Issue by XedGo** [AirtestProject/AirtestIDE#137]
![image](https://user-images.githubusercontent.com/24712124/41092498-99c42516-6a7b-11e8-85af-82ddc4b986b7.png)

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/AirtestIDE/issues/136   link一下

**Comment by rockywhisper** [comment]
@XedGo  Hi， 你好，最近开发环境在升级py3，涉及到较多修改。
0.0.19版本出现了这个bug是一处修复遗漏，我们已经修复了这个问题，预计明天会发布版本进行修复。
真是抱歉，耽误你用啦~

ps：如果着急用，今天也可以暂时使用0.0.18版本： [IDE的历史版本下载连接](http://airtest.netease.com/changelog.html)   （直接下载解压即可使用）

**Comment by XedGo** [comment]
@rockywhisper 多谢老哥，今天下午测试一下

**Comment by XedGo** [comment]
还没发布吗

**Comment by rockywhisper** [comment]
@XedGo   Hi, 新版本v0.1.0已经发布，下载链接详见：  http://airtest.netease.com/changelog.html
该问题已经解决了，可以下载试用下   : )
