### ISSUE TITLE
启动airtestide报错，小程序支持

### ISSUE THREAD

**Issue by zzx11** [AirtestProject/AirtestIDE#138]
![1](https://user-images.githubusercontent.com/38515225/41137588-6ebae238-6acb-11e8-9d1b-f9790d03906b.JPG)
启动airtestIDE时报如截图中的错误，连接手机后无法识别微信小程序中的元素对象

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/issues/77#issuecomment-395636651

感谢反馈，我们后续支持小程序

**Comment by yimelia** [comment]
可以尝试一下当前最新版本的IDE看问题是否依旧~我们在最新版本已经对内核做了升级
