### ISSUE TITLE
win7 64bit系统，选定windows端app后，poco辅助窗选择cocoa-js，IDE闪退

### ISSUE THREAD

**Issue by DXYUANDX** [AirtestProject/AirtestIDE#139]

**Comment by rockywhisper** [comment]
@DXYUANDX  Hi，可以填一下对应的报错么？

[报错原因查看方法](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/1_ide_crash.html#id2)

**Comment by DXYUANDX** [comment]
![image](https://user-images.githubusercontent.com/29771880/41276184-070baa08-6e56-11e8-8d17-185318366c24.png)

**Comment by DXYUANDX** [comment]
![image](https://user-images.githubusercontent.com/29771880/41276439-cf833532-6e56-11e8-867d-b31517271370.png)

**Comment by rockywhisper** [comment]
@DXYUANDX   Hi，我们今天放出了新版本，下载链接： http://airtest.netease.com/changelog.html

问题应该已经解决了。欢迎试用，有问题随时反馈哈，感谢。 : )
