### ISSUE TITLE
使用双显示器的电脑，录制PC端时，图集采集的位置是错误的

### ISSUE THREAD

**Issue by liuxujie521** [AirtestProject/AirtestIDE#14]
例如在A屏幕上点击录制采集
然后操作A屏幕
录制的图集显示为B屏幕上的内容

**Comment by rockywhisper** [comment]
你好，在windows双屏操作时，请使用“设备面板”-“屏幕分辨率”，将左边屏幕调为主屏幕，并将两个屏幕的上边沿对齐。（windows的多屏幕坐标系比较复杂）

**Comment by Meteorix** [comment]
这也是个bug，我们后面修复，目前请按2楼的说法绕过这个问题

**Comment by rockywhisper** [comment]
@liuxujie521  Hi，我们今天发布了新版本，这个问题已经解决了。

新版本下载链接： http://airtest.netease.com/changelog.html
欢迎使用，如果遇到问题还请随时反馈哈，非常感谢。   : )
