### ISSUE TITLE
请问windows端的app怎么使用poco辅助窗查看UI元素？

### ISSUE THREAD

**Issue by DXYUANDX** [AirtestProject/AirtestIDE#140]

**Comment by rockywhisper** [comment]
@DXYUANDX  你好，请问你是普通windows应用，还是游戏应用呢？
如果是Unity、Cocos引擎的游戏，嵌入SDK后切到对应选项即可正常查看，不过普通的windows应用暂时还没有外放支持。

**Comment by rockywhisper** [comment]
@DXYUANDX  你好，目前Windows的普通窗口还没有加入poco支持。

当前只有嵌入Poco-SDK的游戏可以使用windows-poco功能，我们提供了[Windows-Demo游戏](http://top.gdl.netease.com/poco-res/poco-demo-unity-game-win.zip)

体验步骤：
1、使用AirtestIDE连接Windows-Demo游戏；
2、使用“选项”-“设置”-“Poco”-“Windows Content Area Rect”，选定游戏的有效画面区域。
![del](https://user-images.githubusercontent.com/8188879/42311909-858f4de4-8071-11e8-8e71-c7a5f886063b.png)

3、Poco辅助窗选择Unity选项.

Enjoy!

**Comment by rockywhisper** [comment]
@DXYUANDX  你好，本issues暂时关闭了哈，后续有任何问题可以再沟通~
