### ISSUE TITLE
zuk z2无法打开手机窗口

### ISSUE THREAD

**Issue by wubo11** [AirtestProject/AirtestIDE#141]
成功连接电脑，adb devices指令输入之后有显示设备信息。AirtestIDE日志窗口有TB。
![qq 20180608154213](https://user-images.githubusercontent.com/40055117/41145511-de395862-6b32-11e8-83e5-340fae50bd6a.png)

**Comment by rockywhisper** [comment]
@wubo11  Hi, 你可以尝试下，在connect之前打开conenct角标的use ADB orientation选项。

![image](https://user-images.githubusercontent.com/8188879/41146045-a308c9ce-6b34-11e8-9ae4-c31bcb1a90e0.png)

**Comment by wubo11** [comment]
@rockywhisper 你好，我已经选择过了，还是报TB，Airtest自带了一个adb的应用程序，需要帮这个adb配置环境变量吗。我的环境变量里面配置的是自己下载的sdk路径。

**Comment by rockywhisper** [comment]
@wubo11 adb环境变量倒是不用，因为看log里面使用的就是airtest内置的adb.exe的。

我看到在STF的仓库里面同样也有[这个问题](https://github.com/openstf/stf/issues/436) ，我们测试机型中也没有这台机器，我们稍后可能要再确认下。 方便的话，可以换台手机，或者换用模拟器都行。

**Comment by wubo11** [comment]
@rockywhisper嗯，好的，谢谢你。

**Comment by zzldjkzxf** [comment]
@wubo11  经过测试，这个型号手机对/data/local/tmp这个目录用户没有权限访问，所有需要root才能使用Airtest-IDE。建议换用别的机型测试
