### ISSUE TITLE
按钮持续点击没有效果，只体现了单击，我实在搞不定了

### ISSUE THREAD

**Issue by Sinxiaose** [AirtestProject/AirtestIDE#142]
poco("right").long_click(duration = 3.0)

**Comment by adolli** [comment]
你说的持续点击是连续点击多次还是长按？连续点击多次的方法还没有加进去。

**Comment by adolli** [comment]
这个应该是模拟器兼容性的问题。你所使用的是android原生应用测试还是别的引擎？

**Comment by Sinxiaose** [comment]
unity3d！    应该是兼容问题吧 ，希望早点解决，现在哪款模拟器可以使用？  我知道逍遥连接不了，天天有兼容问题，

**Comment by Meteorix** [comment]
可以试试mumu模拟器

**Comment by XedGo** [comment]
@Meteorix MUMU有个致命的缺点就是，无法调用摄像头（尽管没有），使用场景如：微信内扫描小程序开发版二维码

**Comment by adolli** [comment]
@XedGo 其他模拟器能实现微信扫码这种功能？

**Comment by rockywhisper** [comment]
@Sinxiaose  Hi, 本issue暂时先关闭了哈。
如果有更新反馈可以新建issue    :-)
