### ISSUE TITLE
同一个脚本中操作多设备

### ISSUE THREAD

**Issue by TatamiHermit** [AirtestProject/AirtestIDE#143]
当多台手机同时在线，进行多人游戏时，产生的交互、对话、操作等。
是否可以新增一个enhancement，在同一个脚本中，指定device ID发送相应的操作命令。

**Comment by Meteorix** [comment]
可以使用
```
set_current(1)  # 切换到第二台设备
touch(xxx) #在第二台设备上执行touch

set_current(0)  # 切换回第一台设备
```

**Comment by TatamiHermit** [comment]
设备需要先声明吗？还是只要在IDE的设备列表中显示就可以了呢？
另外设备索引号(0)、(1)的顺序如何定义，列表第一个默认是0？

**Comment by Meteorix** [comment]
Just give a try

**Comment by rockywhisper** [comment]
@TatamiHermit  本issue暂时关闭了哈，如有任何问题，欢迎随时反馈  : )

**Comment by MurphyLee2048** [comment]
您好，多设备操作没有问题，但是device screen不会切换，即使在No.2设备上成功执行了操作，可能屏幕仍实时显示的是No.1设备的界面。

**Comment by yimelia** [comment]
IDE里的device screen确实不会自动切换，因为脚本运行在哪个手机上，IDE并不能知道
