### ISSUE TITLE
IDE中使用using导入公共脚本提示找不到。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#145]
AirtestIDE v0.0.19, win版，使用using,提示 ImportError: No module named xxx

**Comment by Meteorix** [comment]
请贴上代码、具体的报错、目录结构

**Comment by StandOutstar** [comment]
目录结构
--project_dir
   --project_commons
      --commons.air
      --project_launcher.py
  --test_xxx.air

project_launcher.py：
   ...
   from airtest.core.api import using
   using("commons.air")
   from commons import *
   ...

运行结果：
 ImportError: No module named commons

**Comment by StandOutstar** [comment]
经实验，导入公共脚本使用 绝对路径 可以导入。

**Comment by Meteorix** [comment]
感谢反馈，已知问题，下个版本会修复
