### ISSUE TITLE
不支持小程序吗【已支持】

### ISSUE THREAD

**Issue by XedGo** [AirtestProject/AirtestIDE#146]
发现列表中，无法识别小程序元素

**Comment by Meteorix** [comment]
应该可以识别的，请问你测试的是哪个小程序

**Comment by XedGo** [comment]
@Meteorix 你可以随便找个小程序测试一下。我指定的是，从启动APP开始，就使用airtest操作（poco）

**Comment by Meteorix** [comment]
最近我们在优化这块，会放出小程序专门的文档和例子

**Comment by XedGo** [comment]
@Meteorix 有大概时间吗

**Comment by Meteorix** [comment]
本周或者下周~ @suyuchen123 @zzldjkzxf  正在施工中

**Comment by XedGo** [comment]
@Meteorix 日常催更

**Comment by Meteorix** [comment]
@XedGo 本来上周支持好了的，结果微信更新了小程序的底层控件。。。

**Comment by Meteorix** [comment]
这周稍晚时候会先放出ios版小程序的教程

**Comment by XedGo** [comment]
... 可惜我没有mac，在等一周吧~~~~~呼呼

**Comment by suyuchen123** [comment]
https://testerhome.com/topics/14736
试试这份文档 @XedGo

**Comment by Meteorix** [comment]
@XedGo  你好，请看这里：[Airtest 使用 Airtest 进行微信小程序自动化测试 (Android & iOS)](https://testerhome.com/topics/14736)。有问题欢迎继续讨论~

**Comment by XedGo** [comment]
好的，多谢！我测试几天

**Comment by Meteorix** [comment]
欢迎开新issue反馈使用上的问题
