### ISSUE TITLE
airtest.core.helper G.add_device 没有判重，多设备时可能重复添加同一个设备，为使用set_current带来麻烦。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#148]
通过log信息，发现是脚本初始时自动连接了两个设备中的一个，随后代码又手动连接了两个这两个设备。
@Meteorix

**Comment by StandOutstar** [comment]
希望set_current可以使用通过serialno来设置当前操作设备。

**Comment by yimelia** [comment]
Hi @StandOutstar 感谢你的建议，目前这个需求在最新版本的airtest代码里已经支持了，你提到的两个点都有涉及：
[代码看这里](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/api.py#L75)

修正了重复添加设备的问题，同时也支持直接用set_current(serialno)来切换当前设备

**Comment by StandOutstar** [comment]
👍
