### ISSUE TITLE
amd显卡崩溃啥时候能修复呀   已经月中拉

### ISSUE THREAD

**Issue by 541347048** [AirtestProject/AirtestIDE#149]
请快快修复呀

**Comment by rockywhisper** [comment]
@541347048 你好，修复包已经打出来了。
目前正在测试中，本周会发出来的   :）

**Comment by 541347048** [comment]
非常感谢！

**Comment by rockywhisper** [comment]
@541347048   Hi, 新版本已经发布，下载链接详见：  http://airtest.netease.com/changelog.html

如果遇到问题还请及时反馈，感谢。      : )
