### ISSUE TITLE
使用logwrap装饰的函数，如果参数字符串中含有汉字，打印和写入到html报告中不能显示为汉字。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#151]
例如：
@logwrap
def log_to_html(msg):
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; pass

log_to_html(u"测试加入log到HTML")

实际在HTML报告中显示为：
log_to_html[u'\u6d4b\u8bd5\u52a0\u5165log\u5230HTML']

**Comment by zzldjkzxf** [comment]
@StandOutstar  这个版本在最新的版本中已经修复，可以测试一下

**Comment by StandOutstar** [comment]
验证ok
