### ISSUE TITLE
IDE不能在IOS 设备屏幕横屏时自动将屏幕翻转回水平，影响控件拾取。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#152]

**Comment by suyuchen123** [comment]
目前这边是可以的，可以提供一下具体状况？

**Comment by suyuchen123** [comment]
已经发现问题，会在明天的更新中修复，明天你可以试一下新版看还有没有问题

**Comment by StandOutstar** [comment]
背景里的控件拾取，可以支持了，但是屏幕翻转后依然有问题，
![image](https://user-images.githubusercontent.com/17442044/41464832-4674777c-70ce-11e8-82d1-c2ad7703b9cd.png)

**Comment by StandOutstar** [comment]
有时，home键也会跑到中间，
![image](https://user-images.githubusercontent.com/17442044/41465243-dc78a436-70cf-11e8-99d1-65e1ffe4396a.png)

**Comment by suyuchen123** [comment]
谢谢反馈，还有另外一个依赖库的问题，今天晚些会放出修复的版本

**Comment by suyuchen123** [comment]
try v0.1.1 http://airtest.netease.com/changelog.html

**Comment by StandOutstar** [comment]
版本：0.1.0
屏幕翻转后依然不能显示成水平的

**Comment by suyuchen123** [comment]
这边现在最新版暂时没有发现这个情况，希望提供一些更详细的信息

**Comment by StandOutstar** [comment]
v0.1.1 on MAC
device:  iPhone SE , IOS 11.4
从竖屏进入固定横屏后显示依然为竖屏。

**Comment by StandOutstar** [comment]
重新连接一下，可以恢复
