### ISSUE TITLE
图像如果和脚本不在同一目录下，log窗口打印有问题，HTML报告中也不能显示。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#153]
log窗口中：
![image](https://user-images.githubusercontent.com/17442044/41402787-d0e4b022-6ff5-11e8-926b-1f16876183d1.png)
Html报告中：
![image](https://user-images.githubusercontent.com/17442044/41402885-098f090e-6ff6-11e8-989c-d2eb2b61a3ee.png)

**Comment by StandOutstar** [comment]
在公共脚本中存入图片类，在测试脚本中使用的

**Comment by yimelia** [comment]
该问题在即将放出的最新版本已经修复~
