### ISSUE TITLE
录制时，用text输入中文就会发生闪退

### ISSUE THREAD

**Issue by Yueve** [AirtestProject/AirtestIDE#155]
![ide](https://user-images.githubusercontent.com/36754926/41446958-4434bda8-7085-11e8-95fe-c4303080009f.jpg)
![default](https://user-images.githubusercontent.com/36754926/41446964-4a9a6968-7085-11e8-8429-355a101d27e0.jpg)

**Comment by rockywhisper** [comment]
@Yueve  今天晚些时候会放出稳定版本，这个问题已经得到修复。

发布后会在QQ群通知的哈   :）

**Comment by rockywhisper** [comment]
@Yueve  Hi, 新版本已经发布，问题已经修复啦。

下载链接详见： http://airtest.netease.com/changelog.html
如果遇到问题还请及时反馈，感谢。 : )

**Comment by Yueve** [comment]
好的，谢谢！你们真的是太棒了 
 
------------------ Original ------------------
From: "王建军"; 
Date: 2018年6月15日(星期五) 晚上8:34
To: "AirtestProject/AirtestIDE"; 
Cc: "Eve"; "Mention"; 
Subject: Re: [AirtestProject/AirtestIDE] 录制时，用text输入中文就会发生闪退 (#155)

 

@Yueve  Hi, 新版本已经发布，问题已经修复啦。
 
下载链接详见： http://airtest.netease.com/changelog.html
 如果遇到问题还请及时反馈，感谢。 : )
