### ISSUE TITLE
出现一个air目录下照片突然被莫名全部删除的情况。

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#157]
版本：0.1.0（06-15）win版

不知道是否与那个删除多余照片功能有关，重新启动IDE总是从上次记录的状况启动（打开上次记录的脚本开启），本次关闭的删除多余照片功能又被重新打开。

**Comment by Meteorix** [comment]
感谢反馈，删除多余照片是个危险的操作，准备屏蔽掉

**Comment by yimelia** [comment]
@StandOutstar 感谢反馈，这个BUG已经在目前[官网最新版本（0.1.1）](http://airtest.netease.com/changelog.html)修复了，可以更新一下再使用
