### ISSUE TITLE
assert_语句截图双击时闪退，环境win64+华为android5.1

### ISSUE THREAD

**Issue by testyao** [AirtestProject/AirtestIDE#159]
file "encodings\utf-8.py",line 16,in decode
unicodeencodeerror: ascii codes cant,t encode characters in position 104-1-9:ordinal not in range(128)

**Comment by yimelia** [comment]
@testyao 你好，很抱歉这是我们之前版本出现的bug，目前已经修复，可以上[官网](http://airtest.netease.com/changelog.html)下载当前的最新版本（已升级至py3）来试用，如果暂时必须要用py2的话，可以下载官网上的0.0.18版本使用。
