### ISSUE TITLE
模拟器不能链接

### ISSUE THREAD

**Issue by mttmyy** [AirtestProject/AirtestIDE#16]
希望可以支持模拟器的链接

**Comment by rockywhisper** [comment]
可以使用android studio自带的模拟器哈，有同学已经用起来了。  :-)

**Comment by Meteorix** [comment]
@rockywhisper 可以出一个连接模拟器的教程

**Comment by rockywhisper** [comment]
好，稍后出一份安卓模拟器的连接文档。

**Comment by kwl01skz** [comment]
nox模拟器可以连接（替换adb之后），偶尔会引起模拟器重启。
device screen显示黑屏，屏幕操作正常。

**Comment by zhangpinGithub** [comment]
nox模拟器可以连接，手动切换到文件夹下的adb目录存放目录，使用adb connect 127.0.0.1:62001连接

**Comment by rockywhisper** [comment]
模拟器本地测试了一遍尚不能顺畅使用。

其中nox模拟器可以部分使用：在IDE设备连接区的“远程设备连接”中，输入“adb connect 127.0.0.1:62001”并连接，设备列表内即可看到对应设备。
缺陷：无法在IDE内展现实时截图，无法实现Airtest脚本录制，只能响应操作。

**Comment by rockywhisper** [comment]
@mttmyy Hi，请暂时先把模拟器作为windows应用嵌入IDE使用。我们会继续研究下模拟器支持。

**Comment by rockywhisper** [comment]
@mttmyy   @zhangpinGithub @kwl01skz  

Hi， [AirtestIDE v0.0.13](http://airtest.netease.com/changelog.html) 增加了连接模拟器的功能， 使用方法参考： [模拟器连接文档](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html)

如有使用问题欢迎随时反馈  :-)

这个issue我就先关闭了哈~
