### ISSUE TITLE
Airtest里的录制swipe操作，脚本跑不起来。

### ISSUE THREAD

**Issue by Jimmy36506** [AirtestProject/AirtestIDE#161]
![image](https://user-images.githubusercontent.com/40386006/41635400-2400a50c-747b-11e8-8f0d-a694bee40341.png)

而且明显与POCO录制的脚本不一样。
![image](https://user-images.githubusercontent.com/40386006/41635425-3fb1fd5a-747b-11e8-8255-165dcc785fc9.png)

**Comment by 541347048** [comment]
我的问题和你一样  你看下你显卡是不是amd的

**Comment by yimelia** [comment]
问题已经修复，将在下个版本放出
