### ISSUE TITLE
请教如何实现 同时在多台设备上跑同一个测试脚本

### ISSUE THREAD

**Issue by IvyyLu** [AirtestProject/AirtestIDE#162]
RT，请教如何实现 同时在多台设备上跑同一个测试脚本？

尝试 用多线程的方式 或多开多个cmd的形式，在2台设备上同一时刻跑同一脚本，发现一台设备上脚本运行正常，但，另一部设备却跑不起来

airtest run F:\wwddzAutoTest\src\Login.air --device Android:///d21ac3d
airtest run F:\wwddzAutoTest\src\Login.air --device Android:///0123456789ABCDEF

**Comment by rockywhisper** [comment]
@IvyyLu 请问跑不起来的具体情况是什么样的？第二台设备完全没有运行，还是其他的情况呢？

**Comment by rockywhisper** [comment]
@IvyyLu    Hi，多个设备上跑同一个测试脚本可以通过开启多个运行进程来实现，比如你说尝试的“开多个cmd的形式”。

请问你之前出现问题的运行脚本是版含有Poco语句脚本吗，具体报错是如何的？

**Comment by zwp198706** [comment]
我也遇到同样的问题

**Comment by zwp198706** [comment]
重点是这上面无法粘图

**Comment by zwp198706** [comment]
![default](https://user-images.githubusercontent.com/37521189/45534606-4d519a00-b82e-11e8-9ccb-064af6f47735.PNG)
见截图，实际只有一个设备在运行

**Comment by zwp198706** [comment]
请问怎么在程序中添加语句让其同时跑起来？

**Comment by zwp198706** [comment]
就是第二个设备压根就没跑起来

**Comment by yimelia** [comment]
@zwp198706 添加多个 `--device Android://xxx` 语句，是多机协作脚本，意思是在同一个脚本里调用多台手机相互互动之类的，如果你的脚本里没有类似set_current(1)这样的语句来切换设备，那么效果确实是只在一台手机上跑了脚本，详情见 [教程](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#)

要让同一个脚本在多台手机上跑，目前需要自行实现，比如自己用多线程控制，或是自己写调度脚本，最简单的方式是写多个bat脚本来一起运行哈
