### ISSUE TITLE
在devices screen窗口phone assistant下show assistant dialog选项选择即崩溃

### ISSUE THREAD

**Issue by Jimmy36506** [AirtestProject/AirtestIDE#168]
连接好设备打开devices screen
![image](https://user-images.githubusercontent.com/40386006/41655603-e8fd81ce-74bf-11e8-9463-d204235257db.png)
在中选择
![image](https://user-images.githubusercontent.com/40386006/41655142-77bf9322-74be-11e8-85f0-c49123113d72.png)下的show assistant dialog选项一选择IDE就崩溃了。
目前在win10的64位与32位中都存在此现象。

**Comment by rockywhisper** [comment]
@Jimmy36506  暂时将入口屏蔽了，此处内容后续可能会进行优化后再开放。  :-)
