### ISSUE TITLE
Minitouch init failed, you might not be able to touch screen

### ISSUE THREAD

**Issue by askj** [AirtestProject/AirtestIDE#17]

**Comment by adolli** [comment]
Can you show me the model type and SDK version of Android device you are using?

**Comment by askj** [comment]
mi3，android4.4.4

**Comment by askj** [comment]
It's okay to change a device...

**Comment by adolli** [comment]
We are improving the compatibility if you got any traceback please let us know. Thanks~

**Comment by herainwang** [comment]
@adolli 我也有这个问题，红米5，miui 9.2.1，android 7.1.2

**Comment by rockywhisper** [comment]
你好，我们有内部测试设备的列表，如果在列表内的设备连不上，请先进行一些问题排查。
连接问题faq：http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id1

**Comment by wsgongyin** [comment]
@herainwang 可以查看一下开发者选项->调试->USB调试（安全设置）[允许通过usb调试修改权限或模拟点击]   这个选项是否已经开启，我这边有几台设备开启这个选项后就可以用了

**Comment by yangxh12** [comment]
你好，我这边使用的是VR设备是一个Android系统，自己用U3D开发的launcher.在使用贵公司的产品出现Minitouch init failed, you might not be able to touch screen。查了一下贵公司的内测表，没有VR相关产品，难道是不兼容吗？谢谢~~

**Comment by Meteorix** [comment]
@yangxh12  https://github.com/AirtestProject/Airtest/issues/27 到这个issue讨论吧
