### ISSUE TITLE
手机设备为金立GN8002S 横屏状态启动IDE时，鼠标点击与实际点击不一致。

### ISSUE THREAD

**Issue by Jimmy36506** [AirtestProject/AirtestIDE#170]
手机设备为金立GN8002S
手机打开横屏状态的游戏：大鱼来了；
启动IDE，连接设备connect时，
鼠标点击的点与实际点击的点不一致。
如图所示：
![image](https://user-images.githubusercontent.com/40386006/41656648-4be44446-74c3-11e8-9b97-44e5b060e132.png)

鼠标点击的点在红框处，实际点击的点在红圈处，导致实际点击的点只能占用一半的屏幕。

**Comment by geonsme** [comment]
我也遇到同样问题了，是华为P9，在4月份版本IDE是没有问题的，后面版本对于这款机器都有问题。你是怎么解决的

**Comment by zzldjkzxf** [comment]
目前已经修复该问题，将在最新版中放出。
