### ISSUE TITLE
版本: 0.1.1 (2018-06-19) IDE，在win10上运行起不来

### ISSUE THREAD

**Issue by zhangwk02** [AirtestProject/AirtestIDE#173]
![image](https://user-images.githubusercontent.com/38233062/41807168-23017792-76fd-11e8-8259-8e01510f577f.png)

**Comment by Meteorix** [comment]
你好，可以贴上后台窗口的截图吗

**Comment by zhangwk02** [comment]
![image](https://user-images.githubusercontent.com/38233062/41807352-945a9be6-7700-11e8-8712-37b014e40822.png)

还有windows日志：
![image](https://user-images.githubusercontent.com/38233062/41807358-a493d810-7700-11e8-88ff-6cbe128e6110.png)


+ | System
-- | --

**Comment by zhangwk02** [comment]
我电脑上有之情的IDE，和最新下载的IDE；默认加载的config还是以前的

**Comment by Meteorix** [comment]
感谢反馈，可能要查查 @yimelia

**Comment by zhangwk02** [comment]
@Meteorix  V0.1.2版的IDE还是存在该问题， win10 64位操作系统，报错还是和之前一模一样

**Comment by rockywhisper** [comment]
@zhangwk02  Hi，你好，请问v0.0.18版本当前运行是否正常？

另外，是否方便留一个邮箱联系方式，以便给你提供更多的错误提取方法。

**Comment by zhangwk02** [comment]
@rockywhisper   邮箱：zhangwenkal@yeah.net     v0.0.18版本当前运行比较稳定

**Comment by zhangwk02** [comment]
@rockywhisper  目前最新班的IDE试过了，还是报同样的错误；
E:\D\Auto_test-tools\AirtestIDE_2018-06-29_py3_win64>AirtestIDE.exe
loading config from : ['C:\\Users\\zhangwk02\\AppData\\Local\\AirtestIDE\\AirtestIDE\\user.json']

![image](https://user-images.githubusercontent.com/38233062/42252822-3be793aa-7f71-11e8-9a33-a0ba7a8611ae.png)




+ System 
  - Provider 
   [ Name]  Application Error 
   - EventID 1000 
   [ Qualifiers]  0 
    Level 2 
    Task 100 
    Keywords 0x80000000000000 
   - TimeCreated 
   [ SystemTime]  2018-07-04T02:00:57.902495000Z 
    EventRecordID 84694 
    Channel Application 
    Computer zhangwk02-szzbn.vanke.net.cn 
    Security 
 - EventData 
   AirtestIDE.exe 
   0.1.0.0 
   5a2e9e81 
   ig9icd64.dll 
   22.20.16.4799 
   59bad4ee 
   c0000005 
   00000000009f7d4c 
   23f8 
   01d4133ad782b0a4 
   E:\D\Auto_test-tools\AirtestIDE_2018-06-29_py3_win64\AirtestIDE.exe 
   C:\windows\System32\DriverStore\FileRepository\ki124455.inf_amd64_0f9ddfab4df0266d\ig9icd64.dll 
   e7cf4336-3fdc-48a9-8023-410a3fad1ebf

**Comment by zhangwk02** [comment]
@rockywhisper  该问题更新电脑显卡驱动，已解决
