### ISSUE TITLE
使用AirtestIDE连接自身电脑上的安卓模拟器，Device Screen黑屏

### ISSUE THREAD

**Issue by hookibaoxue** [AirtestProject/AirtestIDE#174]
1.启动MuMu模拟器
2.启动AirtestIDE

3.在设备窗下的移动设备连接，点上远程设备连接，然后在点击该选项右侧的“连接”。
4.点击设备的 connect

5.进入Device Screen,此时为黑屏

**Comment by Meteorix** [comment]
你好，connect之前需要勾选“use javacap"，参考这里：

http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html#id3

**Comment by gakaki** [comment]
文档已经连接不上了 而且现有文档里还搜索不到
