### ISSUE TITLE
初次安装，英文模式下 【Settings】选项显示的问题

### ISSUE THREAD

**Issue by zhuruiqi** [AirtestProject/AirtestIDE#175]
MacOS 版本 v0.1.1 

安装后初次打开，英文模式 【Options】 下没有 【Settings】 选项，
切换为中文模式，【选项】下面才显示【设置】选项，
再次切换为英文状态能正常显示【Settings】。

**Comment by rockywhisper** [comment]
10月9号的版本将会修复，本issues暂时关闭了哈~
