### ISSUE TITLE
您好，我想一秒内获取多个图像数据，但snapshot会保存文件3秒多一次

### ISSUE THREAD

**Issue by lufei2016** [AirtestProject/AirtestIDE#177]
您好，我想一秒内获取多个图像数据，但snapshot会保存文件3秒多一次。
能否通过某些参数使snapshot不保存，并返回当前屏幕图像？

**Comment by Meteorix** [comment]
可以`G.DEVICE.snapshot()`，参考这里：https://github.com/AirtestProject/Airtest/blob/ec355f002d339ba8fce062df30c66f81cae09c0e/airtest/core/api.py#L205

**Comment by lufei2016** [comment]
谢谢
