### ISSUE TITLE
运行即闪退 

### ISSUE THREAD

**Issue by DnightLee** [AirtestProject/AirtestIDE#178]
运行即闪退
![1_airtest](https://user-images.githubusercontent.com/40618129/41949629-d6a60f84-79f4-11e8-8bba-dac4f214cef0.png)

**Comment by rockywhisper** [comment]
@DnightLee   你好，使用的版本是v0.1.0吗？
我们刚刚发布了新版本v0.1.2，可以尝试下 [新版下载](http://airtest.netease.com/changelog.html)

我在本地确认没问题的哈。

**Comment by DnightLee** [comment]
@rockywhisper 
还是不行噢，有个朋友说可能是系统兼容性问题，我在更新系统ing

**Comment by rockywhisper** [comment]
@DnightLee  好的，如果你是32bit的windows的话，还请使用32bit的包。

方便的话还请提供下详细报错截图，[查看报错方法](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/1_ide_crash.html#id2)

**Comment by DnightLee** [comment]
系统是win7 64位的，路径中有空格，报错还是和最初一样，详见图
![3_airtest](https://user-images.githubusercontent.com/40618129/41950833-9fcf325a-79fa-11e8-8ba0-82a633a5733b.png)
![2_airtest](https://user-images.githubusercontent.com/40618129/41950834-a027550c-79fa-11e8-8e3b-0c2423540483.png)

**Comment by rockywhisper** [comment]
@DnightLee  你好，可以使用cmd打开AirtestIDE.exe，这样发生crash之后可以完整保留具体报错。

在AirtestIDE主目录下，shift+鼠标右键->在此处打开命令窗口， 然后输入"AirtestIDE.exe"执行
再次出现停止工作窗口时，直接点击关闭程序，查看cmd窗口的报错。帮忙截个图哈~

**Comment by xiaoxiangLiu** [comment]
![default](https://user-images.githubusercontent.com/20807131/42122429-5b20be68-7c74-11e8-8ccf-d52d3ddd8c91.png)
![default](https://user-images.githubusercontent.com/20807131/42122432-61b90dd4-7c74-11e8-896b-c5d762545dc2.png)
win7 64位无论是直接点击airtest.exe还是用命令行执行airtest.exe都是报同样的错误，缺少libEGL和openg132sw.dll，在win10 64位中没有发现这个问题。

**Comment by xiaoxiangLiu** [comment]
![default](https://user-images.githubusercontent.com/20807131/42122493-5ec6075c-7c75-11e8-904e-02fc15965356.png)
应该是需要下载一个openGL2.0以上，我去下载试试

**Comment by xiaoxiangLiu** [comment]
更新显卡驱动解决了

**Comment by DnightLee** [comment]
@xiaoxiangLiu  我是继承显卡，驱动已经更新到最新了，openGL2.0 怎么更新？

![1_dx](https://user-images.githubusercontent.com/40618129/42218244-805b3a18-7efa-11e8-9559-c4397ff15d61.png)
![2_dx](https://user-images.githubusercontent.com/40618129/42218240-7fbca66e-7efa-11e8-9fa8-604ee438e162.png)
