### ISSUE TITLE
能否帮忙做一个32位的安装包？ 谢谢了

### ISSUE THREAD

**Issue by hscmcc1** [AirtestProject/AirtestIDE#18]

**Comment by adolli** [comment]
非常抱歉，32bit版本短期内没法打包，后续会陆续增加打包版本，你可以直接使用python库 [airtest](https://github.com/AirtestProject/Airtest) 和 [poco](https://github.com/AirtestProject/Poco)

**Comment by hscmcc1** [comment]
好的，期待后续版本

**Comment by rockywhisper** [comment]
@hscmcc1  Hi，你好，我们今天发布了新版本，其中windows32bit的包也已经提供。
下载连接： http://airtest.netease.com/changelog.html

如果遇到任何问题，欢迎随时反馈，谢谢。   : )

**Comment by hscmcc1** [comment]
好的，非常感谢！

**Comment by hscmcc1** [comment]
运行32位程序出现Login窗口，提示找不到您的文件，该文件可能已被移至别处或遭到删除，ERR_FILE_NOT_FOUND,请问怎样解决呢？

**Comment by rockywhisper** [comment]
Hi，请问可以提供下详细的报错截图吗


| |
王建军
邮箱：rockywhisper@163.com
|

签名由 网易邮箱大师 定制

在2018年06月16日 14:46，hscmcc1 写道：

运行32位程序出现Login窗口，提示找不到您的文件，该文件可能已被移至别处或遭到删除，ERR_FILE_NOT_FOUND,请问怎样解决呢？

**Comment by hscmcc1** [comment]
您好，你发送至您邮箱

**Comment by yimelia** [comment]
@hscmcc1 真的非常抱歉，这个是我们的疏忽，在打包时漏打了一个文件导致的。出现这个提示的原因主要是在显示登录界面时联网超时了，它想显示一个默认的提示需要登录才能使用IDE的界面失败了，建议可以多尝试重新打开几次。

**Comment by hscmcc1** [comment]
嗯嗯，请问如果登陆了以后再断网还会出现问题吗？因为公司有的电脑不能联网
