### ISSUE TITLE
v0.1.2 on MAC 测试报告里页首的测试点显示消失了

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#182]
如图
![image](https://user-images.githubusercontent.com/17442044/41967726-d605a216-7a34-11e8-97e7-8220d250f366.png)

ps: 建议在 页尾步骤导航 里能把测试点步骤也用其他颜色标识出来。
![image](https://user-images.githubusercontent.com/17442044/41967752-f14d9290-7a34-11e8-82f5-7b13634c0bf8.png)

**Comment by yimelia** [comment]
@StandOutstar 收到，不好意思，这个是本周更新的一个疏忽，我们随后会把这个部分加回来

**Comment by StandOutstar** [comment]
v0.1.3 fixed
