### ISSUE TITLE
测试报告中较大的目标图片显示的过于大了，会超出屏幕

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#184]

**Comment by StandOutstar** [comment]
v0.1.3 on MAC

**Comment by zzldjkzxf** [comment]
@StandOutstar  可以贴一下详细信息吗， 例如报告的截图，手机型号之类的

**Comment by StandOutstar** [comment]
![image](https://user-images.githubusercontent.com/17442044/42677967-05d43124-86b0-11e8-8f5b-c4c68abea63a.png)

**Comment by zzldjkzxf** [comment]
已经把报告的图片比例调到合适大小了哈。

**Comment by StandOutstar** [comment]
👌
