### ISSUE TITLE
IDE读取iphone6plus分辨率不正确

### ISSUE THREAD

**Issue by 541347048** [AirtestProject/AirtestIDE#186]
通过IDE回放时，iphone6plus的分辨率为1242x2208，可是官网分辨率1080x1920.
使用iphone6plus录制时读取的分辨率也是1242x2208
这样就导致使用1080的手机截取的图片，在iphone上通过你们的缩放规则以后就找不到了

另外--给个建议，因为现在基本上所有的app在不同分辨率的手机上都做的有适配，就算是手机尺寸比例不一样，但是其实就图像看上去是一样的，所以你们这种图片按分辨率resize的规则就出了问题，本来是一样的图片，结果你们处理完之后变胖了，导致找不到。建议能不能给个开关之类的，可以关掉这个resize

**Comment by 541347048** [comment]
因为除了iPhone 6+以外，其他所有iPhone的DPI是一致的，都是326，用@2x的素材。
但是6+的实际DPI是401，理论上苹果应该用401/326 * @2x=@2.46x的素材，但是这个奇葩的比例对开发者而言很难切图，所以苹果为方便开发者用的是@3x的素材，然后再缩放到@2.46x上，实际上是缩放到2.46/3=83%，苹果选取了一个接近比例的87%。
这样算下来，物理分辨率和虚拟分比率的比例是87%，也就是1920/0.87=2208，1080/0.87=1242。
好处就是开发者更方便，比如准备素材时，字号可以直接调成3x的。

**Comment by 541347048** [comment]
原来是因为这个  可是就回到了建议的那个问题  能不能出个配置开关  不进行resize   要不然这种分辨率不同的就找不到

**Comment by rockywhisper** [comment]
@541347048   你把问题描述的非常清楚，非常感谢。

在目前的机制中，是可以通过代码关闭默认resize的。

 - [匹配时候进行图像适配的位置](https://github.com/AirtestProject/Airtest/blob/3502a7009717922b21e0c86f75d7656b4e95d6a7/airtest/core/cv.py#L138)

 - 关闭方法：
```python
from airtest.core.settings import Settings as ST
ST.RESIZE_METHOD = None
```

你可以试下在脚本中关闭默认resize的效果，看是否符合预期 :-)

**Comment by rockywhisper** [comment]
@541347048  Hi，本issue暂时关闭了哈，后续有问题欢迎随时联沟通~  :-)
