### ISSUE TITLE
airtest运行还是闪退，dx11，opengl支持4.0

### ISSUE THREAD

**Issue by DnightLee** [AirtestProject/AirtestIDE#188]
airtest运行还是闪退，win7集成显卡，dx11，opengl支持4.0，0629最新版本及18版本均无法正常运行
![5_airtest](https://user-images.githubusercontent.com/40618129/42270771-3f8478be-7fb4-11e8-8c5a-a378420bf8a9.png)
![4_airtest](https://user-images.githubusercontent.com/40618129/42270774-3fe87cb0-7fb4-11e8-9015-c04f710ad011.png)
![3_airtest](https://user-images.githubusercontent.com/40618129/42270775-40441930-7fb4-11e8-98b6-ebd2160114b4.png)
![1_airtest](https://user-images.githubusercontent.com/40618129/42270583-d57d060c-7fb3-11e8-987f-5c662d341e0d.png)
![2_airtest](https://user-images.githubusercontent.com/40618129/42270585-d5d9e73c-7fb3-11e8-9ffe-0ec79111d711.png)

**Comment by rockywhisper** [comment]
@DnightLee  你好，最新版本应该已经没有这个问题了。
可以到[官网](http://airtest.netease.com/)下载最新版本试用下。
