### ISSUE TITLE
mac下的airtest ide默认使用自带的python3.6， 如何更改使用自己的环境变量？

### ISSUE THREAD

**Issue by didiaodanding** [AirtestProject/AirtestIDE#189]

**Comment by rockywhisper** [comment]
@didiaodanding  你好，可以使用[新版IDE](http://airtest.netease.com/changelog.html)
设置界面加入了本地python环境的配置，可以填入mac下的python，即可使用本地环境运行脚本。

这个issue暂时关闭了哈~
