### ISSUE TITLE
链接移动设备，失败！请大神帮忙看下

### ISSUE THREAD

**Issue by godismeandyou** [AirtestProject/AirtestIDE#19]
点击connect，提示以下：
Connection failed, please read Docs for more help.
Bug feedback [Click here](https://github.com/AirtestProject/AirtestIDE/issues)
日志报错：
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 331-332: illegal multibyte sequence

**Comment by yimelia** [comment]
@godismeandyou 可能是同时开启了其他的手机助手抢占adb导致的，试试把所有手机助手类软件退出，并且查看任务管理器，确认相关进程都彻底关闭后再试试看
