### ISSUE TITLE
Provide Support for Exporting Result in Excel Sheet

### ISSUE THREAD

**Issue by yogendrayaduwanshi** [AirtestProject/AirtestIDE#198]
Standard Test Case Report format in Excel along with title with verdict.
e.g
Sr. No. 
Test Case Title 
Verdict
Minimal Comment for Fail and PASS

Or else 

Provide for importing excel module in Airtest.
If any alternative is already available then please provide the same

**Comment by SUDARSHANCHAUDHARI** [comment]
You can import openpyxl module in airtest

**Comment by adolli** [comment]
we are focusing on how to go through the test procedure for now. there is not a standard report format in our framework. that is to say, you can use any other libraries to generate your customized report, such as `openpyxl` or `xlwt`.

**Comment by yogendrayaduwanshi** [comment]
Thanks for your response, ill try with existing module e.g. openpyxl  or xlrd

**Comment by JJunM** [comment]
How do you export the test results to Excel?

> Thanks for your response, ill try with existing module e.g. openpyxl or xlrd

**Comment by JJunM** [comment]
How do you export the test results to Excel?
