### ISSUE TITLE
Assets used in report.html have incorrect reference

### ISSUE THREAD

**Issue by nakhbari** [AirtestProject/AirtestIDE#2]
The report html lives in sdcard/reportDir/ on the device and the assets sdcard/logDir/. The report html tries to use the assets located in the sdcard/logDir. So when the file is pulled from the device, it no longer has the correct reference. 

Suggestion: Put the assets in the same directory as the report and use relative references to the assets.

**Comment by zzldjkzxf** [comment]
Now we put assets and report.html into the same directory and used relative references correctly. The latest IDE include this change.

**Comment by nakhbari** [comment]
@zzldjkzxf I tested this today on the v0.0.3_2018-02-11 build and the assets are still in the logDir/

**Comment by zzldjkzxf** [comment]
@nakhbari  You mean you want show the errors on report? Now I diplayed the python trace on instrument test result. I saw this issue, when I catch the python script trace, I exit the test. So it didn't generate the report. I will repair it when I back to company.  Did the reportDir/ generate correctlly when test was success?

**Comment by nakhbari** [comment]
@zzldjkzxf I just ran some successful tests and they did not have the correct files within the reportDir/ on the /sdcard/

**Comment by zzldjkzxf** [comment]
@nakhbari  When I test it locally, it generate a report directory named test_script.log/ under reportDir/. And report.html and it's reference was in.  
Do you mean there was no reportDir/ directory generated when you ran successful test? Or some other error?

**Comment by nakhbari** [comment]
@zzldjkzxf I see the script zip in the results now! Awesome!

2 things could we 
1) Only have the zip file nothing else in the directory
2) name the zip file something unique so we can pull it down from storage. (ex. Netease_report.zip)

**Comment by zzldjkzxf** [comment]
@nakhbari . The latest IDE we fixed it, you can download and check .
