### ISSUE TITLE
分辨率问题

### ISSUE THREAD

**Issue by shmily-cwt** [AirtestProject/AirtestIDE#200]
连接设备界面模糊

![image](https://user-images.githubusercontent.com/28520643/42799376-3be49930-89ca-11e8-9196-4e77f1ed3e10.png)

**Comment by yimelia** [comment]
@shmily-cwt 可以尝试在连手机的下拉菜单那里选择javacap模式看看清晰度会不会有提升

**Comment by shmily-cwt** [comment]
是的选啦javacap，问题已解决，谢谢！
