### ISSUE TITLE
连接WIndows窗体下，text 功能不work

### ISSUE THREAD

**Issue by youlu2017** [AirtestProject/AirtestIDE#201]
我用airtest选择窗体，选中我windows的虚拟机，然后在里面进行一些测试。再进行到输入一些文本内容时，调用text功能，一直输入不了文字到当前光标所在的文本框中。
脚本如下：
exists(![tpl1531818830530](https://user-images.githubusercontent.com/30225643/42808191-4769aa28-89e5-11e8-9364-091444005673.png))
touch(![tpl1531818830530](https://user-images.githubusercontent.com/30225643/42808191-4769aa28-89e5-11e8-9364-091444005673.png))
text("123456")
![capture](https://user-images.githubusercontent.com/30225643/42808109-1296b4bc-89e5-11e8-8381-a039515e34fc.PNG)

**Comment by youlu2017** [comment]
![tpl1531818830530](https://user-images.githubusercontent.com/30225643/42808191-4769aa28-89e5-11e8-9364-091444005673.png)

**Comment by Meteorix** [comment]
你好，在windows上text是用模拟键盘输入实现的，你可以先手动选中这个输入框，单独运行一下text语句试试

**Comment by youlu2017** [comment]
@Meteorix 你好，我没有明白你的意思，window上面要安装模拟键盘吗？
我测试的是windows上桌面程序（WPF），界面上有一个TextBox，我现在光标在这个TextBox上，直接选中脚本中 text("123456") 这一句，文字还是没有输入到TextBox中。

**Comment by Meteorix** [comment]
不用装模拟键盘，你说虚拟机是指什么？

**Comment by youlu2017** [comment]
@Meteorix 从windows上远程连接到另一个VM上。
![capture](https://user-images.githubusercontent.com/30225643/42815760-e9016c6c-89fa-11e8-8e9f-aa8d8064ce61.PNG)

**Comment by Meteorix** [comment]
噢，我们需要测试一下这种情况

**Comment by youlu2017** [comment]
![capture](https://user-images.githubusercontent.com/30225643/42815918-7c410b54-89fb-11e8-9a1b-490a683c183b.PNG)

**Comment by youlu2017** [comment]
@Meteorix 我用一个记事本试了下，也是不work的。见上面的截图

**Comment by youlu2017** [comment]
@yimelia 谢谢，用备用嵌入方式，text可以输入文字到虚拟机的程序中。
