### ISSUE TITLE
能否在以后增加桌面呢

### ISSUE THREAD

**Issue by SSB4455** [AirtestProject/AirtestIDE#202]
现在在WIN上只能处理一个窗口里的内容 当测试的过程需要多个窗口的时候就没法用了(当然 这个不是airtest最主要的需求可以往后放一放)

**Comment by rockywhisper** [comment]
@SSB4455  Hi, Windows模式下，是可以动态找到多个窗口，并进行窗口连接-切换的。

可以参看这个Issues #239 
 - 动态获取窗口句柄handle_id
 - connect_device("windows:///handle_id")
