### ISSUE TITLE
MI Max2 无法连接adb

### ISSUE THREAD

**Issue by wujianqinjian** [AirtestProject/AirtestIDE#203]
米max2  win10  airtest v0.1.5  adb执行失败

**Comment by rockywhisper** [comment]
@wujianqinjian  你好，请查看下官网FAQ文档中的 [设备连接问题](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id9)

如果IDE连接设备、鼠标交互设备均正常，请附上adb执行失败的截图，谢谢~
