### ISSUE TITLE
刷新adb报错

### ISSUE THREAD

**Issue by shmily-cwt** [AirtestProject/AirtestIDE#205]
![image](https://user-images.githubusercontent.com/28520643/43301210-451259f6-9196-11e8-8f60-b4f1fd93f860.png)

**Comment by yimelia** [comment]
@shmily-cwt 你好，可以排查一下是否本地开启了其他手机助手类软件，如果开启了，需要确保它们完全退出（包括系统进程也需要手工结束掉），或者是检查是否有其他进程占用了adb端口
