### ISSUE TITLE
IDE生成的py文件无法在pycharm中成功运行

### ISSUE THREAD

**Issue by gfollower** [AirtestProject/AirtestIDE#208]
已经在pycharm中配置过pocoui，运行时可以正常连接devices并打开测试包，但是不能实现下一步的swipe操作，以至于无法找到操作元素，log文件对比如下：

![log](https://user-images.githubusercontent.com/37744627/43435200-7e1b5766-94b1-11e8-9c05-486f52948bb8.png)

**Comment by adolli** [comment]
是否更新poco到最新版？ `pip install -U pocoui`

**Comment by gfollower** [comment]
poco是最新版

**Comment by adolli** [comment]
滑动操作失败跟pycharm应该是无关的，可以看下你的初始化代码吗？

**Comment by adolli** [comment]
https://github.com/AirtestProject/Poco/issues/56

**Comment by gfollower** [comment]
-from airtest.core.api import *

auto_setup(__file__)
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

poco("ky_sdk_demo").child("com.miui.home:id/icon_container").child("android.widget.FrameLayout").child("com.miui.home:id/icon_icon").click()
poco("com.example.ky_sdk_demo:id/bindphone").swipe([0.0344, 0.4278])


//这个代码是从IDE直接生成的

**Comment by adolli** [comment]
这个代码看上去没问题，有换一个手机试下吗？还是说在AirtestIDE里可以运行，在pycharm里就不行了？

**Comment by gfollower** [comment]
在IDE里可以运行，在pycharm里运行时手机屏幕没有出现swipe操作，没有换手机试过

**Comment by rockywhisper** [comment]
@gfollower  Hi, 暂时没有重现出这个issues，暂时关闭了哈。

如果需要进一步帮助，可以新开一个issues    :-)
