### ISSUE TITLE
生成测试报告问题

### ISSUE THREAD

**Issue by shmily-cwt** [AirtestProject/AirtestIDE#210]
1 airtest run 运行脚本成功，
airtest run C:\Users\yanchuanjie\Desktop\AirTest\test_login.air --device Android:///MAY9X17522W05394 --log C:\Users\yanchuanjie\Desktop\AirTest\log\log
报告会截图到log里面
![image](https://user-images.githubusercontent.com/28520643/43580585-83ecc64c-9688-11e8-918c-aabeab62f04f.png)
2但是运行生成报告命令时有问题，看截图
![a3](https://user-images.githubusercontent.com/28520643/43580655-ce0a960a-9688-11e8-9934-0406f90d5ec0.png)
麻烦帮忙看下是否命令使用错误。谢谢！

**Comment by yimelia** [comment]
@shmily-cwt  是命令使用错误，请查阅 [文档](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_run_script/run_script.html#)
