### ISSUE TITLE
使用IDE处理自定义图片遇到的问题

### ISSUE THREAD

**Issue by HTOBA** [AirtestProject/AirtestIDE#211]
`touch(Template("menu.png"))`
在IDE里运行成功，保存之后下一次打开就被转换成：
`touch(Template(file:///X:/.../menu.png))`
而且开始报错了，很是头大

**Comment by yimelia** [comment]
@HTOBA 你好，这是个BUG，将会尽快在最新版本修复，非常抱歉，并且感谢反馈

**Comment by rockywhisper** [comment]
新版本已经进行了修复，本issues暂时关闭了哈  :-)
