### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by laihanhua** [AirtestProject/AirtestIDE#212]
打开Airtest时出现
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 106: illegal multibyte sequence
之前还不会，有一段时间没用过，现在打开就出现这个问题。用之前写的python文件直接执行测试也有相同的问题。出现问题的包是：airtest/core/android/adb.py

**Comment by rockywhisper** [comment]
@laihanhua  本issue暂时关闭了哈，如有问题请reopen并提供更详细的信息。
