### ISSUE TITLE
windows版本启动提示QT错误

### ISSUE THREAD

**Issue by Programmer-ZX** [AirtestProject/AirtestIDE#213]
![tim 20180804115231](https://user-images.githubusercontent.com/23043552/43672267-005976c6-97dd-11e8-9588-99af93dbcd26.jpg)

**Comment by yimelia** [comment]
@Programmer-ZX 这个问题理论上已经修复，但是你这边又出现了，有点奇怪。可以试一下在AirtestIDE文件夹下，找到`qt5_plugins\platforms`这个目录，把这个`platforms`目录整个拷贝到IDE根目录下，即：`AirtestIDE\platforms\xxx.dll`，然后再启动看看问题是否依旧

**Comment by Programmer-ZX** [comment]
谢谢，当时提问题的时候版本有出现，刚下了最新版，后面的版本修复了
