### ISSUE TITLE
poco 辅助窗无法获取Android设备UI树

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#214]
v 0.1.6 on Mac 
现象：一台ios设备拔掉线断开后，切换Android设备后，辅助窗选择Android后UI树无法获取，此时切换ios后可以获取UI。重启IDE，Android设备UI树依然无法获取。在本地用Python库时可以运行，poco service可以启动，因此应该是IDE问题。

**Comment by adolli** [comment]
`pip install -U hrpc`. 更新一下模块即可
