### ISSUE TITLE
airtest在华为mate10pro机型无法使用输入密码

### ISSUE THREAD

**Issue by iamzhangbp** [AirtestProject/AirtestIDE#215]
测试环境：ide版本v0.1.6, + win764 + 华为mate10pro
执行语句：
poco("com.by.dj.cyou:id/mgp_sdk_2_0_login_chengyou_account_EditText").click()
expected = '1388888888'
text(expected)
poco("com.by.dj.cyou:id/mgp_sdk_2_0_login_chengyou_password_EditText").click()
text("123456")
用户名控件mgp_sdk_2_0_login_chengyou_account_EditText可正常输入字符串
密码控件mgp_sdk_2_0_login_chengyou_password_EditText点击后，弹出华为安全键盘，无法使用yosemite输入法输入密码

**Comment by iamzhangbp** [comment]
请无视吧，这个应该不是ide的错误，修改华为手机设置可解决

**Comment by yimelia** [comment]
是的，修改手机中的密码相关设置项即可解决：

http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/8_faq/2_android_faq.html#text
