### ISSUE TITLE
命令行生成报告图片不显示

### ISSUE THREAD

**Issue by shmily-cwt** [AirtestProject/AirtestIDE#216]
命令行生成报告图片不显示
![a1](https://user-images.githubusercontent.com/28520643/43990047-43fc2724-9d88-11e8-80d4-e583d5ca2502.png)
![a3](https://user-images.githubusercontent.com/28520643/43990048-4b54bc20-9d88-11e8-8d42-33838cad1029.png)
![a4](https://user-images.githubusercontent.com/28520643/43990059-85fb406a-9d88-11e8-8f96-f4f98288f4db.png)

**Comment by yimelia** [comment]
@shmily-cwt 尝试换用chrome浏览器查看，在火狐和IE下可能会因为图片路径是相对路径导致显示不出图片的问题。

**Comment by shmily-cwt** [comment]
Chrome、Firefox、IE 都尝试了结果一样都看不到图片

**Comment by yimelia** [comment]
@shmily-cwt 贴一下你运行脚本的命令行看看，看起来是路径错了，在html里面它找的是log/xx.jpg，但是他们在同一个目录下所以没找到。现在看起来，report那条命令行是没问题的，看看你的run是怎么写的？

**Comment by shmily-cwt** [comment]
运行脚本命令：airtest run C:\Users\yanchuanjie\Desktop\AirTest\test_login.air --device Android:///MAY9X17522W05394 --log log/
运行报告命令：airtest report test_login.air --log_root log/ --outfile log/test_login_log.html --lang zh

麻烦看下有什么问题吗？图片是都在log下面，可以参照第一张图片。

**Comment by yimelia** [comment]
@shmily-cwt 这个问题将在下一个版本修复，目前暂时的解决方案是，在命令行中使用绝对路径就可以了。等版本发布时我会再来留一次言的

**Comment by shmily-cwt** [comment]
好的，谢谢。我试下绝对路径。

**Comment by yimelia** [comment]
该问题已修复，请同步更新AirtestIDE与airtest即可
