### ISSUE TITLE
冷启动 start app之后，poco点击事件报错，热启动就不报错，接着往下走

### ISSUE THREAD

**Issue by Li-Zepeng** [AirtestProject/AirtestIDE#217]

**Comment by Li-Zepeng** [comment]
![image](https://user-images.githubusercontent.com/17584472/44015799-f399bf3e-9f04-11e8-8b9f-99cb11e41a43.png)

**Comment by Li-Zepeng** [comment]
![image](https://user-images.githubusercontent.com/17584472/44015818-006ac1fe-9f05-11e8-87e1-e99db20f94b5.png)

**Comment by adolli** [comment]
冷启动是指？

**Comment by rockywhisper** [comment]
@Li-Zepeng  Hi，本issues暂时关闭。

后续还有问题可以提供更多报错信息，新开一个issues哈    :-)
