### ISSUE TITLE
poco版本最新，windows64位操作系统无法获取Android设备UI树

### ISSUE THREAD

**Issue by Aline1029** [AirtestProject/AirtestIDE#218]
![image](https://user-images.githubusercontent.com/19643509/44024075-d694dfb2-9f1e-11e8-871e-943eeda70bb5.png)

**Comment by CRwangzhen** [comment]
![image](https://user-images.githubusercontent.com/42568409/44450665-11a72400-a624-11e8-83cb-c74b094a2ab6.png)
我哪个都刷不出来

**Comment by adolli** [comment]
https://github.com/AirtestProject/Poco/issues/59
