### ISSUE TITLE
输入法

### ISSUE THREAD

**Issue by xiaoduola666** [AirtestProject/AirtestIDE#22]
手机上的输入法不同，登录界面中有英文和字母组合的，text（“”）根本无法输入

**Comment by adolli** [comment]
能麻烦提供一下你的代码片段和输入界面截图吗？

**Comment by rockywhisper** [comment]
@xiaoduola666  Hi，请问IDE输入失效时焦点是否已经在输入控件上，能否提供更详细的使用信息？

**Comment by rockywhisper** [comment]
@imcxl  请问测试对象是什么应用呢？ 如果可以的话，使用Poco的输入试一下呢？

**Comment by Contentment** [comment]
我遇到的是如果默认记住账号，无法删除账号
