### ISSUE TITLE
Airtest连接雷电和mumu模拟器时显示黑屏

### ISSUE THREAD

**Issue by yanyouqing** [AirtestProject/AirtestIDE#220]
Airtest连接雷电和mumu模拟器时显示黑屏

**Comment by yimelia** [comment]
@yanyouqing 模拟器连接时，在connect按钮的下拉菜单中选择javacap选项，详情请见文档 [模拟器连接](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/2_device_connection/2_emulator_connection.html)
