### ISSUE TITLE
建议，airtestIDE截图工具（位于录像按钮左边）价格截图时像素级放大

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/AirtestIDE#221]
希望airtestIDE截图工具，也加个像其他截图工具一样，有放大效果，如QQ截图等都有这个效果。
毕竟手工截图，就希望截的更准确点，
这样，在图像识别时，也能提高准确度。

**Comment by rockywhisper** [comment]
[新版本下载地址](http://airtest.netease.com/)的android设备截图已经加入了放大镜功能，可以体验下，如果建议随时联系~  :）
