### ISSUE TITLE
我截的图片，脱离ide之后脚本就无法找到了

### ISSUE THREAD

**Issue by q2361005450** [AirtestProject/AirtestIDE#222]
![image](https://user-images.githubusercontent.com/42402405/44136593-f1e9a0ae-a09f-11e8-8080-16eac23c751e.png)

我想实现在自己的python代码中加入airtest的图片识别功能。不知道为什么这段代码用ide跑能成功找到图片，直接在python上跑却找不到图片。

**Comment by yimelia** [comment]
@q2361005450 直接在python上跑是怎么跑的，使用了airtest命令行么？还是直接`python xx.py`来跑的？贴一下报错和命令行的情况看看

**Comment by q2361005450** [comment]
@yimelia 点python xx.py

**Comment by yimelia** [comment]
@q2361005450 似乎贴的2段代码里的Template不一样。在IDE中截的图片，会附带上截图时的分辨率和相关的坐标信息，方便回放时的图片匹配（让跨分辨率时更容易匹配到），自己写的图片文件名会丢失这些信息，可能导致在识别时的成功率降低

**Comment by q2361005450** [comment]
@yimelia 有什么方法可以解决这个问题？

**Comment by yimelia** [comment]
@q2361005450 需要确认一下，你使用的airtest是否自己有修改过呢？看了一下你的log，似乎不是正常情况下的log

**Comment by q2361005450** [comment]
@yimelia 只是加了几句print，没有改过任何东西。

**Comment by rockywhisper** [comment]
@q2361005450  你好，我这边模拟下你的现场试试看。需要你这边提供以下内容：

 - 1、xxx.air脚本
 - 2、对应设备的屏幕截图（可以通过snapshot()获取，通过右键IDE中脚本tab的菜单选项，可以进入截取文件夹去拿文件）
![image](https://user-images.githubusercontent.com/8188879/44502138-a3fe0500-a6c2-11e8-8ea9-f2568348d102.png)

请将对应内容请发送到邮箱： rockywhisper@163.com

**Comment by q2361005450** [comment]
已发

**Comment by q2361005450** [comment]
在网易大大的援助下，终于知道问题出在哪里了。
首先第一点，我是用模拟器进行测试的，如果脱离ide，那么就需要在connect_device函数后面加上详细的配置，主要是下图红框部分
![image](https://user-images.githubusercontent.com/42402405/44575681-1c49f080-a7bf-11e8-94ea-36bf792f7bbb.png)
设置好之后发现还没有成功，原来是前面的init_cevice方法用默认连接方式连接设备，只要删掉即可
![image](https://user-images.githubusercontent.com/42402405/44575746-51564300-a7bf-11e8-9d8e-791e242aca1f.png)
rugu
如果是使用真机的话，将不会有这个问题。
