### ISSUE TITLE
运行 AirtestIDE.exe 报 QQuickWidget cannot be used as a native child widget异常

### ISSUE THREAD

**Issue by graice2013** [AirtestProject/AirtestIDE#224]
AirTest 0.1.6 版本， window 7 64位， 运行 AirtestIDE.exe 报 QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings. 异常
![2018-08-17_150017 airtestide error](https://user-images.githubusercontent.com/24822100/44253361-e4571200-a1ee-11e8-8562-01b17bb9f14b.jpg)
![2018-08-17_15251](https://user-images.githubusercontent.com/24822100/44253369-e91bc600-a1ee-11e8-9b2c-3776b9ca2111.jpg)
![2018-08-17_15251](https://user-images.githubusercontent.com/24822100/44253373-e9b45c80-a1ee-11e8-880b-9315b2456b1a.jpg)

**Comment by yimelia** [comment]
抱歉，部分虚拟机下会出现这个报错，暂时没有找到修复的办法，可能需要换个非集显的电脑才能使用

**Comment by yimelia** [comment]
@graice2013 可以试一下目前官网的最新版本 V1.0.0RC/V1.0.0看看呢
