### ISSUE TITLE
mac系统配置本地python路径后，无法运行脚本

### ISSUE THREAD

**Issue by nian0099** [AirtestProject/AirtestIDE#228]
/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6，路径填的是这个，不知道是配置是否有误

**Comment by yimelia** [comment]
例子：
假设用了虚拟环境： `/Users/username/.virtualenvs/your_env/bin/python3`
系统环境python试一下： `/usr/local/Cellar/python/3.6.5/python3`

如果不行的话，可以把报错信息贴出来看看

**Comment by yimelia** [comment]
以及mac下这样运行貌似确实有些问题，应该是个BUG，我先确认一下，如无意外将在下个版本修复

**Comment by nian0099** [comment]
你好，使用的是系统环境/usr/local/Cellar/python/3.6.5/python3，还是不行，查看了log，log文件里并没有报错信息。。。控制台也没有输出报错

**Comment by yimelia** [comment]
@nian0099 方便的话，可以留一下邮箱么，我重新发一个安装包给你试试看，或者假如你在我们官网的QQ群里的话，可以直接在群里喊一声，我发给你

**Comment by nian0099** [comment]
niannian0099@163.com,已进入讨论群

**Comment by yimelia** [comment]
更正：
例子：
假设用了虚拟环境： `/Users/username/.virtualenvs/your_env/bin/python3`
系统环境python试一下： `/usr/local/Cellar/python/3.6.5/bin/python3`
一定要用 bin目录下的可执行文件
