### ISSUE TITLE
Ubuntu16.04 启动后控件不显示

### ISSUE THREAD

**Issue by murmured** [AirtestProject/AirtestIDE#229]
如图，安装的是最新版的0.16
![_20180823112739](https://user-images.githubusercontent.com/16380057/44529198-16e89980-a71e-11e8-990a-8f47f4468d9c.png)

**Comment by murmured** [comment]
在/usr/lib下启动AirtestIDE，如下图，是openGL没有安装么？
![image](https://user-images.githubusercontent.com/16380057/44953062-a16c8e00-aec0-11e8-8251-5f500effc058.png)

**Comment by adolli** [comment]
是的，需要安装opengl2.0以上的版本

**Comment by shownb** [comment]
同样的问题。不知道怎么解决。 @adolli @murmured
