### ISSUE TITLE
小米5x手机打开所有应该打开的开关，airtestide点击连接无反应

### ISSUE THREAD

**Issue by test-boss1** [AirtestProject/AirtestIDE#230]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。)

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
@test-boss1 你好，我们测试过小米5x这台手机，是可以正常连接airtest-ide使用的，需要插入sim卡并按图设置：
![image](https://user-images.githubusercontent.com/6896468/44643950-f4e46500-aa04-11e8-9613-2fc1fe2d6bb1.png)

如果依然失败，请首先检查是否本机开启了手机助手类软件，务必彻底关闭所有手机助手（并且在任务管理器中结束进程）。可以附上随着IDE一同启动的那个黑色命令行窗口里的log来帮助我们更好地定位问题。

**Comment by adolli** [comment]
Closed due to inactive for 5 days. Any further questions please reopen it.

**Comment by test-boss1** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 161, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 84, in __init__
  File "app\plugins\device\android\android_phone.py", line 187, in startFrameStream
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\core\android\rotation.py", line 61, in start
  File "airtest\core\android\rotation.py", line 42, in _install_and_setup
  File "airtest\core\android\adb.py", line 560, in install_app
  File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[] stderr[adb: failed to install C:\Users\wb-ly401389\Downloads\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\apks\RotationWatcher.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
]

**Comment by test-boss1** [comment]
@yimelia 会出现以上的问题，但是都是按照小米手机设置来操作的

**Comment by yimelia** [comment]
@test-boss1 你好，log里的`Install canceled by user`说明了airtest在尝试向你的手机里安装应用，而被你忽略掉了，此时需要去手机上面点同意就行了

**Comment by test-boss1** [comment]
@yimelia 手机界面就没有收到相关应用安装的提示

**Comment by yimelia** [comment]
可能是直接被手机拦截阻止了，可以看一下手机里的开发者选项中，有没有类似于“允许通过USB安装”的选项，需要打开。
![image](https://user-images.githubusercontent.com/6896468/51291103-fc062100-1a40-11e9-9c5e-760044586739.png)
这个问题是手机设置相关的问题，需要自行排查，你这款手机型号我们这里是有的，并且确认可用。

**Comment by yimelia** [comment]
@test-boss1 好的，我们后续会补充到文档里，感谢分享

**Comment by test-boss1** [comment]
在一个，什么时候支持python3

**Comment by yimelia** [comment]
IDE里换成py3已经半年多了。。。可以更新一下新版本
