### ISSUE TITLE
mac 连接木木模拟器黑屏

### ISSUE THREAD

**Issue by dingwenjie** [AirtestProject/AirtestIDE#231]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
最新mac版airtest ide 连接上 最新版木木模拟器，预览图黑屏

**截屏**

**复现步骤**
1. 点击remote connection 右侧的 connect按钮，没有反馈响应不知道是正常还是失败。
2. 点击mobile phone 里的 emulator-5554对应的action项的connect按钮，输出log，Failed to execute ADB commands, please read [Docs]
3. 点击第2条里的connect按钮右边的小三角按钮，点击Use ADB orientation选项，再次点击connect按钮，连接成功，但是预览窗口里是黑屏效果

**预期效果**
预期看到模拟器的实时画面，实际看到黑屏。点击黑屏下面的android菜单键和home键，是能对模拟器产生效果的，所以，只是显示问题，连接是成功的

**python 版本:** `python2.7`

**操作系统:** `mac 10.13.6`

**设备:**
 - 系统: [e.g. Android 4.4.4]
  木木模拟器 1.4.10

**其他相关环境信息**

**Comment by adolli** [comment]
木木模拟器我记得还要勾选上use JAVACAP

**Comment by rockywhisper** [comment]
@dingwenjie  

你好，文档中的[模拟器连接教程](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/2_device_connection/3_emulator_connection.html#id2)比较清晰，勾选javacap后应该可以正常使用。

![image](https://user-images.githubusercontent.com/8188879/45273389-1d7c5c80-b4e5-11e8-9ab7-63deb1520fab.png)

验证过没有问题，本issues暂时关闭了哈  :-)

**Comment by dingwenjie** [comment]
@adolli @rockywhisper 嗯嗯多谢，非常感谢回复
