### ISSUE TITLE
未连接设备log文件为空时，测试报告应该是failed吧。。。

### ISSUE THREAD

**Issue by shmily-cwt** [AirtestProject/AirtestIDE#235]
未连接设备log文件为空时，测试报告应该是failed吧。。。
![image](https://user-images.githubusercontent.com/28520643/45862994-ba24e100-bda6-11e8-8e8b-159a350bfd74.png)
![image](https://user-images.githubusercontent.com/28520643/45863000-c610a300-bda6-11e8-8b7d-0eb0d5cb0852.png)

**Comment by rockywhisper** [comment]
@shmily-cwt  Hi，如果是未连接设备的话，运行时候会报错，并且无法生成log.txt：
![image](https://user-images.githubusercontent.com/8188879/46590530-9243b600-cae6-11e8-9400-669baa3cea4c.png)

这样在执行report生成报告时会报错无法生成报告的：
![image](https://user-images.githubusercontent.com/8188879/46590543-b2737500-cae6-11e8-8762-a70121d916af.png)

请确认具体的报错场景和信息，本issues暂时关闭。如需进一步帮助可以新开一个issues哈。
