### ISSUE TITLE
Add custom path of sys.path didn't work

### ISSUE THREAD

**Issue by padiyes123** [AirtestProject/AirtestIDE#237]
Remove any following parts if does not have details about

**Describe the bug**
Based on this link: [http://airtest.netease.com/docs/en/1_online_help/advanced_features.html#add-sys-path-path](http://airtest.netease.com/docs/en/1_online_help/advanced_features.html#add-sys-path-path)
We could add custom sys.path, so the script could use modules from Python. In this case, I'm trying to use **pyautogui** module, and create alert. But after edit the settings and put Custom Python Path to the site packages, it won't works anyway. I've modify the sys.path by adding some special char but still with no result. More details provided below after 4 run.

**Screenshots**
Running AirtestIDE and it's console window:
![image](https://user-images.githubusercontent.com/28912459/46139495-e34ae300-c278-11e8-9a13-f0a60e905ed9.png)

Setting of Airtest:
![image](https://user-images.githubusercontent.com/28912459/46139363-8f3ffe80-c278-11e8-8f69-63daa871042d.png)

**To Reproduce**
1. Open Airtest IDE
2. In the Script Editor, import the needed module and write the script, in my case:
    _import pyautogui_
    _pyautogui.alert('This is an alert box.')_
3. Acces menu Options > Settings
4. Fill Custom Python Path with custom Python module. In my case "C:\Development\Python\Python36\Lib\site-packages"
5. Click OK
6. Run the script (or press F5)
7. Notice that nothing happened, the LOG running but the script wasn't executed

#Step4 modified already with this format but with no result:
- path
- [path]
- ['path']
- [r'path']

**Expected behaviour**
An alert window will be appear, as shown below when executed in python interface:
![image](https://user-images.githubusercontent.com/28912459/46140027-29ed0d00-c27a-11e8-934d-b6f76d63f733.png)

**AirtestIDE version:** `0.1.5`
**AirtestIDE version:** `1.0.0`

**Platform:** `Windows7 64bit,`

**Comment by yimelia** [comment]
@padiyes123 Sorry, we modified the feature but didn't update the document. if you use AirtestIDE 1.0.0, just set your python.exe like this:

![image](https://user-images.githubusercontent.com/6896468/46242725-b32d4c80-c3fe-11e8-932e-3d9ab3eac9da.png)

**Comment by yimelia** [comment]
@padiyes123 make sure you have installed airtest/pocoui to your python env. please run `pip install airtest` & `pip install pocoui` in your python environment. if you need more help, please reopen the issue :)

**Comment by padiyes123** [comment]
Utilizing AirtestIDE v100, your suggestion work like a charm. Thanks for your help, looking forward the next collaboration with you again 👍
