### ISSUE TITLE
[Windows] Airtest unable to generate HTML report when path contain space

### ISSUE THREAD

**Issue by padiyes123** [AirtestProject/AirtestIDE#238]
**Describe the bug**
In Windows OS, Airtest unable to generate HTML report when Aitest path or script path contain space.

**Screenshots**
![image](https://user-images.githubusercontent.com/28912459/46459239-7d171080-c7e2-11e8-99f4-88c6b38498e1.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Put the master of Airtest into a folder that contain space in the log. As well as the .air script.
2. Open the Airtest and run the script.
3. Generate HTML Log.
4. Please note that Airtest unable to create the HTML Log.

**Expected behaviour**
The HTML log should be created despite any char put into the path.

**AirtestIDE version:** `1.0.0`

**Platform:** `Windows10 64bit`

**Smartphone (please complete the following information):**
 - any

**Additional context**
I've create small batch script to overcome this issue. The main idea is to put double quotes on the path string before throw it in a command. Would be great to have this implemented in Airtest as default.
[create log.html.bat.zip](https://github.com/AirtestProject/AirtestIDE/files/2445339/create.log.html.bat.zip)

**Comment by yimelia** [comment]
hi @padiyes123 ,please provide the error messages as following: 
![image](https://user-images.githubusercontent.com/6896468/46590583-01b9a580-cae7-11e8-9aea-6231ce23c0a7.png)

thank you :)

**Comment by padiyes123** [comment]
re-Tested in Airtest v110 (_AirtestIDE_2018-11-06_py3_win64_), this issue no longer happened.
