### ISSUE TITLE
[Windows] How to find URI of running program in Windows

### ISSUE THREAD

**Issue by padiyes123** [AirtestProject/AirtestIDE#239]
Remove any following parts if does not have details about

**Describe the bug**
[Windows] How to find URI of running program in Windows? Inside the Log Viewer if we run any script in Windows App (we need to connect it manually), there's an URI shows, indicate which App we will connect the script. The URI changes each time the App relaunched (like PID), but it's longer than PID itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/28912459/46460168-5c9c8580-c7e5-11e8-9a6b-a4bc82ed4cc4.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Airtest
2. Connect manually to any windows program (either Select Window or Search WIndow)
3. Run any script
4. Inside Log Viewer, please notice the URI (marked with RED in screenshot above)
5. How to find URI of running program in Windows

**Expected behaviour**
There's should be a way to find this number, so we could automatically connect the AUT from the start we're executing the script.

**AirtestIDE version:** `1.0.0, any`

**Platform:** `Windows10 64bit, etc.`

**Smartphone (please complete the following information):**
 - N/A, connect to WIndows App instead

**Additional context**
URI could be saw in Airtest Console Windows too, when we use Select WIndow manually to connect with Windows App, as shown below:
![image](https://user-images.githubusercontent.com/28912459/46460869-73dc7280-c7e7-11e8-8b73-0a9fdce7ae79.png)

**Comment by rockywhisper** [comment]
@padiyes123  Hi, sorry, we have a holiday and the response is not timely.

As for this problem, we have [a detailed instruction about the windows URL usage](https://airtest.readthedocs.io/en/latest/README_MORE.html#connect-windows-application), you have two options:

 - use `"Windows:///"`, `airtest` will use the whole desktop;
 - use `Regular expression` of the title of the window to select the target window, like `"Windows:///?title_re=unity.*"`.

**Comment by padiyes123** [comment]
@rockywhisper Thanks for the feedback, really appreciate it :) 

Indeed that we could capture the title of the application in order to connect the Airtest. But, I would like to avoid that nor to connect the whole desktop. Here my case:
1. I need to run 4 instance of the App (calculator) << able to do it using Airtest
2. I need to connect to the first App only (the first calculator window) << still need to research how to do it
I saw that the URI always vary from each launch, so I'm hoping that it will help me to achieve that.

Is it able to do utilize current airtest feature?

**Comment by rockywhisper** [comment]
@padiyes123  Hi, I'm assuming that you have 4 instances of calculator already, and you want to get the handle of the top one. We know that all the windows are shown layer by layer and we call the layer sequence Z-order. And there's a way to get all the target handles in Z-order at one time.

 - **1.  Assuming you have 4 windows on hand:**
![image](https://user-images.githubusercontent.com/8188879/46597547-20ce2c80-cb13-11e8-90fb-8d61f08bcf23.png)

 - **2. Get the handle list of the 4 windows whoes `Regular expression` is `title_re=".*计算器.*"`**:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pywinauto.findwindows import find_elements


def main():
    # the Chinese charactors "计算器" means "Calculator", you can replace it with English title:
    element_list = find_elements(title_re=".*计算器.*")
    # print each of the handle of the "计算器" windows:
    for element in element_list:
        print(element.handle)


if __name__ == '__main__':
    main()
```

The printed data is the handles of Calculators you want in Z-order. (The first one is the top one, the last handle is of the bottom window.)


Hope this is what you want      :-)

**Comment by padiyes123** [comment]
Hello, Could you please review my result below? Actually, the script was able to saw those 4 instances, but it still failed to print each of the handle.
![image](https://user-images.githubusercontent.com/28912459/46729441-87884d00-ccaf-11e8-99c6-d5eddf5f1d31.png)

**Comment by rockywhisper** [comment]
@padiyes123  
Hi, would you look at line 6 of this script:
![image](https://user-images.githubusercontent.com/8188879/46736672-35a1f000-cccc-11e8-9051-182b338118d4.png)
You're trying to connect a window with ```Windows:///?title_re=Calculator```, there're 4 windows, so airtest cannot tell which one to connect.

**So you can just delete line 6 and run it again to get the handles printed.**

Actually, you should get the handle of the target window, then connect the window with the handle.
``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pywinauto.findwindows import find_elements


def main():
    # the Chinese charactors "计算器" means "Calculator", you can replace it with English title:
    element_list = find_elements(title_re=".*计算器.*")
    # print each of the handle of the "计算器" windows:
    for element in element_list:
        print(element.handle)
    # get target handle of top Calculator window (note: next line will throw exception if no Calculator window exists...)
    target_handle = element_list[0].handle
    # connect the window with the handle, just like the way AirtestIDE do:
    connect_device("Windows///%s" % target_handle)

main()
```
![image](https://user-images.githubusercontent.com/8188879/46737170-6898b380-cccd-11e8-8020-a88b44143ebb.png)

**Comment by rockywhisper** [comment]
@padiyes123  

Hi, I'll close this issue now. 
If there's any further question, just tell me   :-)
