### ISSUE TITLE
AirtestIDE 后续有开源的计划吗

### ISSUE THREAD

**Issue by CPPAlien** [AirtestProject/AirtestIDE#24]
如果开源，可以把该 IDE 扩展到更多的场景中去，比如普通应用的测试等，期待你们会开源 ：）

**Comment by adolli** [comment]
IDE只是个快速产出测试脚本的工具，我们的自动化测试框架Airtest和Poco已经开源，如果需要扩展到普通应用中使用，可以考虑直接把框架当作代码库来使用。

```bash
pip install airtest pocoui
```

**Comment by Meteorix** [comment]
@CPPAlien 你好，“普通应用的测试”指的是Android源生应用的测试吗？

另外对于IDE，我们目前还在整理代码，后续不排除开源的可能

**Comment by CPPAlien** [comment]
太棒了，希望你们可以开源，这样开发者可以做些其它平台的支持，比如 iOS、Web 等。目前我想尝试 把 AirTest 模块 和 Appium 结合起来，做一下 iOS 和 Android 应用的测试。
