### ISSUE TITLE
一加5T，Android8.1.0，poco辅助窗选择Android后手机上的pocoservice一直在重新安装并运行

### ISSUE THREAD

**Issue by malepiwei** [AirtestProject/AirtestIDE#241]
**描述问题bug**
连接上手机后，运行脚本或者poco辅助窗选Android后，手机一直在重复安装并运行pocoservice
log提示still waiting for uiautomation ready.

**设备:**
 - 型号: 一加5T
 - 系统: Android 8.1.0

**Comment by rockywhisper** [comment]
@malepiwei  
Hi，应该是兼容性问题，我们会验证下这个设备。

感谢反馈啦  :-)

**Comment by rockywhisper** [comment]
@malepiwei 
你好，我们本地的一加5T手机上，对设备进行重启问题可以解决。

该设备系统有点独特，可以尝试下重启设备的方法试试看 :-)

**Comment by yimelia** [comment]
如果还有问题，请reopen这个issue哈
