### ISSUE TITLE
华为某一款手机无法使用airtest工具

### ISSUE THREAD

**Issue by yyqbqw** [AirtestProject/AirtestIDE#244]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。)
使用该手机测试，在airtest点击connect，log查看框显示 
ADB端口:5037 被以下进程占用: 'svchost.exe', 进程编号pid: 4196.
请手动关闭该进程!
但是端口冲突已在环境变量中设置新的端口，而且在cmd中执行adb devices是可以显示设备的，其他类型手机连接均没有问题。

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**复现步骤**
1. Go to '刷新ADB'
2. Click on 'connect'
3. See error

**预期效果**
(预期想要得到什么、见到什么)
可以连接成功，显示手机桌面

**python 版本:** `python2.7`

**操作系统:** `Windows10  64bit`

**设备:**
 - 型号: [e.g. huawei ]
 - 系统: [e.g. Android 9.0]
 - (别的信息)

**其他相关环境信息**

**Comment by rockywhisper** [comment]
@yyqbqw  
此处是adb端口被占用导致的，log窗提示了：
“ADB端口:5037 被以下进程占用: 'svchost.exe', 进程编号pid: 4196.”
目前IDE内部都默认用了5037端口，在环境变量中设置新端口确实会导致问题，建议用回默认的5037.

端口占用解决方法，参看[博客-方法一](https://www.jianshu.com/p/ca33c67302d7)杀掉进程。然后使用IDE进行连接。

**Comment by yyqbqw** [comment]
但是其他型号的手机是可以正常连接的，也可以正常显示手机桌面，是不是由于手机和airtest不兼容呢

**Comment by rockywhisper** [comment]
@yyqbqw 

1、端口修改之前，其他手机可以正常连接吗？

2、Android 9.0设备请使用AirtestIDE官网上的最新版本，如果仍然不行，可以提供下手机具体型号。

**Comment by yyqbqw** [comment]
@rockywhisper 谢谢，下载了最新版本，已经可以使用
