### ISSUE TITLE
Selenium Window模式，点击airtest_touch控件，页面会放大很多倍，无法截取想要的图片

### ISSUE THREAD

**Issue by wuzhen1** [AirtestProject/AirtestIDE#248]
![qq 20181024170306](https://user-images.githubusercontent.com/44185122/47419416-b8d44300-d7ae-11e8-91e4-4557f5f51430.png)
![qq 20181024170319](https://user-images.githubusercontent.com/44185122/47419427-bd98f700-d7ae-11e8-82fe-027b50660879.jpg)

**Comment by zzldjkzxf** [comment]
@wuzhen1  看你连了笔记本的双屏，可能是两个屏幕的分辨率不同造成的，要不你试试只用笔记本，看能否正常截图？

**Comment by rockywhisper** [comment]
@wuzhen1  你好，这个issue暂时关闭了哈，如果仍有问题可以再新建一个.

**Comment by yimelia** [comment]
可以对另外一个屏幕设置笔记本的相同分辨率，保持2个屏幕分辨率相同的情况下，再重新尝试看看，这个单先关闭了。
