### ISSUE TITLE
[Windows10] Memory issue with windows app

### ISSUE THREAD

**Issue by huy2368** [AirtestProject/AirtestIDE#249]
**Describe the bug**
My computer has 16Gb RAM. I have started running script on Airtest for 20 minutes, on Task manager memory is increased from 2x% to 9x% then OS kills all running apps. I didn't see those RAM differences in Airtest process but memory is 2x% as usual after I stop running my script.

**Screenshots**
![image](https://user-images.githubusercontent.com/39150262/47424365-b58e8680-d7b1-11e8-8175-5fd0a5b17b1b.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Airtest
2. Open script. Use function connect_device("Windows:///?title=") to connect a windows app and make a loop with while True:.
3. Run script.
4. Check memory on Task manager after 20 minutes

**Expected behaviour**
When i run my script above with adb connect to a Android phone, it is fine.
I hope that is same on Windows with a Windows app too.

**AirtestIDE version:** `1.0.1 11-10-2018

**Platform:** `Windows10 64bit, etc.`

**Comment by yimelia** [comment]
hi @huy2368 , sorry, this bug has been fixed and will be submitted at the next update.

**Comment by huy2368** [comment]
perfect. thanks @yimelia.
can you share me exact schedule?

**Comment by yimelia** [comment]
I am not sure now, but if you want to run a long script, just try to use the [command line](https://airtest.readthedocs.io/en/latest/README_MORE.html#running-air-from-cli)

**Comment by rockywhisper** [comment]
@huy2368  
Hi, buddy, we plan to release the fixed version next Tuesday. (2018-11-06)

We'll close this issue after that.

**Comment by huy2368** [comment]
good morning,
great news. thank you a lot for your information.

**Comment by rockywhisper** [comment]
@huy2368  
Hi, we've released the fixed version today. Hope you can have a try.     :-)
