### ISSUE TITLE
Android8.1 小屏智能机无法使用

### ISSUE THREAD

**Issue by 10cl** [AirtestProject/AirtestIDE#250]
$ adb shell wm size
Physical size: 240x320
版本： Android 8.1 

![image](https://user-images.githubusercontent.com/6964022/47473257-8b39d900-d844-11e8-9db6-10f3b9efeb6c.png)
![image](https://user-images.githubusercontent.com/6964022/47473283-9d1b7c00-d844-11e8-9f91-82228687a187.png)

无法点击，代码无法操作也无法实现点击。
ACTION 使用 usb ADB touch 也无效
只有这排按键有效
![image](https://user-images.githubusercontent.com/6964022/47473347-e53a9e80-d844-11e8-928e-7beb8b92055a.png)

**Comment by rockywhisper** [comment]
@10cl 
Hi，请恕我孤陋寡闻，确实没见过这种机器啊...能够提供一下手机型号么.

另外IDE的控制台窗口上可以看下是否有报错，也可以一并贴出截图哈。  :-)

**Comment by rockywhisper** [comment]
@10cl 
btw, 小屏手机不是触屏的？
是使用方向键控制的么，如果是这样的话，可以考虑使用纯adb指令来写脚本。

**Comment by 10cl** [comment]
@rockywhisper 
不是大众机，KONKA COOLPAD 啥的，按键 + 鼠标手的模式搞，IDE如果可以模拟鼠标就能搞定，我先直接adb指令来搞吧 -。-
![image](https://user-images.githubusercontent.com/6964022/47552506-72f6b680-d937-11e8-92f2-0db895744191.png)

**Comment by rockywhisper** [comment]
@10cl   
Hi，这种机器没有触屏功能，模拟input支持应该是被禁用掉了（类似于电视盒子），应该只能用模拟鼠标了。请知悉。

我把这个issues关闭了哈~
