### ISSUE TITLE
.air文件夹里的写文件，用命令airtest run运行无法写入

### ISSUE THREAD

**Issue by zwwtx** [AirtestProject/AirtestIDE#251]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题（本软件）

**描述问题bug**
air文件里的读写文件 在pycharm还有airtestIde里运行都可以
但是用命令airtest run 运行就不行了
文件存不起来

**截屏**
![image](https://user-images.githubusercontent.com/44486186/47542367-a6254f80-d90f-11e8-80c1-0a71af720fa2.png)
![image](https://user-images.githubusercontent.com/44486186/47542480-32d00d80-d910-11e8-893e-c5fd8ad552ba.png)

**复现步骤**
1. airtestIde进行创建脚本XXX.air，里头的.py文件里输入读写文件代码
2. airtest run运行脚本
D:\InstallSoft\Python27\python.exe E:/cl_game_with_android_mobile/runner/runner.py
airtest run E:\cl_game_with_android_mobile\testcases\test_create_role.air --device Android:///d6ebce81 --log E:\cl_game_with_android_mobile\test_reports\20181026095042

**预期效果**
用命令airtest run 运行 能写文件
fp = open(file_path, 'r+')
fp.write(id_str)
fp.close()

**python 版本:** `python2.7`

**操作系统:** `Windows10 64bit`

**设备:**
 - 型号: OnePlus 3T
 - 系统:Android 7.1.1

**其他相关环境信息**
air文件里的读写文件 在pycharm还有airtestIde里运行都可以
但是用命令airtest run 运行就不行了,读文件可以 写文件不行

**Comment by yimelia** [comment]
环境问题，可自行解决，我直接关闭本问题了

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/47543641-c6580d00-d915-11e8-87e5-744d4cdc1035.png)

**Comment by yimelia** [comment]
![file](https://user-images.githubusercontent.com/6896468/47543883-eb00b480-d916-11e8-86fe-50815d8231c3.gif)
