### ISSUE TITLE
Text instead of image

### ISSUE THREAD

**Issue by chelovekley** [AirtestProject/AirtestIDE#253]
Airtest IDE v1.0.1

Hello.
When i use any of the functions:
touch
swipe
....
The image is attached to the code as a link.

Tell me 
How to change the format.

![default](https://user-images.githubusercontent.com/44580442/47661661-13fd9f80-dbcc-11e8-8fcb-dbf3f2c7b581.png)

**Comment by yimelia** [comment]
hi @chelovekley , unzip the AirtestIDE to English path may avoid this problem :)

**Comment by yimelia** [comment]
update to AirtestIDE v1.2.0 may solve this problem
