### ISSUE TITLE
使用rk 开发板，android5.1, 接显示器，无触摸，只有鼠标输入 

### ISSUE THREAD

**Issue by monkeycraps** [AirtestProject/AirtestIDE#256]
使用rk 开发板，android5.1, 接显示器，无触摸，只有鼠标输入 
尝试过 git@github.com:LoCorVin/minitouch.git，里面增加了 single touch 的支持，需要检测事件 
libevdev_has_event_code(evdev, EV_ABS, ABS_X); 还是不支持 

这种情况 minitouch 不支持，use adb touch 也没反应，有人知道咋办么？
另外rk 开发板，android5.1, 接红外触摸屏，minitouch 能检测到 mulit touch，但是输入的touch 事件无效

**Comment by rockywhisper** [comment]
@monkeycraps  
你好，如果minitouch和adb的操作输入都不行的话，可能暂时无法进行IDE的设备模拟操作。

我们手头没有类似的硬件设备，暂时也没有办法进行调试。   :-(

**Comment by monkeycraps** [comment]
> @monkeycraps
> 你好，如果minitouch和adb的操作输入都不行的话，可能暂时无法进行IDE的设备模拟操作。
> 
> 我们手头没有类似的硬件设备，暂时也没有办法进行调试。 :-(

1. 设备我可以提供一份给你们
2. 还是想用minitouch 完成这个功能，有什么思路么，ev_abs, abs_x 之类的定义我不太熟悉，我应该往哪个方向走

**Comment by monkeycraps** [comment]
> @monkeycraps
> 你好，如果minitouch和adb的操作输入都不行的话，可能暂时无法进行IDE的设备模拟操作。
> 
> 我们手头没有类似的硬件设备，暂时也没有办法进行调试。 :-(

另外我在杭州的，你们是在杭州的网易么

**Comment by monkeycraps** [comment]
修正 airtest 在红外触摸下的问题，已经设置修改python 路径指向本地执行，但是点击ide 里的屏幕还是没有反应
![1544121010308](https://user-images.githubusercontent.com/2322555/49604160-2f787900-f9c8-11e8-82dc-02f920555ea5.jpg)

**Comment by rockywhisper** [comment]
@monkeycraps   你好，请问是否可以提一个Airtest-pr？

**Comment by yimelia** [comment]
@monkeycraps 
最新版本的ide勾选adb touch后，支持直接操控设备屏幕，但是滑动操作有一定延迟，会等待鼠标操作完成后才进行滑动
