### ISSUE TITLE
电脑蓝屏，运行中的已有脚本代码会被清空

### ISSUE THREAD

**Issue by liszero** [AirtestProject/AirtestIDE#257]
使用airtest运行已保存的脚本的同时，使用迅雷下载文件，因迅雷突然大批量文件写入硬盘，导致电脑蓝屏，重启后项目包中py文件与图片正常，但py文件内容清空

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/cn/3_record_script/0_script_faq.html#id28
