### ISSUE TITLE
用Airtest图形辨识功能测试Flash游戏问题

### ISSUE THREAD

**Issue by frog7431** [AirtestProject/AirtestIDE#259]
我目前正在尝试用Airtest做UI自动化测试
不过因为对象是嵌在browser中的flash游戏，我原先的想法是透过selenium启动browser，透过chromeOpitons默认执行flash、到flash阶段时再运用airtest api辨识图片的功能，进行游戏UI的分辨

但目前参数设定上似乎没有发生效果
读取到flash的页面时，仍须手动启动flash
想请教你们该如何排除问题，感谢
```py
from airtest.core.api import *
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
from selenium.webdriver.chrome.options import Options

chromeOpitons = Options()

prefs= {
    "profile.managed_default_content_settings.images":1,
    "profile.content_settings.plugin_whitelist.adobe-flash-player":1,
    "profile.content_settings.exceptions.plugins.*,*.per_resource.adobe-flash-player":1,
}

chromeOpitons.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(chrome_options=chromeOpitons)
driver.get("xxxxxxxxxxxxxxxxxxxx")
```
**预期效果**
预期可自动载入flash后，可以Airtest api对flash进行图形辨识录制

**操作系统:** `Windows10 64bit`

**Comment by adolli** [comment]
尼个睇上去似系chrome driver嘅问题，你之前有无试过用selenium程式运行通过？

**Comment by frog7431** [comment]
@zzldjkzxf  我一开始是透过Airtest中的selenium window中的元件去访问内含flash的网页，但卡在需要手动启动flash的操作上，才寻找这个替代方案

# -*- encoding=utf8 -*-
__author__ = "test"

import os
from airtest.core.api import *
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
from selenium.webdriver.chrome.options import Options

print("os= ",os.getcwd())
chromeOpitons = Options()

prefs= {
    "profile.managed_default_content_settings.images":1,
    "profile.content_settings.plugin_whitelist.adobe-flash-player":1,
    "profile.content_settings.exceptions.plugins.*,*.per_resource.adobe-flash-player":1,
}

chromeOpitons.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(chrome_options=chromeOpitons)
driver.implicitly_wait(20)

driver.get("http://armorgames.com/play/1716/gemcraft?fp=b-strategy")

但从Airtest的log中没有看到错误讯息，不确定chrome设置失败的原因为何

**Comment by xin7c** [comment]
兄dei，貌似你是直接用的selenium lib？感觉是俩进程呢··

**Comment by frog7431** [comment]
@xin7c 是的，我查不到其他人使用Airtest测试flash网页的经验，所以套selenium查到的方式试试，可是执行时却也没收到错误讯息，不知该从何下手

**Comment by yimelia** [comment]
手动启动flash功能可能与浏览器的设置有关？可以考虑修改浏览器的默认安全策略来使它默认开启flash，我先暂时关闭这个issue了
