### ISSUE TITLE
录制的时候能不能记录我每个操作的间隙

### ISSUE THREAD

**Issue by yuchong2018** [AirtestProject/AirtestIDE#26]
自动添加sleep时间？

**Comment by rockywhisper** [comment]
你好，一般录制间隙会比正常操作长，保存录制操作间隙可能不太妥当。
我们有回放间隔的参数设置，可以查看下高级设置的使用说明，调整其中的OPDELAY：http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_advanced_features/1_script_record_features.html#id10

**Comment by Meteorix** [comment]
根据我们内部的使用经验，自动sleep并不好，建议手动sleep，更好的是在必要的时候使用wait函数
