### ISSUE TITLE
IDE运行脚本，安卓device screen会被断开

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/AirtestIDE#260]
**描述问题bug**
升级到IDE 1.1.0后，运行脚本，安卓device screen会被断开，  
此问题在v1.0.0上无问题是`正常的`

**预期效果**
预期就是跑着脚本，电脑上的截屏依然存在！

**python 版本:** `python3.7`

**操作系统:** 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/11660641/48183329-501dc680-e369-11e8-99ec-1124d2bbd5f2.png">

**Comment by yimelia** [comment]
感谢反馈，这个问题可能是我们升级新版中造成的新bug，我们会查一下

**Comment by xin7c** [comment]
> 感谢反馈，这个问题可能是我们升级新版中造成的新bug，我们会查一下

还有就是当我用command + Q退出IDE的时候，会提示崩溃，我直接用鼠标X掉就没这个提示。

**Comment by yimelia** [comment]
@xin7c 屏幕断开这个问题可能是ADB版本不一致导致的，可以尝试将本地python环境的airtest更新到最新版本，以及我们的AirtestIDE也可以同步更新一下

**Comment by yimelia** [comment]
duplicated #265

**Comment by yimelia** [comment]
@xin7c 用command + Q退出IDE的时候的崩溃问题，我们这里没能成功重现，你可以试下[用命令行启动IDE](http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2)，然后退出IDE崩溃后，看一下命令行中是否有错误log，可以另开一个issue
