### ISSUE TITLE
IDE运行脚本，安卓device screen会被断开

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/AirtestIDE#265]
如题，请问这样是正确的吗？？

**Comment by yimelia** [comment]
已确认该问题是1.1.0带来的新问题，目前已知的简单解决方案是，将旧版本IDE（例如没问题的[1.0.1版本](http://airtest.netease.com/changelog.html#v1_0_1)）文件夹中，`airtest\core\android\static\adb\windows`这个路径下的3个adb文件复制出来，替换掉新版本同一目录下的3个文件，即可消除此问题。

非常抱歉，我们将在下个版本放出时修复这个问题。

**Comment by yimelia** [comment]
关于ADB的版本统一问题，请各位参考[文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#airtestadb)
