### ISSUE TITLE
循环怎么编写，怎么设置循环次数

### ISSUE THREAD

**Issue by yuanze12345678** [AirtestProject/AirtestIDE#267]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。)

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yuanze12345678** [comment]
# -*- encoding=utf8 -*-
from airtest.core.api import *
auto_setup(__file__)
touch(Template(r"tpl1541930024516.png", record_pos=(-0.111, 0.792), resolution=(720.0, 1440.0)))#1
touch(Template(r"tpl1541930026291.png", record_pos=(0.135, 0.785), resolution=(720.0, 1440.0)))#2
怎么循环1和2

**Comment by yimelia** [comment]
airtest是python的第三方库，所编写出来的脚本依然是python脚本，请遵照python语法来写即可。
如果需要教程，请参考 [这里](https://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000/001431676242561226b32a9ec624505bb8f723d0027b3e7000)

**Comment by yuanze12345678** [comment]
谢谢
