### ISSUE TITLE
swipe 窗口参数说明有step参数，但是实际显示又没有

### ISSUE THREAD

**Issue by yuchong2018** [AirtestProject/AirtestIDE#27]
![image](https://user-images.githubusercontent.com/31157418/37693135-a43c7bc6-2cf8-11e8-832e-ddcdf3b68116.png)

**Comment by yuchong2018** [comment]
swipe操作好像比较麻烦，不明白具有怎么操作

**Comment by yuchong2018** [comment]
swipe(Template(file:///D:/AirtestIDE/untitled.air/tpl1521601755054.png, record_pos=(-0.016, 0.301), resolution=(1080, 1776)), vector=[-0.1873, 0.0001])
这个vector参数怎么解释。我向←滑了一个屏幕，但是实际运作的时候只滑动了一点点距离，导致没有滑屏成功

**Comment by rockywhisper** [comment]
vector=[-0.1873, 0.0001]  x=-0.1873意味着滑动时向左滑动0.1873宽度的距离，y=0.0001意味滑动时向上滑动0.0001的高，是滑动矢量的概念。
但是手机的响应一般与滑动距离和滑动时间都有关系，每台手机的响应情况均有所不同，你可以把duration调整大一些，不如duration=2，意思是2s才完成整个滑动，可以观察下手机的滑动响应效果。
