### ISSUE TITLE
可以通过坐标点击吗，怎么编写通过坐标点击脚本？怎么无限循环脚本？并记录脚本循环了多少次。

### ISSUE THREAD

**Issue by linyinmobayu** [AirtestProject/AirtestIDE#271]
![1542032489 1](https://user-images.githubusercontent.com/44891340/48353116-9789b700-e6c9-11e8-9e6e-410eb1fc05c3.jpg)
# -*- encoding=utf8 -*-

（源码）from airtest.core.api import *

auto_setup(__file__)

for i in range(10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000):  
    touch(Template(r"tpl1542028072156.png", record_pos=(-0.372, 0.725), resolution=(1080.0, 1920.0)))#1
    touch(Template(r"tpl1542028077488.png", record_pos=(-0.122, 0.711), resolution=(1080.0, 1920.0)))#2
    touch(Template(r"tpl1542028081352.png", record_pos=(0.125, 0.711), resolution=(1080.0, 1920.0)))#3
    touch(Template(r"tpl1542028084478.png", record_pos=(0.389, 0.718), resolution=(1080.0, 1920.0)))#4
    touch(Template(r"tpl1542028081352.png", record_pos=(0.125, 0.711), resolution=(1080.0, 1920.0)))#3
    touch(Template(r"tpl1542028077488.png", record_pos=(-0.122, 0.711), resolution=(1080.0, 1920.0)))#2
    touch(Template(r"tpl1542028072156.png", record_pos=(-0.372, 0.725), resolution=(1080.0, 1920.0)))#1
    touch(Template(r"tpl1542028084478.png", record_pos=(0.389, 0.718), resolution=(1080.0, 1920.0)))#4
    click()#坐标=[60,750][180,810]
![1542033048 1](https://user-images.githubusercontent.com/44891340/48353551-afae0600-e6ca-11e8-979d-dbcf15f9f6df.jpg)

    谢谢，我刚刚使用这个框架

**Comment by yuanze12345678** [comment]
谢谢
