### ISSUE TITLE
[Airtest] Capture specific area function

### ISSUE THREAD

**Issue by padiyes123** [AirtestProject/AirtestIDE#272]
**Describe the bug**
In Airtest, we have snapshot to capture the whole screen of the device. But, for more details in image matching function, a more details of snapshot will be needed.
I have 2 solution in my mind:
a. Snapshot will be performed from specific coordinate to another one (from x1,y1 to x2,y2)
b. Snapshot will be performed from specific coordinate and extended to certain radius (start from x,y-radius to x,y+radius)
Is there something like that available in current Airtest version?

**Screenshots**
The Snapshot function listed in Airtest Assistant
![image](https://user-images.githubusercontent.com/28912459/48391310-9b085700-e738-11e8-9d14-25b71c006342.png)

**To Reproduce**
No additinal info to repro the issue.

**Expected behaviour**
Expected that new snapshot function to capture specific area available in Airtest. Or, there's something similar with it present in current Airtest?

**AirtestIDE version:** `1.1.0` (also occur in all previous version)

**Platform:** `Windows10 64bit, etc.`

**Smartphone (please complete the following information):**
 - Device: All the device
 - OS: All the OS

**Comment by yimelia** [comment]
> a. Snapshot will be performed from specific coordinate to another one (from x1,y1 to x2,y2)

try [this](https://pillow.readthedocs.io/en/5.3.x/reference/Image.html#PIL.Image.Image.crop)?

**Comment by padiyes123** [comment]
So, for the conclusion (cmiiw):
1. Currently there's no airtest feature to snapshot specific area from the device. And by the WontFix label, this feature also didn't planned in the near future.
2. It could be achieved using [PIL module](https://pillow.readthedocs.io/en/5.3.x/reference/Image.html#PIL.Image.Image.crop), thus require additional module in Python installation.
Thanks for the feedback @yimelia

**Comment by yimelia** [comment]
hi @padiyes123 , there is an [example](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/win/win.py#L105) in airtest.core.win

```
from airtest import aircv
img = aircv.corp_image(aircv.imread("filename.png"), [rect.left, rect.top, rect.right, rect.bottom])
```
hope this is helpful :)
