### ISSUE TITLE
[Airtest] Multi Touch/Multi Tap in Android

### ISSUE THREAD

**Issue by padiyes123** [AirtestProject/AirtestIDE#273]
**Describe the bug**
Is there any way to perform Multi Touch in Android? 
I've search all of the documentation of Airtest and even the ADB to perform Multi Touch with no result. Since there are some action that need multi touch and also multi-tap-and-hold in some applications, I'm really need this feature to work with.

**Screenshots**
No screenshot needed.

**To Reproduce**
No step needed to repro this issue.

**Expected behaviour**
Willing to have multi touch function and/or multi-tap-and-hold inside the Airtest.

**AirtestIDE version:** `1.1.0 and previous version`

**Platform:** `Windows10 64bit, etc.`

**Smartphone (please complete the following information):**
 - Device: All device
 - OS: Android

**Comment by yimelia** [comment]
see [this](https://github.com/AirtestProject/Airtest/blob/master/playground/android_motionevents.py)
