### ISSUE TITLE
如何生成可以独立查看的报告

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/AirtestIDE#274]
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
很简单，求问如何将日志生成在指定的文件夹下，截图不会丢失？  
目前我的操作是：
1、airtest run "AppiOS.air" --device iOS:///127.0.0.1:8100 --log "log/"  
2、airtest report "AppiOS.air" --log_root "log/" --static_root "log/report/"  
3、将静态文件放在log.html同一目录下，打包给别人，别人才能看到完整的日志  

**预期结果**
有没有一个标准的操作，能从命令行执行、生成日志，这个日志可以独立在任何机器上显示完整呢？

**python 版本:** `python3.7`

**操作系统:** `Mojava`

**Comment by yimelia** [comment]
report命令支持 `--export dir` 参数，可以指定一个导出目录，将报告导出为可以复制给别人看的完整文件夹

**Comment by xin7c** [comment]
> report命令支持 `--export dir` 参数，可以指定一个导出目录，将报告导出为可以复制给别人看的完整文件夹

谢谢
