### ISSUE TITLE
建议AirTestIDE可以自定义airtest的路径，可以选择不用内置的airtest

### ISSUE THREAD

**Issue by wanghehacker** [AirtestProject/AirtestIDE#275]
建议AirTestIDE可以自定义airtest的路径，可以选择不用内置的airtest

**Comment by yimelia** [comment]
设置文档在 [这里](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python)， 可以在本地python环境安装了airtest以后，设置到IDE里去，然后执行时就会使用本地的python.exe来运行了
