### ISSUE TITLE
[enhancement]AirtestIDE截图时提供生成截图中心点坐标的选项（或者截图模式下显示坐标并给一个能将当前坐标直接输出到代码的功能）

### ISSUE THREAD

**Issue by rebootag** [AirtestProject/AirtestIDE#276]
有情况下为了提高效率需要结合图像识别(Airtest，可识别图像，但是慢也占资源)和直接点击坐标（app的UI的固定位置，不灵活但是快且省资源）。建议给个截图后是生成template或者中心坐标的选项，或者不行的话给一个简单的中心坐标和template转换的功能（我用过template里的比例乘上分辨率但是出来的结果经常会不对）。

**Comment by yimelia** [comment]
你好，这个功能我们正在制作中了，预计下个版本会放出，感谢提议

**Comment by yimelia** [comment]
在AirtestIDE v1.2.0版本中我们提供了一个查看鼠标位置对应的屏幕坐标功能，具体设置和使用方法请查阅[文档](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#device)

另外，例如`touch` 和`exists`等多个接口返回值都是找到的坐标(x, y)，可以使用一个变量来接收这个坐标后，下次直接点击这个变量，也能达到你希望的效果。
