### ISSUE TITLE
Mac 10.14 连接设备报错

### ISSUE THREAD

**Issue by SingleDogLee** [AirtestProject/AirtestIDE#278]
报错信息：
![image](https://user-images.githubusercontent.com/16349898/48711310-ed200f80-ec45-11e8-8ab6-9dd9c0cd8667.png)
系统信息：
![image](https://user-images.githubusercontent.com/16349898/48711325-f610e100-ec45-11e8-897f-c7b337af55cb.png)
python版本
![image](https://user-images.githubusercontent.com/16349898/48711336-fd37ef00-ec45-11e8-8637-623cc3357c70.png)
连接的设备是模拟器，非真机

那个写死的路径是什么意思？另为什么会是3.6的版本。settings里面设置custom python好像没有生效

**Comment by yimelia** [comment]
连接设备时使用的是IDE内置的Python，与设置中的本地python无关（它是在跑脚本时使用的）。模拟器连接遇到问题可以参考 [这里](http://airtest.netease.com/docs/cn/2_device_connection/3_emulator_connection.html#id6)，勾选了 `use javacap`后如果依然连接失败，可以再加上勾选 `use adb orientation`后再连接即可。
