### ISSUE TITLE
打开airtest频繁闪退，需要重复打开多次

### ISSUE THREAD

**Issue by Justintang1225** [AirtestProject/AirtestIDE#279]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
每次打开airtest，前两次必定闪退
![image](https://user-images.githubusercontent.com/20553613/48592033-7fdc5800-e981-11e8-825c-354873201398.png)

```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by adolli** [comment]
看样子像显卡驱动比较旧，试试升级一下显卡驱动。

**Comment by yimelia** [comment]
可以参考 [文档](http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id3)
升级显卡驱动，升级DX版本，以及尝试禁用本地的集成显卡，保留独立显卡之后再重启，都有可能解决此问题
