### ISSUE TITLE
Recognizing two images 

### ISSUE THREAD

**Issue by antarnis** [AirtestProject/AirtestIDE#280]
I'm trying to do the following test:

```
If exist Button A or Button B:
    If exist Image A:
        Action A
    Elif exist Image B:
        Action A
    Else
        Break
```

Basically I would like to test two (2) UIs that has the same button functions. I tried using the 'and' function and the 'or' function. Both did not work. How do I go about doing so in Airtest?

**Comment by rockywhisper** [comment]
@antarnis  
Hi, sorry for late response.

There's `exists(image)` API in `Airtest` can do this, this API returns None if the image doesn't found in current screen.

```python
pos = exists(image_of_button_A) or exists(image_of_button_B)
# if image_of_button_A is not in current screen, 
# then exists(image_of_button_A) returns None,  pos=exists(image_of_button_B)

if pos:
    touch(pos)
else:
    # when pos is None, it means both image_of_button_A and image_of_button_B are not in current screen.
    pass
```
