### ISSUE TITLE
IDE左上侧录制按钮，点击一次后，仍显示的是“Start Recording”

### ISSUE THREAD

**Issue by 1986494745** [AirtestProject/AirtestIDE#282]
**描述问题bug**
IDE左上侧录制按钮，点击一次后，仍显示的是“Start Recording”

**截屏**
![image](https://user-images.githubusercontent.com/26402490/48932896-11773700-ef39-11e8-8f06-fe55976cc15c.png)

**预期效果**
录制按钮，未进行录制时，鼠标预览是“Start Recording”；
正在进行录制时，鼠标预览应是“Stop Recording”，但现仍显示为“Start Recording”

**python 版本:** `python2.7`

**操作系统:** `macOS 10.14.1`

**Comment by rockywhisper** [comment]
@1986494745   你好，感谢反馈，下个版本的IDE将会修复。
