### ISSUE TITLE
无法在IDE里对Android设备UI进行操作

### ISSUE THREAD

**Issue by Sunraych** [AirtestProject/AirtestIDE#283]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
无法在IDE里对Android设备UI进行操作

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**复现步骤**
1. 连接小米4 Android6.0手机设备
2. 在IDE上查看手机画面
3. 在IDE上对手机界面进行操作

**预期效果**
期望可以对手机界面进行操作并响应，包括点击、滑动等操作

**python 版本:** `python3.6`

**操作系统:** `MacOS 10.14.1`

**设备:**
 - 型号: 小米4
 - 系统: Android 6.0  MIUI 9
 - (别的信息)

**其他相关环境信息**

**Comment by yimelia** [comment]
小米手机连接请参考 [文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id8) 进行部分设置的修改。
本帖暂时关闭，若还是不行，请查看与IDE一同启动的命令行窗口里是否有报错信息，把报错截图贴出来，再reopen这个issue
