### ISSUE TITLE
ubuntu环境下 Python 的文件引用问题

### ISSUE THREAD

**Issue by achenglike** [AirtestProject/AirtestIDE#284]
ubuntu环境下的文件引用问题

```
from airtest.core.api import *
ST.PROJECT_ROOT = "/User/test/project"
# test1.air的实际路径为/User/test/project/test1.air
using("test1.air")
from test1 import test
```
在Ubuntu下不能会产生找不到test1的错误提示

![截屏](https://s1.ax1x.com/2018/11/29/FeZQQx.png)

`python3.6.0` IDE自带

Ubuntu16.04 LTS

**Comment by Jimmy36506** [comment]
![issur](https://user-images.githubusercontent.com/40386006/49359776-18a8fc80-f712-11e8-82f0-d00aa195864c.gif)
看到你的描述和图片上的路径是不一样的。或者再次确认一下路径是否正确？

**Comment by achenglike** [comment]
抱歉抱歉，我路径写错了，谢谢了。
