### ISSUE TITLE
请问在Ubuntu16.04下如何通过终端启动IDE？

### ISSUE THREAD

**Issue by Gpwner** [AirtestProject/AirtestIDE#285]
在官网下载.deb安装文件之后，使用dpkg -i 命令安装，装完之后没法启动IDE啊？
请问是怎么启动的呢？？？

**Comment by rockywhisper** [comment]
@Gpwner 
Hi，你好。
通过`dpkg -i AirtestIDE.deb`安装的软件，可以通过`dpkg -L AirtestIDE`定位软件位置。

安装位置位于`usr/bin`下面，可以直接通过以下指令启动软件：
```shell
/usr/bin AirtestIDE
```

**Comment by Gpwner** [comment]
root@ubuntu:~# dpkg -i AirtestIDE_2018-11-06_py3_ubuntu16-04.deb
(Reading database ... 105560 files and directories currently installed.)
Preparing to unpack AirtestIDE_2018-11-06_py3_ubuntu16-04.deb ...
Unpacking airtestide (1.1.0) over (1.1.0) ...
Setting up airtestide (1.1.0) ...
Processing triggers for mime-support (3.59ubuntu1) ...
root@ubuntu:~# /usr/bin AirtestIDE
-bash: /usr/bin: Is a directory
root@ubuntu:~#

**Comment by Gpwner** [comment]
> @Gpwner
> Hi，你好。
> 通过`dpkg -i AirtestIDE.deb`安装的软件，可以通过`dpkg -L AirtestIDE`定位软件位置。
> 
> 安装位置位于`usr/bin`下面，可以直接通过以下指令启动软件：
> 
> ```shell
> /usr/bin AirtestIDE
> ```

你看下面是我的控制台输出，怎么回事？

**Comment by Gpwner** [comment]
> @Gpwner
> Hi，你好。
> 通过`dpkg -i AirtestIDE.deb`安装的软件，可以通过`dpkg -L AirtestIDE`定位软件位置。
> 
> 安装位置位于`usr/bin`下面，可以直接通过以下指令启动软件：
> 
> ```shell
> /usr/bin AirtestIDE
> ```

root@ubuntu:~# dpkg -i AirtestIDE_2018-11-06_py3_ubuntu16-04.deb
(Reading database ... 105560 files and directories currently installed.)
Preparing to unpack AirtestIDE_2018-11-06_py3_ubuntu16-04.deb ...
Unpacking airtestide (1.1.0) over (1.1.0) ...
Setting up airtestide (1.1.0) ...
Processing triggers for mime-support (3.59ubuntu1) ...
root@ubuntu:~# /usr/bin AirtestIDE
-bash: /usr/bin: Is a directory
root@ubuntu:~#

**Comment by rockywhisper** [comment]
@Gpwner  你好。

可以cd到```/usr/bin```目录下，启动AirtestIDE可执行文件。
如果在其他目录的话，可以```/usr/bin/AirtestIDE```启动。
