### ISSUE TITLE
Record Battery via Airtest

### ISSUE THREAD

**Issue by padiyes123** [AirtestProject/AirtestIDE#288]
**Describe the bug**
I want to record the battery over time, so I could know when or while using which function, the battery will be dropeed. 
It can be done via adb command (send the command via terminal), but unfortunately, it will kill the communication between Airtest and device (since they are also using the same adb to connect each other). Also, I can't just capture specific area, since I need to intepret the number to create a graphic.

**Screenshots**
No screenshot needed.

**Expected behaviour**
Is there any standard function could be used? Or a way out to record the device statistic like this?

**AirtestIDE version:** `all version`

**Platform:** `Windows10 64bit.`

**Smartphone (please complete the following information):**
 - All Device, all Firmware

**Comment by yimelia** [comment]
duplicated of AirtestProject/Airtest#191

please use `shell()` to run adb command, like [this](http://airtest.netease.com/docs/en/1_quick_start/2_test_with_Android_device.html#adb-instruction-call)

or this [example](https://github.com/AirtestProject/Airtest/issues/191#issuecomment-432487390) may help you
