### ISSUE TITLE
 illegal multibyte sequence

### ISSUE THREAD

**Issue by QAwangyang** [AirtestProject/AirtestIDE#29]
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 106-107: illegal
multibyte sequence

adb 可以 直接连上，重启了adb也不好使

**Comment by Meteorix** [comment]
你好，能提供完整的报错信息吗？

**Comment by QAwangyang** [comment]
Traceback (most recent call last):
  File "app\plugins\device\device_panel\util.py", line 25, in adbDevices
  File "airtest\core\android\adb.py", line 189, in devices
  File "airtest\core\android\adb.py", line 165, in cmd
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 106-107: illegal
multibyte sequence

**Comment by yimelia** [comment]
@QAwangyang 有没有同时开启了别的手机助手类型的软件，可以先全部关闭并且确保任务管理器里没有相关进程，然后再试试看

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/issues/10 与这个问题有关

@QAwangyang 先按 @yimelia 的说法试试，应该可以绕过这个问题

**Comment by QAwangyang** [comment]
@Meteorix  嗯那个issue 看了，试了下拔了usb线 远程连接也是同样的错误。进程里也没有adb进程。
用你们之前的那个atx 可以正常连上跑起来。

**Comment by Meteorix** [comment]
@QAwangyang 我们会尽快修复这个bug

@yimelia 可以先在IDE里面写一个更完善的adb device接口

**Comment by yimelia** [comment]
@QAwangyang 求顺便帮忙看一下具体的报错信息~~感激不尽！

进入AirtestIDE文件夹，在 “AirtestIDE/airtest/core/android/static/adb/windows” 目录下按住shift+鼠标右键打开命令行终端，输入”adb.exe devices”，然后看看输出的内容是什么，应该输出内容是有中文导致的问题

**Comment by Meteorix** [comment]
@QAwangyang 感谢，这个问题我们应该加到FAQ中

**Comment by QAwangyang** [comment]
@Meteorix  不客气 已经可以用了。。谢谢及时解决问题。。效率还挺高你们。。
