### ISSUE TITLE
import本地脚本报错ImportError: cannot import name 'xxxx'

### ISSUE THREAD

**Issue by cindy0403** [AirtestProject/AirtestIDE#290]
**描述问题bug**
本地文件夹结构：Scripts文件夹里有code.air文件和GetEmailCode.air文件
想在GetEmailCode.air脚本中使用code.air文件中定义的clearChromeData方法
from airtest.core.api import using
using(r"D:/Python_ALPHA/airTest_workspace/Scripts/code.air")
from code import clearChromeData

报错：ImportError: cannot import name 'clearChromeData'
右键选中【只运行选中代码】时正常执行

**截屏**
![importerror](https://user-images.githubusercontent.com/42829330/49858476-f4df6800-fe2f-11e8-9245-af326f06b038.jpg)

**复现步骤**

**python 版本:** 
3.6.5

**airtest 版本:**
1.0.24

**操作系统:**
Windows7 64bit

**设备:**
 - 型号: SO-03J
 - 系统: 7.1.1

**其他相关环境信息**
在airtestIDE中运行报错，但选择所要执行的代码右键【只运行选中代码时】可以正常debug运行

**Comment by yimelia** [comment]
暂时看不出问题，可以尝试在using之前把脚本父路径加入到sys.path试一下？

**Comment by cindy0403** [comment]
感谢确认，很抱歉，脚本中文件名有问题(code.air)，换成其他文件名脚本通过。打扰了，issue关闭。
