### ISSUE TITLE
命令行运行时输入框Yosemite错误

### ISSUE THREAD

**Issue by ljz2009y** [AirtestProject/AirtestIDE#292]
我通过IDE运行.air的任务时，程序可以正常的运行。
但是我切换到使用 python 来执行 
   airtest run xxx.air --recording --log log/xxx.air/
命令的时候，就会提示 Yosemite 错误，不能正常弹出键盘。

**Comment by ljz2009y** [comment]
![image](https://user-images.githubusercontent.com/2174368/50210778-f968cb00-03b1-11e9-96dd-37bef7b2962e.png)

**Comment by rockywhisper** [comment]
@ljz2009y 
你好。可以按照以下步骤进行修复：

 - 请确保本地airtest更新到最新版本 ``pip install -U airtest pocoui```;
 - [在AirtestIDE设置界面中配置本地python.exe路径](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html)，查看运行是否正常;
![image](https://user-images.githubusercontent.com/8188879/50211622-0d153100-03b4-11e9-84a4-7b455e42d35b.png)

 - 在命令行中运行测试脚本，查看是否恢复正常。

**Comment by yimelia** [comment]
请贴出报错log
