### ISSUE TITLE
web测试 脚本运行报错

### ISSUE THREAD

**Issue by SimThread** [AirtestProject/AirtestIDE#293]
**描述问题bug**
点击运行脚本（f5），报如下错误
RuntimeError: Invalid handle 0x20c26 passed to connect()

**截屏**
![image](https://user-images.githubusercontent.com/30016355/50394922-cb153200-079b-11e9-8e42-4e3432a14e81.png)

**复现步骤**
1.按照官网web自动化测试的步骤执行
2.点击运行脚本时报错

**预期效果**
正常执行脚本

**python 版本: 本地未安装，使用AirtestIDE

**操作系统:** `Windows10 64bit`

**其他相关信息**
window测试点击运行脚本正常，web测试点击运行脚本不正常

**Comment by yimelia** [comment]
重启IDE，不要连接任何windows窗口，然后直接运行web测试看看，不要把两种不同的测试写在同一个脚本里，否则需要另外管理窗口的连接。而且web测试下不需要`auto_setup`那一行，可以考虑去掉。

**Comment by SimThread** [comment]
@yimelia 多谢~重启之后好了
