### ISSUE TITLE
win10下web测试脚本未正常执行且不报错，macOS系统下正常

### ISSUE THREAD

**Issue by SimThread** [AirtestProject/AirtestIDE#295]
**描述问题bug**
win10下web测试 脚本未正常执行且不报错。最终执行代码停留在`ele = driver.find_element_by_xpath("//a[@href='https://www.591.com.hk/home/user/login']")`上

**截屏**
![image](https://user-images.githubusercontent.com/30016355/50411731-6a3e3600-083d-11e9-9b07-8a2b88a7a43f.png)

**代码**
```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)

driver.get("https://www.591.com.hk/")


# 进入登录页面 
ele = driver.find_element_by_xpath("//a[@href='https://www.591.com.hk/home/user/login']")
print(ele)
ele.click()
driver.switch_to_new_tab()
driver.find_element_by_xpath("//input[@type='tel']").send_keys("18050862370")
driver.find_element_by_xpath("//input[@type='password']").send_keys("cx5063820110")
driver.find_element_by_xpath("//input[@type='password']").click()
driver.find_element_by_id("btnSubmit").click()
driver.assert_exist("//*[@id=\"header\"]/div/div/div[2]/ul/li/a", "xpath", "登录成功.")
```

**复现步骤**
1.开启airtest ide
2.点击执行脚本（f5）

**预期效果**
正常执行登录成功demo

**python 版本:** 
airtest ide 自带python

**操作系统:** `Windows10 64bit`

**其他相关环境信息**
airtest ide版本 v1.1.0
mac上运行正常，win10运行异常

**Comment by zzldjkzxf** [comment]
@SimThread 一下子看不出来问题，是后面的代码都没有执行吗，看一下后台的log窗有没有trace？

**Comment by SimThread** [comment]
@zzldjkzxf 对，后面的代码没有执行，一直停留在ele = ...这一行。
从后台日志看不出问题来
```
{"tag": "function", "depth": 1, "time": "2018-12-25 15:13:50", "data": {"name": "get", "call_args": {"self": "<airtest_selenium.proxy.WebChrome (session=\"a0451f97613fc147d46eca20b79c45b2\")>", "address": "https://www.591.com.hk/"}, "start_time": 1545722027.032175, "ret": null, "end_time": 1545722030.424123}}
```

**Comment by SimThread** [comment]
@yimelia 
![image](https://user-images.githubusercontent.com/30016355/50416898-f3fdfb80-085d-11e9-8498-19e2616d32c7.png)
我检查了一遍，我电脑里没有类似手机助手，360的软件。可否告知如何完全卸载软件及其配置，我重新下载安装

**Comment by SimThread** [comment]
![image](https://user-images.githubusercontent.com/30016355/50417898-b4d2a900-0863-11e9-8eed-bd72d652d900.png)
想不通，我本地确实是有adb.exe文件存在的啊

**Comment by SimThread** [comment]
![image](https://user-images.githubusercontent.com/30016355/50418041-6376e980-0864-11e9-9043-333430650e63.png)
直接指向adb.exe devices会失败，./adb.exe devices和使用adb.exe的绝对路径就正常。但是这个是否是导致我现在这个问题的原因？

**Comment by SimThread** [comment]
在我连接安卓手机后打印的日志变化了。不明白的是为什么我运行web自动化脚本，打印了一堆安卓设备日志
![image](https://user-images.githubusercontent.com/30016355/50418400-1f84e400-0866-11e9-8bfd-3b7c7dcdfe2d.png)

**Comment by zzldjkzxf** [comment]
@SimThread 安卓这部分log原因我不太清楚是怎么回事。但是运行部分卡主可能是因为那个弹窗的原因，你手动把那个点掉看看会不会继续往下运行？

**Comment by SimThread** [comment]
@zzldjkzxf 跟弹窗没关系，这个我测试过，在mac上运行的时候也有这个弹窗，能正常执行。
刚刚又用本地的python执行，发现也可以，就是在我win10上的airtest ide运行异常
![image](https://user-images.githubusercontent.com/30016355/50419005-70e2a280-0869-11e9-861b-12cca40a8cc4.png)

**Comment by SimThread** [comment]
![image](https://user-images.githubusercontent.com/30016355/50436036-d0e75080-091e-11e9-831d-e6e95da11a16.png)
关联本地python后，运行正常
