### ISSUE TITLE
Poco连接真机，录制脚本后，执行报“invalid syntax”

### ISSUE THREAD

**Issue by ReddyRenJie** [AirtestProject/AirtestIDE#297]
链接android真机后（华为荣耀9i），通过poco录制脚本，点击运行脚本，提示“invalid syntax”

**截屏**
![_20181228143305](https://user-images.githubusercontent.com/41139448/50505311-dcb54d00-0aad-11e9-97a1-e4ed8d2d87ec.png)

**复现步骤**
from poco.drivers.android.uiautomation import AndroidUiautomationPocopoco(text="Attractions").click()
poco("android.widget.ScrollView").child("android.view.ViewGroup").child("android.view.ViewGroup")[1].child("android.view.ViewGroup")[1].child("android.view.ViewGroup").click()
poco(boundsInParent="[0.24722222222222223, 0.02456140350877193]").click()
poco("android.widget.FrameLayout").offspring("android.widget.FrameLayout").offspring("android.widget.FrameLayout").child("android.view.ViewGroup").child("android.view.ViewGroup")[1].child("android.view.ViewGroup").child("android.widget.ScrollView").child("android.view.ViewGroup").child("android.view.ViewGroup")[1].child("android.view.ViewGroup")[1].child("android.widget.HorizontalScrollView")[1].child("android.view.ViewGroup").child("android.view.ViewGroup")[1].child("android.view.ViewGroup")[0].click()

poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

**预期效果**
点击运行脚本后，运行脚本

实际：
 File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "D:\airtest\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\test.air\test.py", line 5
    from poco.drivers.android.uiautomation import AndroidUiautomationPocopoco(text="Attractions").click()
                                                                             ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 1 test in 0.151s

FAILED (errors=1)
[Finished]

**python 版本:** `我自己机器上装的是python3.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: 华为荣耀9i
 - 系统: [e.g. Android 8.1]

**Comment by yimelia** [comment]
是简单的python语法错误，增加回车即可
