### ISSUE TITLE
Selenium中，airtest_touch图像识别成功后不执行点击

### ISSUE THREAD

**Issue by hmdfdyh** [AirtestProject/AirtestIDE#298]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues

**描述问题bug**
如题

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/46224002/50519030-dea1ff00-0af3-11e9-937d-31396cd5cd2e.png)

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**Comment by zzldjkzxf** [comment]
这个匹配后是通过移动您的鼠标再模拟点击来完成的，再运行的时候不要动鼠标。然后可以观察一下是否鼠标位置有变化，和是否点击。
