### ISSUE TITLE
Poco连接真机，录制脚本后，执行报"ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接"

### ISSUE THREAD

**Issue by zhengxc117** [AirtestProject/AirtestIDE#299]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
Poco连接真机，录制脚本后，执行报"ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接

**截屏**
![_20181229111437](https://user-images.githubusercontent.com/46233973/50532880-f5c80780-0b5a-11e9-9a04-bb7ea0a4d7cf.png)

**复现步骤**
1. keyevent("BACK")
2. start_app("com.qiyi.video)
3. poco(text="游戏直播").click()

**预期效果**
能够正常点击

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: 小米 5X
 - 系统: Android 7.1.2

在windows上执行到poco的代码就出现此问题：
"ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接"
![_20181229111437](https://user-images.githubusercontent.com/46233973/50532880-f5c80780-0b5a-11e9-9a04-bb7ea0a4d7cf.png)

**Comment by yimelia** [comment]
应该是选错poco类型了，选到了unitypoco，而从截图来看这是个普通的android应用程序，选Android模式即可
文档见[这里](http://airtest.netease.com/docs/cn/6_poco_framework/poco_quick_start.html)
