### ISSUE TITLE
win10系统上链接华为P9手机，DeviceScreen比较模糊

### ISSUE THREAD

**Issue by niulamei** [AirtestProject/AirtestIDE#30]

**Comment by rockywhisper** [comment]
你好，IDE目前默认降低了手机视频流分辨率至800左右，以保证操作的流畅度，后面会考虑提供此处的设置选项，让用户可以控制。

**Comment by rockywhisper** [comment]
@niulamei  你好，外放版本：0.0.10将提供“选项”-“设置”-“Mobile Device Display Pixels”，可以手动调节手机画面的展示分辨率。
这个issue关闭了哈。
