### ISSUE TITLE
如何在使用selenium window打开浏览器后，使用脚本对页面进行调试？

### ISSUE THREAD

**Issue by SimThread** [AirtestProject/AirtestIDE#306]
**描述问题bug**
如何在使用selenium window
![image](https://user-images.githubusercontent.com/30016355/50885889-ee8ddd00-1429-11e9-9c74-66b6a8480b1e.png)这个按钮
打开浏览器后，使用脚本对页面进行调试？
比如打印一个节点信息？
比如只执行print(driver.find_element_by_xpath("//a[@href='www,baidu.comlogin']"))，如果要执行整个用例测试进行调试的话就得每次执行driver = WebChrome()

**预期效果**
断点调试或者不用每次都执行整个用例测试

**Comment by zzldjkzxf** [comment]
@SimThread  点击这个按钮![image](https://user-images.githubusercontent.com/33257680/50886817-6e1cab80-142c-11e9-9ea4-992a7c4e48e2.png)进入录制模式，所有节点信息都会在log查看窗显示出来。

**Comment by zzldjkzxf** [comment]
@SimThread  运行时好像不太好打印全部信息，你可以看看selenium的文档有没有对应的接口，selenium的api都是可以直接使用的

**Comment by SimThread** [comment]
@zzldjkzxf 多谢~
