### ISSUE TITLE
airtestIDE连接mumu模拟器失败  且黑屏

### ISSUE THREAD

**Issue by lucylucyi** [AirtestProject/AirtestIDE#308]
模拟器版本：2.0.31
日志信息：
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 get-state
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 wait-for-device
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.sdk
Device:127.0.0.1:7555 updated <airtest.core.android.android.Android object at 0x000001522F9A6278> -> <airtest.core.android.android.Android object at 0x000001523DEDA978>
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys display
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys SurfaceFlinger ; echo ---$?---
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys input ; echo ---$?---
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getevent -p ; echo ---$?---
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 install -r D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\apks\RotationWatcher.apk
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-2/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
D:\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---

**Comment by yimelia** [comment]
[mumu模拟器连接文档](http://airtest.netease.com/docs/cn/2_device_connection/3_emulator_connection.html#id2)
是否勾选了 `use javacap` 选项？

**Comment by lucylucyi** [comment]
是的！  勾选了
如果只勾选javac  会报这个错误：
LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 161, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 80, in __init__
  File "app\plugins\device\android\android_phone.py", line 106, in _initDev
  File "airtest\core\android\android.py", line 517, in display_info
  File "airtest\core\android\android.py", line 536, in get_display_info
  File "airtest\utils\snippet.py", line 106, in ready_func
  File "airtest\core\android\minicap.py", line 136, in get_display_info
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

如果同时勾选javac和use ADB oritation，也不行  但是会闪一下黑屏

**Comment by lucylucyi** [comment]
已经按照官方文档操作了  但就是连接不上！
