### ISSUE TITLE
怎么取消text("1")，输入后自动跳转到下一行

### ISSUE THREAD

**Issue by yuanze12345678** [AirtestProject/AirtestIDE#309]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里
**截屏**

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by rockywhisper** [comment]
@yuanze12345678 
Hi，你好，[text接口](http://airtest.netease.com/docs/cn/5_airtest_framework/airtest_all_module/airtest.core.api.html#airtest.core.api.text)有对应的`enter`参数可以设置，默认为True。可以写为：
```python
text("文本输入写在这里", enter=False)
```
