### ISSUE TITLE
s8手机的适配~

### ISSUE THREAD

**Issue by QAwangyang** [AirtestProject/AirtestIDE#31]
![image](https://user-images.githubusercontent.com/18697155/37749998-a5d9f5b2-2dc5-11e8-9637-14e539fb9109.png)

适配有点问题 导致点击也有问题

**Comment by rockywhisper** [comment]
你好，这个是已知问题哈，我们在FAQ进行了解决说明，请参考：
http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id6

**Comment by QAwangyang** [comment]
好的 谢谢
