### ISSUE TITLE
代码自动补全功能，在使用自定义启动器后失效

### ISSUE THREAD

**Issue by micdsk** [AirtestProject/AirtestIDE#310]
代码自动补全功能，在使用自定义启动器后失效
**前置条件**
1、已设置自定义启动器
![image](https://user-images.githubusercontent.com/38874187/51363610-c9792880-1b13-11e9-8290-4be62221d0ac.png)

2、使用了自定义启动器后，脚本里面不会再重复加如下图这段
![image](https://user-images.githubusercontent.com/38874187/51363786-9a16eb80-1b14-11e9-8f3a-981194c51330.png)

**多次调试后的效果**
1、air脚本有这段代码时，如下，提示正常

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)

![image](https://user-images.githubusercontent.com/38874187/51363469-0ee92600-1b13-11e9-85e4-ec227d517447.png)

2、去掉导入driver的那段代码，自动补全功能失效，如下图
![image](https://user-images.githubusercontent.com/38874187/51363700-3a204500-1b14-11e9-8ae0-893844b404e4.png)

3、英文点"." ，换成中文"。"，提示如下
![image](https://user-images.githubusercontent.com/38874187/51363728-5cb25e00-1b14-11e9-9713-0cfcd030c791.png)

**预期效果**
使用自定义启动器后，即使脚本里面不加以下代码
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)
也要能实现代码自动补全效果

**python 版本:** `python3.6`

**操作系统:** `Windows10`

**Comment by rockywhisper** [comment]
@micdsk  你好，这可能是处bug，我们会尽快查证修复。

**Comment by yimelia** [comment]
确实是BUG，但是并不是想象中的问题。
在截图显示出来的这个场景里，无论输入`.`还是`。`，都是不应该出现下拉菜单的，因为自动补全功能是分析当前的py文件（它并不能知道你的`launcher.py`里的内容与当前脚本有什么关联）。事实上，这个截图里输入`。`号后，出现的下拉补全菜单里的内容应该是无用的。
因此，这里的BUG应该是”**在输入中文符号时，不应该出现下拉补全菜单**“。
非常感谢你的测试与反馈，我们将在下个版本修复它。
