### ISSUE TITLE
MIX MAX手机连接成功后，点击connect,AirtestIDE中看不到手机屏幕的镜像

### ISSUE THREAD

**Issue by lixiaoyan88** [AirtestProject/AirtestIDE#311]
**描述问题bug**
MIX MAX手机连接成功后，点击connect,AirtestIDE中看不到手机屏幕的镜像

**截屏**
![image](https://user-images.githubusercontent.com/24809167/51732638-d5d42700-20b9-11e9-91d9-df328cfda557.png)

**复现步骤**
1. 连接小米MAX手机，系统6.0.1
2. 点击connet

**预期效果**
显示手机镜像

**python 版本:** `python2.7`

**操作系统:** `Mac OS`

**设备:**
 - 型号: [MI Max]
 - 系统: [e.g. Android 6.0.1]

**Comment by yimelia** [comment]
连接手机时，会往手机上安装几个apk，部分手机需要开启设置才能安装成功
小米手机的设置看[文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id8)
