### ISSUE TITLE
启动脚本时，log报错显示找不到元素

### ISSUE THREAD

**Issue by ayue-NAN** [AirtestProject/AirtestIDE#317]
**前提**
该apk使用的是cocos框架，已嵌入poco-sdk
**代码**
poco=AndroidUiautomationPoco()
time.sleep(5)
poco("android.widget.FrameLayout").offspring("android.widget.FrameLayout").child("android.widget.EditText")[1]

**Screenshots**
![image](https://user-images.githubusercontent.com/22957532/52557170-a0556a80-2e29-11e9-8e2a-6d90e357bf2c.png)

**本机+测试真机**
**AirtestIDE version:** `1.1.0`
**Platform:** `mac`
**Device:** xiaomi PAD
**OS:** 4.4.4

**log**
{"tag": "info", "depth": 0, "time": "2019-02-11 18:21:50", "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py\", line 62, in runTest\n  File \"/Users/dm/Desktop/ces/SuperClass.air/ces.air/ces.py\", line 18, in <module>\n    poco(\"android.widget.FrameLayout\").offspring(\"android.widget.FrameLayout\").child(\"android.widget.EditText\")[1]\n  File \"/Users/wjjn3033/dev/idestable/poco/poco/proxy.py\", line 184, in __getitem__\n  File \"/Users/wjjn3033/dev/idestable/poco/poco/proxy.py\", line 821, in _do_query\npoco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of \"android.widget.FrameLayout>android.widget.FrameLayout/android.widget.EditText\"\n"}}

**Comment by yimelia** [comment]
应该是poco类型选错了吧，`poco=AndroidUiautomationPoco()`这个是android原生，你这里应该不是这个类型

**Comment by ayue-NAN** [comment]
不好意思哈。。。后来使用了StdPoco这个模块，执行完后无误。

**Comment by ayue-NAN** [comment]
@yimelia 
但是我这边又出现另一种情况，和研发沟通了，说登录页面也是cocos-lua
为什么登录页面的相关页面元素定位不了呢。。。如截图
![image](https://user-images.githubusercontent.com/22957532/52683386-9fcde880-2f7d-11e9-8ac2-774d1963922a.png)

**Comment by yimelia** [comment]
从截图上看，是已经刷出了ui节点信息的，是信息不对么？可以确认一下那个refresh的时间是否和当前时间差距很小（保证poco没有断开）

**Comment by ayue-NAN** [comment]
嗯。刷出来的ui节点是登录成功后的页面元素

**Comment by yimelia** [comment]
操作过程是先登录成功了之后往回退到现在这个界面的，还是说一打开游戏就进入到这个界面然后就发现POCO刷出来的信息不对？

**Comment by ayue-NAN** [comment]
![image](https://user-images.githubusercontent.com/22957532/52683787-f12aa780-2f7e-11e9-9eac-77868360ee79.png)
未登录时，发现刷不出来ui树，然后就打算先登录，然后再刷下试试。上面的截图是未登录的时候

**Comment by yimelia** [comment]
那可能是这样的，在接入SDK的时候，挂载的对象是在登录完成后才创建的，所以在刚进入游戏时没能刷出UI树，等到登录成功后刷出UI树以后又往回退时，那个对象可能不存在了，导致了poco断开。

**Comment by ayue-NAN** [comment]
我现在卸载重装了apk
出现截图如下：
![image](https://user-images.githubusercontent.com/22957532/52684351-f25cd400-2f80-11e9-9a6e-778af27f1b22.png)
查了下adb logcat，其中关于poco的部分信息如截图：
![image](https://user-images.githubusercontent.com/22957532/52684394-0f91a280-2f81-11e9-87d3-55b424e6106e.png)

备注：
最后我使用了poco辅助框的录制功能，登录页面，输入手机号，输入验证码，点击登录按钮，这些操作都没有代码生成，只有登录成功后的操作，才有代码。目前只能先通过touch登录成功后，才进行poco操作了。
不过，还是希望晓得原因是什么

**Comment by yimelia** [comment]
可能就是因为挂载poco的那个对象是在登录成功后才创建的吧

**Comment by ayue-NAN** [comment]
万分感谢哈，和技术沟通了下，poco对象是登录后才创建的。

特别谢谢您

**Comment by yimelia** [comment]
可以这样，你看看是不是登录界面是android和cocos混合做的，可能登录界面可以用android的poco来抓取

**Comment by ayue-NAN** [comment]
嗯。。有问过，说都是cocos写的。。。确实是因为poco对象创建的时机是登录后的
