### ISSUE TITLE
华为P10手机，鼠标点击右边的屏幕的任何应用，脚本在写，但是屏幕没有反应

### ISSUE THREAD

**Issue by xiaohai2003ly** [AirtestProject/AirtestIDE#32]
我用的华为P10 Android7.0， vivo r9, android 7.1.1手机，手机连接上，开始录制，鼠标点击右边的屏幕的任何应用，脚本在录制，但是手机没有反应，但是如果操作手机，airtest的屏幕会跟着变化，为何？

**Comment by yimelia** [comment]
@xiaohai2003ly 假如没有点任何“录制”按钮，仅仅是将手机连接好之后，用鼠标去点击屏幕是否有反应？还是在点击录制之后，去操作手机才没有反应的？
可能需要你帮忙贴一下连上手机后的命令行窗口中的Log内容，非常感谢你的反馈，如果需要更多帮助可以直接加QQ讨论群 437119175

**Comment by xiaohai2003ly** [comment]
无论点还是没有电录制，用鼠标点击屏幕都没有反应

**Comment by xiaohai2003ly** [comment]
@yimelia 
点击录制按钮前和点击录制按钮后都没有用，鼠标点击屏幕没有反应。
这里不能贴图，log的内容我不知道怎么复制出来

**Comment by yimelia** [comment]
@xiaohai2003ly 可以麻烦你加Q群反馈，或者把图片发到airtest@service.netease.com 这个邮箱吗~真的非常感谢~~

**Comment by xiaohai2003ly** [comment]
@yimelia 好的，我下周一发给你邮箱

**Comment by adolli** [comment]
直接把图片回到issue里也可以

**Comment by Meteorix** [comment]
github的issue可以直接贴图的，复制之后直接在文本框粘贴。建议直接用issue讨论，这样后面的人可以参考，目前看来p10提的issue有好几个

**Comment by rockywhisper** [comment]
@xiaohai2003ly  你好，我们重新测试了华为P10手机，没有重现出你所说的问题来，方便的话请到QQ群内进行反馈哈。（QQ讨论群： 437119175）
这条issue暂先关闭了哈。
