### ISSUE TITLE
mix2s 不能正常连接

### ISSUE THREAD

**Issue by helloCx** [AirtestProject/AirtestIDE#320]
手机型号：mix2s 
![image](https://user-images.githubusercontent.com/26318927/52693328-6b6c2380-2fa1-11e9-8998-51fc6ed9ccac.png)
问题如图
![11550041679_ pic_hd](https://user-images.githubusercontent.com/26318927/52693346-77f07c00-2fa1-11e9-9f68-ffa4aa60d61f.jpg)
手机设置
![image](https://user-images.githubusercontent.com/26318927/52693435-b5eda000-2fa1-11e9-85c2-a487bb89da03.png)
电脑系统

**Comment by helloCx** [comment]
![image](https://user-images.githubusercontent.com/26318927/52693594-0fee6580-2fa2-11e9-8917-c07b5af4decb.png)
选中 UseAdb后报错 try again

**Comment by yimelia** [comment]
把IDE更新到最新版本试一下

**Comment by helloCx** [comment]
不行，我刚下载的airtest 小米5测过好用   小米5x 和 mix2s 不知道什么问题都不行

**Comment by yimelia** [comment]
首先可以尝试一下这个操作： 查看手机设置—》授权管理—》USB安装管理—》去掉USB安装应用的相关限制
如果仍然失败，可以 [使用命令行启动IDE](http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2)，这样启动后，能在命令行窗口看到log，此时尝试连接手机，然后将窗口里的报错log截图发上来看看

**Comment by helloCx** [comment]
仓了天了，我居然发现我用的版本是2018年5月份的！跳进黄河也洗不清了，我昨天刚用airtest 就遇到这种问题，昨天点击下载给我下载2018年的，今天点击下载居然是19年版本了！
![image](https://user-images.githubusercontent.com/26318927/52770635-97090f80-306e-11e9-8893-dc4b360fa6c7.png)
下载最新的搞定了
