### ISSUE TITLE
鼠标移动至selenium Window的部分按钮上，hover弹层的内容没有完全显示

### ISSUE THREAD

**Issue by luoABCD123456** [AirtestProject/AirtestIDE#324]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。)

**截屏**
![image](https://user-images.githubusercontent.com/47559548/52761080-efc7b080-304c-11e9-94d8-649052d6abc1.png)

![image](https://user-images.githubusercontent.com/47559548/52761082-f3f3ce00-304c-11e9-96d0-3c5f36504173.png)

![image](https://user-images.githubusercontent.com/47559548/52761086-f6eebe80-304c-11e9-9080-0b8ba86be8c7.png)

**预期效果**
完整显示弹层内容

**python 版本:** `python3.6`

**操作系统:** `Windows10 64bit`

**Comment by yimelia** [comment]
请问一下，在airtest辅助窗上面的hover效果是否正常？
以及win10系统是否开启了放大等功能？

**Comment by luoABCD123456** [comment]
> 请问一下，在airtest辅助窗上面的hover效果是否正常？
> 以及win10系统是否开启了放大等功能？


1. 在airtest辅助窗上面的hover效果是正常的
2.放大功能是什么意思

**Comment by rockywhisper** [comment]
@luoABCD123456  您好，应该是不同的分辨率导致的渲染问题。

可以尝试调整下系统的显示器分辨率，要在大显示屏上显示的话，就调整为大显示屏的分辨率。
![image](https://user-images.githubusercontent.com/8188879/52767589-ed258500-3065-11e9-8a8f-595b6fe39f93.png)

**Comment by luoABCD123456** [comment]
> @luoABCD123456 您好，应该是不同的分辨率导致的渲染问题。
> 
> 可以尝试调整下系统的显示器分辨率，要在大显示屏上显示的话，就调整为大显示屏的分辨率。
> ![image](https://user-images.githubusercontent.com/8188879/52767589-ed258500-3065-11e9-8a8f-595b6fe39f93.png)

ok，谢谢
