### ISSUE TITLE
IDE识别设备分辨率出错，导致点击不准确

### ISSUE THREAD

**Issue by liusyoo** [AirtestProject/AirtestIDE#325]
**描述问题bug**
IDE中使用touch控制设备，match result位置不准确。

**截屏**
![image](https://user-images.githubusercontent.com/24716056/52837447-c0d33c80-3129-11e9-88f1-b189820fbdfb.png)
try match with _find_template
threshold=0.7, result={'result': (649, 620), 'rectangle': ((625, 597), (625, 644), (673, 644), (673, 597)), 'confidence': 0.9669367671012878}
match result: {'result': (649, 620), 'rectangle': ((625, 597), (625, 644), (673, 644), (673, 597)), 'confidence': 0.9669367671012878}
F:\other\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell input tap 649 620

**复现步骤**
1. 连接安卓设备
2. 通过 'adb shell wm size' 修改安卓设备分辨率
3. 使用airtest IDE的touch

**预期效果**
正常控制设备

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 系统: Android 7.1
 - wm size：
    Physical size: 1280x720
    Override size: 1540x720

**其他相关环境信息**
打包instrumentation测试apk后，运行在安卓中，当该安卓的Override size大于Physical size的时候，运行时日志里看到的resize也出现异常：resolution： （1280，720）=>(553, 720)

**Comment by rockywhisper** [comment]
@liusyoo 
你好，这个设备看起来像是模拟器。
因为涉及到设备分辨率获取这个通用接口，案例比较特殊，需要评估下实际使用意义。

请问下修改设备分辨率的主要目的是什么呢？

**Comment by liusyoo** [comment]
> @liusyoo
> 你好，这个设备看起来像是模拟器。
> 因为涉及到设备分辨率获取这个通用接口，案例比较特殊，需要评估下实际使用意义。
> 
> 请问下修改设备分辨率的主要目的是什么呢？

**Comment by liusyoo** [comment]
你好，是模拟器。由于现在手机的分辨率较多，我们用模拟器来测试和展现不同分辨率下的效果

**Comment by tiann** [comment]
同样的问题，wm size之后不对了，但是为何这个 issue close了？

**Comment by yimelia** [comment]
重设分辨率后，可以考虑先断开再重新connect一次模拟器，看是否正常

**Comment by tiann** [comment]
重设之后断开重连不正常。重连的时候 minicap -P 参数，指定的分辨率并非重设之后的分辨率

**Comment by EraChen233** [comment]
你用的是什么模拟器？我们试着重现一下

**Comment by tiann** [comment]
与模拟器没有关系，任何真机都可以复现。步骤如下：

**Comment by EraChen233** [comment]
真机的问题在下一个版本会修复
模拟器的问题我昨天拿夜神模拟器试了一下，通过adb shell wm size 修改分辨率，即使没有重启也是立即生效，能正常显示的

**Comment by tiann** [comment]
我使用模拟器试一下，一会儿回来反馈

**Comment by tiann** [comment]
我用 Android 官方模拟器试了一下，也是有这个问题的。我可能漏说了一点：

分辨率从大往小调是没问题的，如果从小往大调就会出现这个问题。

比如说，设备原来是 1080x1920 调整为 1280x2560 就会有这个情况；如果本身就是 1280x2560，那么再往低调是没问题的。

**Comment by EraChen233** [comment]
出现问题之后，重新连接IDE就可以了
后面修复的真机也需要重新连接的

**Comment by tiann** [comment]
多谢，坐等新版本发布 😃

**Comment by tiann** [comment]
新版 1.2.2 已修复这个问题，感谢！
