### ISSUE TITLE
Android 如何判断设备并指定运行

### ISSUE THREAD

**Issue by shzzj** [AirtestProject/AirtestIDE#327]
**描述问题bug**
Android正常连接一个设备可以运行,但是同一个电脑连接两个设备要怎么指定运行呢

我的 adb devices是
MKJNW18419004817和
7HZTT4SSCMJNLJ9S

我现在可以用connect_device("android:///MKJNW18419004817")指定第一个设备运行A代码
但是判断设备的方法没找到

**预期效果**
我想要实现
if(device==MKJNW18419004817){
//跑A方法
}else if(device==7HZTT4SSCMJNLJ9S){
//跑B方法
}else if(device==第三设备){
//跑C方法
}
请问如何实现

**python 版本:** `python3+

**操作系统:** `mac

**设备:**
 - 型号: 华为
 - 系统: Android 7+

**Comment by yimelia** [comment]
可以试一下这样
```
# 拿到当前设备
dev = device()
# 拿到设备号
print(dev.uuid)
```
