### ISSUE TITLE
不能够控制手机，无法使用鼠标点击

### ISSUE THREAD

**Issue by wujie59888** [AirtestProject/AirtestIDE#329]
![qq 20190221184252](https://user-images.githubusercontent.com/47286519/53163641-837b1d00-3609-11e9-99cf-b82c2d0e7dad.png)
![qq 20190221184549](https://user-images.githubusercontent.com/47286519/53163648-86760d80-3609-11e9-88f6-3fd96a571c60.png)
手机没有触控设备

**Comment by rockywhisper** [comment]
@wujie59888  
请提供手机型号。

![image](https://user-images.githubusercontent.com/8188879/53164040-57ac6700-360a-11e9-94d8-85769ff5d238.png)
另外可以按照说明尝试勾选`use ADB touch`，看下是否可以正常操作。
（注意连接前需要在开发者选项中打开`模拟位置`开关。）

**Comment by wujie59888** [comment]
@rockywhisper  你好，尝试勾选了use ADB touch 不能用。是不是手机没有安装触摸屏就不能识别?没有 touch device.

**Comment by wujie59888** [comment]
@rockywhisper 我用TOTAL CONTROL可以点击控制

**Comment by wujie59888** [comment]
我发现初始化的时候就失败了，是因为找不到触摸屏的相关接口应该是，我这个板子是没有触摸屏的，但应该不影响adb touch啊，我勾选adb touch 也是一样的，minitouch initial failed

**Comment by yimelia** [comment]
可能是airtest的bug，我需要时间确认一下

**Comment by wujie59888** [comment]
我可以把机器快递给你验证，另外命令模式测试过是可以的

**Comment by wujie59888** [comment]
你好，添加device/ android label 2啥意思?最新的时间表有么？

**Comment by yimelia** [comment]
添加device/ android label 2啥意思?
- 不清楚，这个问题是什么意思？
最新的时间表有么？
- 暂时还没有，这个问题比预想中要复杂，我会尽快想办法支持，但是不一定能够实现。没有触摸屏的设备我们原本就是不支持操控的。

**Comment by wujie59888** [comment]
美女，其他家都可以啊

**Comment by yimelia** [comment]
最新版本1.2.1已支持ADB TOUCH操作手机屏幕
