### ISSUE TITLE
swipe方法缺少steps参数

### ISSUE THREAD

**Issue by chenyitest** [AirtestProject/AirtestIDE#33]
swipe(v1,v2=None,vector=None,duration=0.01)
下面的参数说明隔了steps参数，方法中没有该参数
![1](https://user-images.githubusercontent.com/37651408/37756184-884dc636-2de3-11e8-8645-b2ff1e785a28.png)

**Comment by yimelia** [comment]
@chenyitest 实际上是有这个参数的，只是在平时的使用当中用处比较小，整个swipe的流程如下：

swipe指令是在一条直线上滑动，直线上有若干插值点，比如默认是A-B-C-D-E总共5个插值点。
swipe另外有个参数是duration，意思是多久完成这次完整的swipe，比如duration=1的话，
那么，从A点开始按下，每隔0.25s向手机发送一次move到下一个插值点，直到1s后到达E点，抬起，最后完成整个swipe操纵。

**Comment by rockywhisper** [comment]
@chenyitest  内置的参数均有默认值，所以生成语句中没有增加对应的参数。
如有需要，可以自己添加:  swipe(图片, steps=5, duration=1)

这个issue先关闭了哈。
