### ISSUE TITLE
运行完测试用例,点击关闭，直接挂掉了

### ISSUE THREAD

**Issue by xiaohuanyao** [AirtestProject/AirtestIDE#330]
**描述问题bug**
关闭的时候，ide崩溃了

**复现步骤**
1.ide打开两遍
2.关闭其中一个
3.剩下的一个运行一个异常的脚步

**预期效果**
关闭的时候没有，崩溃弹窗弹出

**python 版本:** `没有安装`

操作系统: windows7

**设备:**
 - 型号: B250M-D2VX-ST
 - 系统: 专业版64位（6.1，版本7601）
 - (别的信息)

**其他相关环境信息**
windows上运行异常，

**Comment by yimelia** [comment]
最好不要同时打开2个IDE
