### ISSUE TITLE
运行脚本报错没有airtest模块

### ISSUE THREAD

**Issue by guxichen** [AirtestProject/AirtestIDE#332]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
运行脚本报错没有airtest模块

**截屏**
![image](https://user-images.githubusercontent.com/39250680/53218035-81f73680-3695-11e9-8824-61999935f8ca.png)

**复现步骤**
1. 运行脚本

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**设备:**
**其他相关环境信息**

**Comment by yimelia** [comment]
请参考[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#python) 部署python运行环境，安装airtest和pocoui等相关库
