### ISSUE TITLE
adb和IED都连接上，运行脚本就会无法连接设备

### ISSUE THREAD

**Issue by guxichen** [AirtestProject/AirtestIDE#333]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
adb和IED都连接上，运行脚本就会无法连接设备

**截屏**
![image](https://user-images.githubusercontent.com/39250680/53225212-4028b900-36b2-11e9-8b6d-94361d01b7b0.png)
![image](https://user-images.githubusercontent.com/39250680/53225217-4454d680-36b2-11e9-8886-e48ac773c23a.png)
![image](https://user-images.githubusercontent.com/39250680/53225322-9bf34200-36b2-11e9-98ea-179f16db2d7f.png)
![image](https://user-images.githubusercontent.com/39250680/53225317-98f85180-36b2-11e9-972e-c337b8660c91.png)

**复现步骤**
1. adb显示有设备
2. IED也可以连接上手机屏幕
3. 运行脚本就会报错
4. 设备会无法连接后再次连接上

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: vivo Y55
 - 系统:安卓6.0.1
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
可能是ADB版本冲突导致的问题，最新版本在win7系统上会自动替换IDE目录下的ADB，导致与本地安装的airtest里使用的ADB版本不同，详见[这里](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#airtestadb)

解决办法是，将本地airtest目录下的adb替换为IDE里同一个版本即可，也就是你所使用的 `C:\Python37\lib\site-packages\airtest\core\android\static\windows` 下的 `adb.exe` ，用IDE目录下的 `tools/adb39` 替换一下即可。
