### ISSUE TITLE
点击运行脚本会卡在IDE界面，没有任何报错信息

### ISSUE THREAD

**Issue by guxichen** [AirtestProject/AirtestIDE#335]
**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
点击运行脚本会卡在界面，没有任何报错信息，在安卓真机以及安卓模拟器运行都会卡在这里，后台也没有报错信息

**截屏**
![image](https://user-images.githubusercontent.com/39250680/53294670-ff51b100-3825-11e9-8de9-4c7efc069be2.png)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: 夜神模拟器，vivo y55,vivo x9
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
如果不是要用本地python环境来跑脚本的话，设置里的`custom python path` 没有必要填写，你填写了一个python.dll是错误的，直接留空就可以了。
如果需要用本地python环境来跑脚本，请参考这个[文档](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python)
