### ISSUE TITLE
将SDK文件夹放入项目后，打开项目就报错

### ISSUE THREAD

**Issue by a476477251** [AirtestProject/AirtestIDE#338]
![image](https://user-images.githubusercontent.com/39767771/53383903-12928700-39b4-11e9-82fb-8dc96b4be5be.png)

游戏是Unity3D ugui，网上下下来的SKD内的Unity3D文件夹中的ngui文件夹删除后，再将Unity3D文件夹放入项目，打开项目后就报错，空间名
在项目内查询了报错的文件，Unity3D\fairygui和Unity3D\ugui文件夹内都有UnityNode.cs
这个要怎么解决

**Comment by TreHack** [comment]
删掉fairygui这个文件夹就可以了

**Comment by a476477251** [comment]
删了之后还是报一堆的问题
我下载旧版18年10月16的SDK是正常的

**Comment by TreHack** [comment]
贴下错误看看呢

**Comment by a476477251** [comment]
Assets/Unity3D/PocoManager.cs(70,13): error CS0246: The type or namespace name `SocketException' could not be found. Are you missing `System.Net.Sockets' using directive?
无法黏贴图片，只能复制错误

**Comment by TreHack** [comment]
收到，我们处理下，需要using  System.Net.Sockets
