### ISSUE TITLE
如何提高iOS的执行流畅度

### ISSUE THREAD

**Issue by zjsjayce** [AirtestProject/AirtestIDE#339]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。)

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by zjsjayce** [comment]
iOS如何杀死进程？只能用控件吗

**Comment by yimelia** [comment]
请确认部署的是我们提供的 [ios-Tagent](https://github.com/AirtestProject/iOS-Tagent)，而不是facebook-wda，会比wda更流畅一些
如有更多问题，请补充完善描述后reopen这个issue，感谢

**Comment by zjsjayce** [comment]
> 请确认部署的是我们提供的 [ios-Tagent](https://github.com/AirtestProject/iOS-Tagent)，而不是facebook-wda，会比wda更流畅一些
> 如有更多问题，请补充完善描述后reopen这个issue，感谢

WDAError: WDAError(status=6, value=Session does not exist)
return self._fetch_no_alert(method, url, data)
File "/usr/local/lib/python2.7/site-packages/wda/init.py", line 114, in _fetch_no_alert
return httpdo(target_url, method, data)
File "/usr/local/lib/python2.7/site-packages/wda/init.py", line 90, in httpdo
raise WDAError(r.status, r.value)
WDAError: WDAError(status=6, value=Session does not exist)

Python环境执行测试脚本，WDA报错。10次的循环只能执行6次
