### ISSUE TITLE
【新需求】AirtestIDE能否在设备连接界面，增加上下左右及确定按钮，以便进行电视端的脚本录制？

### ISSUE THREAD

**Issue by zhilaizhiw** [AirtestProject/AirtestIDE#343]
这是个AirtestIDE的使用需求建议。

**描述问题需求**
为了更好地支持安卓TV上的自动化脚本录制，建议在设备连接界面增加“上、下、左、右、确定”几个按键，对应的key code分别是“DPAD_UP、DPAD_DOWN、DPAD_LEFT、DPAD_RIGHT、ENTER”。

现有的设备连接界面已有“菜单、home、返回、power”四个按键，如果再加上上述几个电视端常用的按键，对于电视端的使用和录制将提供极大的方便。目前的UI更适合手机端的使用，可以增加一个触发按钮，点击后显示适合电视端使用的上述方向键和确定键。

**Comment by zhilaizhiw** [comment]
安卓TV研发和测试也是比较大的一块儿吧，请问能否回复一下，是否能加上这个功能呢？

**Comment by rockywhisper** [comment]
@zhilaizhiw   
你好，非常感谢你的反馈，我们近期将评估一下这项需求。

**Comment by yimelia** [comment]
新版本已经加上啦，http://airtest.netease.com/changelog.html
