### ISSUE TITLE
单条命令可以运行，F5运行整个脚本，可运行位置报错

### ISSUE THREAD

**Issue by wujie59888** [AirtestProject/AirtestIDE#345]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues

**描述问题bug**
右键运行选中代码 touch((500, 450))可以运行。
F5运行整个脚本touch((500, 450))报错

**截屏**
![image](https://user-images.githubusercontent.com/47286519/53549552-6dbca900-3b6f-11e9-8f02-0e6f88a94cb3.png)
![image](https://user-images.githubusercontent.com/47286519/53549559-71e8c680-3b6f-11e9-9dc2-ee4ed0c16834.png)
![image](https://user-images.githubusercontent.com/47286519/53549614-93e24900-3b6f-11e9-8112-aa3730ea18fc.png)

强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
加`&&touch_method=ADBTOUCH`

**Comment by wujie59888** [comment]
@yimelia 加了
&&touch_method=ADBTOUCH
确实不会报错了，谢谢
