### ISSUE TITLE
在华为mate 9pro 和小米 mix 2 同一个APP按照图片点击同一位置无法都成功。

### ISSUE THREAD

**Issue by hhy2589** [AirtestProject/AirtestIDE#346]
你好：使用airtest进行测试，同一个APP在问题描述的手机型号截取的图片分别如附件所示，假如在华为手机录制了，则无法在小米手机回放，如果在小米手机录制了则无法在华为手机回放，有什么技巧或者规避方式么。多谢。
![tpl1551348641747](https://user-images.githubusercontent.com/47594542/53559540-483a9a00-3b85-11e9-83ce-e9e29ec9323e.png)
![tpl1551348669691](https://user-images.githubusercontent.com/47594542/53559541-483a9a00-3b85-11e9-8f16-457eb16c8ca3.png)

**Comment by yimelia** [comment]
可以参考[文档](http://airtest.netease.com/docs/cn/5_airtest_framework/airtest_api_info.html#id8)
可选的解决方案：
- 根据项目实际缩放规则进行分辨率适配
- 降低识别阈值来提高成功率
- 修改截图内容，尽可能少截取空白部分
- 或者干脆只要识别到华为或小米其中一张截图就算成功
