### ISSUE TITLE
Device compatibility page is accessed an error occurs.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/AirtestIDE#348]
Remove any following parts if does not have details about

**Describe the bug**
The page is accessed and an error occurs.
+ http://airtest.netease.com/docs/en/2_device_connection/6_android_support.html 

**Screenshots**
A **screenshot** is strongly recommended. Please include both AirtestIDE window and the **black console window**.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**AirtestIDE version:** `1.0.15`

**Platform:** `Windows7 64bit, etc.`

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by EraChen233** [comment]
Thanks for pointing out. Here is the latest list we maintaining. 
https://github.com/AirtestProject/Airtest/blob/master/docs/wiki/platforms.md#android
