### ISSUE TITLE
view Report improvement request

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/AirtestIDE#349]
Remove any following parts if does not have details about

**Describe the bug**
Report improvement request
- Even if any item of the complete test item fails, it is shown in the report as if all the items failed.
![1](https://user-images.githubusercontent.com/46311868/53773889-880bd380-3f2f-11e9-94ef-22167b5460b2.png)
- I hope to be able to check the test results according to the form of the test case.
![kakaotalk_20190226_131126843](https://user-images.githubusercontent.com/46311868/53773823-49761900-3f2f-11e9-97bf-4d8b5a3070b2.png)

**Screenshots**
A **screenshot** is strongly recommended. Please include both AirtestIDE window and the **black console window**.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**AirtestIDE version:** `1.0.15`

**Platform:** `Windows7 64bit, etc.`

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by EraChen233** [comment]
Thanks for your advice. We will consider this issue as soon as possible.

**Comment by JJunM** [comment]
> Thanks for your advice. We will consider this issue as soon as possible.

I think you know the improvement plan of the test result.

**Comment by JJunM** [comment]
> Thanks for your advice. We will consider this issue as soon as possible.

I think you know the improvement plan of the test result.
