### ISSUE TITLE
Do you provide schedule management function for testing?

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/AirtestIDE#350]
Remove any following parts if does not have details about

**Describe the bug**
Can I set a test execution schedule so that I can execute the script according to that schedule?

**Comment by EraChen233** [comment]
Run Airtest with [command lind](http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#running-scripts-using-the-command-line) and add [schedule](https://schedule.readthedocs.io/en/stable/)  task with python

![image](https://user-images.githubusercontent.com/5961185/54183673-a64d7280-44df-11e9-8adf-0dfe451faddb.png)

![image](https://user-images.githubusercontent.com/5961185/54183592-8158ff80-44df-11e9-904e-67784bd2f6f4.png)
