### ISSUE TITLE
请问，可以接入持续集成吗

### ISSUE THREAD

**Issue by test-h** [AirtestProject/AirtestIDE#352]
Remove any following parts if does not have details about

**Describe the bug**

**Screenshots**
A **screenshot** is strongly recommended. Please include both AirtestIDE window and the **black console window**.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**AirtestIDE version:** `1.0.15`

**Platform:** `Windows7 64bit, etc.`

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by EraChen233** [comment]
可以的

**Comment by yimelia** [comment]
可以，支持命令行启动任务，请参考[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id3)
