### ISSUE TITLE
Deepin系统中无法运行airtest ide

### ISSUE THREAD

**Issue by yuhao-w** [AirtestProject/AirtestIDE#353]
**描述问题bug**
Deepin安装Airtest IDE后无法启动

**截屏**
![image](https://user-images.githubusercontent.com/45590791/54022930-99264000-41ce-11e9-9da2-348e6f63839a.png)
![image](https://user-images.githubusercontent.com/45590791/54022993-c115a380-41ce-11e9-8f0c-b5aa68e9fab3.png)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.6`

**操作系统:** `Deepin15.9.1 64bit`

**Comment by yimelia** [comment]
很抱歉，我们目前只支持了`ubuntu16-04`版本，其他版本的系统暂时还没有支持

**Comment by yimelia** [comment]
可以考虑用windows或者Mac写好脚本后，单独用python来执行脚本就可以了，命令行的运行方式可以参考[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id3)
