### ISSUE TITLE
求问：日志模块有什么方法可以实现”开关“日志记录?

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/AirtestIDE#359]
**描述问题**
我在使用airtestIDE进行自动化测试用例的开发，使用它自带的日志模块，会把我操作的每一个步骤（touch、text之类）都记录下来。但是每个用例都有大约十几个步骤，这就导致了测试结束后查看日志会有非常多的无效信息。我想调整一下日志的记录频率（比如每一个用例或几个用例的操作完成后才写入一次日志），不知道airtestIDE有没有提供什么方法呢？如果没有，也可以告知一下日志模块的主要构成部分，我可以尝试着自己在这个基础上写一些新方法，万分感谢！

**预期效果**
想找出能“开关”或控制日志记录频率的方法
或者找出日志记录方面的源代码，在此基础上进行修改

**python 版本:*
python3.6.5

**操作系统:** 
`Windows10 64bit`

**Comment by yimelia** [comment]
log相关源码见[这里](https://github.com/AirtestProject/Airtest/blob/master/airtest/utils/logwraper.py)

可以在`airtest.core.api`中看到，例如像`touch`这样的接口，都会有一个`@logwrap`装饰器
