### ISSUE TITLE
脚本打包成apk后,执行报错

### ISSUE THREAD

**Issue by shudaixiong1013** [AirtestProject/AirtestIDE#365]
步骤:
1.脚本连接手机在PC端可以正常使用
2.打包成apk后,手机连接电脑:运行指令:adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

结果:脚本未运行..
1.keyevent("BACK") >此类脚本也未运行..<手机未有反应>
2.存在截图的脚本抛出异常,提示图片未找到:
![image](https://user-images.githubusercontent.com/15087325/54665238-7296cc00-4b21-11e9-84f4-230a8f2e9aba.png)

我的测试脚本如下:
![image](https://user-images.githubusercontent.com/15087325/54665493-344ddc80-4b22-11e9-925d-f8bb5d5591d3.png)

**设备:**
 - 型号: [华为荣耀8x]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**Comment by yimelia** [comment]
Duplicate of #364 
直接看364的回复即可，我先关闭这个issue了
