### ISSUE TITLE
IDE登陆验证问题

### ISSUE THREAD

**Issue by MaXDon** [AirtestProject/AirtestIDE#367]
这个IDE注册登陆花了半个多小时，什么狗屁图像验证，使用这种看起来高大上的验证，明明点正确了，就是过不了。。。。

**Comment by yimelia** [comment]
这个其实是因为渲染的问题，导致网页那边认为验证不通过。。。可以直接点skip跳过登录阶段的

**Comment by MaXDon** [comment]
> 
> 
> 这个其实是因为渲染的问题，导致网页那边认为验证不通过。。。可以直接点skip跳过登录阶段的

留着容易误导。。。还有大侠这个解释：类似--你写了个UI，不能点击，然后解释给用户，是因为坐标转换有问题，所以导致不能触发

**Comment by yimelia** [comment]
不好意思哈，这个解释容易引起误会。其实是因为我们在软件里渲染出了一个网页，然后通过网页去访问注册页面，所以在部分机器上面可能由于渲染速度的问题，导致网页那边认为验证过程有问题，所以需要重新尝试多次才能通过。在大部分机器上都是比较容易通过的，但是确实有很少部分用户反馈很难通过验证，所以我们也提供了skip方式来跳过这个验证。
