### ISSUE TITLE
IDE运行后无法生成html 报告

### ISSUE THREAD

**Issue by daisylong126** [AirtestProject/AirtestIDE#368]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
今天开始IDE运行后无法生成Log，提示
![image](https://user-images.githubusercontent.com/37356308/54741787-7a766f00-4bfa-11e9-8ee0-5578044d86da.png)
或者报告是空内容：
![image](https://user-images.githubusercontent.com/37356308/54741850-a1cd3c00-4bfa-11e9-8fbe-08bf8b44595f.png)
实际scripts下面是有log的
![image](https://user-images.githubusercontent.com/37356308/54741884-b90c2980-4bfa-11e9-9454-7af9cd333fe4.png)
删除了之后重新运行也无法解决，已经下载了最新的IDE版本

**复现步骤**
在出现问题前可能做过的操作：
1、运行一直出现找不到图片（实际有重新用assert_exist重新截图），运行时的阈值>70
 
![image](https://user-images.githubusercontent.com/37356308/54742192-a6462480-4bfb-11e9-9202-55599847a22a.png)
2、手动将另外一个air里生成的截图copy到了此文件夹，并删除了几张不需要的截图
3、接着开始出现Log无法生成

**预期效果**
可以正常生成log

**python 版本:** `python3.6'

**操作系统:** `Windows10 64bit`

**其他相关环境信息**
无

**Comment by yimelia** [comment]
点击生成报告的时候，在IDE的log窗口里会多一行命令行，把它复制下来，另外开个命令行窗口粘贴进去运行一次，这样可以看到报错log，然后把log贴出来看看。
初步猜测可能是跟手工替换过图片文件有关，或者是log文件被修改过、不是最新、图片路径不对等问题，都是有可能的。所以最好独立运行一次命令行，看看是什么报错

**Comment by yimelia** [comment]
以及也可以将log.txt发上来我们帮忙看一下，前提是确保log.txt是最新运行的结果

**Comment by daisylong126** [comment]
![image](https://user-images.githubusercontent.com/37356308/54743186-70566f80-4bfe-11e9-8446-140284f26c63.png)

[log.txt](https://github.com/AirtestProject/AirtestIDE/files/2991436/log.txt)

**Comment by daisylong126** [comment]
log错了，我重新上传

**Comment by daisylong126** [comment]
![image](https://user-images.githubusercontent.com/37356308/54743393-fb376a00-4bfe-11e9-87cd-cf21b9567f9c.png)
![image](https://user-images.githubusercontent.com/37356308/54743422-0ee2d080-4bff-11e9-828d-e828d1a588f1.png)
[log.txt](https://github.com/AirtestProject/AirtestIDE/files/2991452/log.txt)
重新上传，以这个为准

**Comment by yimelia** [comment]
在后面单独运行命令行的时候，修改一下命令行，把文件夹都加上引号再运行，你这个没有成功运行。
以及初步猜测和图片替换过有关，因为找不到图片的话，生成是会失败的。

**Comment by daisylong126** [comment]
C:\Users\win 10>D:\AirtestIDE_2019-01-15_py3_win64\AirtestIDE reporter D:\AirtestProject\Scripts\temp.air --log_root C:\Users\win 10\AppData\Local\Temp\AirtestIDE\scripts\9d750035ed5f06db36f8e8cf1205083b --outfile C:\Users\win 10\AppData\Local\Temp\AirtestIDE\scripts\9d750035ed5f06db36f8e8cf1205083b\log.html --static_root D:\AirtestIDE_2019-01-15_py3_win64\airtest\report --lang zh --plugin airtest_selenium.report poco.utils.airtest.report
usage: airtest [-h] {run,info,report} ...
airtest: error: unrecognized arguments: 10\AppData\Local\Temp\AirtestIDE\scripts\9d750035ed5f06db36f8e8cf1205083b 10\AppData\Local\Temp\AirtestIDE\scripts\9d750035ed5f06db36f8e8cf1205083b\log.html

C:\Users\win 10>"D:\AirtestIDE_2019-01-15_py3_win64\AirtestIDE" reporter "D:\AirtestProject\Scripts\temp.air" --log_root "C:\Users\win 10\AppData\Local\Temp\AirtestIDE\scripts\9d750035ed5f06db36f8e8cf1205083b" --outfile "C:\Users\win 10\AppData\Local\Temp\AirtestIDE\scripts\9d750035ed5f06db36f8e8cf1205083b\log.html" --static_root "D:\AirtestIDE_2019-01-15_py3_win64\airtest\report --lang zh --plugin airtest_selenium.report poco.utils.airtest.report"
Traceback (most recent call last):
  File "AirtestIDE.py", line 76, in <module>
  File "AirtestIDE.py", line 51, in main
  File "airtest\cli\__main__.py", line 13, in main
  File "airtest\report\report.py", line 386, in main
  File "airtest\report\report.py", line 323, in report
  File "airtest\report\report.py", line 83, in _analyse
  File "airtest\report\report.py", line 83, in <listcomp>
  File "airtest\report\report.py", line 90, in _translate_step
  File "airtest\report\report.py", line 196, in _translate_code
  File "airtest\aircv\aircv.py", line 14, in imread
airtest.aircv.error.FileNotExistError: File not exist: tpl1553064998449.png
[14920] Failed to execute script AirtestIDE



确实是找不到图片，要怎么解决呢

**Comment by EraChen233** [comment]
这个地址有空格，需要双引号包围起来，不然会被识别成两个参数
![image](https://user-images.githubusercontent.com/5961185/54746159-718b9a80-4c06-11e9-969f-26007378d315.png)

**Comment by yimelia** [comment]
@daisylong126 
可能是因为你替换了图片导致的，那要看你是如何替换图片的了，替换过脚本里的图片之后，需要重新运行一次脚本生成最新的log，否则里面还用了旧的图片就会导致问题

**Comment by yimelia** [comment]
@EraChen233  和空格问题无关，IDE里运行命令行的时候是处理过路径带空格的问题的，自己单独运行命令行才会因为空格导致运行失败。

**Comment by daisylong126** [comment]
> @daisylong126
> 可能是因为你替换了图片导致的，那要看你是如何替换图片的了，替换过脚本里的图片之后，需要重新运行一次脚本生成最新的log，否则里面还用了旧的图片就会导致问题

我是在文件夹里自己删的，之后不记得有没有马上运行了，后面出问题了之后是有运行的，但是没用了。。。那现在要怎么解决呢？重新建一个air？

**Comment by yimelia** [comment]
删掉log目录里的文件，重新运行一遍脚本，再重新点生成html。
报错的原因应该是log.txt里面的那个`tpl1553064998449.png`，原本应该存在于你的.air脚本里的，但是可能被你替换成了别的图片，导致它找不到。
要不就是替换的新图片改成原来的图片的名字，要不就是重新用新脚本来生成一次log，确保log里的图片名都是最新的。

**Comment by daisylong126** [comment]
我已经重新建了一个air，代码copy过来了，部分图片重新生成，部分图片直接从原来的air复制过来了，运行后还是无法生成report

**Comment by yimelia** [comment]
要确认.air文件里的同名.py文件里，图片的名字也得是正确的呀
IDE里右键有个选项可以切换图片模式和代码模式，能看到每张图片是有个名字的，要确保每个图片都存在于.air目录里

**Comment by daisylong126** [comment]
![image](https://user-images.githubusercontent.com/37356308/54796281-87db3a00-4c8a-11e9-96aa-67cc113b762b.png)
![image](https://user-images.githubusercontent.com/37356308/54796285-8d388480-4c8a-11e9-8bf3-0b181f2a4be0.png)
我检查了遍，基本是正确都在的

**Comment by daisylong126** [comment]
我代码的思路是把函数写在一个叫function_customer的air，然后主程序sanityTestAndrodCustomer去调用它,一开始是写在一个文件里的我觉得太杂了所以分出去，直接copy代码（包含有图片的）到function_customer里面，后来运行到识别图片的时候报错了，我意识到可能是function_customer这里面没有原来的图片（我不记得copy代码后有没有运行了），所以把原来sanityTestAndrodCustomer里的图片copy了过来，但还是不行
![image](https://user-images.githubusercontent.com/37356308/54796456-45fec380-4c8b-11e9-9aac-2465e0f80e23.png)

**Comment by yimelia** [comment]
试一下不直接用sys.path.append，改用`using`这个接口看看。文档地址在[这里](https://airtest.readthedocs.io/zh_CN/latest/README_MORE.html#import-from-other-air)
可以先sys.path.append父目录（到Scripts那一层就好），然后用using("xxx.air")，再import
using的逻辑里面，会把对应的.air文件夹添加到自己的图片搜索路径中，方便找到图片。

**Comment by daisylong126** [comment]
> 试一下不直接用sys.path.append，改用`using`这个接口看看。文档地址在[这里](https://airtest.readthedocs.io/zh_CN/latest/README_MORE.html#import-from-other-air)
> 可以先sys.path.append父目录（到Scripts那一层就好），然后用using("xxx.air")，再import
> using的逻辑里面，会把对应的.air文件夹添加到自己的图片搜索路径中，方便找到图片。

看了例子还是不太明白用法qaq
![image](https://user-images.githubusercontent.com/37356308/54797524-70eb1680-4c8f-11e9-87c5-7a7c7e4170a8.png)
我这个air没有写类，只写了函数，要调用里面的函数应该怎么写？

**Comment by yimelia** [comment]
是的，就是你这样写，直接调

**Comment by daisylong126** [comment]
![image](https://user-images.githubusercontent.com/37356308/54798542-46e82300-4c94-11e9-950f-c8a2dff9155b.png)
不行啊，报错了
![image](https://user-images.githubusercontent.com/37356308/54798557-54051200-4c94-11e9-9006-9a6c80141591.png)

**Comment by daisylong126** [comment]
可以了，我把func....前面去掉了，我再运行一下

**Comment by daisylong126** [comment]
运行后ok了，但报告截图没出来
![image](https://user-images.githubusercontent.com/37356308/54798982-20c38280-4c96-11e9-8570-ba70baf07e8d.png)

**Comment by yimelia** [comment]
其他步骤的截图正常吗，比如touch那些语句的截图

**Comment by daisylong126** [comment]
也不行
![image](https://user-images.githubusercontent.com/37356308/54799085-8e6fae80-4c96-11e9-934a-d3bec9e35fca.png)

**Comment by yimelia** [comment]
右键脚本标题，选第二个选项打开log目录，看看是否有存在全屏截图？
理论上应该是没什么问题的，你还做了什么其他修改吗

**Comment by yimelia** [comment]
浏览器用chrome打开试试，其他浏览器可能图片加载会有问题

**Comment by daisylong126** [comment]
> 浏览器用chrome打开试试，其他浏览器可能图片加载会有问题

改成chrome可以了~
