### ISSUE TITLE
Mac Airtest 可以连接Android真机吗?

### ISSUE THREAD

**Issue by 18282906067** [AirtestProject/AirtestIDE#370]
我在Mac机器上安装Airtest后
我想连接我的手机
我的手机是Android
但是我没有找到连接办法,请问可以连接吗?

**Comment by yimelia** [comment]
与Windows下的连接方法相同，如果有手机连接上的疑问，参考[文档FAQ](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html)
