### ISSUE TITLE
Windows game does not respond to requests after connecting Windows to Air test IDE

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/AirtestIDE#371]
I have a game made on Unity under Windows, we built poco and now, when I run the Airtest IDE and select the window with the game, this game does not respond to requests and commands, the feeling that it just hangs and it is impossible to manipulate it, recording auto-tests does not work, not one of the interface elements can not be clicked. When you try to write a test through the unity project tree, nothing happens after you run the test, although the test works fine (no errors) but nothing happens in the game

**Comment by rockywhisper** [comment]
@Chesterfild 
Hi, did you integrate the Poco-SDK into your game?
[Integrate guide](https://poco.readthedocs.io/en/latest/source/doc/integration.html#unity3d)

**Comment by Chesterfild** [comment]
Yes, I did, but unfortunately, it doesn't work
Video: https://yadi.sk/i/zkI9wJaLOaPErQ
Screenshot: https://yadi.sk/i/4gH_wyaksfWAaQ

**Comment by rockywhisper** [comment]
@Chesterfild 
Hi, buddy, sorry I didn't get that you were using a windows client...

Poco auto-recording feature only supports android & ios devices for now. And windows‘ poco auto-recording is now released yet. Sorry for the inconvenience. We'll release this feature as soon as possible.

Now you can double-click （or right click） on the item in the poco UI-tree to generate poco code.

**Comment by Chesterfild** [comment]
@rockywhisper 

The problem is not only in auto-recording, the video shows that I'm trying to click on any button in the window, but the buttons do not respond, also, the video shows that when I run the test, which is written "poco("NewOnPlanetGameBtn").click()" Airtest moves my mouse cursor and tries to click this button, but nothing happens

**Comment by rockywhisper** [comment]
@Chesterfild 
As for this problem, you can check this ["Embed window without embedding"](http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#embedded-window-mode-windows), then you can connect the windows without embedding it into AirtestIDE.

![image](https://user-images.githubusercontent.com/8188879/55157809-5259b380-5198-11e9-8fd0-c1a8e6815452.png)

**Comment by Chesterfild** [comment]
@rockywhisper 

![2019-03-28_15-15-07](https://user-images.githubusercontent.com/46621847/55160727-a77fd000-516c-11e9-80bc-bccc359f9d41.png)

Unfortunately I for some reason do not have this item in settings

**Comment by Chesterfild** [comment]
@rockywhisper 

Thank you very much, you helped me a lot.
The process has moved forward
