### ISSUE TITLE
产品是否支持离线运行？

### ISSUE THREAD

**Issue by mayue1352** [AirtestProject/AirtestIDE#372]
airtest是非常强大的产品，但是对于无法联网的工作环境想要应用是否支持？谢谢！
很抱歉这个提的不是产品bug，没有找到联系方式（q群已满）才在此提问，请谅解！

**Comment by yimelia** [comment]
都是支持离线的，如果开启IDE时无法登录，可以选择skip来跳过登录。
另外，airtest与poco是python第三方库，安装到本地后可以直接用命令行运行。
http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id3

**Comment by mayue1352** [comment]
> 都是支持离线的，如果开启IDE时无法登录，可以选择skip来跳过登录。
> 另外，airtest与poco是python第三方库，安装到本地后可以直接用命令行运行。
> http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id3

我以为是没联网报错了，请教下程序报failed to create d3d shaders这个要怎么解决？显卡问题吗？

**Comment by yimelia** [comment]
可以试一下更新显卡驱动，以及重装DirectX看看
