### ISSUE TITLE
怎么让循环输入每次加1，并让等待循环每次加8秒

### ISSUE THREAD

**Issue by yuanze12345678** [AirtestProject/AirtestIDE#377]
第一次输入1
等待8s
第二次输入2
等待16s
第三次输入3
等待24s
第四次输入4
等待32s

**Comment by yuanze12345678** [comment]
@brantxiong @Meteorix @EraChen233 @adolli

**Comment by EraChen233** [comment]
写个For循环处理

**Comment by yuanze12345678** [comment]
for i in range(5):
   touch((626,1205))#我
   poco(name="").click()#
  poco(name="").click()#
  text("1",enter=False)#输入1
  poco(").click()#
  touch((226,1200))#
  poco(name="").click()#
  sleep(8)#等待8秒

怎么让每次输入增加+1，等待每次+8.
告诉我一下，谢谢

**Comment by yuanze12345678** [comment]
@brantxiong @Meteorix @EraChen233 @adolli

**Comment by yuanze12345678** [comment]
告诉我一下怎么写的，谢谢。

**Comment by EraChen233** [comment]
```
for i in range(1,5):
	print("input ", i)
	print("waite ", i*8, "\n")
```
