### ISSUE TITLE
OPPO k1  无法连接 AirtestIDE 

### ISSUE THREAD

**Issue by 0onezero1** [AirtestProject/AirtestIDE#378]
* 测试开发环境AirtestIDE使用问题 无法连接 oppo k1 手机

**Comment by rockywhisper** [comment]
@0onezero1 
请问是否可以提供系统版本信息，我们找找相关设备测试下。

**Comment by yimelia** [comment]
我们这里尝试了oppo k1手机，是可以连接并且能成功跑脚本的，我们所用的手机环境如下：
![image](https://user-images.githubusercontent.com/6896468/56564619-07895b00-65e1-11e9-8bee-dc2d45e0e01b.png)

OPPO和VIVO系手机的设置请参考文档：
http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo
