### ISSUE TITLE
airtestproject可以做saas平台的pc端web的ui自动化测试吗？类似于管理系统这样的ui自动化可以做吗

### ISSUE THREAD

**Issue by wx8098** [AirtestProject/AirtestIDE#38]

**Comment by wx8098** [comment]
airtestproject可以做saas平台的pc端web的ui自动化测试吗？类似于管理系统这样的ui自动化可以做吗

**Comment by adolli** [comment]
下个版本会出h5版的poco-sdk，到时候可以对web应用或者浏览器页面进行控件识别。

**Comment by rockywhisper** [comment]
@wx8098   你好，我们 [上周的版本0.0.15](http://airtest.netease.com/changelog.html) 支持了selenium的插件支持。  [操作文档](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/4_advanced_features/4_selenium.html)

这个issue暂时关闭了哈，如果后续有问题随时联系。
