### ISSUE TITLE
HUAWEI P10 Plus 不兼容（不在设备支持列表中）

### ISSUE THREAD

**Issue by siaminem** [AirtestProject/AirtestIDE#383]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**( 测试开发环境AirtestIDE使用问题)**

**描述问题bug**
当我在确认ADB是否能正常连接手机时，按照windows部分进行操作，cmd中这样显示
List of devices attached
adb server version (39) doesn't match this client (40); killing...
* daemon started successfully
Y2J5T17421000577        device
我怀疑是设备兼容性的问题。
设备名称：华为 P10 Plus 型号：VKY-AL00
**截屏**

![image](https://user-images.githubusercontent.com/43562156/55614480-99aafa00-57bf-11e9-8f31-0606186c6998.png)

**python 版本:** `python3`

**操作系统:** `Windows10 64bit`

**设备:**
 - 型号: [VKY-AL00]
 - 系统: [Android 8.0.0]

**Comment by yimelia** [comment]
这个没问题的，只是因为ADB版本不同导致有个报错信息而已，能正确显示出 `设备号 device`那行就没错了

**Comment by siaminem** [comment]
但是我点击 refresh adb 后没有显示出我的设备名称啊

**Comment by yimelia** [comment]
可以先点一下restart adb，然后稍等一会之后再点refresh adb
如果是windows版本，随着IDE启动会有一个额外的黑色命令行窗口，可以把那个命令行窗口里的log截出来看看

**Comment by siaminem** [comment]
好的 谢谢您 我试一下！
