### ISSUE TITLE
Is it only possible with mac pc to automate iOS app testing?

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/AirtestIDE#385]
Is it only possible with mac pc to automate iOS app testing?

**Comment by EraChen233** [comment]
Replace iproxy with wdaproxy, 

```
brew install openatx/tap/wdaproxy
wdaproxy
```
Fill ip_of_mac:8100 in `IOS APP Connection`. Then you can connect iPhone with AirtestIDE on windows.
![image](https://user-images.githubusercontent.com/5961185/55718887-6b335600-5a2f-11e9-986c-dca586826398.png)


Here is the source code of wdaproxy.
https://github.com/openatx/wdaproxy
