### ISSUE TITLE
Can't download Airtest IDE

### ISSUE THREAD

**Issue by TadasFatmap** [AirtestProject/AirtestIDE#386]
When I'm in Term of Service page and I click "Agree and download" button it just simply doesn't work and download is not starting. I'm using the latest Chrome browser

**Comment by yimelia** [comment]
sorry, it maybe a bug, you can download it from this url: 
http://top.gdl.netease.com/AirtestIDE_2019-01-15_py3_win64.zip
or other version:
http://top.gdl.netease.com/AirtestIDE_2019-01-15_py3_Mac10-12.dmg
