### ISSUE TITLE
【Mac】IDE的log查看窗中print中文都展示为unicode码

### ISSUE THREAD

**Issue by clergychen** [AirtestProject/AirtestIDE#387]
**描述问题bug**
在mach环境下，IDE的log查看窗中打印的中文都展示为unicode码

**截屏**
![image](https://user-images.githubusercontent.com/18215714/55771286-07a23a80-5aba-11e9-8e2e-e7da3e9c519b.png)

**复现步骤**
1. 新建一个脚本
2. 写上 print("中文")
3. 运行，查看log窗口

**预期效果**
打印信息中的中文可以打印出来

**python 版本:** `IDE自带的python版本`

**操作系统:** `Mac pro  10.13.4`

**其他相关环境信息**
(在mac上运行中文展示异常，在windows上正常。)

**Comment by yimelia** [comment]
这个问题已修复，本周将会放的新版本里应该就好了
