### ISSUE TITLE
AirTest的测试报告图片无法显示

### ISSUE THREAD

**Issue by zct19950518** [AirtestProject/AirtestIDE#39]
看了生效报告的目录，没找到有图片生成
![img20180326_100925](https://user-images.githubusercontent.com/37786513/37883644-39ec969a-30de-11e8-8362-6181f928cd88.png)

**Comment by yimelia** [comment]
@zct19950518 你好~在报告运行的过程中有没有相关的log可以帮忙保存下来贴出来吗~以及如果方便的话，可以右键点击脚本名字，选择第二个选项打开脚本生成的结果窗口，把里面的log.txt文件的内容也贴出来看看（顺便看一下这个文件夹里面有没有成功生成屏幕截图文件）

**Comment by zct19950518** [comment]
@yimelia log.txt所在的目录看到了有报告的图片生成，但是网页版测试报告里面显示不出图片，log.txt如下
![popo 2018326153019](https://user-images.githubusercontent.com/37786513/37892548-bf2148ca-310a-11e8-907f-506011d26758.png)
![popo 201832615315](https://user-images.githubusercontent.com/37786513/37892555-c3e50e3c-310a-11e8-8443-9f4bfd7e2056.png)


[log.txt](https://github.com/AirtestProject/AirtestIDE/files/1846754/log.txt)

**Comment by rockywhisper** [comment]
@zct19950518  你好，我们今天发布了新版本，这个问题应该已经得到了修复。

下载链接： http://airtest.netease.com/changelog.html
欢迎下载使用，遇到问题的话还请随时反馈，非常感谢 : )
