### ISSUE TITLE
Xcode10运行iOS-Tagent提示"Test failed"

### ISSUE THREAD

**Issue by Yogurt1270** [AirtestProject/AirtestIDE#392]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题（本软件）

**描述问题bug**
directory not found for option '-F/Users/username/Desktop/auto/iOS-Tagent/Carthage/Build/iOS'

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**复现步骤**
1. 在Xcode打开“WebDriverAgentRunner”
2.配置相应开发者账号
3.选择连接真机，点击“Test”（已添加信任）

**预期效果**
真机连接成功

**python 版本:** `python3.6.5`

**操作系统:** `Mac OS`

**设备:**
 - 型号: [iPhone6]
 - 系统: [iOS12.1.4]

**Comment by EraChen233** [comment]
请提供xcode具体版本号，以及这一段bug提示是什么情况下看到的
![image](https://user-images.githubusercontent.com/5961185/55860437-d0f61e00-5ba6-11e9-87be-f70f682fed1c.png)

**Comment by Yogurt1270** [comment]
Xcode：Version 10.2 (10E125)
选择真机后，点击“Product”-“Test”之后，提示build成功，然后弹出Test Failed。

Ld /Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner normal arm64 (in target: WebDriverAgentRunner)
    cd /Users/lidong/Desktop/auto/iOS-Tagent
    export IPHONEOS_DEPLOYMENT_TARGET=9.3
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Products/Debug-iphoneos -F/Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Products/Debug-iphoneos -F/Users/lidong/Desktop/auto/iOS-Tagent/Carthage/Build/iOS -F/Users/lidong/Desktop/auto/iOS-Tagent/WebDriverAgentLib -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -filelist /Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/Objects-normal/arm64/WebDriverAgentRunner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=9.3 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/Objects-normal/arm64/WebDriverAgentRunner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -all_load -framework XCTest -framework WebDriverAgentLib -Xlinker -dependency_info -Xlinker /Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/Objects-normal/arm64/WebDriverAgentRunner_dependency_info.dat -o /Users/lidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfsttwcalswhjhfvajyrhnflwsfh/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner

ld: warning: directory not found for option '-F/Users/lidong/Desktop/auto/iOS-Tagent/Carthage/Build/iOS'

**Comment by EraChen233** [comment]
IOS-Tagent 目前还没有对Xcode 10.2发布最新的支持，所以可能会遇到一些未知错误。所以我们目前建议先降低Xcode版本进行测试 (*^_^*)。

**Comment by Yogurt1270** [comment]
好的，感谢Airtest团队。

**Comment by IcyW** [comment]
请问现在支持了吗？

> ld: warning: directory not found for option '-F/Users/icy/my_Developer/iOS-Tagent/Carthage/Build/iOS'

**Comment by IcyW** [comment]
请问现在支持了吗？Xcode10.0遇到这个问题

> ld: warning: directory not found for option 'xxxxx/iOS-Tagent/Carthage/Build/iOS'

**Comment by EraChen233** [comment]
> 请问现在支持了吗？Xcode10.0遇到这个问题
> 
> > ld: warning: directory not found for option 'xxxxx/iOS-Tagent/Carthage/Build/iOS'

这个是警告，不是错误，可以整理一下具体的情况，提个issue

**Comment by IcyW** [comment]
> > 请问现在支持了吗？Xcode10.0遇到这个问题
> > > ld: warning: directory not found for option 'xxxxx/iOS-Tagent/Carthage/Build/iOS'
> 
> 这个是警告，不是错误，可以整理一下具体的情况，提个issue

对这里只是一个警告，然后我也是Test Failed了，没有console不知道报错在哪

**Comment by EraChen233** [comment]
整理一下具体的情况，提个issue

**Comment by gemarkq** [comment]
xcode 11.5 ios 13.5 同样遇到这个问题，请问有什么方法解决吗？显示build成功，但是test失败

**Comment by jiaoyujulx** [comment]
我是用xcode10.2.1,ios12.5.4也是building成功，test失败，没有看到任何日志
