### ISSUE TITLE
Xcode9.4.1打开iOS-Tagent提示"Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode."

### ISSUE THREAD

**Issue by Yogurt1270** [AirtestProject/AirtestIDE#394]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
Xcode9.4.1打开iOS-Tagent提示版本不匹配

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。!
![image](https://user-images.githubusercontent.com/8851635/55879705-d452cf00-5bd1-11e9-879a-bec790e735f7.png)

**复现步骤**
1. 使用Xcode9.4.1打开项目，提示错误见附件

**预期效果**
看到项目工程

**python 版本:** `python3.6.5`

**操作系统:** `MacOS`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by EraChen233** [comment]
这是xcode版本太低的原因，推荐使用xcode10.1

**Comment by Yogurt1270** [comment]
好的，谢谢，我在9.3，9.4，10.0都试了。
