### ISSUE TITLE
官网上不低到3.7是不是写错了。应该是想说不低于2.7吧？

### ISSUE THREAD

**Issue by stimwhx** [AirtestProject/AirtestIDE#395]
若运行代码时，在cv2模块报 ImportError: DLL load failed: 找不到指定模块 的错，如果使用的python版本低于3.7，请直接运行:

pip uninstall opencv-contrib-python
# 若以下安装语句运行失败，可以尝试更新pip到最新版本后重试
pip install opencv-contrib-python==3.2.0.7
如果使用了python3.7，请安装 Visual C++ redistributable 2015， 参考 文档.

**Comment by yimelia** [comment]
没有写错，请仔细阅读内容，这里说的是2种情况，假如用了3.7版本，以及低于3.7版本，处理办法可以不同
