### ISSUE TITLE
poco正确识别UI树，但是无法使用冻结、监视、录制功能

### ISSUE THREAD

**Issue by nocklee** [AirtestProject/AirtestIDE#399]
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
1、工程用的NGUI，我把poco/U3D文件夹下的非NGUI的文件夹删除后把U3D文件加放在了项目下的Assets/ThridPartyPlugins文件夹
![image](https://user-images.githubusercontent.com/29427615/56263576-11f5b180-6116-11e9-8d47-9c8616af0d6e.png)

2、在Unity场景中的root_ui下add component/poco manager
![image](https://user-images.githubusercontent.com/29427615/56263554-f7bbd380-6115-11e9-9dd6-8d592a1e11c5.png)

3、poco正常连接，IDE中POCO辅助窗出现UI树
![image](https://user-images.githubusercontent.com/29427615/56263609-2c2f8f80-6116-11e9-8c37-8ff3e1f04748.png)

**4、使用冻结功能**
![image](https://user-images.githubusercontent.com/29427615/56263675-731d8500-6116-11e9-8791-4825f778186a.png)
UI树冻结，UNITY正常运行（画面不冻结，按钮正常点击）

**5、使用监视功能**
鼠标悬停在UI上没有任何反应

**6、使用录制功能**
不会自动记录操作

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - unity版本: 5.6.6f2 

**其他：**
Demo也无法实现上述功能

无报错，不清楚哪里配置有问题？

**Comment by yimelia** [comment]
把unity那个游戏窗口从编辑器里拖出来，然后在IDE中选windows的选定窗口，把unity游戏窗口嵌入到IDE中
![image](https://user-images.githubusercontent.com/6896468/56266299-71f05600-611e-11e9-8fb3-31d3cd4469e2.png)

操作过程可以参考官网首页上面那个"windows"分页的视频，里面就是用了unity游戏

**Comment by nocklee** [comment]
实在不好意思提出这些很低级的问题 T.T

只是如这个操作 还是没有效果，就是
![image](https://user-images.githubusercontent.com/29427615/56266579-1ffc0000-611f-11e9-83c6-1f0e290f0769.png)
使用POCO提供的DEMO 也无法实现上述功能

**Comment by nocklee** [comment]
![image](https://user-images.githubusercontent.com/29427615/56266968-1aeb8080-6120-11e9-891d-47de37323734.png)
以上是在POCO VIEW中打开DEMO，这里可以对UI进行定位

**Comment by rockywhisper** [comment]
@nocklee  你好，嵌入模式下，目前是可以正常显示出包围盒效果的：
![image](https://user-images.githubusercontent.com/8188879/56268001-f644d800-6122-11e9-8d12-c3a233ad08d8.png)
目前需要手动点击树节点，才会显示出对应的包围盒。
