### ISSUE TITLE
IDE exports the test for the incorrect script

### ISSUE THREAD

**Issue by nakhbari** [AirtestProject/AirtestIDE#4]
If there is 2 python script in the IDE and click on build the apk for FTL it’ll build the apk for the first script instead of the second one

**Comment by zzldjkzxf** [comment]
We repair this bug on the latest IDE. Now you can edit script and build the apk correspondingly.

**Comment by nakhbari** [comment]
@zzldjkzxf I tested this today on the v0.0.3_2018-02-11 build and it still built an old script.

**Comment by nakhbari** [comment]
Ahah! the package name changed, so i was running an old test APK. This is working as expected 😄

**Comment by nakhbari** [comment]
Actually I am still seeing this issue. Is there somewhere where we can see which test was outputted? could we name the APK the script name maybe?

**Comment by zzldjkzxf** [comment]
@nakhbari  I thought the latest version was 2018-02-12. And I tried it on windows today, it worked correctly.  I think you can see output test on ..\tool\copy_app\test_script.air relative to apk path. I will name the Apk the script name later.  Maybe you can download the latest IDE and try it again. If it still not worked for MAC.  Let me know what files under output test path.

**Comment by nakhbari** [comment]
@zzldjkzxf the path at which the test apk ends up being in Mac is

/private/var/folders/9y/6flqq3756vx7skck928pl9bc00clkg/T/AirtestIDE/apk/Test.apk

I think the app i'm downloading from the website is giving me an older version. The IDE says it's an older version (see screenshot)

![image](https://user-images.githubusercontent.com/2754461/36283453-726ee1b0-1259-11e8-94a3-bd2419c8f954.png)

The DMG is marked as 02-12 but if I look at the files dates, they're all last modified on the 11th. Do you think this is the issue?

<img width="539" alt="screen shot 2018-02-15 at 2 09 35 pm" src="https://user-images.githubusercontent.com/2754461/36283670-06cd0a8a-125a-11e8-8f73-4264d808b81a.png">

**Comment by zzldjkzxf** [comment]
@nakhbari I think you can see origin output python script at /private/var/folders/9y/6flqq3756vx7skck928pl9bc00clkg/T/AirtestIDE/tool/copy_app/test_script.air 
And you can see tarfile that include output python script at /private/var/folders/9y/6flqq3756vx7skck928pl9bc00clkg/T/AirtestIDE/tool/assets/private.mp3, 
extract the script file and see which script was compressed.
Moreover, when you test the apk on phone, you should delete the old test apk. It will be something wrong if you cover install the test apk.
As for the version problem, I'll ask my colleague JianJun.

**Comment by zzldjkzxf** [comment]
@nakhbari I think you can see origin output python script at /private/var/folders/9y/6flqq3756vx7skck928pl9bc00clkg/T/AirtestIDE/tool/copy_app/test_script.air 
And you can see tarfile that include output python script at /private/var/folders/9y/6flqq3756vx7skck928pl9bc00clkg/T/AirtestIDE/tool/assets/private.mp3, 
extract the script file and see which script was compressed.
Moreover, when you test the apk on phone, you should delete the old test apk. It will be something wrong if you cover install the test apk.
As for the version problem, I'll ask my colleague JianJun.
.

**Comment by nakhbari** [comment]
Oh wow, you're right. I only overwrote the app. When i uninstall and reinstall it works fine! 👌

**Comment by rockywhisper** [comment]
We locked IDE version  on 2018-02-11, so the version info on IDE title-bar is v0.0.3_2018-02-11.
And we built and released the package on 2018-02-12, so the files tag is 2018-02-12.
Sorry for the misunderstanding info, I'll do some improvements later.
