### ISSUE TITLE
Airtest1.2.1版本链接oppo手机，后台报“[WinError 10054] 远程主机强迫关闭了一个现有的连接”

### ISSUE THREAD

**Issue by hejiong19860303** [AirtestProject/AirtestIDE#406]
测试手机;oppo A557

操作步骤：在AirtestIDE上连接上手机后（使用usb数据线进行连接），在poco辅助窗口选择cocos-js ,日志报“on error [WinError 10054] 远程主机强迫关闭了一个现有的连接。”

![image](https://user-images.githubusercontent.com/49967806/56706295-ffe3c680-6746-11e9-9dd6-9ebdc89e8d34.png)

![image](https://user-images.githubusercontent.com/49967806/56706247-d62a9f80-6746-11e9-9459-c134bc3e00f6.png)

**Comment by yimelia** [comment]
先在手机上打开已经成功嵌入poco-cocosjs sdk的应用，然后再试

**Comment by hejiong19860303** [comment]
嵌入poco-cocosjs sdk的应用已经打开，但是还是报“”远程主机强迫关闭了一个现有的连接


![image](https://user-images.githubusercontent.com/49967806/56706438-91533880-6747-11e9-9650-ec82e72d1ccd.png)
![image](https://user-images.githubusercontent.com/49967806/56706450-9a440a00-6747-11e9-92cf-72110213b787.png)

**Comment by yimelia** [comment]
可能是嵌入没有成功导致的，没能成功连上Poco的服务

**Comment by hejiong19860303** [comment]
没有嵌入成功的意思是？ 怎么判断是否嵌入成功？



发件人：yimelia <notifications@github.com>
发送时间：2019-04-25 10:54
主题：Re: [AirtestProject/AirtestIDE] Airtest1.2.1版本链接oppo手机，后台报“[WinError 10054] 远程主机强迫关闭了一个现有的连接” (#406)
收件人："AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>
抄送："hejiong19860303"<hejiong@tinman.cn>,"Author"<author@noreply.github.com>

可能是嵌入没有成功导致的，没能成功连上Poco的服务

**Comment by hejiong19860303** [comment]
2019-04-25 

hejiong 




可能是嵌入没有成功导致的，没能成功连上Poco的服务

上面这句的意思是引擎cocox-js（SDK）没有成功嵌入到应用中吗？
