### ISSUE TITLE
app是源生的但是在poco里面找不到源码

### ISSUE THREAD

**Issue by QQ929304643** [AirtestProject/AirtestIDE#408]

**Comment by yimelia** [comment]
请提供更多信息，否则我们无法帮到你：什么APP，什么型号手机，是否在黑色命令行窗口里看到报错，手机是否在不断重装pocoservice

**Comment by QQ929304643** [comment]
我装了pocosevervice但是他一直在我手机卸载重装。。。实在搞不定，之前用python3.6的时候还行换了python3.7就出现这种情况了

**Comment by QQ929304643** [comment]
我装了pocosevervice但是他一直在我手机卸载重装......实在搞不定，之前用python3.6的时候还行换了python3.7就出现这种情况了     APP：微信、vivo手机，模拟器也运行不了
 手机一直不断的重装pocoservice

**Comment by QQ929304643** [comment]
请问一下大佬如何解决：   APP：是微信，手机型号是viovo    ，模拟器也是没有poco-Android源生代码  pocoservice在手机一直不断的重装

**Comment by QQ929304643** [comment]
> 请提供更多信息，否则我们无法帮到你：什么APP，什么型号手机，是否在黑色命令行窗口里看到报错，手机是否在不断重装pocoservice

请问一下大佬如何解决：APP：是微信，手机型号是viovo，模拟器也是没有poco-Android源生代码pocoservice在手机一直不断的重装

**Comment by yimelia** [comment]
可以先看一下这个文档，尝试将Yosemite输入法设置为默认：http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo

如果还是不行，可以尝试下卸载掉手机里的2个pocoservice.apk，然后手工重装一下，这2个apk的位置和名字都可以在IDE目录下的`poco\drivers\android\lib`里找到

**Comment by QQ929304643** [comment]
> 可以先看一下这个文档，尝试将Yosemite输入法设置为默认：[http](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo)：//airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo[](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo)
> 
> 如果还是不行，可以尝试下卸载掉手机里的2个pocoservice.apk，然后手工重装一下，这2个APK的位置和名字都可以在IDE下目录的`poco\drivers\android\lib`里找到

好的我尝试一下谢谢

**Comment by QQ929304643** [comment]
> > 可以先看一下这个文档，尝试将Yosemite输入法设置为默认：[http](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo)：//airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo
> > 如果还是不行，可以尝试下卸载掉手机里的2个pocoservice.apk，然后手工重装一下，这2个APK的位置和名字都可以在IDE目录下的`poco\drivers\android\lib`里找到
> 
> 好的我尝试一下谢谢

手工重装了用airtest 然后连接vivo手机pocovice还是存在一直重装。。。 pocovice我已经手工重装了  还是一样。。。

**Comment by QQ929304643** [comment]
pocovice两个都已经手工重装了 ，但是还是出现vivo手机一直不断的重装


------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 上午10:20
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>;
抄送: "这个叫什么东西没玩过耶"<929304643@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] app是源生的但是在poco里面找不到源码 (#408)




可以先看一下这个文档，尝试将Yosemite输入法设置为默认：http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo
 
如果还是不行，可以尝试下卸载掉手机里的2个pocoservice.apk，然后手工重装一下，这2个apk的位置和名字都可以在IDE目录下的poco\drivers\android\lib里找到

**Comment by yimelia** [comment]
在你的python环境里pip list，看一下`websocket-client`版本号是多少，如果版本号高于0.48.0，尝试卸载掉重装一下：
`pip uninstall websocket-client`
`pip install websocket-client==0.48.0`

**Comment by QQ929304643** [comment]
> 在你的python环境里点子列表，看一下`websocket-client`版本号是多少，如果版本号高于0.48.0，尝试卸载掉重装一下：
> `pip uninstall websocket-client`
> `pip install websocket-client==0.48.0`

还是存在pocovice一直重装问题
