### ISSUE TITLE
Decive Screen手机界面显示不全

### ISSUE THREAD

**Issue by dalanzhu** [AirtestProject/AirtestIDE#409]
![image](https://user-images.githubusercontent.com/25153851/56862550-b7463a80-69de-11e9-93bf-c306f237662b.png)

页面显示3/4  但实际按钮布局为整个显示框

**Comment by rockywhisper** [comment]
@dalanzhu   
请参考这个[连接显示不全](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id9)进行设置。
