### ISSUE TITLE
vivo y35(android 5.0.2) 手机 adb 无法连接

### ISSUE THREAD

**Issue by wanglizhang-123** [AirtestProject/AirtestIDE#411]
vivo y35(android 5.0.2) 手机 adb 无法连接, 重启ADB 也无法连接

**Comment by yimelia** [comment]
请根据[文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id1)进行问题自查，并查看VIVO相关设置章节。
或者提供更多有效信息，目前提供的信息无法帮上忙
