### ISSUE TITLE
"Poco Inspector" button doesn't work as intended, when connected to a PC Unity Build [Windows 10]

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/AirtestIDE#412]
**Describe the bug**
Poco inspector button doesn't work as expected, when the inspector button is used to mouse over NGUI on a PC Unity project. No UI information such as size of the UI, position of the UI, name of the UI and so on appears. [Even though the Poco game object in unity project is configured properly to find NGUI objects]  

**To Reproduce**
Steps to reproduce the behaviour:
1. Use any Unity project with poco UI enabled, and has UGUI [Unity GUI] or NGUI in the project
2. Build project
3. Open Unity Build, [Unity Window]
3. Use Airtest IDE, Version v.1.2.0 [Or Higher] to connect to the newly opened window
4. Use Poco inspector button, and find out that it doesn't work like expected when compared to connected to an Android/iOS device. 

**Expected behaviour**
The poco inspector button should display the Unity's UGUI or NGUI position, size, name, UIPath like expected. 

**AirtestIDE version:** `1.0.15`
Airtest IDE, Version v.1.2.0 [Or Higher] 

**Platform:** `Windows7 64bit, etc.`
Windows 10

**Comment by yimelia** [comment]
sorry, we have not supported this feature yet, we will support it as soon as possible.
