### ISSUE TITLE
How do I import another module?

### ISSUE THREAD

**Issue by YSH2224** [AirtestProject/AirtestIDE#413]
Remove any following parts if does not have details about

I want to know how to use another module in a test.py file using airtest. im trying to use a module called playsound but when i write:
from playsound import playsound
playsound('myfile.mp3')

it doesnt work, how should i import this module?

**Comment by yimelia** [comment]
if you are using AirtestIDE, you can [use local python environment](http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#use-local-python-environment-to-run-scripts-trial) to import your module.
