### ISSUE TITLE
I think you know how to set Custom Python Path on MacOS.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/AirtestIDE#415]
I think you know how to set Custom Python Path on MacOS.

**Comment by EraChen233** [comment]
If you want to know how to custom python for AirtestIDE, here's the answer.

Click `Option` -> `Settings`

![image](https://user-images.githubusercontent.com/5961185/57266288-e5e2a600-70ad-11e9-84c6-16e98291a377.png)

**Comment by JJunM** [comment]
> If you want to know how to custom python for AirtestIDE, here's the answer.
> 
> Click `Option` -> `Settings`
> 
> ![image](https://user-images.githubusercontent.com/5961185/57266288-e5e2a600-70ad-11e9-84c6-16e98291a377.png)

How to choose a Python file path installed???????

**Comment by EraChen233** [comment]
What do you mean ?
Click `open` button on the right side, open your python directory and select python.exe.
