### ISSUE TITLE
Can't login AirtestIDE macOS

### ISSUE THREAD

**Issue by kilirushi** [AirtestProject/AirtestIDE#419]
The captcha in tool can't verify 
I'm using macOS Mojạve version 10.14.4
Please see the attached clip:
[Screen Recording.zip](https://github.com/AirtestProject/AirtestIDE/files/3157392/Screen.Recording.zip)

**Comment by thuantran** [comment]
The same thing happens on AirtestIDE_2019-04-16_py3_win64 with Windows 10 1904. Any help would be appreciated.

**Comment by EraChen233** [comment]
If you cannot verify it, click `skip` button in the lower right to skip this step.

![image](https://user-images.githubusercontent.com/5961185/57421128-1dcc2380-723d-11e9-803e-0e68010f379a.png)
