### ISSUE TITLE
AirtestIDE最新版，新加纯py文件后，在文件中加入注释代码，运行后报UnicodeDecodeError

### ISSUE THREAD

**Issue by hejiong19860303** [AirtestProject/AirtestIDE#420]
![image](https://user-images.githubusercontent.com/49967806/57435054-fb52fe00-726e-11e9-836f-6d30b3651d03.png)

**Comment by yimelia** [comment]
用Notepad++打开该代码文件，确认文件编码是UTF-8编码
![image](https://user-images.githubusercontent.com/6896468/57435449-06f2f480-7270-11e9-84d7-5d16ccd369f8.png)

**Comment by hejiong19860303** [comment]
确定是utf-8




但是执行的时候还是报错：

2019-05-09 

hejiong 



发件人：yimelia <notifications@github.com>
发送时间：2019-05-09 15:35
主题：Re: [AirtestProject/AirtestIDE] AirtestIDE最新版，新加纯py文件后，在文件中加入注释代码，运行后报UnicodeDecodeError (#420)
收件人："AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>
抄送："hejiong19860303"<hejiong@tinman.cn>,"Author"<author@noreply.github.com>

用Notepad++打开该代码文件，确认文件编码是UTF-8编码

**Comment by RunningIkkyu** [comment]
遇到同样的问题，请问 @hejiong19860303 解决了吗？

**Comment by yimelia** [comment]
@RunningIkkyu 
这是新版本的BUG，可以重新到官网下载已经修复过此问题的win64位版本（名称相同，但是已经修复过此问题了）
win32版本因为打包问题暂时还没有替换，我们后续会重新更换

**Comment by RunningIkkyu** [comment]
> @RunningIkkyu
> 这是新版本的BUG，可以重新到官网下载已经修复过此问题的win64位版本（名称相同，但是已经修复过此问题了）
> win32版本因为打包问题暂时还没有替换，我们后续会重新更换

请问是AirtestIDE_2019-04-16_py3_win64.zip  这个包么？我电脑安装的就是官网下载的64位包啊

**Comment by yimelia** [comment]
@RunningIkkyu 
是的，名字没有变，但是包的内容我们替换成了修复这个问题的版本了
重新下载一个试试
