### ISSUE TITLE
关于unity3d文件夹复制到项目后报错的问题

### ISSUE THREAD

**Issue by 394659383** [AirtestProject/AirtestIDE#421]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
将SDK里面的Unity3D文件夹复制到项目里面后启动unity直接报错

**截屏**
![QQ图片20190510110952](https://user-images.githubusercontent.com/50472952/57500275-740c9580-7315-11e9-8a5f-b3e46daa54c0.png)

**复现步骤**
1. 复制文件夹
2. 启动unity

**预期效果**
在去年8月我当时在群里面反应过这个问题，当时是你们技术重新发的两个脚本给我走的另外一种初始化流程，现在由于时间太久了找不到记录了，我以为你们文档里面有添加这种问题的处理方法，结果没有0.0.请问现在我需要怎样处理才能正常添加sdk不报错。
注：不懂C#语法

**操作系统:** `Windows7 64bit`

**Comment by yimelia** [comment]
这个问题是因为`JsonSerializerSettings`这个名字与你们项目有命名冲突导致的，之前的解决办法是，用这个[minijson](https://gist.github.com/darktable/1411710) 文件来替代poco中使用的`Newtonsoft.Json`，来解决这个命名冲突的问题。

- 把3rd那个目录删掉
- 把minijson.cs放进去
- 修改pocomanager.cs里面所有涉及到JsonCovert的地方，和最开始的引用，改成minijson的解析方式

这个问题由于不典型，其他项目中不太会出现（只是因为名字重复了），因此没有写进文档里。

**Comment by chasezhao** [comment]
这个文件在哪里能找到？？？？我也遇见这个问题了··但是没能找到你的minijson

**Comment by 394659383** [comment]
> 这个文件在哪里能找到？？？？我也遇见这个问题了··但是没能找到你的minijson
https://gist.github.com/darktable/1411710#file-minijson-cs或者点上面那个minijson连接，需自备翻墙工具

**Comment by momo164474** [comment]
你好，我也遇到了同名文件冲突的问题，这个连接打不开了，能再发一次吗
