### ISSUE TITLE
打包时一直弹错误框

### ISSUE THREAD

**Issue by Dyd1989** [AirtestProject/AirtestIDE#422]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题（本软件） 

**描述问题bug**
打包时一直弹错误框，并没有使用目标目录，却一直弹窗提示you are using the target build folder,please close first的弹窗。

**截屏**
![image](https://user-images.githubusercontent.com/32152153/57567305-8ec03680-7409-11e9-8b2f-149e046bc3db.png)

**复现步骤**
1. Go to 'Firebase'
2. Click on '打包测试apk'

**预期效果**
想打包成测试apk

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**设备:**
 - 型号: [华为honor 9i]
 - 系统: [Android 8.0]

**Comment by yimelia** [comment]
之前有没有成功打包过？这个报错一般是2种情况，用来生成临时apk的文件夹没有写入权限，或者是那个文件夹正好被打开了（并且可能开了相关的cmd窗口停留在那里）。尝试用管理员权限打开IDE重试，或者是确认本地没有开启任何指向打包成功后的目录的CMD窗口即可。
