### ISSUE TITLE
ide无法连接手机，提示‘gbk’ codec can't decode bytes

### ISSUE THREAD

**Issue by geonsme** [AirtestProject/AirtestIDE#43]
应该是adb shell执行后输出中文log，而cmd输出中文报错

**Comment by adolli** [comment]
see also #29

**Comment by rockywhisper** [comment]
@geonsme  这种情况一般是由于手机助手等第三方软件占用adb导致，我们今天会放出新版本在软件内进行解决提示。这个issue先关闭了哈  :-)
