### ISSUE TITLE
用IDE脚本运行成功，pycharm运行提示元素查找超时

### ISSUE THREAD

**Issue by coolluo01** [AirtestProject/AirtestIDE#434]
商城界面选择网银支付，会跳转到第三方支付界面，用pycharm运行python脚本，点击下一步操作 未执行，提示下一个元素查找超时，用IDE运行正常
![图片](https://user-images.githubusercontent.com/32696828/58222428-95737580-7d48-11e9-81ff-a7a1e05147df.png)
![图片](https://user-images.githubusercontent.com/32696828/58222483-c489e700-7d48-11e9-9813-a845efd1c886.png)
![图片](https://user-images.githubusercontent.com/32696828/58222666-5e519400-7d49-11e9-9314-00b220c76f9c.png)

**Comment by yimelia** [comment]
看一下本地的poco版本号是多少？`pip install -U pocoui` 升级到最新试试

**Comment by coolluo01** [comment]
升级到最新版本后，问题已解决
