### ISSUE TITLE
是否支持windows seerver 2008R2

### ISSUE THREAD

**Issue by amazinglZ** [AirtestProject/AirtestIDE#435]
在windows seerver 2008R2中运行后，无法打开，窗口信息无法看到

**Comment by amazingHX** [comment]
[图片]

**Comment by amazinglZ** [comment]
![L`FR%V6KMK(CFM)}%AORJJO](https://user-images.githubusercontent.com/34085354/58532677-dcfe7380-8218-11e9-8071-96fc10b0d522.jpg)

**Comment by amazinglZ** [comment]
打开后窗口一闪而过，图片为展示内容

![FYA__T O5YRCGR1MXHTPU L](https://user-images.githubusercontent.com/34085354/58533003-d58b9a00-8219-11e9-90ee-9ad81b7b02a6.png)

**Comment by yimelia** [comment]
试一下在网上找这几个dll，放到你的`C:/Windows/System32`中（64位系统可以考虑找到64位版本的对应文件，放到`C:\Windows\SysWOW64`下）
![image](https://user-images.githubusercontent.com/6896468/58533699-c7d71400-821b-11e9-8d4f-e8a1b36ba4af.png)
红框中的文件一定要放

**Comment by amazinglZ** [comment]
> 试一下在网上找这几个DLL，你放到的`C:/Windows/System32`中（64位系统可以考虑找到64位版本的对应文件，放到`C:\Windows\SysWOW64`下） 红框中的文件一定要放
> ![图片](https://user-images.githubusercontent.com/6896468/58533699-c7d71400-821b-11e9-8d4f-e8a1b36ba4af.png)

这个一定要Windows Server2008R2，对应的文件么，我现在很难找到对应版本的

**Comment by yimelia** [comment]
尝试根据你的系统是64位还是32位的来找

**Comment by amazinglZ** [comment]
我这边已经尝试很多版本，结果都不行，是否方便提供一下上述文件=-=

**Comment by yimelia** [comment]
可以提供一个邮箱我发给你

**Comment by amazinglZ** [comment]
2939794293@qq.com  万分感谢

**Comment by yimelia** [comment]
已发，但是不能确保问题能够得到解决。。我们这里没有win server2008的系统可以进行测试

**Comment by amazinglZ** [comment]
尝试过了，，还是不可以，，十分感谢您的回复

**Comment by amazinglZ** [comment]
下载了32位的客户端后可以使用了
