### ISSUE TITLE
能否支持绿色版chrome

### ISSUE THREAD

**Issue by brucmao** [AirtestProject/AirtestIDE#436]
我用的是绿色版的[chrome](https://csharp.love/chrome-update-tool.html)，默认没有安装在c盘。
![image](https://user-images.githubusercontent.com/6119652/58568067-22955d80-8266-11e9-896e-8839c2863194.png)
chrome路径设置如上图，

**描述问题bug**
点击运行提示 cannot find Chrome binary

如果我用安装版的firefox则没有这个问题，但是firefox只支持运行，不支持录制

**截屏**

![image](https://user-images.githubusercontent.com/6119652/58571685-d863aa80-826c-11e9-8c03-5404abea19b4.png)

**python 版本:** `python3.7.2`

**操作系统:** `Windows10 专业版 64bit 1809`

**设备:**
chrome 版本 `74.0.3729.169`
geckodriver 对应版本为 http://npm.taobao.org/mirrors/chromedriver/74.0.3729.6/

**Comment by yimelia** [comment]
有可能是不支持的，可能还是需要一个安装版本的原版chrome好一些，而且有一定的可能性即使它支持的话，也可能无法进行录制（这点只是猜测）。
目前网上能搜到的相关信息很少，所以我们无法帮助到你，可能直接去询问该版本chrome的制作者会更好一点。
