### ISSUE TITLE
【Windows10 x64】无法打开AirtestIDE

### ISSUE THREAD

**Issue by wodesenlin** [AirtestProject/AirtestIDE#438]
描述：
运行AirtestIDE.exe 文件，一个纯白色窗口出现后即闪退，无法打开IDE

截屏
![image](https://user-images.githubusercontent.com/26407724/59004363-f53f4580-884b-11e9-86d1-0f6a3ccfc5fc.png)

复现步骤
1、双击AirtestIDE.exe 
2、等待
3、AirtestIDE 的命令窗口闪退

**Comment by wodesenlin** [comment]
操作系统: Windows10 64bit

1一个月前刚下载时是可以使用的，今天再使用时，发现无法打开。

**Comment by EraChen233** [comment]
请参考 http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2 ，提供error信息

**Comment by wodesenlin** [comment]
上面的截图就是出现的所有信息

**Comment by 123lzw** [comment]
我也是这个问题
![image](https://user-images.githubusercontent.com/41624542/59985661-5d23c780-9665-11e9-80e1-0c112eb7e632.png)

**Comment by yimelia** [comment]
hi @123lzw 
我们有一个测试版本的IDE，可以下载下来试试看能不能用，点[这里](https://top.gdl.netease.com/AirtestIDE_2019-06-24_py3_win64_CompatibilityMode.zip)

下载完毕后解压，双击 `兼容模式启动.bat` 这个脚本来启动IDE（注意**不是**直接双击AirtestIDE.exe来启动），看看这个版本是否对你有帮助

**Comment by van123456** [comment]
测试版本也没有用
![image](https://user-images.githubusercontent.com/28648636/60330110-50d09f00-99c4-11e9-94de-7b76577d7f6f.png)

**Comment by yimelia** [comment]
@van123456 
或者试一下官网上面的历史版本呢？找几个旧一点的版本试试看

**Comment by van123456** [comment]
adb杀了，用你发的测试版本起来了，感谢
![image](https://user-images.githubusercontent.com/28648636/60333115-d1929980-99ca-11e9-957a-fa1e796968d1.png)

**Comment by Chen-Ed** [comment]
> 亚行杀了，用你发的测试版本起来了，感谢
> ![图片](https://user-images.githubusercontent.com/28648636/60333115-d1929980-99ca-11e9-957a-fa1e796968d1.png)

大哥 亚行杀了是什么意思，我跟你的情况一样，要怎么解决呢

**Comment by yimelia** [comment]
@Chen-Ed 
任务管理器-进程，找到所有的adb.exe，结束进程

**Comment by Chen-Ed** [comment]
@yimelia 谢了老哥 能打开了。    我有个旧问题，这打开.py文件，这编辑框显示不出来了
![image](https://user-images.githubusercontent.com/53363383/62108165-f769d180-b2db-11e9-8ec9-9c98353777e6.png)

**Comment by yimelia** [comment]
用的是这个页面上面提供的那个兼容性模式启动的IDE吗？

**Comment by Chen-Ed** [comment]
是啊 杀掉adb.exe 然后运行兼容模式运行.bat  IDE起来了，然后随便打开一个.py文件，就成上面那样了

**Comment by yimelia** [comment]
你的机器配置是什么样的，显卡型号和内存大小

**Comment by Chen-Ed** [comment]
基本硬件信息

    机箱: 系统机箱

        机箱类型: Notebook

        制造商: ASUSTeK COMPUTER INC.

        序列号: H6N0CV02868423G

        有锁: False

        安全状态: None

        UUID: 5F9C6057-0991-C545-8829-3AF0E000EF33

    主板: X441UVK

    基本输入/输出系统（BIOS）: BIOS Date: 02/28/17 11:28:21 Ver: 05.0000C

    中央处理单元（CPU）: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

    物理内存 X 2

        4GB

        4GB

    硬盘: KingDian S370 256GB (238.5GB)

    视频卡 X 2

        Intel(R) HD Graphics 620

        NVIDIA GeForce 920MX

    监视器 X 2

        通用即插即用监视器

        默认监视器

    音频设备 X 2

        英特尔(R) 显示器音频

        Realtek High Definition Audio

    网络适配器

        WLAN - Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC (Connected)

        以太网 - Realtek PCIe FE Family Controller (Connected)

    键盘: USB 输入设备

    键盘: PC/AT 增强型 PS/2 键盘(101/102 键)

    鼠标: HID-compliant mouse

    鼠标: HID-compliant mouse

硬件分数 (基本分数: 0)

    处理器（每秒计算）: 0

    内存（每秒内存操作）: 0

    图形（Windows Aero的桌面性能）: 0

    游戏图形（3D商务和游戏图形性能）: 0

    主硬盘（硬盘数据传输率）: 0

**Comment by yimelia** [comment]
禁用一下集成显卡，再打开试一下，这样会强制用独立显卡去打开

**Comment by Chen-Ed** [comment]
我禁用了集显驱动后重新打开 并没有解决。但是发现了一个意外的解决方案：1.打开IDE 2.打开.py脚本 3.关闭IDE 4.重新打开IDE    这样子.py文件能显示出来

**Comment by yimelia** [comment]
可能的解决方案：
1. 更新你的显卡驱动到最新之后重试。
2. 如果还是不行，打开刚才文件夹里的`兼容模式启动.bat`，把内容改成下面这样：
```
set AIRTESTIDE_OPENGL=angle
AirtestIDE.exe
```
然后再双击这个bat启动看看
