### ISSUE TITLE
很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行

### ISSUE THREAD

**Issue by MumuTester** [AirtestProject/AirtestIDE#441]
# -*- encoding=utf8 -*-
__author__ = "Administrator"

from airtest.core.api import *

auto_setup(__file__)

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)
==============================================================
"D:\AirtestIDE\AirtestIDE" runner "C:\Users\Administrator\Desktop\1234.air"  --log "C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\01e6259519c0ba2171142d830150ce25"
============================================================

[Start running..]
do not connect device
save log in 'C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\01e6259519c0ba2171142d830150ce25'
[11:26:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[11:26:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[11:26:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 79UNW19403000029 wait-for-device
[11:26:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 79UNW19403000029 shell getprop ro.build.version.sdk
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)

**Comment by yimelia** [comment]
请把报错内容完整地贴出来，这个log正好把实际报错内容漏掉了。。。
顺便，在代码的第三行`auto_setup(file)`
应该改为： `auto_setup(__file__)`

**Comment by MumuTester** [comment]
# -*- encoding=utf8 -*-
__author__ = "Administrator"
from airtest.core.api import *
auto_setup(__file__)


from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)



======================================


"D:\AirtestIDE\AirtestIDE" runner "C:\Users\Administrator\Desktop\1234.air"  --log "C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\01e6259519c0ba2171142d830150ce25"
=============================================================================================================================


[Start running..]
do not connect device
save log in 'C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\01e6259519c0ba2171142d830150ce25'
[11:40:46][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[11:40:46][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[11:40:46][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 79UNW19403000029 wait-for-device
[11:40:46][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 79UNW19403000029 shell getprop ro.build.version.sdk



=============================================================================================================================
我修改了 还是不行呀




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 中午11:37
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




请把报错内容完整地贴出来，这个log正好把实际报错内容漏掉了。。。
 顺便，在代码的第三行auto_setup(file)
 应该改为： auto_setup(__file__)

**Comment by yimelia** [comment]
报错是什么？

**Comment by MumuTester** [comment]
我把报错日志也放在下面了。我用“==============”把代码、日志、我的回复隔开了




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 中午11:44
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




报错是什么？

**Comment by yimelia** [comment]
在log里看Traceback这个关键词，你发的这段log里没有报错信息

**Comment by MumuTester** [comment]
我通过图上的地址去打开日志文件log.txt，发现日志里面是空的，咋个回事呢




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 中午11:47
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




在log里看Traceback这个关键词，你发的这段log里没有报错信息

**Comment by MumuTester** [comment]
点击图上的小地球却可以打开我的游览器，说明我的游览器路径设置是没有问题的




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 中午11:47
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




在log里看Traceback这个关键词，你发的这段log里没有报错信息

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/59244752-59954700-8c48-11e9-9644-aca6ce373d49.png)

麻烦截出运行时log最后的traceback部分，类似图上这样

**Comment by MumuTester** [comment]
------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 中午12:57
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)





 
麻烦截出运行时log最后的traceback部分，类似图上这样

**Comment by yimelia** [comment]
@MumuTester 
看不到你的回复内容，麻烦补充描述清楚你遇到的问题，否则只能关闭issue了

**Comment by MumuTester** [comment]
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\Administrator\Desktop\1234.air\1234.py", line 9, in <module>
    driver = WebChrome()
  File "D:\AirtestIDE\airtest_selenium\proxy.py", line 30, in __init__
    service_log_path=service_log_path, desired_capabilities=desired_capabilities)
  File "D:\AirtestIDE\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "D:\AirtestIDE\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\AirtestIDE\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\AirtestIDE\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "D:\AirtestIDE\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)




----------------------------------------------------------------------
Ran 1 test in 3.265s


FAILED (errors=1)
[Finished]





------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 下午2:09
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




@MumuTester
 看不到你的回复内容，麻烦补充描述清楚你遇到的问题，否则只能关闭issue了

**Comment by yimelia** [comment]
试一下把`driver = WebChrome()`这行代码，改为传入你的chromedriver.exe实际位置来初始化，类似这样：
```
driver = WebChrome(r"E:\chrome\chromedriver.exe")
```

**Comment by MumuTester** [comment]
我在试一下把游览器驱动和游览器版本换一下看看
，你先不要关闭我的工单，我难的再发一个




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 下午2:15
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




试一下把driver = WebChrome()这行代码，改为传入你的chromedriver.exe实际位置来初始化，类似这样：
 driver = WebChrome(r"E:\chrome\chromedriver.exe")

**Comment by MumuTester** [comment]
我按照你说的做了，虽然游览器被打开了还是报错，而且get不到链接




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月11日(星期二) 下午2:15
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




试一下把driver = WebChrome()这行代码，改为传入你的chromedriver.exe实际位置来初始化，类似这样：
 driver = WebChrome(r"E:\chrome\chromedriver.exe")

**Comment by yimelia** [comment]
尝试自己百度这个报错信息吧。。。这个可能是selenium的设置问题、环境问题之类引发的

**Comment by MumuTester** [comment]
我已经找到问题啦，是因为电脑里面之前装过version 75的，安装其他的版本时无法替换注册表，导致无论怎么安装都无法解决，所以这种情况你们要统计一下，以后你们好给他的客户处理




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月13日(星期四) 上午9:55
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




尝试自己百度这个报错信息吧。。。这个可能是selenium的设置问题、环境问题之类引发的

**Comment by yimelia** [comment]
@MumuTester 
是说之前装的chrome是75版本的，然后又重装了别的版本吗？
后面是怎么处理的？

**Comment by MumuTester** [comment]
删除注册表里面75的注册表信息，重新安装就好啦




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年6月13日(星期四) 上午10:56
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "."<229421064@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 很久没有用过了，今天突然报错，点击小地球是可以打开的，单运行脚本无法运行 (#441)




@MumuTester
 是说之前装的chrome是75版本的，然后又重装了别的版本吗？
 后面是怎么处理的？

**Comment by yimelia** [comment]
具体是注册表中哪个键值呢？我记录一下这个信息
