### ISSUE TITLE
Airtest can continue to run the script if it failed?

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/AirtestIDE#442]
I have a game, and i have a long test-cases, i want to start one or two script and just to read the result about performance in the evening, but if one of my test is failed, Airtest just stop the script

**Comment by yimelia** [comment]
hi @Chesterfild 
Add some try..catch statements where possible errors, like 
```
try:
    touch(picture)
except:
    do sth
```
or touch the screen if the picture exists
```
if exists(picture):
    touch
```

**Comment by Chesterfild** [comment]
> Привет @Chesterfild
> Добавьте несколько операторов try..catch, где возможные ошибки, такие как
> 
> ```
> try:
>     touch(picture)
> except:
>     do sth
> ```
> 
> или коснитесь экрана, если изображение существует
> 
> ```
> if exists(picture):
>     touch
> ```

Ya this is obviously, i can make condition
``
if exist (picture)==0:
    assert_exist (picture, "comment")
else:
    touch (picture) 
But if i get the new build with change or new content, or developer broke something i failed test, and i need just turn off setting of force stop scrept.

May be i can do this in code of Airtest, but, i don't know how...

I need continue test no mather what happend and, just reed what happend wrong. Can enione help me with thst?

**Comment by yimelia** [comment]
hi @Chesterfild 
We usually take the following methods:
1.  implement a method like `touch_if_exists`, like this:
```
def touch_if_exists(picture):
    pos = exists(picture)
    if pos:
        touch(pos)
```
then use it in your code to replace `touch()`

2. Divide the long test-cases into multiple sub-test-cases, we provide [using](https://airtest.readthedocs.io/en/latest/README_MORE.html#import-from-other-air) API to do this:
```
from airtest.core.api import using
using("cases.air")
from cases import case1, case2
case1()
case2()
```

3. or use some unit test framework like [unittest](https://docs.python.org/3/library/unittest.html), but ti's code can't run in AirtestIDE, you can use Pycharm/sublime/vscode to run the code.

Maybe there are other ways I have not mentioned...hope these can help you

**Comment by Chesterfild** [comment]
> hi @Chesterfild
> We usually take the following methods:
> 
> 1. implement a method like `touch_if_exists`, like this:
> 
> ```
> def touch_if_exists(picture):
>     pos = exists(picture)
>     if pos:
>         touch(pos)
> ```
> 
> then use it in your code to replace `touch()`
> 
> 1. Divide the long test-cases into multiple sub-test-cases, we provide [using](https://airtest.readthedocs.io/en/latest/README_MORE.html#import-from-other-air) API to do this:
> 
> ```
> from airtest.core.api import using
> using("cases.air")
> from cases import case1, case2
> case1()
> case2()
> ```
> 
> 1. or use some unit test framework like [unittest](https://docs.python.org/3/library/unittest.html), but it's code can't run in AirtestIDE, you can use Pycharm/sublime/vscode to run the code.
> 
> Maybe there are other ways I have not mentioned...hope these can help you

Thank's this is lot a help!
