### ISSUE TITLE
AirtestIDE不能执行脚本

### ISSUE THREAD

**Issue by Luke838** [AirtestProject/AirtestIDE#444]
pycharm里面可以运行脚本，但今天打开IDE，居然不能运行run，点击不反应，也没有error
![QQ截图20190616085606](https://user-images.githubusercontent.com/51840604/59557770-13a7fc80-9015-11e9-8775-a335802d2a8e.png)
![2](https://user-images.githubusercontent.com/51840604/59557776-33d7bb80-9015-11e9-846c-4f2002ee8d93.png)

**Comment by yimelia** [comment]
如果重启IDE，还有没有出现这个问题？

**Comment by Luke838** [comment]
您好！这个问题已好！谢谢！
以前操作的时候在这个地方加了个路径，所以执行不了，非常感谢！
另外：
请跟您教下在pycharm中批量执行多个airtest脚本，实现脚本驱动，一个air脚本一个用例，能生成漂亮的log和report实现，做成jenkins集成。

怎么实现？
因为我在各类商城搜索有关airtest这类资料少之又少？
------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 上午9:34
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>;
抄送: "Luke-覃璐"<378446574@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AirtestProject/AirtestIDE] AirtestIDE不能执行脚本 (#444)




如果重启IDE，还有没有出现这个问题？

**Comment by yimelia** [comment]
这个需求可以自行实现。。。。
我们公司内部是做了一套系统来完成这个操作的
