### ISSUE TITLE
IDE里引用到自定义模块问题

### ISSUE THREAD

**Issue by Chersh-Pan** [AirtestProject/AirtestIDE#445]
AirtestIDE 中使用sys.path.append的方式引用了一个自定义的模块，但是这个模块里面又使用了pycharm IDE中常见的from dir_path import module 这种方式引用，结果在AirtestIDE 中运行出现：

ImportError: No module named 这种错误。

确定一下：如果一定要用airtestide 或者 command 方式运行脚本，所有涉及到相关的模块引用都必须用sys.path.append的方式么？

**Comment by Chersh-Pan** [comment]
模块里面定义了类，使用sys.path.append也无法使用？

**Comment by yimelia** [comment]
由于你的问题描述不是特别清楚，所以目前只能先这样回答：
1. 假如是在一个.air脚本中，想要import另外一个.air脚本里的内容，请参考[文档](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#air)
2. 假如是import别的模块，import方式与**在python脚本中的import没有什么不同**，如果想要引入一个模块，确实是要先告诉脚本它的位置，否则python找不到那个模块所在的路径。
在pycharm中，运行脚本时，它会自动帮你把项目路径加入到sys.path中，所以会减少很多问题。但是如果是单独在命令行中python xx.py来跑，就可能会让这些找不到路径的问题暴露出来了，在AirtestIDE中可能也是类似的问题。
总结原因就是，如果希望能够import一个模块，首先要确保它是一个可以被引用到的[模块](https://python3-cookbook.readthedocs.io/zh_CN/latest/c10/p01_make_hierarchical_package_of_modules.html)，其次要告诉脚本它所在的位置，否则脚本可能会找不到，最后需要检查下引用的层级与路径（比如尽量先用绝对路径、检查是否路径层级写多了或者写少了一层等等原因）。
这种import的问题需要本地调试，请将.air脚本视为一个普通的.py文件来做相关的操作。
