### ISSUE TITLE
Can i named log file myself?

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/AirtestIDE#446]
Right now, AirTest he names log file like this "ffb8e4d4bf3d72986680112abda2a48f" but for the others who work with auto-test name is especially important, i don't finde in option how to rename or name log file.

P.s I see this topic was create for the bug and i hope i don't bother in you.
Thanks!

**Comment by EraChen233** [comment]
Try to run airtest with command line:
http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#generating-a-test-report

![image](https://user-images.githubusercontent.com/5961185/59647496-f78b9300-91ad-11e9-8df7-6d7009d8a571.png)

**Comment by EraChen233** [comment]
What's the output of your command line? Can you take a screenshot?

For supplement, you can also set custom log name by building report with
``` python
# generate html report
from airtest.report.report import simple_report
simple_report(__file__, output='log.html')
```

**Comment by Chesterfild** [comment]
> What's the output of your command line? Can you take a screenshot?
> 
> For supplement, you can also set custom log name by building report with [simple_report](https://airtest.readthedocs.io/en/latest/all_module/airtest.report.report.html?highlight=simple_report):
> 
> ```python
> # generate html report
> from airtest.report.report import simple_report
> simple_report(__file__, output='log.html')
> ```

![2019-06-18_11-27-03](https://user-images.githubusercontent.com/46621847/59670346-155ff480-91bc-11e9-9c9e-52c2fe8e91cc.png)
![2019-06-18_11-28-30](https://user-images.githubusercontent.com/46621847/59670420-36c0e080-91bc-11e9-8c6a-09f436feae17.png)
![2019-06-18_11-28-18](https://user-images.githubusercontent.com/46621847/59670421-37597700-91bc-11e9-92b5-18a11467a072.png)
![2019-06-18_11-30-31](https://user-images.githubusercontent.com/46621847/59670611-7f789980-91bc-11e9-9c2d-ac5922f8269a.png)

I try to do this, but, it's doesn't work, or, you mean i need write this in the end of test?
And need to import airtest.report.report?

**Comment by EraChen233** [comment]
![image](https://user-images.githubusercontent.com/5961185/59671490-51ad4800-91f0-11e9-9285-954ac84117c0.png)

**Comment by Chesterfild** [comment]
![2019-06-18_11-44-09](https://user-images.githubusercontent.com/46621847/59671744-7be61200-91be-11e9-83e9-16e33d41d19b.png)

Yeah, I know, I changed a little bit, because my first option was at least showing signs of life.

**Comment by Chesterfild** [comment]
![2019-06-18_11-42-39](https://user-images.githubusercontent.com/46621847/59672018-fe6ed180-91be-11e9-9a89-53501ac5b8fd.png)

And, i get this...

![2019-06-18_11-49-21](https://user-images.githubusercontent.com/46621847/59672079-22321780-91bf-11e9-8e5d-b3b220b59d99.png)
![2019-06-18_11-48-52](https://user-images.githubusercontent.com/46621847/59672080-22caae00-91bf-11e9-884f-6bc76ab973c4.png)

**Comment by EraChen233** [comment]
1. For this question, you need install airtest in your local python env by `pip install airtest` and `pip install pocoui`. See this for more info http://airtest.netease.com/docs/en/1_online_help/running_scripts.html#deploying-your-python-environment
    > “airtest” is not internal or external command, operable program or batch file


2. And the second question, set custom log name by building report with simple_report:
You did right in this picture. But you need to run script to build a log.txt. After that run this report code.

``` python
# generate html report
from airtest.report.report import simple_report
simple_report(__file__, output='log.html')
```
![image](https://user-images.githubusercontent.com/5961185/59672697-86ba9a00-91f2-11e9-81b1-b6532c548315.png)
