### ISSUE TITLE
inspector里面双击插入的poco对象代码和录制工具里录出来的poco代码找控件都不够准确，建议换更准确的代码模板

### ISSUE THREAD

**Issue by kaluluosi** [AirtestProject/AirtestIDE#45]
![image](https://user-images.githubusercontent.com/1620585/37913651-fbd236ca-3147-11e8-9293-f85d8308864f.png)
![image](https://user-images.githubusercontent.com/1620585/37913660-0004b2fe-3148-11e8-829f-c5549b28d044.png)

inspector里面双击插入的poco对象代码和录制工具里录出来的poco代码都不够准确，建议换更准确的方式来生成代码。

poco对象的child链方式找控件相对更准确，一旦出现同一层级有n个同名对象的时候才考虑用差异属性做识别。

**Comment by adolli** [comment]
谢谢你的反馈。自动创建的语句时会自动判断当前场景节点是否有重复，单纯使用child链会导致语句过长，偶尔也会使用了一些不恰当用的属性名，如果编写脚本过程中发现选择不合适请手动维护你的测试脚本的健壮性，自动生成语句只是辅助。

**Comment by kaluluosi** [comment]
get
