### ISSUE TITLE
TypeError in AirtestIDE when try to generate simple_report in AirtestIDE file name "Report.py"

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/AirtestIDE#455]
When i try to start generate a simple report, i get a TypeError message in log Viewer in file "airtest\report\report.py" on the line 46

Code: https://codeshare.io/UbKVU
![2019-07-01_13-53-00](https://user-images.githubusercontent.com/46621847/60434570-b5c80700-9c07-11e9-8292-39a52fe1b93a.png)

**Comment by EraChen233** [comment]
What is your complete log.txt ?

**Comment by Chesterfild** [comment]
> What is your complete log.txt ?

Oh hi, good to see you!

log.txt is empty.
I do what you say last time.

**Comment by Chesterfild** [comment]
> What is your complete log.txt ?

I am a retard... I lock on the default log folder and i see what in ther... All work.
I sory!

**Comment by EraChen233** [comment]
You made a logical mistake. You have to run script first and generate a log.txt. After that, you can build the report.
