### ISSUE TITLE
Airtets running scripts using the command line

### ISSUE THREAD

**Issue by Wingoc** [AirtestProject/AirtestIDE#456]
在命令行执行脚本是，只能从Airtest中获取--device的参数吗？
例如，在Windows系统是执行时参数：“--device Windows:///134264 ”，
“134264”应该是随机生成的吧？还有没有其它方法或者途径获取到该编号，而不用每次都只能从Airetst中获取呢？
![image](https://user-images.githubusercontent.com/15171684/60478289-c2566900-9cb4-11e9-9225-410a54008850.png)

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id8

**Comment by Wingoc** [comment]
能否给个匹配Windows窗口的例子？直接用AirtestIDE中获得窗口句柄是ok的：device = ['windows:///68204']，但是我尝试用path和title_re去匹配酷狗音乐程序都报错？是我写得有问题麽？
![image](https://user-images.githubusercontent.com/15171684/60558901-5ee43e00-9d7d-11e9-9aa1-d4a5c3665ce1.png)

**Comment by yimelia** [comment]
title_re那里去掉空格看看

**Comment by Wingoc** [comment]
> title_re那里去掉空格看看

尝试了也是不通过，连接字符串不是都支持 pywinauto 的 connect 接口去连接窗口的麽?
![image](https://user-images.githubusercontent.com/15171684/60560985-960a1d80-9d84-11e9-86f4-7b50bbe67085.png)

**Comment by yimelia** [comment]
你少写了一个问号
这里是参数的意思，类似于URL里面带的参数?title_re，不写问号就会把整个字符串当做句柄传进去

**Comment by Wingoc** [comment]
> 你少写了一个问号
> 这里是参数的意思，类似于URL里面带的参数?title_re，不写问号就会把整个字符串当做句柄传进去

加上是问号，但是还是有点问题，这个是32/64为版本的问题麽？还是还有哪里设置得不对？
![image](https://user-images.githubusercontent.com/15171684/60569328-abda0b80-9da1-11e9-958e-1eeaebb20a83.png)

**Comment by yimelia** [comment]
文档里都写了例子了，对着例子抄就是了。。。。。。。。。不需要另外写引号
如果是32/64位版本问题，会有个warning，但是应该还是能用的：
![image](https://user-images.githubusercontent.com/6896468/60570618-88fd2680-9da4-11e9-9ac6-148124026939.png)

**Comment by Wingoc** [comment]
> 文档里都写了例子了，对着例子抄就是了。。。。。。。。。不需要另外写引号
> 如果是32/64位版本问题，会有个warning，但是应该还是能用的：
> ![image](https://user-images.githubusercontent.com/6896468/60570618-88fd2680-9da4-11e9-9ac6-148124026939.png)

好的，感谢分享！
