### ISSUE TITLE
Airtest IDEV1.2.1的AirTest辅助窗里部分功能变灰不可点.......

### ISSUE THREAD

**Issue by DSMjyp** [AirtestProject/AirtestIDE#457]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题

**描述问题bug**
Airtest IDEV1.2.1由于不知道删了C盘什么文件导致AirTest辅助窗里的大部分功能变灰不可用.......但是之前写好的脚本还是能继续运行，其他功能试了下都是正常的。

**截屏**
![20190702162242](https://user-images.githubusercontent.com/26500207/60497096-bc797b80-9ce6-11e9-8832-9ce788c92163.jpg)

**复现步骤**
1. 不知道怎么就删掉了C盘下temp临时文件.....

**python 版本:** `python3.6`

**操作系统:** `Windows7 64bit`

**Comment by yimelia** [comment]
请先连上一台设备/windows窗口

**Comment by DSMjyp** [comment]
> 请先连上一台设备/windows窗口

连着手机呢。后来我自己运行了即便脚本，这个地方又神奇的恢复了，然后我就自己关掉这个issue啦~
