### ISSUE TITLE
AirtestIDE连接OPPO A59st 横屏后界面显示不全

### ISSUE THREAD

**Issue by xiaozhu-hello** [AirtestProject/AirtestIDE#458]
AirtestIDE连接OPPO A59st 横屏后界面显示不全。第一次连接手机，竖屏正常显示，横屏出现显示不全的问题后。如截图。

windwos10企业版，
AirtestIDE：1.2.1
机型：OPPO A59st

备注：记得好像之前AirtestIED：1.2.0横竖屏一直都没有问题，升级1.2.1后就出现上述问题，但现在切换为1.2.0的IDE也存在这个问题。
![image](https://user-images.githubusercontent.com/52484491/60571623-91eef780-9da6-11e9-8d52-a2af0eacc885.png)

**Comment by yimelia** [comment]
我们这里没有A59st这个型号，我找了一台A59s试了一下，是可以正常旋转的，没有出现你说的问题。
或者试一下，在connect之前，下拉菜单里勾选`use adb orientation`那个选项看看会不会好？

**Comment by xiaozhu-hello** [comment]
在提示我安装了Yosemite。但是切换成use adb orientation，还是老样子。换成了 Use javacap进行连接，横竖屏，可以正常显示了。谢谢提供思路。

**Comment by xiaozhu-hello** [comment]
在提示下安装了Yosemite。但是切换成use adb orientation，还是老样子。换成了 Use javacap进行连接，横竖屏旋转，AirtestIDE中手机屏幕都可以正常显示了。谢谢提供思路。
