### ISSUE TITLE
OPPO A5使用poco库，报AdbShellError错误

### ISSUE THREAD

**Issue by Pyparson** [AirtestProject/AirtestIDE#460]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 这里

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。)
导入poco库时，运行脚本报如下错误：airtest.core.error.AdbShellError: stdout[b''] stderr[b'']

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/49591929/60647899-5c631080-9e71-11e9-991b-2de2f7fb5874.png)

**复现步骤**
导入poco库，运行脚本

**预期效果**
(预期想要得到什么、见到什么)
脚本可正常执行

**python 版本:** `python3.7`

**操作系统:** `macOS 10.13.6`

**设备:**
 - 型号: [OPPO A5]
 - 系统: [Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
参考文档：
http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#vivo

设置yosemite输入法为默认输入法即可

**Comment by Pyparson** [comment]
已解决，谢谢
