### ISSUE TITLE
修改默认log路径后下划线错了导致无法在IDE中生成报告文件

### ISSUE THREAD

**Issue by Milkwtea** [AirtestProject/AirtestIDE#461]
**(重要！问题分类)**
测试开发环境AirtestIDE使用问题

**描述问题bug**
修改默认log路径后下划线错了导致无法在IDE中生成报告文件

**截屏**
![image](https://user-images.githubusercontent.com/34088130/60706254-a31d3d00-9f3b-11e9-8eec-11ce7fc0b326.png)
![image](https://user-images.githubusercontent.com/34088130/60706399-f42d3100-9f3b-11e9-9762-b9b75ff2f806.png)
![image](https://user-images.githubusercontent.com/34088130/60706415-fd1e0280-9f3b-11e9-8682-9e941eea867f.png)

**复现步骤**
1. 设置中修改了路径，如图1，可以看到下划线是反了的。
2. 点击生成报告按钮，无法生成报告，如图2，可以看到命令行中下划线反了
3. 在命令行中通过正的下划线，可以正常生成报告，如图3

**预期效果**
修改log路径后的路径下划线是正确的

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**Comment by abcdd12** [comment]
试试把python路径还原下
