### ISSUE TITLE
通过linux后台进行远程真机调试脚本，同时用STF查看手机画面时报错

### ISSUE THREAD

**Issue by houraic** [AirtestProject/AirtestIDE#462]
测试开发环境AirtestIDE使用问题

**描述问题bug**
通过linux后台进行远程真机调试脚本，同时用STF查看手机画面时第一句poco.click()就报错

**截屏**
错误1：
![image](https://user-images.githubusercontent.com/48099950/60785622-2cc04b00-a186-11e9-86f1-22057533fd9a.png)
错误2：
![image](https://user-images.githubusercontent.com/48099950/60785626-32b62c00-a186-11e9-95d8-bd4d1a58c93b.png)

**复现步骤**
如描述

**预期效果**

**python 版本:**
3.6

**操作系统:** 
linux+stf

**设备:**
错误1：
 - 型号: 三星SMG9350
 - 系统: Android 7
错误2：
 - 型号: 华为KIWTL00
 - 系统: Android 5.1.1

**其他相关环境信息**
windows直接连手机可以运行

**Comment by yimelia** [comment]
IDE目前只支持windows、mac以及ubuntu的16.04版本。
如果是linux，单独运行脚本可能没问题，但是不能确保IDE是可用的
