### ISSUE TITLE
不能生成测试报告

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/AirtestIDE#465]
忘了搞的什么了突然就不成了，之前生成过

![QQ截图20190712195816](https://user-images.githubusercontent.com/52645118/61126691-c28a0c00-a4df-11e9-9994-108bd3712772.png)

![QQ截图20190712195903](https://user-images.githubusercontent.com/52645118/61126615-85be1500-a4df-11e9-804f-2c46accf1e37.png)
![QQ截图20190712200126](https://user-images.githubusercontent.com/52645118/61126730-dcc3ea00-a4df-11e9-90ea-2a47902d2ccd.png)

**Comment by yimelia** [comment]
重新运行一次脚本再生成就好了

**Comment by yimelia** [comment]
如果还是不行，可以从这里[下载](https://github.com/AirtestProject/AirtestIDE/issues/438#issuecomment-504846599)新版本的包再重新运行+生成报告

**Comment by abcdd12** [comment]
第二个方法解决了问题  谢了
