### ISSUE TITLE
不能运行脚本

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/AirtestIDE#466]
之前还是可以正常运行的，今天不知道怎么就不可以了
airtest 右边可以点击界面，可以正常录制脚本，就是回放脚本的时候出这个问题
![QQ截图20190713175442](https://user-images.githubusercontent.com/52645118/61170114-523ec180-a597-11e9-890d-aa9f745b5b2e.png)

**Comment by yimelia** [comment]
是否设置了自定义的python.exe路径
如果是的话，参考这个[文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#airtestadb)
