### ISSUE TITLE
脚本停止运行后，再次运行还是从上次运行的地方运行

### ISSUE THREAD

**Issue by panchsh5** [AirtestProject/AirtestIDE#467]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要)**
**描述问题bug**
脚本停止运行后，再次运行还是从上次运行的地方运行，重启软件还是如此

**截屏**
![image](https://user-images.githubusercontent.com/46131103/61170311-1ce7a300-a59a-11e9-9e16-5910279a79a7.png)

**复现步骤**

**预期效果**
重新运行，希望是从头开始运行

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [ Android 7.1.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
请注意看报错提示，不是从这里开始运行，而是这里有语法错误。
上一行少了半个括号。
