### ISSUE TITLE
三星设备无法连接Two SM device can't connect the AirtestIDE

### ISSUE THREAD

**Issue by shuolifunplus** [AirtestProject/AirtestIDE#47]
SM-9200和SM-9300设备无法连接成功。- 
![image](https://user-images.githubusercontent.com/37897017/38078782-f3b36598-336f-11e8-9eae-9db3333d2f9a.png)

**Comment by Meteorix** [comment]
@shuolifunplus 你好，你这是在测试Unity游戏吧？你的Unity游戏接入了Poco-SDK吗？
