### ISSUE TITLE
Airtest：Win7+Honor8无法全屏且操作页面有误

### ISSUE THREAD

**Issue by ALaDingC** [AirtestProject/AirtestIDE#470]
步骤：
1.Airtest正常连接后，手机页面无法全屏；
2.进入微信消息列表页面：点击手机屏幕中的第一条信息--->发现实际打开得是最上面【Windons 微信已登录，手机通知已关闭】页面；
  点击第四条信息--->实际打开得是第二条信息页面；

猜想：
2.虽然Airtest中未全屏，但对其进行操作时，仍默认该页面已全屏，实际点击的坐标为全屏后的坐标。

**Comment by yimelia** [comment]
无法全屏是否是[这样](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id9)的？
参考链接里的设置方法改一下手机设置看看

**Comment by ALaDingC** [comment]
> 无法全屏是否是[这样](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id9)的？
> 参考链接里的设置方法改一下手机设置看看

刚试了，确实是这个原因，谢谢你啦！！是我自己粗心啦
