### ISSUE TITLE
airtest连真机使用poco的时候pocoservice一直重装

### ISSUE THREAD

**Issue by 929304643** [AirtestProject/AirtestIDE#471]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)
![image](https://user-images.githubusercontent.com/52984538/61340994-4002a300-a877-11e9-9c77-e5eb0ee77af0.png)

**描述问题bug**
之前的时候airtest使用poco都是可以正常使用换了python3.7之后一连真机poco service一直重装

**截屏**
![image](https://user-images.githubusercontent.com/52984538/61341030-5b6dae00-a877-11e9-94f8-6c9c7309b92e.png)

**复现步骤**
1.打开airtest
2.airtest连接华为RNE-AL00
3.在真机打开源生APP
4.airtest使用poco辅助窗口的android
5.发现poco services一直重装

**预期效果**
(预期想要得到什么、见到什么)
见到UI渲染树的元素`

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
windows

**Comment by 929304643** [comment]
解决了

**Comment by Aimee-zhao** [comment]
我也是一直有这个问题，自动化执行脚本的时候，一直重装PocoService,现在都还没好。怎么办呢

**Comment by wu997134245** [comment]
> 解决了

怎么解决的

**Comment by cnscorpions** [comment]
@929304643 老哥说下是啥原因嘛
