### ISSUE TITLE
keyevent windows下 删除键不生效

### ISSUE THREAD

**Issue by QuiQiJingFeng** [AirtestProject/AirtestIDE#472]
keyevent("delete")
keyevent("-delete")
keyevent("BackSpace")
都试过了,没有用

**Comment by yimelia** [comment]
文档里写了示例了：http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#keyevent

`keyevent("{BACKSPACE}")`

请自行翻阅pywinauto的文档https://pywinauto.readthedocs.io/en/latest/code/pywinauto.keyboard.html
