### ISSUE TITLE
win10环境下 命令行模式运行不起来

### ISSUE THREAD

**Issue by Jatom-c** [AirtestProject/AirtestIDE#474]
win10+mumu模拟器+python3.7
在IDE里面运行正常，用命令行模式运行就报错
执行命令：airtest run cwz.air --device Android://127.0.0.1:5037/127.0.0.1:7555
![image](https://user-images.githubusercontent.com/22453572/61432014-ab28a400-a961-11e9-8558-2e4660eccfc9.png)

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id10

**Comment by Jatom-c** [comment]
我本机win10 powershell下提示使用""包含&字符  用^&会报错

**Comment by yimelia** [comment]
命令行已经提示告诉了你要用""包含它们，请认真阅读命令行的报错信息

**Comment by Jatom-c** [comment]
嗯 我改回来可以运行 我只是看到文档上写着windows下使用^&  这里做个提醒而已

**Comment by yimelia** [comment]
好的，感谢反馈
