### ISSUE TITLE
AirtestIDE V1.2.1 日志等级设置无效

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/AirtestIDE#478]
**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） 

**详细描述问题bug：**
使用AirtestIDE V1.2.0时，报告形式非常详细，具体到某一行某个代码，但是用了V1.2.1之后，五个报告等级无论怎么设置，都只会提示到方法级别，没有具体到代码。

这是一个bug还是说需要我设置日志等级之后重启才能生效呢？

**操作系统:** `Windows7 64bit`
- AirtestIDE版本号：V1.2.1

**截屏**

![报错信息太简单](https://user-images.githubusercontent.com/42226268/61528475-76941580-aa51-11e9-845e-984d53fc5a3d.png)

**Comment by yimelia** [comment]
不一定是BUG，可能只是这一个报错没有显示到具体代码而已。

可以附上更多信息：你的完整代码、执行过程、命令行终端是否有其他报错

**Comment by niuniuprice** [comment]
> 不一定是BUG，可能只是这一个报错没有显示到具体代码而已。
> 
> 可以附上更多信息：你的完整代码、执行过程、命令行终端是否有其他报错

全部报错都在问题上面这张图上了。


执行代码非常简单（为了快速测试）：
只有keyevent("%{SPACE}n")这一行（最小化窗口）

执行过程：
airtest.cli.runner.run_script运行脚本
airtest.report.report.LogToHtml.report()生成报告
[（与#461中提到的运行过程相同）](https://github.com/AirtestProject/Airtest/issues/461)


目前已经尝试修改不同的log提示等级，然后重启，再运行，但是最终显示的log详细程度都是和问题上图是一样的

**Comment by yimelia** [comment]
贴一下执行过程的命令行内容看看

**Comment by niuniuprice** [comment]
> 贴一下执行过程的命令行内容看看

![image](https://user-images.githubusercontent.com/42226268/61602900-07dfd380-ac6e-11e9-9988-950b19acd471.png)

**Comment by yimelia** [comment]
暂时看不出是什么问题，可以直接在本地安装Python环境+airtest，然后用本地python环境来跑看看。
AirtestIDE在运行的时候外面额外封装了一层内容，可能有什么问题没能完全显示出来。
目前看来报错内容很像前几天你报的那个issue

**Comment by niuniuprice** [comment]
> 暂时看不出是什么问题，可以直接在本地安装Python环境+airtest，然后用本地python环境来跑看看。
> AirtestIDE在运行的时候外面额外封装了一层内容，可能有什么问题没能完全显示出来。
> 目前看来报错内容很像前几天你报的那个issue

本地环境跑是没有问题的，一旦出错会是显示得更仔细的形式：
![image](https://user-images.githubusercontent.com/42226268/61603616-d9172c80-ac70-11e9-956e-b0f9a14bc801.png)

报错内容是#461的内容，因为我也是在报那个issue的时候发现的IDE和本地环境显示报告的不同。。。
麻烦告知一下是否一直以来都是IDE显示的信息不如本地python环境下的详细？

**Comment by yimelia** [comment]
具体原因暂时无法确定。
IDE里的运行机制原本就与直接运行python命令行是不同的，相当于是额外封装了一层内容，先运行IDE的启动脚本，再运行到具体的脚本内容。我们是尽可能将所有log都打印出来的，但是可能由于运行机制的问题导致在特殊情况下少了最后那层log，限于水平问题，我暂时不清楚如何解决。
