### ISSUE TITLE
使用wait_for_any例子中，性能较好的手机，点击到移动状态的鱼，总是滞后，不能点击到

### ISSUE THREAD

**Issue by Leonylzhao** [AirtestProject/AirtestIDE#48]

**Comment by adolli** [comment]
移动的物体不容易点中，[demo game](http://poco.readthedocs.io/en/latest/source/doc/poco-example/waiting_events.htmll)中的物体移动较快，从识别到点击对不同手机有不同的滞后，这种情况请尽量等待物体位置稳定后再进行操作，或者预估一个适当的延迟或点击位置，例如向物体运动方向预先点击。可参考 [.focus](http://poco.readthedocs.io/en/latest/source/poco.proxy.html?highlight=focus#poco.proxy.UIObjectProxy.focus) 方法.

**Comment by Leonylzhao** [comment]
好的，谢谢您的解答！

**Comment by adolli** [comment]
后续遇到库使用相关问题可提到对应仓库中。[poco]()

**Comment by adolli** [comment]
后续遇到**库使用**相关问题可直接提到对应仓库中。
* [poco](https://github.com/AirtestProject/Poco/issues)
* [airtest](https://github.com/AirtestProject/Airtest/issues)
