### ISSUE TITLE
代码中包含poco自动录制生成的代码时，无法正常缩进，运行脚本抛出IndentationError

### ISSUE THREAD

**Issue by shijianzhihu** [AirtestProject/AirtestIDE#484]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
I am new.
我的代码中包含poco自动录制生成的代码，它无法正常缩进，运行脚本抛出IndentationError，请看截图，why？
**复现步骤：**
![image](https://user-images.githubusercontent.com/26112446/62003729-ea1edc80-b14d-11e9-90c9-ff01ad83df1e.png)

**python 版本:** `AirtestIDE自带`

**操作系统:** MacOS 10.13.6`

**手机设备信息:**
 - 手机型号: 华为荣耀10
 - Android系统版本号:  Android 9
 - (别的信息)

**其他相关信息补充**
- AirtestIDE版本号：1.2.1
我在sublime中对python代码进行了格式化，但是AirtestIDE中仍然会出现此错误，why?

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
在文本过长的情况下，有时候IDE的编辑框里缩进可能会显示成两个空格宽度，但是从你的截图看不出是这个问题。
请贴出代码文本原文内容

**Comment by shijianzhihu** [comment]
> 在文本过长的情况下，有时候IDE的编辑框里缩进可能会显示成两个空格宽度，但是从你的截图看不出是这个问题。
> 请贴出代码文本原文内容

`# -*- encoding=utf8 -*-
__author__ = "rethink"

import time

from airtest.core.api import *
auto_setup(__file__)


using('common.air')
from common import poco,TIMEOUT,SLEEPTIME,openLiteApp,enterMoudlePage

start_time = time.time()

openLiteApp('mxyc')   # 打开微信小程序，进入首页

enterMoudlePage('停车场')  # 从小程序进入进入车场首页

try:
    poco(text="查缴停车费").click()
    paybtn = poco(text="立即付款")
    time.sleep(TIMEOUT)
    if not paybtn:
poco("android.widget.LinearLayout").offspring("com.tencent.mm:id/dbq").child("android.widget.FrameLayout").child("android.widget.FrameLayout").child("android.widget.FrameLayout")[1].child("android.widget.RelativeLayout").child("android.widget.FrameLayout").child("android.widget.FrameLayout").child("android.widget.FrameLayout")[0].offspring("android.view.ViewGroup").child("android.widget.FrameLayout").offspring("android.webkit.WebView")[0].child("android.view.View")[1].child("android.view.View")[3].child("android.view.View")[0].click()
        touch(tpl1564137020517.png)
        for i in range(7):
            touch(tpl1564137037787.png)
        sleep(SLEEPTIME)

        poco(text="查缴停车费").click()
        wait_for_any(paybtn,timeout=TIMEOUT)
        assert(paybtn.exists())

    paybtn.click()
    sleep(SLEEPTIME)
    assert(poco(text="微信支付").exists())
    touch(Template(r"tpl1564313042054.png", record_pos=(0.006, 0.938), resolution=(1080, 2280)))
    sleep(SLEEPTIME)

    assert(poco("com.tencent.mm:id/fow").exists())

    poco("com.tencent.mm:id/lb").click()
    touch(Template(r"tpl1564313782547.png", record_pos=(-0.285, -0.914), resolution=(1080.0, 2280.0)))

finally:
    # 关闭小程序
    poco('关闭').click()

    # 返回到“发现”页
    poco("com.tencent.mm:id/lb").click()

    # 返回到“微信”页
    poco(text="微信").click()
    home()
    stop_app('com.tencent.mm') 

end_time = time.time()
elapsed_time = int(end_time-start_time)
print('运行耗时：>>>>>>>>>>>',elapsed_time)








`

**Comment by shijianzhihu** [comment]
> 在文本过长的情况下，有时候IDE的编辑框里缩进可能会显示成两个空格宽度，但是从你的截图看不出是这个问题。
> 请贴出代码文本原文内容

Hello，代码我已经贴出来了，不知道是否可以满足要求，这是我在学习过程中写的一个Demo，common.py中的代码并没有给出。
正如上面说的，IDE的编辑框里缩进可能会显示成两个空格宽度，这不就会因为缩进问题导致到吗运行失败吗？ 
以下是用pycharm格式化后的结果，AirtestIDE运行仍然会报错；
![image](https://user-images.githubusercontent.com/26112446/62016906-31a57700-b1e7-11e9-9d41-15bae4cf9578.png)

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/62017275-9e6d4100-b1e8-11e9-991f-1c6fcf3f5e1e.png)

**Comment by yimelia** [comment]
>正如上面说的，IDE的编辑框里缩进可能会显示成两个空格宽度，这不就会因为缩进问题导致到吗运行失败吗？

不会，只是显示看起来不像是缩进成4个空格而已，况且在你的截图里也并没有这个问题。
请仔细看我截图框选的部分，pycharm已经把错误的部分给你标红了，请自行认真检查代码。
