### ISSUE TITLE
连接真机和模拟器后刷新ADB均无法显示设备

### ISSUE THREAD

**Issue by FionaFang001** [AirtestProject/AirtestIDE#485]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)
**复现步骤：**
1.连接真机和夜神模拟器
![image](https://user-images.githubusercontent.com/53285436/62105883-3dbc3200-b2d6-11e9-80b7-57bd23219528.png)
2.连接远程设备，重启、刷新ADB，均无法显示移动设备
![image](https://user-images.githubusercontent.com/53285436/62105968-8542be00-b2d6-11e9-8e9a-bb8de4a306c7.png)
**ADB 版本:** `1.0.40`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:vivo X9S
 - Android系统版本号:  Android 7.1.2

- AirtestIDE版本号：v1.2.1

**Comment by yimelia** [comment]
1. 真机连接问题请查看文档：http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#adb
>手机上需要将 开发者选项 开启，并开启 USB调试 选项，并且在接入电脑时，选择 允许该PC对设备进行调试，否则手机状态为unauthorized是无法连接的

2. 模拟器连接请查看文档 http://airtest.netease.com/docs/cn/2_device_connection/3_emulator_connection.html
