### ISSUE TITLE
Linux版本后期是否提供窗口程序自动化测试功能?

### ISSUE THREAD

**Issue by oahzuw** [AirtestProject/AirtestIDE#486]
Current OS is not 'Windows'! You may try to connect a android device. 如下图: 

![图片1](https://user-images.githubusercontent.com/1906531/62193377-36665880-b3aa-11e9-9ff2-59f9cf50e67e.png)

**Comment by yimelia** [comment]
很抱歉，暂时只支持Ubuntu16.04版本，其他的系统版本由于用户数量较少，我们的人力有限，暂时没有办法腾出人手做兼容
