### ISSUE TITLE
mac上的IDE打开之后出两个图标，其中一个一直在跳

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/AirtestIDE#488]
**描述问题bug**
mac上的IDE打开之后出两个图标，其中一个一直在跳

![image](https://user-images.githubusercontent.com/11660641/62339900-37b19580-b510-11e9-8cd1-0c69e656d8b1.png)

**python 版本:** `python3.6.5`

**airtest 版本:** `1.2.1`

**其他相关环境信息**
macbook pro 2017款 mojave 10.14.6

> 但是在2015款的 macbook pro mojave 10.14.6上就没事，只有一个图标，也不会有跳动情况

**Comment by yimelia** [comment]
是的，后台额外多开了一个进程。

**Comment by xin7c** [comment]
> 是的，后台额外多开了一个进程。

所以是已知的bug嘛··？

**Comment by yimelia** [comment]
是的，如果可以的话将在下个版本修复

**Comment by qaperf** [comment]
这bug也太明显了吧...我也遇到了

**Comment by qaperf** [comment]
![image](https://user-images.githubusercontent.com/20239146/67557243-4abab700-f747-11e9-8615-c9648f483ff6.png)
网易出品的不都是精品嘛...

**Comment by qaperf** [comment]
![image](https://user-images.githubusercontent.com/20239146/67557297-6920b280-f747-11e9-925d-1a0d0e6a9b9a.png)

**Comment by yimelia** [comment]
@qaperf 
你好，之前我们对这个问题的定性有误，并不是BUG。
macos在后台开启了进程的时候，会多一个图标，闪动表示在运行中。这个进程是IDE启动时运行的后台进程，不是BUG，也无法消除掉图标。
对此带来的不便，深感抱歉。
