### ISSUE TITLE
更改project文件夹名称后，IDE里就不能打开这个project了

### ISSUE THREAD

**Issue by APKFans** [AirtestProject/AirtestIDE#49]
提示No *.py file,choose another project
![image](https://user-images.githubusercontent.com/7353139/38128957-7441c0d2-342f-11e8-8e16-0d989b6d71cf.png)

**Comment by Meteorix** [comment]
@APKFans 文件夹里面有个py文件，改成同名的

**Comment by rockywhisper** [comment]
@APKFans  建议不要手动修改，可使用AirtestIDE里面的 **“另存为”功能** 。
这条issue先关闭了哈。
