### ISSUE TITLE
airtest装完pocoservice后，pocoservice在手机上不停重复启动崩溃

### ISSUE THREAD

**Issue by xiaojunliu19** [AirtestProject/AirtestIDE#491]
![QQ截图20190802150920](https://user-images.githubusercontent.com/30660949/62351497-43b14d80-b538-11e9-9feb-6efb88298a97.png)

![QQ截图20190802151518](https://user-images.githubusercontent.com/30660949/62351536-5cb9fe80-b538-11e9-9de1-1488e0193152.png)
实测在本人所有手机上都出现了这个问题，华为mate10,mate20,oppo findx , vivo x27, 小米9,三星所有手机均有此问题

**Comment by yimelia** [comment]
可能是网络问题，电脑或者手机是否开启了网络代理？

**Comment by xiaojunliu19** [comment]
电脑应该是有公司的代理，但是只在我的电脑上这样，在其他同事的电脑上都ok，手机没有设置代理


------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午3:25
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>;
抄送: "刘晓军"<793504743@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AirtestProject/AirtestIDE] airtest装完pocoservice后，pocoservice在手机上不停重复启动崩溃 (#491)




可能是网络问题，电脑或者手机是否开启了网络代理？

**Comment by yimelia** [comment]
如果每台手机都不行的话，一般情况下是本地电脑的问题，需要排查一下具体环境是否有冲突，例如：本地不要开启任何手机助手类软件（并且确保系统进程里也没有残留），本地没有开启网络代理等。
这个需要你自己来排查你和同事的电脑之间有什么不同了。。

**Comment by xiaojunliu19** [comment]
自查未开启任何手机助手类软件，也没有开启网络代理，需要airtest的开发同学提供一下具体的crash原因来解决问题

**Comment by yimelia** [comment]
具体crash原因我也不清楚，log中没有体现。一般情况下都是因为电脑开了网络代理导致的，如果不是的话，我也不清楚还有什么其他原因，很抱歉帮不上忙

**Comment by xiaojunliu19** [comment]
![image](https://user-images.githubusercontent.com/30660949/62355447-a0653600-b541-11e9-8cde-b36e9899f982.png)
为什么开了pocoservice后会占用这么多的5037端口
