### ISSUE TITLE
使用本地python（Python 2.7.14），命令行窗口运行报错

### ISSUE THREAD

**Issue by banlu9999** [AirtestProject/AirtestIDE#493]
**详细描述问题bug：**
使用本地python（Python 2.7.14），命令行窗口运行报错

**复现步骤：**
1、IDE-选项-设置-Custom python path，设置本地python路径为：C:\python2.7\python.exe
2、未修改Custom Launcher Path

**python 版本:** `Python 2.7.14`

**操作系统:** `Windows10 家庭中文版 64bit`

**手机设备信息:**
 - Android系统版本号: [Android 7.1.2]

**其他相关信息补充**
- AirtestIDE版本号：AirtestIDE_2019-05-09_py3_win64
相同的代码，未设置python本地路径的时候，运行正常；
主要部分的代码，单独在本地pycharm中运行也正常；

**截屏**

![image](https://user-images.githubusercontent.com/20240928/62362522-b974e380-b54f-11e9-89e9-cf179b66aa8a.png)

**Comment by liaolu9999** [comment]
辛苦相关开发看一下，是否是配置的问题？

**Comment by yimelia** [comment]
检查系统python中的pip list内容，可能是装错库了，看下是装了`pocoui`还是装了`poco`。

`pocoui`才是正确的库，如果装错了，可以卸载掉重新装一下：

```
pip uninstall poco
pip install pocoui
```

**Comment by banlu9999** [comment]
卸载重装后，还是有报错？@yimelia
![image](https://user-images.githubusercontent.com/20240928/62363257-8895ae00-b551-11e9-95c0-598aaa34e6e8.png)

**Comment by yimelia** [comment]
请贴出pip list的运行结果

**Comment by banlu9999** [comment]
麻烦再看一下
![image](https://user-images.githubusercontent.com/20240928/62364325-bbd93c80-b553-11e9-802b-3f2bbb4c2037.png)

![image](https://user-images.githubusercontent.com/20240928/62364295-aa903000-b553-11e9-8046-92339d0257b3.png)

**Comment by yimelia** [comment]
环境中是否只有一个python，就是C盘里那个py2.7的python
以及你的air目录里检查下有没有叫poco的目录，如果有的话也会有影响，导致它找错poco的位置

**Comment by banlu9999** [comment]
环境中是只安装了一个python
![image](https://user-images.githubusercontent.com/20240928/62364795-09a27480-b555-11e9-987d-289a520e70ff.png)

air目录下的poco需要整个删掉么？
![image](https://user-images.githubusercontent.com/20240928/62364759-ed063c80-b554-11e9-9de6-e9c59c1e0973.png)

**Comment by banlu9999** [comment]
删掉air目录下的poco文件夹后，重启IDE，还是报错
![image](https://user-images.githubusercontent.com/20240928/62364910-571ee180-b555-11e9-8f39-b14a202f24aa.png)

**Comment by yimelia** [comment]
。。。
不是的
我的意思是，有很多人会无意中将自己的测试脚本所在的文件夹命名为airtest或者是poco，可能会导致在import上面有问题，所以才让你检查一下。
你可以试一下在本地的python终端里运行一下那行import看看结果

**Comment by banlu9999** [comment]
本地运行也有问题是什么原因咧？
![image](https://user-images.githubusercontent.com/20240928/62365630-250e7f00-b557-11e9-9e19-9ac8866f9cc8.png)
