### ISSUE TITLE
IDE 中的log窗口可以查看某个控件的payload信息, 这个在python的程序中怎么做到? 

### ISSUE THREAD

**Issue by OriLiMu** [AirtestProject/AirtestIDE#494]
如图, 我用的是安卓的原生界面, 我查看了poco的代码似乎没有获取这个某个控件的payload的接口, 

请问我自己该怎么快速的实现这个功能, 

![image](https://user-images.githubusercontent.com/11295355/62417392-74040380-b680-11e9-803e-41cac3eacff9.png)

1. 我看了一个获取文本的命令是这样的: 
命令格式: 
<class 'dict'>: {'id': 'f375cd3b-2c82-40f5-9247-552329463793', 'uri': 'poco-uiautomation-framework', 'method': (('getattr', 'attributor'), ('getattr', 'getAttr'), ('call', (('uri', '[Lcom.netease.open.libpoco.sdk.AbstractNode;@87fac10(414ec759-58f7-478a-b1ab-a1b9e9037095)'), ('', 'text'))))}

2. 
有没有类似获取payload的命令? 

我看了有一个dump 可以获取到所有的控件payload, poco.agent.hirexxx.dump
用这个也可以自己实现一个类似的方法。

想知道你们有没有现成的接口可以做这个功能? 谢谢。

**Comment by OriLiMu** [comment]
proxy.py 的这个函数可以一个一个的获取属性, 能不能一次性的获取所有属性?

    def attr(self, name):

**Comment by yimelia** [comment]
我看了下，IDE这边也是通过dump接口来获取全部控件信息的，然后再根据实际点击哪个控件，从完整的信息里筛选找出具体的控件内容，所以也没有具体的接口
