### ISSUE TITLE
Airtest IDE在官网上MAC版本下载不了

### ISSUE THREAD

**Issue by Miracle521** [AirtestProject/AirtestIDE#496]
官网上下载MAC版本的Airtest IDE，点击同意并下载按钮后，一直在等待相应状态，无法下载

![image](https://user-images.githubusercontent.com/37792300/62766431-09f6be80-bac5-11e9-8c61-6f5c46998b52.png)

**Comment by yimelia** [comment]
点击那个“如果下载失败，请点这里”的链接试试
