### ISSUE TITLE
Mac AirtestIDE，连接上网易MUMU模拟器，无法出现UI树

### ISSUE THREAD

**Issue by jb522185660** [AirtestProject/AirtestIDE#497]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
Mac AirtestIDE，连接上网易MUMU模拟器，无法出现UI树，已打开某个安卓原生APP

**复现步骤：**
连接上网易MUMU模拟器，无法出现UI树，已打开某个安卓原生APP

**python 版本:** `python3.x`
python3.6
**操作系统:** `Windows7 64bit`
Mac os 10.14.4
**手机设备信息:**
 - 手机型号:网易MUMU模拟器1.7.5
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：最新版本

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![DEA733CD-B383-4F21-8144-93A4A23FF8E1](https://user-images.githubusercontent.com/3723116/62829444-1e0aff00-bc30-11e9-8f52-d088c8d46d39.png)

**Comment by yimelia** [comment]
mumu的兼容性有点问题，之前很长时间里的版本都没法连上IDE，建议换一个模拟器

**Comment by jb522185660** [comment]
可以了，给模拟器安装上Pocoservice.apk就可以
