### ISSUE TITLE
aritest的屏录功能在实例化了Poco对象后stop-recording有重复调用问题

### ISSUE THREAD

**Issue by kaluluosi** [AirtestProject/AirtestIDE#50]
这是没有实例化Poco对象的脚本的运行结果
![image](https://user-images.githubusercontent.com/1620585/38129394-7797ea02-3431-11e8-98b9-fdaee0e53b4b.png)
![image](https://user-images.githubusercontent.com/1620585/38129417-8eaf941a-3431-11e8-817d-85d39190a0f6.png)

这是实例化了Poco对象的脚本的运行结果
![image](https://user-images.githubusercontent.com/1620585/38129424-98a3f18c-3431-11e8-8008-2716b486b245.png)

![image](https://user-images.githubusercontent.com/1620585/38129474-c2e51f48-3431-11e8-863b-c07f1b8d7368.png)

可以看到只要实例化了Poco，那么stop-record就会被调用两次。

**Comment by adolli** [comment]
请麻烦再贴一下你的settings面板的配置或者launcher文件

**Comment by kaluluosi** [comment]
没有用自定义launcher。
而我也查到了点头绪，teardown的时候虽然只连了一个设备但是不知道为何循环了2次。这个报错没啥影响就是了。
![image](https://user-images.githubusercontent.com/1620585/38597185-a65c61be-3d88-11e8-878b-b29ef70b01d2.png)

**Comment by Meteorix** [comment]
@kaluluosi 你是自己用命令行运行的.air脚本吗？目前我们在AirtestIDE中没有指定recording参数，试试更新到最新版的IDE？

**Comment by kaluluosi** [comment]
@Meteorix  是我用命令行调用的。

**Comment by rockywhisper** [comment]
@kaluluosi  Hi，本issue暂时关闭了哈，后续仍有问题可以新建issues。

**Comment by yuanze12345678** [comment]
AirtestIDE怎么把脚本for的

**Comment by adolli** [comment]
@yuanze12345678 for什么？

**Comment by yuanze12345678** [comment]
# -*- encoding=utf8 -*-
from airtest.core.api import *
auto_setup(__file__)
touch(Template(r"tpl1541933106166.png", record_pos=(-0.372, 0.832), resolution=(1080.0, 1920.0)))
touch(Template(r"tpl1541933110940.png", record_pos=(-0.125, 0.811), resolution=(1080.0, 1920.0)))
循环怎么编写，怎么设置循环次数

**Comment by yuanze12345678** [comment]
@adolli 循环怎么编写，怎么设置循环次数
# -*- encoding=utf8 -*-
from airtest.core.api import *
auto_setup(__file__)
touch(Template(r"tpl1541933106166.png", record_pos=(-0.372, 0.832), resolution=(1080.0, 1920.0)))
touch(Template(r"tpl1541933110940.png", record_pos=(-0.125, 0.811), resolution=(1080.0, 1920.0)))
