### ISSUE TITLE
无法输入中文，

### ISSUE THREAD

**Issue by zhuyujie000** [AirtestProject/AirtestIDE#500]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/48507102/63082506-f9d55800-bf78-11e9-9def-d8bdf14f1941.png)

**Comment by yimelia** [comment]
抱歉，这个是之前外放的IDE里面带的一个BUG，重新下载一次IDE可能可以解决。
或者是直接创建.air后缀的脚本也可以。

**Comment by yimelia** [comment]
（顺带一说，感觉用图像识别来做打城考勤可能有点难啊）

**Comment by zhuyujie000** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    别提了、乱世，我要滚服了。本来稳征服，非要一打四。有没有抽卡玄学，给三石说来队满配三皇，不然不充钱                                                                                                                                      





        
    
     
    

    在2019年08月16日 10:23，yimelia<notifications@github.com> 写道： 


（顺带一说，感觉用图像识别来做打城考勤可能有点难啊）



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
