### ISSUE TITLE
建议：增加脚本调试功能

### ISSUE THREAD

**Issue by qingshiyue** [AirtestProject/AirtestIDE#501]
当执行脚本比较长时，脚本调试很费时；
建议：
       增加debug功能，能够只运行脚本指定片段，方便调试出错脚本

**Comment by yimelia** [comment]
暂时只能使用这个：http://airtest.netease.com/docs/cn/3_record_script/0_script_faq.html#id27
对于poco代码可能不够实用，但是对于airtest截图代码的调试是足够用了
