### ISSUE TITLE
我的mac电脑下载了，打开不了来安装

### ISSUE THREAD

**Issue by goddess520** [AirtestProject/AirtestIDE#51]

**Comment by rockywhisper** [comment]
你好，这个问题同 #28 ，AirtestIDE目前对一部分Mac（比如AMD显卡类型）不支持，我们目前正在解决这个问题，解决后会在QQ群里发送通知哈~

**Comment by rockywhisper** [comment]
@goddess520   Hi，我们今天发布了新版本，这个问题已经解决啦。

下载链接： http://airtest.netease.com/changelog.html
欢迎使用，如有任何问题随时反馈哈，感谢  : )
