### ISSUE TITLE
脚本编辑框无内容显示

### ISSUE THREAD

**Issue by 948462448** [AirtestProject/AirtestIDE#510]
**详细描述问题bug：**
打开ide后创建新的项目，脚本编辑框内无内容显示

**复现步骤：**

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`
**截屏**
![image](https://user-images.githubusercontent.com/26214482/63412103-93917f00-c429-11e9-84b2-5de5a7c6bbbb.png)

![image](https://user-images.githubusercontent.com/26214482/63412599-a22c6600-c42a-11e9-9f3e-cf7d97ccb19f.png)

**Comment by yimelia** [comment]
参考这个 https://github.com/AirtestProject/AirtestIDE/issues/438#issuecomment-504846599
