### ISSUE TITLE
无法使用adb接口命令

### ISSUE THREAD

**Issue by rgxiwei** [AirtestProject/AirtestIDE#511]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
无法使用帮助文档里面提供的adb接口，提示无法识别命令。
**复现步骤：**

**python 版本:** `python3.7.3

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![捕获1](https://user-images.githubusercontent.com/23026308/63420555-795f9d00-c439-11e9-8a9d-d503d7084605.PNG)

![捕获2](https://user-images.githubusercontent.com/23026308/63420604-9d22e300-c439-11e9-9850-f0ba97d6af2e.PNG)

**Comment by EraChen233** [comment]
代码编写错误，逻辑有误.
``` python
from airtest.core.android.adb import ADB
ADB().version()
```
