### ISSUE TITLE
airtest

### ISSUE THREAD

**Issue by MUYIJIAN** [AirtestProject/AirtestIDE#515]

**Comment by MUYIJIAN** [comment]
airtest的教学视频看不了

**Comment by yimelia** [comment]
请问是哪个教学视频？

**Comment by MUYIJIAN** [comment]
就是官网首页的




yangjian1@globalegrow.com
 
From: yimelia
Date: 2019-08-26 11:19
To: AirtestProject/AirtestIDE
CC: MUYIJIAN; Author
Subject: Re: [AirtestProject/AirtestIDE] airtest (#515)
请问是哪个教学视频？

**Comment by yimelia** [comment]
那几个都只是几分钟的演示小视频，看不了可能是因为你们那边的网络访问163这边服务器有点问题，但是看不了影响不大，主要看文档比较有用。

**Comment by MUYIJIAN** [comment]
好的




yangjian1@globalegrow.com
 
From: yimelia
Date: 2019-08-29 09:25
To: AirtestProject/AirtestIDE
CC: MUYIJIAN; Author
Subject: Re: [AirtestProject/AirtestIDE] airtest (#515)
那几个都只是几分钟的演示小视频，看不了可能是因为你们那边的网络访问163这边服务器有点问题，但是看不了影响不大，主要看文档比较有用。
