### ISSUE TITLE
填写数据信息 点击获取验证码

### ISSUE THREAD

**Issue by changjiang2** [AirtestProject/AirtestIDE#516]
应用场景 是 我正在填写 一组表单数据 其中填到 点击获取验证码    我想问下 这个验证码因为是动态获取的每次拿到的码都是不一样的  我该让AirTest 每次怎么输入正确的验证码  求大神告知 谢谢!

**Comment by yimelia** [comment]
需要自行实现获取验证码的逻辑，比如自己点击短信界面、点击最新短信、拿到短信内容、解析出验证码。
如果是网页图片验证码，需要自行实现识别逻辑。
验证码存在的意义是验证当前是否人类在进行操作，用自动化脚本来做，确实不容易完成。
建议直接让你们的程序提供跳过验证码的方式来实现测试流程。

**Comment by changjiang2** [comment]
好的谢谢 




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>; 
发送时间: 2019年8月26日(星期一) 下午2:48
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>; 
抄送: "→_→"<863121318@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirtestProject/AirtestIDE] 填写数据信息 点击获取验证码 (#516)




需要自行实现获取验证码的逻辑，比如自己点击短信界面、点击最新短信、拿到短信内容、解析出验证码。
 如果是网页图片验证码，需要自行实现识别逻辑。
 验证码存在的意义是验证当前是否人类在进行操作，用自动化脚本来做，确实不容易完成。
 建议直接让你们的程序提供跳过验证码的方式来实现测试流程。
