### ISSUE TITLE
unity 接了sdk后 发现同层级同名称的ui 运行脚本的时候会找不到

### ISSUE THREAD

**Issue by wangwencheng888** [AirtestProject/AirtestIDE#52]
1.同层级UI通命名UI无法识别
2.能不能增加一个关闭游戏重启游戏的接口。 测试中重新连接游戏是一个比较常规但是特别繁琐的测试点

**Comment by adolli** [comment]
同层级同名UI可以用下标索引访问  `poco(...)[0]`. 但是注意下标的序号是按照空间顺序从左到右从上到下的，具体可细节请参考API文档。

重启游戏可以通过两个函数实现。 `stop_app`和`start_app`. 等周一我再编辑一下这个回复
