### ISSUE TITLE
POCO文件放入项目时报错 The type or namespace name `XR' does not exist in the namespace `UnityEngine

### ISSUE THREAD

**Issue by pxs1997** [AirtestProject/AirtestIDE#522]
将poco删除ugui和fairygui后放入项目
报错Assets/Resources/Unity3D/VRSupport.cs(44,44): error CS0234: The type or namespace name `XR' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?

![image](https://user-images.githubusercontent.com/54696292/63990970-8b67cc80-cb18-11e9-80fc-130b9ca3e86d.png)

![image](https://user-images.githubusercontent.com/54696292/63990979-94f13480-cb18-11e9-8ffd-6c37480fb18c.png)

**Comment by yimelia** [comment]
先把目录下面那个VRSupport文件删掉再试试（你第一张截图里的最后一个文件）

**Comment by pxs1997** [comment]
在PocoManager中是实例化VRSupport对象，删除了会报错，我们项目使用的unity版本是
Version 4.7.2f1 (a7fe7b7f3d1f)
会不会是unity的版本太低，没有XR VR相关的代码可以引用

**Comment by pxs1997** [comment]
> 先把目录下面那个VRSupport文件删掉再试试（你第一张截图里的最后一个文件）
在PocoManager中是实例化VRSupport对象，删除了会报错，我们项目使用的unity版本是
Version 4.7.2f1 (a7fe7b7f3d1f)
会不会是unity的版本太低，没有XR VR相关的代码可以引用

**Comment by pxs1997** [comment]
> 先把目录下面那个VRSupport文件删掉再试试（你第一张截图里的最后一个文件）

在PocoManager中是实例化VRSupport对象，删除了会报错，我们项目使用的unity版本是
Version 4.7.2f1 (a7fe7b7f3d1f)
会不会是unity的版本太低，没有XR VR相关的代码可以引用

**Comment by pxs1997** [comment]
> 先把目录下面那个VRSupport文件删掉再试试（你第一张截图里的最后一个文件）

![image](https://user-images.githubusercontent.com/54696292/64139828-d6455500-ce34-11e9-9c1b-308f7150bcd4.png)
报错定位在这个位置

**Comment by yimelia** [comment]
直接把这个文件删掉不行的么？

**Comment by pxs1997** [comment]
> 直接把这个文件删掉不行的么？

其他脚本里应用了这个VRSupport，删除了就报错了
![image](https://user-images.githubusercontent.com/54696292/64142169-769f7780-ce3d-11e9-843a-f2107d3190ee.png)

**Comment by TreHack** [comment]
在pocomanger.cs这个文件中搜索‘vr’  把搜索出来的地方都删掉。

**Comment by pxs1997** [comment]
> 在pocomanger.cs这个文件中搜索‘vr’ 把搜索出来的地方都删掉。

！不报错了 谢谢
