### ISSUE TITLE
WebDriverAgent&Appium, when linked to the devices, the app crashed

### ISSUE THREAD

**Issue by Meng-Chou** [AirtestProject/AirtestIDE#525]
Remove any following parts if does not have details about

**Describe the bug**
Because the facebook WebDriverAgent(https://github.com/facebook/WebDriverAgent.git) now is archived, i couldn‘t create a new issue there. The probelm is :
****[Background]   ****
Xcode 10.3& Mac OS： Mojave 10.14.6&appium：1.13.0& device：iphone7p with OS 12.3.1;
****[problem]   ****
I downloaded the facebook WebDriverAgent by link https://github.com/facebook/WebDriverAgent.git ，when i use appium inspector to find the WebElements on iOS devices,  WebDriverAgent can be build successfully on linked devices, but when click product—>test  or test Runner, the app crashed and crashed。 Finally ,Xcode console is printing:
unrecognized selector sent to class 0x104bfc130
specifically，
![image](https://user-images.githubusercontent.com/53571388/64058527-0d222d80-cbdf-11e9-859b-f69cf2572f65.png)

Who know any ways may  work out? help

**Comment by EraChen233** [comment]
iOS-Tagent does not support 10.3 yet. Try a lower version, 10.2 or 10.1.
Mac can install multi xcode apps.
