### ISSUE TITLE
小米8 MIUI10 9.8.22|开发版 minicap启动失败

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [AirtestProject/AirtestIDE#526]
**分类**
测试开发环境AirtestIDE使用问题

**详细描述问题bug：**
小米8 MIUI10 9.8.22|开发版 minicap启动失败

**复现步骤：**
正常链接使用就能复现

**python 版本:** `python3.x`

**操作系统:** `Mac 10.13.6`

**手机设备信息:**
 - 手机型号:小米8 MIUI10 9.8.22|开发版
 - Android系统版本号: Android 9

**其他相关信息补充**
- AirtestIDE版本号：1.2.1

```
 /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s fbcd1d21 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_11181' -P 1080x2248@349x727/0 -l 2>&1
PID: 7465
INFO: Using projection 1080x2248@349x726/0
INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display
Vector<> have different types (this=0x7ff5fa6990, rhs=0x7ff5fa6ab0)
Aborted
```
**截屏**
<img width="292" alt="111" src="https://user-images.githubusercontent.com/13994321/64060033-d7d70900-cbf9-11e9-9627-786e861e5866.png">
![222](https://user-images.githubusercontent.com/13994321/64060037-db6a9000-cbf9-11e9-85cd-c2acd4753448.png)

**Comment by yimelia** [comment]
可以参考文档进行错误排查： http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id8

**Comment by BeiKeJieDeLiuLangMao** [comment]
@yimelia 
我已经按照您所说的 Guide 进行过开发者设置，但是上述的问题是 minicap 内部启动过程报错，我换成 javacap 就能用了。
但是 javacap 的 fps 实在太低了，看着很难受，所以提了这个 issue 希望官方解决 minicap 的兼容性问题。

**Comment by yimelia** [comment]
我看了下，MIUI 10是Android 10的版本了，目前minicap还不支持Android10，所以暂时用不了minicap。
目前在Android10下面，勾选IDE的三个选项之后再connect手机是可以连的，但是在横屏下会有问题，只有竖屏是好的

**Comment by naodeng** [comment]
@yimelia  MIUI10 9.8.22|开发版 的Android系统版本号: Android 9，非Android10。查阅minicap官方文档应该是支持Android 9

**Comment by BeiKeJieDeLiuLangMao** [comment]
@yimelia 
![71622](https://user-images.githubusercontent.com/13994321/64163872-a322b600-ce74-11e9-80e2-44a67165bf4a.jpg)

**Comment by yimelia** [comment]
我们手头有这个版本号的MIUI，确实是安卓10

![image](https://user-images.githubusercontent.com/6896468/64239526-feb37900-cf32-11e9-827e-db461aa6579a.png)

**Comment by Neilcc** [comment]
同样的问题， 看起来是小米兼容的问题，新版miui 不论android  9 和 Android 10 都挂了 日志如下 INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display
Vector<> have different types (this=0x7fca7f7c40, rhs=0x7fca7f7d60)  
看起来是创建的buffer 的类型 和 surface 类型不对

**Comment by AITCK** [comment]
小米8 开发版 android9 遇到同样问题

**Comment by yimelia** [comment]
@timaker 小米的MIUI兼容问题，可以直接改用javacap截图即可
