### ISSUE TITLE
ArtiTest0.09 连接小米5失败

### ISSUE THREAD

**Issue by aihanghang** [AirtestProject/AirtestIDE#53]
我安装了ArtisTest0.09, 小米5驱动安装正常，但点击连接时提示fail, 画面如下:
![1](https://user-images.githubusercontent.com/20196362/38188165-33ddf46a-368d-11e8-8562-0c25558a6c50.jpg)
![1](https://user-images.githubusercontent.com/20196362/38188166-3446033e-368d-11e8-8540-c3f69c0aadc8.jpg)

后台的log画面如下:  请看看是哪里的问题.

![2](https://user-images.githubusercontent.com/20196362/38188207-72677ca6-368d-11e8-9ad8-aed40e50ef0a.jpg)

**Comment by rockywhisper** [comment]
@aihanghang  你好，小米的设备需要在开发者选项中勾选上部分选项：
[对应文档说明](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id6)
可以检查后再试一下哈。

**Comment by aihanghang** [comment]
我按照说明开启了三个选项，好像还是同样的问题.

![3](https://user-images.githubusercontent.com/20196362/38188977-b5bdd952-3690-11e8-890b-5a1383c1729f.png)

**Comment by rockywhisper** [comment]
@aihanghang Hi，请问昨天换了USB线之后连接是否稳定了呢？

**Comment by rockywhisper** [comment]
@aihanghang  你好，小米5设备多次测试都表现正常。按照之前的经验，可能是以下两种原因：①有第三方软件强占adb；②USB线的连接不稳定。
因为每个人的电脑环境不一样，可能要自己查看下具体情况。

我暂时把这条issues关闭了哈，后续有其他相关疑问可以随时在QQ群（437119175）沟通哈    :-)
