### ISSUE TITLE
MI8无法连接

### ISSUE THREAD

**Issue by gegelaopiaoke** [AirtestProject/AirtestIDE#530]
![image](https://user-images.githubusercontent.com/29562144/64331411-54f0ec80-d005-11e9-9eb6-d6f87b49c4bf.png)
你好，我的米8连不上，adb可以连接，系统是MIUI10 9.8.221开发版

**Comment by gegelaopiaoke** [comment]
已经按照要求手机设置都开了 USB调试，USB安装。USB连接

**Comment by yimelia** [comment]
duplicate of #526
