### ISSUE TITLE
查看日志报告时，提示日志目录中没有日志文件

### ISSUE THREAD

**Issue by wen1074489416** [AirtestProject/AirtestIDE#531]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)
查看日志报告时，提示日志目录中没有日志文件
可能是我设置问题，但是不知道该如何解决，麻烦告知下怎么处理，谢谢啦
**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![airtest](https://user-images.githubusercontent.com/34625355/64408152-a3ab8e80-d0b8-11e9-8021-1da7d25e6948.png)

**Comment by EraChen233** [comment]
把运行脚本的时候，IDE的log窗口输出贴出来，
方便的话，最好把脚本也贴上来

**Comment by wen1074489416** [comment]
> 把运行脚本的时候，IDE的log窗口输出贴出来，
> 方便的话，最好把脚本也贴上来

因为比较急，我把系统重装了，已经没有那个问题了，但是不知道具体什么导致的
