### ISSUE TITLE
是用本地python路径后Airtest 抛出 DeviceConnectionError("device not ready“）

### ISSUE THREAD

**Issue by WTHK** [AirtestProject/AirtestIDE#532]
![Snipaste_2019-09-07_13-17-50](https://user-images.githubusercontent.com/38538378/64470196-eed5a800-d171-11e9-83a6-a43673d1f0df.png)

**Comment by yimelia** [comment]
可以把ADB的版本统一成同一个版本就可以解决（IDE中使用的版本和airtest不同）
