### ISSUE TITLE
小米8SE 连接Airtest问题

### ISSUE THREAD

**Issue by slimetest** [AirtestProject/AirtestIDE#534]
* 测试开发环境AirtestIDE使用问题（本软件）

**详细描述问题bug：**
勾选use Javacap就可以正常连接手机，显示界面到Airtest，但是界面模糊，，且无法模拟点击操作。
不勾选use Javacap，点击connect后，黑屏大概3-5秒，就自动退出连接。期间点home键等功能有效。

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`
Windows10 64
**手机设备信息:**
 - 手机型号:小米8SE
 - Android系统版本号: [e.g. Android 8.1] 安卓9.0，MIUI 10
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
连接勾选Use javacap:
![image](https://user-images.githubusercontent.com/55084930/64519973-c1caf600-d327-11e9-9f1c-ec1758453b61.png)
![image](https://user-images.githubusercontent.com/55084930/64520794-71549800-d329-11e9-97ba-0cfd75e4da4f.png)

连接不勾选Use javacap:
![image](https://user-images.githubusercontent.com/55084930/64520845-84676800-d329-11e9-8563-e34ec144b1f3.png)
![image](https://user-images.githubusercontent.com/55084930/64521975-94804700-d32b-11e9-9676-104667eceef3.png)

还有个问题：连接时有勾选 use ADB touch就无法点击，不勾选就，可以点击，完全反了。

**Comment by slimetest** [comment]
同一台电脑，连其他安卓6.0手机是正常的

**Comment by yimelia** [comment]
Duplicate of #526
