### ISSUE TITLE
Airtest cannot make touch event on samsung S9

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/AirtestIDE#535]
My test case work fine on any device in company, but on Samsung S9 this is just don't work, AIrtest don't show a message on log panel, nothin, he just think he make a tab on the screen and go to next step.
What's wron?

**Comment by yimelia** [comment]
hi @Chesterfild 
Does your S9 use Android10?

**Comment by Chesterfild** [comment]
> hi @Chesterfild
> Does your S9 use Android10?

No, S9 working on android 9, and this is strange, last time when i working on it, all be fine.

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/en/3_faq/ide_crash.html#how-can-i-check-the-cause-of-airtestide-crash

do you have any screenshot? the error message in the console log maybe helpful

**Comment by Chesterfild** [comment]
> http://airtest.netease.com/docs/en/3_faq/ide_crash.html#how-can-i-check-the-cause-of-airtestide-crash
> 
> do you have any screenshot? the error message in the console log maybe helpful

I don't know what's happened, but when i try to record the video for you, all work fine, i don't touch anything in code, and on devices... But, today all work.

If this is happening again, i try to get a video and log
