### ISSUE TITLE
Can i get a screen resolution on my device with ADB command?

### ISSUE THREAD

**Issue by Chesterfild** [AirtestProject/AirtestIDE#537]
I need to write command when script start:
"adb shell dumpsys window | find "DisplayWidth""
And put value in variable.

I try to find how to do it in documentation but i find only how to connect device.

**Comment by EraChen233** [comment]
Try function `get_current_resolution` or `display_info`

https://airtest.readthedocs.io/en/latest/all_module/airtest.core.android.android.html#airtest.core.android.android.Android.get_current_resolution

``` python
dev=device()
res1 = dev.get_current_resolution()
print(res1)
res2 = dev.display_info
print(res2)
```
