### ISSUE TITLE
运行1.2.2版本的AirtestIDE，无响应

### ISSUE THREAD

**Issue by ldonlytest** [AirtestProject/AirtestIDE#538]
**详细描述问题bug：**
1. 点击.exe运行，一会报无响应
2.从兼容模式启动.bat 运行，问题如1
3.对比上一个版本，上一个版本正常

如图

![image](https://user-images.githubusercontent.com/24670637/64662413-fac7af80-d47a-11e9-9671-e00874636fd2.png)

**复现步骤：**
必现

**python 版本:** `电脑安装有python2.7及python3.6`

**操作系统:** `Windows7 32bit`

**Comment by EraChen233** [comment]
错误信息在你发的截图里，后面的那个命令行窗口，可以重新截图，把完整错误信息贴出来吗

**Comment by yimelia** [comment]
@ldonlytest 
hi，不使用兼容性模式运行，进入到AirtestIDE目录下，按住shift+鼠标右键，选择打开命令行窗口
然后在窗口中输入AirtestIDE.exe运行，在卡死时界面上会有报错，把报错发出来看看。
无需使用兼容性模式，我们想看一下原版是否缺失了文件导致问题

**Comment by ldonlytest** [comment]
> @ldonlytest
> hi，不使用兼容性模式运行，进入到AirtestIDE目录下，按住shift+鼠标右键，选择打开命令行窗口
> 然后在窗口中输入AirtestIDE.exe运行，在卡死时界面上会有报错，把报错发出来看看。
> 无需使用兼容性模式，我们想看一下原版是否缺失了文件导致问题

嗨，你好，提示找不到指定模块，如图
![image](https://user-images.githubusercontent.com/24670637/64666682-b2fc5480-d489-11e9-8921-539761cf6194.png)
内容：

D:\soft\AirtestIDE_2019-09-10_py3_win32\AirtestIDE_2019-09-10_py3_win32>AirtestI
DE.exe
Info: filter not set, use raven.filter.FullPassFilter instead.
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001

QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll
is available
Failed to load opengl32sw.dll (找不到指定的模块。)
Failed to load and resolve WGL/OpenGL functions
loading config from : ['C:\\Users\\lidan\\AppData\\Local\\AirtestIDE\\AirtestIDE
\\user.json']
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001

QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll
is available
Failed to load opengl32sw.dll (找不到指定的模块。)
Failed to load and resolve WGL/OpenGL functions
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creatio
n failed.
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001

QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll
is available
Failed to load opengl32sw.dll (找不到指定的模块。)
Failed to load and resolve WGL/OpenGL functions
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options Q
Flags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, gre
enBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, sam
ples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInte
rval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers installe
d.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, ma
ke sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll
and d3dcompiler_*.dll) are available in the application executable's directory o
r in a location listed in PATH.

**Comment by yimelia** [comment]
@ldonlytest 
旧版本的32位包你还留着不？可能是缺了一个文件，可以把`AirtestIDE_2019-04-16_py3_win32\PyQt5\Qt\bin`目录下的 `opengl32sw.dll` 文件，拷贝一份到新版本的相同目录下（`PyQt5\Qt\bin`）里面看看

**Comment by ldonlytest** [comment]
> @ldonlytest
> 旧版本的32位包你还留着不？可能是缺了一个文件，可以把`AirtestIDE_2019-04-16_py3_win32\PyQt5\Qt\bin`目录下的 `opengl32sw.dll` 文件，拷贝一份到新版本的相同目录下（`PyQt5\Qt\bin`）里面看看

拷贝过去就正常

**Comment by yimelia** [comment]
@ldonlytest 
好的，非常感谢你的帮助，我去补充一下这个文件到安装包里
