### ISSUE TITLE
用Airtest IDE运行脚本之后，报告里不会生成日志文件

### ISSUE THREAD

**Issue by wen1074489416** [AirtestProject/AirtestIDE#539]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)
用Airtest IDE运行脚本之后，报告里不会生成日志文件,之前也反馈过，但是没人回复我，可能是因为我问的问题太低级了吧，但是确实没有找到相关资料，默认的配置我没有动过，但是我也怀疑，日志生成了，也可能生成到别的位置，因为是新手不知道该如何排查该问题，望看到的人可以帮忙关注下，或者提供下日志配置的地址文件，谢谢了
**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)
 Android 7.1.2
**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：
windows7
**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/34625355/64665196-416dd780-d484-11e9-8d3f-f895cea4ede6.png)

**Comment by EraChen233** [comment]
可以把运行代码的时候，AirtestIDE的输出贴出来吗？

**Comment by yimelia** [comment]
最好将脚本内容一并贴出

**Comment by yimelia** [comment]
运行脚本和生成报告，本身就是两个分开的步骤
请查看文档：http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id1
