### ISSUE TITLE
Aritest辅助窗功能不可用

### ISSUE THREAD

**Issue by dagejirenwu** [AirtestProject/AirtestIDE#540]
![youdu图片20190911153144](https://user-images.githubusercontent.com/55180256/64676993-4d1fc500-d4a9-11e9-8536-d33e7359b766.png)
之前点击录制屏幕的时候软件卡死过一次，之后录制功能就无法用了，用代码写的也不行，重启电脑也不好使，删了软件重新下载也不行，报错NoneType object has no attribute touch

**Comment by dagejirenwu** [comment]
![youdu图片20190911153519](https://user-images.githubusercontent.com/55180256/64677261-ca4b3a00-d4a9-11e9-9f98-f37031a2f54f.png)

**Comment by yimelia** [comment]
需要先连上一台设备，比如一台安卓手机、或者windows窗口、或ios手机

**Comment by dagejirenwu** [comment]
> 需要先连上一台设备，比如一台安卓手机，或者窗窗口，或IOS手机
我的是WINDOWS测试，没有测手机

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/tutorial/7_如何测试Windows应用程序/
