### ISSUE TITLE
AirtestIDE中运行脚本，使用subprocess执行adb命令，提示adb: command not found

### ISSUE THREAD

**Issue by violet4783** [AirtestProject/AirtestIDE#541]
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题：**
AirtestIDE中运行.py脚本，使用subprocess执行adb命令，提示adb: command not found
但在终端直接执行脚本没有问题

**python 版本:** `python3.7`

**操作系统:** `macOS`

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**截屏**
![image](https://user-images.githubusercontent.com/18345833/64679888-367c6c80-d4af-11e9-881c-bfce2593b6ca.png)
![image](https://user-images.githubusercontent.com/18345833/64679903-41cf9800-d4af-11e9-9501-8f1ad731ec7f.png)

**Comment by yimelia** [comment]
截图中的报错似乎不是 `adb: command not found`
如果是找不到adb的话，可以试着将adb改为完整的adb可执行文件的路径试试
但是从你的报错来看不是这个问题，IDE在运行脚本时是额外在外面包了一层代码的，所以不一定与本地环境运行的结果完全一致，这个需要你们自己排查下那个adb devices的输出究竟是不是有问题

**Comment by violet4783** [comment]
- 。- 是我记错了吗？
Command 'adb devices' returned non-zero exit status 127 
状态码127的含义就是没有找到命令啊  ……

**Comment by violet4783** [comment]
改为完整的adb可执行文件的路径就OK了，谢谢

**Comment by yaoliangcui** [comment]
改为完整的adb可执行文件——这个改哪里？
