### ISSUE TITLE
ide中的Windows窗口连接无法连接微信开发者工具中的模拟器

### ISSUE THREAD

**Issue by ChikinTam** [AirtestProject/AirtestIDE#542]
在是用ide中Windows连接功能是，选中微信开发者工具模拟器后，设备框中没有任何显示。
![image](https://user-images.githubusercontent.com/47165837/64688020-2029dd00-d4be-11e9-8e01-9c6ce3db717f.png)
因为看到微信开发者工具中有新的自动化测试功能，但是不够airtest方便，但是其中的模拟器挺好用，所以想使用airtestIDE中Windows窗口连接到模拟器中，但是该功能貌似目前无法正常使用
模拟器打开命令
cmd进入开发者工具目录
输入：cli --auto <项目地址>

**Comment by yimelia** [comment]
试一下无嵌入方案看看能不能用，文档地址在这里：http://airtest.netease.com/docs/cn/2_device_connection/5_windows_connection.html#id2

**Comment by ChikinTam** [comment]
> 试一下无嵌入方案看看能不能用，文档地址在这里：http://airtest.netease.com/docs/cn/2_device_connection/5_windows_connection.html#id2
按照文档设置，选择模拟器后，还是无法对其进行操作

**Comment by yimelia** [comment]
能否具体描述“无法对其进行操作”是什么样的问题
