### ISSUE TITLE
查看测试报告时，没有展示具体操作步骤

### ISSUE THREAD

**Issue by wen1074489416** [AirtestProject/AirtestIDE#545]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)
有个疑问，这个最新版的报告，内容是不是没有展示出来呀，还是我哪里需要配置一下
**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
生成的报告没有操作步骤
**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`
windows7

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)
用的mumu模拟器

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/34625355/64771373-6e53e480-d581-11e9-9e62-8ce2464e2dcd.png)

**Comment by yimelia** [comment]
生成报告过程中是否有报错信息？
尝试换一个浏览器打开看看，比如使用chrome，或者是浏览器的非兼容性模式（非IE内核）

**Comment by wen1074489416** [comment]
处理好了，确实是浏览器版本兼容问题，之前用了个假谷歌，谢谢了
