### ISSUE TITLE
Log查看窗中中文乱码

### ISSUE THREAD

**Issue by 971507252** [AirtestProject/AirtestIDE#55]
将脚本保存到本地，命名为中文，运行时在Log查看窗中显示乱码

**Comment by adolli** [comment]
麻烦将log窗口截个图或者贴一下显示了什么乱码

**Comment by rockywhisper** [comment]
@971507252  Hi，这个问题在最新版本包内已修复。 [AirtestIDE下载](http://airtest.netease.com/changelog.html)
