### ISSUE TITLE
After running script Yosemite gets installed and doest let my manual keyboard to slide up 

### ISSUE THREAD

**Issue by anandplay17** [AirtestProject/AirtestIDE#550]
After running script, Yosemite gets installed and doest let my manual keyboard to slide up 

STR:
1. Run the script once 
2. Obsrevre in android notification Yosemite gets enabled and blocks the keyboard from coming up

**Comment by EraChen233** [comment]
Change default keyboard in setting.
https://www.androidcentral.com/how-set-default-keyboard-your-android-phone
