### ISSUE TITLE
求助：Airtest有没有办法模拟键盘输入内容？

### ISSUE THREAD

**Issue by shijianzhihu** [AirtestProject/AirtestIDE#555]
**详细描述问题bug：**
我现在页面上有一个支付密码输入框，类似于微信支付（如下图），Airtest有没有办法模拟键盘输入内容？如果使用图片识别的方式，数字8和0经常会识别错误，识别阈值已经提高到了0.90。
![](https://user-images.githubusercontent.com/26112446/65386866-429be000-dd73-11e9-9f4f-e67852c41340.png)

**python 版本:** `python3.7.0`
**操作系统:** `MacOS`
**AirtestIDE:** `the latest`

**Comment by yimelia** [comment]
http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#text
如果打开了相关手机设置还是不能用yosemite输入法，说明是部分应用为了安全性故意不让你用这种方式来输入，只能用图像识别来输了
图像识别的话，可以尽可能通过修改截图来提升识别率 ，比如这里有一个教程：https://airtest.doc.io.netease.com/tutorial/9_%E5%A6%82%E4%BD%95%E7%94%9F%E4%BA%A7%E5%85%BC%E5%AE%B9%E6%80%A7%E5%BC%BA%E7%9A%84%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95%E8%84%9A%E6%9C%AC/
