### ISSUE TITLE
输入法问题

### ISSUE THREAD

**Issue by Linzero580** [AirtestProject/AirtestIDE#558]
python版本：3.7.4
设备：Coolpad5267 Android6.0
问题：
每次运行脚本的时候，都会自动安装一个Yosemite的软件
![image](https://user-images.githubusercontent.com/18110385/65401601-e4ffa600-ddfb-11e9-9a71-0859461377ed.png)
，需要输入文字的时候都会被屏蔽掉，请问如何解决这个问题？

**Comment by EraChen233** [comment]
在设置，键盘，切换默认键盘

**Comment by Linzero580** [comment]
> 在设置，键盘，切换预设键盘

这个操作并不能解决问题

**Comment by yimelia** [comment]
@Linzero580 
不知道你遇到了什么问题，可以参考文档：https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#4
