### ISSUE TITLE
三星手机截图时AirtestIDE崩溃。重新打开后，之前保存的脚本无法打开，说是缺少*.py文件。大概过了十分钟左右又正常了，但是崩溃的那个工程不见了。

### ISSUE THREAD

**Issue by leavescy** [AirtestProject/AirtestIDE#56]
三星手机截图时AirtestIDE崩溃。重新打开后，之前保存的脚本无法打开，说是缺少*.py文件。大概过了十分钟左右又正常了，但是崩溃的那个工程不见了。

**Comment by rockywhisper** [comment]
@leavescy  你好，请问是否方便提供下手机截图触发崩溃报错现场， [查看崩溃报错的方法](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/1_ide_crash.html#id2) 。

另外，我们排查下保存逻辑，解决下崩溃后工程不见的问题。

**Comment by rockywhisper** [comment]
@leavescy  你好，这个问题在 [新版本IDE](http://airtest.netease.com/changelog.html) 中已经得到修复，欢迎下载使用。

我关掉这个issues了哈，如发现其他问题欢迎随时沟通。
