### ISSUE TITLE
airtest是否支持等待用户键盘输入的功能（可以用一个变量保存将用户的输入字符）

### ISSUE THREAD

**Issue by rgxiwei** [AirtestProject/AirtestIDE#562]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
你好，没有完全明白你的意思是什么？
能否详细描述你的需求，如果可能的话，最好给出一个示例

**Comment by rgxiwei** [comment]
你好，我给你举个例子把
例如待测app有两个button，一个叫A，一个叫B，需要对其中一个button执行click操作，但是具体click操作哪一个button需要用户在键盘输入A或者B来决定。比如python有input()函数可以获取用户键盘输入的“A”字符，然后脚本就知道此时应该对A进行click操作。
不知道我描述清除了没有？

**Comment by yimelia** [comment]
先进行输入，然后再获取到输入框里的内容进行判断，例如poco里面就有获取控件值的对应接口可以使用。
如果不能使用Poco，想用airtest来截图识别的话，可能在准确度上面会不如预期，但你也可以尝试这么做：截图输入框内的文字，与预设好的输入A的文字图片进行比较，但是成功率会比较低。

**Comment by rgxiwei** [comment]
目前是这样，用户的输入只是在控制台体现（例如，在pyCharm中有控制台，输入完成后，回车，用户输入的字符会保存在代码中变量里），app里面没有输入框的，用户的输入也不会在app中显示。
