### ISSUE TITLE
打包的apk怎么运行

### ISSUE THREAD

**Issue by jinjie412** [AirtestProject/AirtestIDE#564]
打包的apk通过adb指令可以运行,在模拟器里面直接运行apk没有效果

**Comment by yimelia** [comment]
请根据文档上的说明来运行

**Comment by jinjie412** [comment]
我根据文档上的操作方式运行成功了，我是在模拟器上直接运行没效果

**Comment by jinjie412** [comment]
@yirr 我根据文档上的操作方式运行成功了，我是在模拟器上直接运行没效果

**Comment by jinjie412** [comment]
> 
> 
> 请根据文档上的说明来运行

我根据文档上的操作方式运行成功了，我是在模拟器上直接运行没效果

**Comment by yimelia** [comment]
如果没理解错你的意思的话，你是在模拟器上**直接运行**了打包出来的apk，这样运行是有问题的，请参考文档上面的adb指令来运行，如果是模拟器，可以自行修改那条adb指令，指定用你的模拟器来执行即可。
意思就是说，**必须要通过adb shell才能运行打包出来的apk**，不管你用什么型号的手机。

**Comment by jinjie412** [comment]
> 
> 
> 如果没理解错你的意思的话，你是在模拟器上**直接运行**了打包出来的apk，这样运行是有问题的，请参考文档上面的adb指令来运行，如果是模拟器，可以自行修改那条adb指令，指定用你的模拟器来执行即可。
> 意思就是说，**必须要通过adb shell才能运行打包出来的apk**，不管你用什么型号的手机。

我用的是雷电模拟器，模拟器里面带终端控制里面有adb的命令，我在模拟器里面用adb命令可以正常正常运行吗，我的目的是脱离电脑直接在模拟器上直接运行apk。
