### ISSUE TITLE
touch(v,times= 2) 两次touch等待时间太长了，没办法识别为双击

### ISSUE THREAD

**Issue by Andylau1994** [AirtestProject/AirtestIDE#565]
bug描述
touch(v,times= 2) 两次点击等待的间隔太长了，无法识别为双击

**复现步骤：**
1.touch(v,times= 2)
2.执行脚本

看了下api.py， times = 2 是执行了两次touch函数? 以为是双击操作，感觉直接点击两次左键更有效，我目前使用的这个模块的入口就只有双击，两次识别时间比较长就不当作是双击了，没办法使用。

**python 版本:** `python3.6.4`

**操作系统:** `Windows10 64bit`

**Comment by yimelia** [comment]
试一下 `double_click`这个接口看看

**Comment by Andylau1994** [comment]
后面看见这个接口了哈哈

**Comment by yimelia** [comment]
是测试windows下的应用么？还是安卓手机？

**Comment by Andylau1994** [comment]
windows 的，尝试用一下AirTest
