### ISSUE TITLE
小米mix2s不兼容问题

### ISSUE THREAD

**Issue by jmz3095544190** [AirtestProject/AirtestIDE#573]
小米mix2s机型连接不上，不兼容问题

**Comment by yimelia** [comment]
请参考文档修改手机配置 https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_3

我们有这台手机，是可以连的，没有遇到问题。
如果是基于安卓10的MIUI，暂时还未支持，不是机型问题，是系统问题，我们后续会尽快支持的。

**Comment by jmz3095544190** [comment]
thanks




------------------ 原始邮件 ------------------
发件人: "yimelia"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 上午9:52
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com>;
抄送: "蒋明泽"<3095544190@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AirtestProject/AirtestIDE] 小米mix2s不兼容问题 (#573)




请参考文档修改手机配置 https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_3
 
我们有这台手机，是可以连的，没有遇到问题。
 如果是基于安卓10的MIUI，暂时还未支持，不是机型问题，是系统问题，我们后续会尽快支持的。
