### ISSUE TITLE
命令行 连接模拟器运行脚本时报错 json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by emiyamuto** [AirtestProject/AirtestIDE#574]
**详细描述问题bug：**
命令行 连接模拟器运行脚本时报错 json.decoder.JSONDecodeError

**复现步骤：**
我的方法是选择的最简单的方法，直接在log里面复制的运行代码
也就是用单纯用airtest ide的环境来运行脚本。

**python 版本:** `python3.65`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:mumu模拟器
 - Android系统版本号: [e.g. Android 6.01]

**其他相关信息补充**
直接用airtest ide运行可以运行脚本，此时模拟器连接勾选了javacap与adb orientation
本机的环境下python也已经安装了airtest

- AirtestIDE版本号：v1.2.2

**截屏**
![image](https://user-images.githubusercontent.com/56816473/67182529-0612e100-f412-11e9-8f97-518c4f2d2913.png)

**Comment by yimelia** [comment]
模拟器是什么品牌？是否是MUMU？
在IDE里先运行一次看看是否是正常的

**Comment by emiyamuto** [comment]
> 模拟器是什么品牌？是否是MUMU？
> 在IDE里先运行一次看看是否是正常的

模拟器为mumu
在ide中可以运行

**Comment by yutian567** [comment]
我也是一样的问题 IDE里可以，命令行就报这个错

**Comment by yimelia** [comment]
@emiyamuto @yutian567 
可以参考文档：https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2
在命令行终端里运行，可能需要加转义符号，否则命令行参数里的&&符号可能识别不到
