### ISSUE TITLE
请问，Airtest Project集成到Jenkins，如何解决测试报告中的图片路径问题？

### ISSUE THREAD

**Issue by shijianzhihu** [AirtestProject/AirtestIDE#575]
**详细描述问题bug：**
为了批量运行脚本，我自定义了一个启动器。只需要将所有的case都放到`suite/`目录下，启动器就可以实现批量运行脚本，然后把各个case的脚本运行结果汇总到一个`summary.html`页面中，如下：
![](https://user-images.githubusercontent.com/26112446/67293806-83744980-f517-11e9-9b3f-131e2f5c593b.png)

在与Jenkins集成时，因为目前好像还没专门的插件对airtest project项目进行支持，所以我是通过对脚本运行时Jenkins Console的输出内容进行匹配，比如内容中包含‘ERROR:’，我就会将Job构建状态变为Fail.然后触发邮件通知，将上面的summary.html作为唯一附件发送。

目前打开邮件中收到的附件，点击case名称，现在可以跳转到自带的测试报告页面。由于在生成报告时，我已经设置了static_root和export_dir参数，所以页面样式可以正常展示，但是仍然无法显示每一步的log截图。如果将整个目录（包含截图和log.html）打包作为Jenkins邮件附件发送，又实在是不方便收件人查看，特别是在身边没有电脑的时候。

请问，Airtest Project集成到Jenkins，如何解决测试报告中的图片路径问题？
目前网上这方面的内容比较缺少，官网也没有给出说明，请问网易的经验可否分享一下呢？不胜感激。这样也有利于Airtest的推广。

**Comment by EraChen233** [comment]
我们目前提供了一个收费方案，能解决你提出的这些问题，如果有兴趣的话，可以加QQ群 AirtestProject讨论2群 1017250147，私聊管理员
