### ISSUE TITLE
iOS 10.3.1 iphone6splus 真机无法连接airtestIDE

### ISSUE THREAD

**Issue by Alexno1no2** [AirtestProject/AirtestIDE#576]
iOS 10.3.1 iphone6splus 真机无法连接airtestIDE

操作系统：`MacOS Mojave 10.14.5`  xcode 10.2.1

http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/2_device_connection/4_ios_connection.html

已按照 2.4.3 简单部署流程 完成了step1和step2，且通过http://127.0.0.1:8100/inspector 已经可以在mac上看到手机端页面
![image](https://user-images.githubusercontent.com/56922388/67450234-4d39e580-f64f-11e9-972a-b17b0a5e9764.png)

进行step3时，无法连接

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.6`

**操作系统:** `MacOS Mojave 10.14.5`   xcode 10.2.1

**手机设备信息:**
 - 手机型号:
iOS 10.3.1 iphone6splus
 - (别的信息)

**其他相关信息补充**

- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by EraChen233** [comment]
首先，xcode还不支持10.2.1，换一个低版的xcode吧
其次，你用的iOS版本比较低，在高版本xcode下，会截图不完整，可以看一下这个
https://airtest.doc.io.netease.com/tutorial/6_IOS_automated_testing/#_2

**Comment by Alexno1no2** [comment]
python是已经升级成了最新的3.7.4

**Comment by EraChen233** [comment]
和python无关

**Comment by Alexno1no2** [comment]
总结：过程中有几个问题 1、xcode版本太高 降级到10.2后解决 2、通过IDE连接手机不通，原因为电脑上配置了网络代理，去掉代理，保持手机与电脑在同一个网络后连接成功
