### ISSUE TITLE
'Export Report' exports log.html to the wrong directory

### ISSUE THREAD

**Issue by brendan-mz** [AirtestProject/AirtestIDE#578]
**Describe the bug**
Exporting a report from Airtest IDE places the log.html file in the wrong directory. log.html is exported one directory above the exported .log folder, when it should actually be exported inside the .log folder. Attempting to open the log.html file from the export directory results in a page with broken CSS, js and images. Manually moving the log.html file to the .log folder fixes the issue.

**To Reproduce**
1. Run any test case in Airtest IDE, e.g. 'my_test.air'
2. Click on the '+' dropdown button at the top-right of the editor panel
3. Select 'Export Report' from the dropdown menu
4. Choose an export directory using the file browser
5. Airtest IDE will automatically open the directory containing the exported report
6. Open the file 'log.html' from the directory above
7. Observe that the CSS, js, and image links are not working and page is not rendering correctly.

**Expected behavior**
Exported report HTML should render correctly. The file log.html should be exported to the .log folder in the export directory, rather than to the export directory itself.

**Screenshots**
![Screen Shot 2019-10-24 at 11 09 17 AM](https://user-images.githubusercontent.com/47615318/67513972-c38b1780-f650-11e9-9905-06b6dffbd873.png)
![Screen Shot 2019-10-24 at 11 11 00 AM](https://user-images.githubusercontent.com/47615318/67514053-ec131180-f650-11e9-9632-d4b010927478.png)
![Screen Shot 2019-10-24 at 11 11 24 AM](https://user-images.githubusercontent.com/47615318/67514063-f0d7c580-f650-11e9-9b42-2bea0c0e3863.png)

**python version:** `python2.7`

**airtest version:** `1.1.1`
**Airtest IDE version:** `1.2.2`

**Comment by brendan-mz** [comment]
Thanks @EraChen233. Are there plans to allow specifying a custom report launcher script in Airtest IDE settings, similar to how you can set a custom test launcher script?

**Comment by EraChen233** [comment]
Airtest Project is an open source project. You can modify the code file locally.
1. Custom python path for yuor IDE. http://airtest.netease.com/docs/en/1_online_help/ide_settings.html#use-local-python-environment-to-run-scripts-trial
1. Install the Airtest and Poco libraries by executing `pip install pocoui` and `pip install airtest` 
1. Modify report file *python/Lib/site-packages/airtest/airtest/report/report.py* directly on your local computer.

**Comment by brendan-mz** [comment]
@EraChen233 Yeah I'm already using the custom python virtualenv as well as a custom launcher script in Airtest IDE. However, the custom launcher only allows you to hook into test execution, not into report generation. 

If I was able to specify a custom report generator path, then I would be able to fix this bug by simply overriding the incorrect output file path that the IDE is generating, and then pass the corrected version to the Airtest report function.

It looks like a custom report generator script is already supported (there's a reporter script in the 'sample' folder), but it's not hooked up to Settings in the IDE like the custom launcher path is.

**Comment by EraChen233** [comment]
To save log.html in the correct directory, you can temporarily try the following method. Or wait for next release of AirtestIDE.

Find report.py in `python/Lib/site-packages/airtest/airtest/report/report.py`

Comment these code.
![image](https://user-images.githubusercontent.com/5961185/67731237-79c87580-fa32-11e9-8838-27fa41963646.png)

https://github.com/AirtestProject/Airtest/blob/master/airtest/report/report.py#L319
