### ISSUE TITLE
录制swipe操作

### ISSUE THREAD

**Issue by EgoistInory** [AirtestProject/AirtestIDE#582]
录制swipe操作 在红米note6上操作APP cell左滑，有时候并不能生效
可能是录制的手法问题，录制滑动的过程中走了曲线，但人不容易察觉

**Comment by yimelia** [comment]
看一下和IDE一起启动的那个黑色命令行窗口里面，在你录制swipe的过程中有没有什么报错信息，可以截一个图看看。
我们目前手头没有红米note6，暂时不能进行测试

**Comment by EgoistInory** [comment]
伴随IDE启动的命令行窗口 程序坞上显示是打开的，但是打不开窗口，有其他获取日志的方法嘛
我的机子是Mac OS Catalina 10.15   2017MBP

**Comment by yimelia** [comment]
可以用命令行方式打开，参考这个[文档](https://airtest.doc.io.netease.com/IDEdocs/getting_started/crash_abnormalProblem/#airtestide_1)

**Comment by EgoistInory** [comment]
<img width="1124" alt="截屏2019-10-2914 39 02" src="https://user-images.githubusercontent.com/35621232/67743890-fbcc9480-fa5a-11e9-828c-42fbd35e1b47.png">

<img width="322" alt="截屏2019-10-2914 39 50" src="https://user-images.githubusercontent.com/35621232/67744016-57971d80-fa5b-11e9-8747-255cc0e20d7f.png">

明白了，是我录制的问题
