### ISSUE TITLE
华为MATE30PRO不能连接airtest

### ISSUE THREAD

**Issue by dragonpatton** [AirtestProject/AirtestIDE#583]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
手机可以识别ADB devices，都是正常点击connect
就报下面的错，进去
C:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-10
中查看，根本没有【arm64-v8a】这个文件夹

下面是报错信息
    display_info = self.minicap.get_display_info()
  File "airtest\utils\snippet.py", line 104, in ready_func
    method()
  File "airtest\utils\snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 86, in install_or_upgrade
    self.install()
  File "airtest\core\android\minicap.py", line 132, in install
    self.adb.push(path, "%s/minicap.so" % device_dir)
  File "airtest\core\android\adb.py", line 429, in push
    self.cmd(["push", local, remote], ensure_unicode=False)
  File "airtest\core\android\adb.py", line 187, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'C:\\AirtestIDE_2019-09-11_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']
**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`
安卓10
**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by EraChen233** [comment]
请问手机系统是Android 10吗？

**Comment by yimelia** [comment]
duplicate of https://github.com/AirtestProject/Airtest/issues/504

**Comment by FasterthanHongKongreport** [comment]
我也是同款手机，没问题，但是poco用不了

**Comment by yimelia** [comment]
@FasterthanHongKongreport 
有问题麻烦重新描述清楚遇到了什么问题。
如果用不了poco，可以参考这个文档第五条，看下手机助手里的设置 https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_6
