### ISSUE TITLE
WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening.

### ISSUE THREAD

**Issue by cash2910** [AirtestProject/AirtestIDE#585]
* 测试开发环境AirtestIDE使用问题
**详细描述问题bug：**
   连接后python 脚本报错。

**python 版本:** `python3.6`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - Mumu模拟器

- AirtestIDE版本号：1.2.2

**截屏**
![image](https://user-images.githubusercontent.com/3990693/67825345-faa37200-fb03-11e9-98bb-efeb8c6a2410.png)
手动执行：  
![image](https://user-images.githubusercontent.com/3990693/67825366-13138c80-fb04-11e9-84d9-da58d1fc564e.png)

尝试修改python 脚本。airtest\core\android\minicap.py  新增了：

**Comment by cash2910** [comment]
index = display_info.index("{")
display_info = display_info[index:len(display_info)]
但是没起作用 python  感觉没有更新python 代码

**Comment by cash2910** [comment]
adb devices  可以看到mumu 设备信息

**Comment by yimelia** [comment]
1. 请描述清楚遇到了什么问题
2. 请将图1里的报错信息完整地贴出来
3. 如果是模拟器连接问题，请先阅读[文档](https://airtest.doc.io.netease.com/IDEdocs/device_connection/3_emulator_connection/)里的连接步骤

**Comment by cash2910** [comment]
@yimelia    勾选完Use javacap 点击连接后 命令行提示信息如下：
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 get-state
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 wait-for-device
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.sdk
Device:127.0.0.1:7555 updated <airtest.core.android.android.Android object at 0x00000195478EBEF0> -> <airtest.core.android.android.Android object at 0x00000195470AF1D0>
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap ; echo ---$?---
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap.so ; echo ---$?---
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
version:5
upgrade minicap to lastest version: -1->5
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell rm /data/local/tmp/minicap*
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.product.cpu.abi
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.preview_sdk
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.release
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-23/x86/minicap.so /data/local/tmp/minicap.so
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
minicap installation finished
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 162, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 83, in __init__
  File "app\plugins\device\android\android_phone.py", line 111, in _initDev
  File "airtest\core\android\android.py", line 527, in display_info
    self._display_info = self.get_display_info()
  File "airtest\core\android\android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

手动执行最后的命令：
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---

提示：
E:\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
{
    "id": 0,
    "width": 1440,
    "height": 810,
    "xdpi": 160.00,
    "ydpi": 160.00,
    "size": 10.33,
    "density": 1.69,
    "fps": 60.00,
    "secure": true,
    "rotation": 0
}
---0---

怀疑是这个warning 引起的。

**Comment by yimelia** [comment]
文档的最后有提到：
> 在部分版本的模拟器上，可能勾选了 use javacap 后依然连接失败，此时可以尝试再勾选 use adb orientation 选项后再重新连接即可。

如果勾选之后再连依然不成功的话，可以考虑升级MUMU模拟器到最新版本，或者换个品牌模拟器。MUMU模拟器之前的大概半年到一年内的版本都是不支持的。

**Comment by cash2910** [comment]
你这个回复真好 完美的解决了问题。。。真是国内技术人员的好典范。
