### ISSUE TITLE
小米9手机连接不上airtest IDE

### ISSUE THREAD

**Issue by gogolzf** [AirtestProject/AirtestIDE#586]

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4

**Comment by gogolzf** [comment]
![youdu图片20191031112344](https://user-images.githubusercontent.com/49018133/67916550-06a93580-fbd1-11e9-90dd-65c569d5f0b3.png)

**Comment by gogolzf** [comment]
我键盘已经设置了Yosemite,开启了开发者选项，但还是不行

**Comment by yimelia** [comment]
安卓10的支持我们正在进行测试，尚未外放，还需要一点时间。
duplicate of #504

**Comment by yimelia** [comment]
安卓10的支持我们正在进行测试，尚未外放，还需要一点时间。
duplicate of #504
