### ISSUE TITLE
三星S9+连接后手机界面预览分辨率不正确，没有填满，点击的位置按照原分辨率

### ISSUE THREAD

**Issue by paiguFK** [AirtestProject/AirtestIDE#59]

**Comment by Meteorix** [comment]
https://github.com/AirtestProject/Airtest/issues/8  duplicated here

**Comment by rockywhisper** [comment]
@paiguFK  你好，文档中也有提到 [三星设备分辨率调节](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id7)

这个issue先关闭了哈。
