### ISSUE TITLE
如何在远程服务器上连接本地的手机

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#591]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

写好的脚本需要在远程服务器上运行，但是手机是通过USB在本地计算机连接的。
是否只可以通过wifi远程连接设备?例如adb connect ip:port。有什么方法可以让远程的服务器连接到本地的手机设备？

**Comment by yimelia** [comment]
可以通过wifi远程连接设备，类似这样：https://airtest.doc.io.netease.com/IDEdocs/device_connection/1_android_phone_connection/#3

只要你能想办法连上ADB就可以使用。
具体请根据你们自己的实际情况，用搜索引擎查询ADB的连接方式来解决。
