### ISSUE TITLE
小米9 pro 无法使用minicap

### ISSUE THREAD

**Issue by HynemanKan** [AirtestProject/AirtestIDE#592]
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
小米9 pro 在使用airtest时，无法使用minicap

**复现步骤：**
直接连接

**python 版本:** `python3.x`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号: 小米 9 pro
 - Android系统版本号:  Android 9
 - MIUI 11.0.2.0
 - (别的信息)

**其他相关信息补充**

- AirtestIDE版本号：1.2.1

**截屏**
ide log 窗口
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 wait-for-device
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell getprop ro.build.version.sdk
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell ls /data/local/tmp/minicap
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell ls /data/local/tmp/minicap.so
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
version:5
**skip install minicap**
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell pm path jp.co.cyberagent.stf.rotationwatcher
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-U7SD3GwtMvydsxfw32YjZw==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s d8a3eb24 forward --no-rebind tcp:15961 localabstract:minicap_15961

跳过minicap安装？

ide黑窗
[09:52:24][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 480, in run
  File "app\plugins\device\android\util.py", line 471, in _get_android_frame
  File "airtest\core\android\minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 325, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 219, in get_stream
    stopped = next(gen)
  File "airtest\core\android\minicap.py", line 233, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "airtest\core\android\minicap.py", line 298, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout

[Warning] The current device is unplugged!

单独测试minicap报错
PID: 32661
INFO: Using projection 2340x1080@2340x1080/0
INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display
Vector<> have different types (this=0x7ff3238370, rhs=0x7ff3238490)
Aborted

**Comment by yimelia** [comment]
暂时可以先勾选 `use javacap`来替代minicap。
顺便问下这个MIUI版本是专门针对海外用户的版本么？

**Comment by HynemanKan** [comment]
不是，正常国行

**Comment by wuxinyao** [comment]
> 暂时可以先勾选 `use javacap`来替代minicap。
> 顺便问下这个MIUI版本是专门针对海外用户的版本么？

我小米9用use javacap可以了，感谢
