### ISSUE TITLE
华为20I无法连接设备

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#593]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)
![image](https://user-images.githubusercontent.com/43715934/68358711-48e3f100-0154-11ea-8090-a20f4fef0b58.png)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/43715934/68358730-57320d00-0154-11ea-9184-210f6734feb5.png)
![image](https://user-images.githubusercontent.com/43715934/68358746-5ef1b180-0154-11ea-8d4d-b3eec831f326.png)

================================================
华为的honor20i，还有另一个型号华为honor 8 lite也有同样问题。

1.输入法设置中，取消安全输入
2.开发者选项->监控ADB安装应用取消，打开仅充电模式下允许调试

都已经设置了，但是插上USB后还是无法检测到设备
是不是和华为自带的手机管家有关系？

其他手机，小米，vivo没有问题，都可以连接，但部分华为的手机不可以连接

**Comment by yimelia** [comment]
能否在IDE的设备列表里看到这台设备？看一下[文档](https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#adb) 这里，如果完全看不到你的设备，可能只是因为没有装驱动（但是一般来说装了华为手机管家之后都是能看到的）

如果能看到设备，状态为device，但是不能连接的话，麻烦贴一下命令行黑色窗口的报错信息出来看一下

**Comment by keltonxue** [comment]
使用adb devcies看不到设备，所有这个感觉不是aritest问题，一般的adb命令都看不到设备，但是我所有的设置都配置了，其他手机就没问题。
那这样的话是我手机驱动的问题吗，这种怎么解决呢，安装什么驱动？adb驱动？

**Comment by yimelia** [comment]
有些手机需要在连上USB的时候勾选MTP模式才能识别，可以参考一下[这个](https://jingyan.baidu.com/article/36d6ed1fa7084f1bcf4883ce.html)
还有一种情况是没有装华为手机的驱动，这一般是去华为官方网站上面下载驱动，现在估计都是下载华为官方提供的手机助手之后，能在手机助手上面连接的话就说明驱动安装上了（但是需要注意的是，最好不要同时开启任何手机助手和AirtestIDE/运行airtest脚本，否则可能会有冲突）

**Comment by keltonxue** [comment]
MTP我已经试过了，里面所有的选项都试了，还是没用，我按照驱动看看
