### ISSUE TITLE
在pycharm里面编写的时候keyevent("BACK")会出问题，但是在airtestIDE里可以正常运行

### ISSUE THREAD

**Issue by wucheng139** [AirtestProject/AirtestIDE#594]
**描述问题bug**
在pycharm里面编写的时候keyevent("BACK")会出问题，但是在airtestIDE里可以正常运行

```
Traceback (most recent call last):
  File "D:/下载/Chrome/薅羊毛-东方头条/toutiao/python/toutiao.py", line 421, in <module>
    keyevent("BACK")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\airtest\core\api.py", line 353, in keyevent
    G.DEVICE.keyevent(keyname, **kwargs)
AttributeError: 'NoneType' object has no attribute 'keyevent'
[11:17:07][DEBUG]<airtest.core.android.adb> C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 46f2412e0304 forward --remove tcp:13691
[11:17:07][DEBUG]<airtest.core.android.adb> C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 46f2412e0304 forward --remove tcp:17059
```

**相关截图**
![image](https://user-images.githubusercontent.com/45967120/68401508-d35c3d00-01b4-11ea-9de0-3609c054d31d.png)

**复现步骤**

**预期效果**
想实现按安卓机上的返回键的返回效果。在AirtestIDE里可以正常返回，但是在pycharm里编写的则报错

**python 版本:** `python3.7.4`

**airtest 版本:** `1.0.27`

**设备:**
 - 型号: [redmi note4x]
 - 系统: [miui11]

**其他相关环境信息**
(在pycharm上运行异常，在AirtestIDE上正常。)

**Comment by yimelia** [comment]
要先连上一台安卓设备才能运行后续代码，参考[教程](https://airtest.doc.io.netease.com/tutorial/2_Airtest_introduction/#_4)

**Comment by wucheng139** [comment]
> 要先连上一台安卓设备才能运行后续代码，参考[教程](https://airtest.doc.io.netease.com/tutorial/2_Airtest_introduction/#_4)

当然是用usb连上的呀

**Comment by yimelia** [comment]
我的意思是，**在airtest脚本代码里，告诉airtest应该连上某一台设备**，请查阅我提供的教程链接里的源码解释和说明，并且自行查阅connect_device的api文档

**Comment by wucheng139** [comment]
> 我的意思是，**在airtest脚本代码里，告诉airtest应该连上某一台设备**，请查阅我提供的教程链接里的源码解释和说明，并且自行查阅connect_device的api文档

是告诉了airtest连上某一设备的的，那些代码我都有。swipe和click都没问题。单单keyevent出了问题

**Comment by yimelia** [comment]
请贴出最小可复现问题的代码，里面最好包括一个点击操作+你的keyevent操作
请确认是否是每台手机都执行不了，还是某一台手机执行不了，并且执行不了的手机在连上IDE后也能执行

**Comment by wucheng139** [comment]
`#!/usr/bin/env python
# encoding: utf-8
from airtest.core.android import *

__author__ = "pascal"

from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco

device_id = '46f2412e0304'
device_1 = Android(device_id)

poco = AndroidUiautomationPoco(device_1, use_airtest_input=False, screenshot_each_action=False)
auto_setup(__file__)
poco(desc = '短信').click()
keyevent('BACK')`
在每台手机上都执行不了，并且执行不了的手机在连上AirtestIDE后同样的代码是能执行的

**Comment by wucheng139** [comment]
```
#!/usr/bin/env python
# encoding: utf-8
from airtest.core.android import *

__author__ = "pascal"

from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco

device_id = '46f2412e0304'
device_1 = Android(device_id)

poco = AndroidUiautomationPoco(device_1, use_airtest_input=False, screenshot_each_action=False)
auto_setup(__file__)
poco(desc = '短信').click()
keyevent('BACK')
```
在每台手机上都执行不了，并且执行不了的手机在连上AirtestIDE后同样的代码是能执行的

**Comment by yimelia** [comment]
```
device_id = '46f2412e0304'
device_1 = Android(device_id)
poco = AndroidUiautomationPoco(device_1
```
仅仅只是这样写的话，poco知道应该使用这台手机，但是airtest不知道，必须要告诉airtest当前连上了某台手机（这两个库是分开的，它们之间并不会共享这个数据）
具体如何连接请查阅文档，用connect_device/命令行传入--device参数/在auto_setup里面传入设备参数，这几个方法都可以

**Comment by primejava** [comment]
很明显这是兼容性的bug,问题没有解决 应该重新打开

**Comment by yimelia** [comment]
@primejava 
抱歉，真的不是兼容性问题，这是两个不同的python第三方库，不会共享数据。
请查阅文档以获得更多细节。
