### ISSUE TITLE
小米8无法连接airtest

### ISSUE THREAD

**Issue by 787786815** [AirtestProject/AirtestIDE#595]
手机设备信息:

手机型号: 小米 8
Android系统版本号: Android 9
MIUI 11.0.4

AirtestIDE版本号：1.2.2

**详细描述问题bug：**
在Airtest IDE中点击connect，无法连接手机。

**复现步骤：**
使用Airtest连接小米8.

**操作系统:** `Windows10 64bit`

**其他相关信息补充**
使用airtest1.2.1有相同报错。

**截屏**

![image](https://user-images.githubusercontent.com/10229030/68455702-f7f8f900-0236-11ea-8b83-2d120fa5312e.png)

![image](https://user-images.githubusercontent.com/10229030/68455781-270f6a80-0237-11ea-9c73-86069e609e48.png)

**Comment by yimelia** [comment]
可以考虑勾选use javacap来连接

**Comment by yimelia** [comment]
Duplicate of #592

**Comment by supercating** [comment]
> 可以考虑使用javacap来连接

在哪里勾选javacap 呢？

**Comment by yimelia** [comment]
@xiaoduola666 
可以在连接手机之前，点那个connect按钮旁边的下拉菜单，选择use javacap之后，再去点击connect按钮连接手机
