### ISSUE TITLE
卸载了pocoserivce和Yosemite后，再次连接没有提示安装

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#596]
之前在手机端安装了pocoserivce和Yosemite，但是用户无意删除了
再次连接手机的时候就好像没有提示安装了，有没有办法在删除了这2个软件后再次安装的方法，或者可以通过其他例如apk的方式安装吗

**Comment by EraChen233** [comment]
![image](https://user-images.githubusercontent.com/5961185/68458953-ff240500-023e-11ea-995e-1d1e5497ce3f.png)

在IDE的安装包里，这个路径有apk
可以用 adb命令安装  `adb install xxxx.apk`
