### ISSUE TITLE
卸载完pocoserivce和Yosemite后无法再次安装

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#597]
由于用户的误操作，卸载了pocoserivce和Yosemite，然后连接的时候就没有提示再次安装了
之前跳出过安装界面，但是选择了取消，后面就再次连接时候没有提示了

有没有方式可以按照上这个2个软件，或者有没有apk方式安装

**Comment by EraChen233** [comment]
Duplicate of #596

**Comment by keltonxue** [comment]
安装了RotationWatcher.apk之后并没有pocoservice这个图标安装好，然后poco仍然无法用啊
是不是RotationWatcher和pocoservice是2个东西啊，现在是没有了pocoservice

**Comment by yimelia** [comment]
在`poco\poco\drivers\android\lib`目录下的两个apk也要装
