### ISSUE TITLE
使用vivo手机无法调用手机虚拟键盘操作

### ISSUE THREAD

**Issue by Tinklibo** [AirtestProject/AirtestIDE#598]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
控件识别问题

**详细描述问题bug：**
使用vivo手机无法调用手机虚拟键盘操作，在搜素框中输入内容，点击键盘的搜索键，调用搜索键失败

**复现步骤：**

**python 版本:** `python3.7.2

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 
![image](https://user-images.githubusercontent.com/33279933/68463878-8460e700-024a-11ea-91b4-070bf8f93c8e.png)

**其他相关信息补充**
代码
poco("com.htd.supermanager:id/edittext_search").click()#点击搜索输入框

poco("com.htd.supermanager:id/edittext_search").set_text("")

poco("com.htd.supermanager:id/edittext_search").set_text("测测测测测")

sleep (1)

keyevent("KEYCODE_SEARCH")#调用键盘搜索按钮

**截屏**
![image](https://user-images.githubusercontent.com/33279933/68463724-3f3cb500-024a-11ea-90e0-1af1784b4a9d.png)

**Comment by yimelia** [comment]
参考文档：https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#_2
