### ISSUE TITLE
测试PC端网游时，重新打开浏览器大小和录制界面不一样大时，测试失败

### ISSUE THREAD

**Issue by echo528** [AirtestProject/AirtestIDE#599]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
用的是基于截图的测试，应该是切换浏览器后，比对找不到样本截图的图像了
**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/46102251/68469107-72844180-0254-11ea-8a73-2c19ffb91cd7.png)

**Comment by yimelia** [comment]
可以附上查找这张图的过程中的log出来看一下。

不过基本上主要原因是，分辨率发生很大的变化以后，导致图像识别成功率降低。具体的解决办法有几种，可以参考我们提供的这篇教程：
https://airtest.doc.io.netease.com/tutorial/9_Improved_compatibility/#3

我上面给出的链接是教程里提到的调整分辨率一节，可以根据你们游戏的具体规则来进行缩放策略调整。同时，也可以考虑调低这张图识别成功率的阈值来提升成功率，或者是最简单的办法：每一次打开游戏嵌入IDE之前，都保证游戏是基本上相同的分辨率就可以了。

**Comment by echo528** [comment]
好的，谢谢yimelia，按照你发的方法，现在识别成功率提高了很多

> 可以附上查找这张图的过程中的log出来看一下。
> 
> 不过基本上主要原因是，分辨率发生很大的变化以后，导致图像识别成功率降低。具体的解决办法有几种，可以参考我们提供的这篇教程：
> https://airtest.doc.io.netease.com/tutorial/9_Improved_compatibility/#3
> 
> 我上面给出的链接是教程里提到的调整分辨率一节，可以根据你们游戏的具体规则来进行缩放策略调整。同时，也可以考虑调低这张图识别成功率的阈值来提升成功率，或者是最简单的办法：每一次打开游戏嵌入IDE之前，都保证游戏是基本上相同的分辨率就可以了。
