### ISSUE TITLE
Typo "Save poject" should be "Save project"

### ISSUE THREAD

**Issue by nakhbari** [AirtestProject/AirtestIDE#6]
Typo "Save poject" should be "Save project"

<img width="163" alt="screen shot 2018-02-13 at 6 02 35 pm" src="https://user-images.githubusercontent.com/2754461/36184373-2b7dcf2c-10e8-11e8-9e09-f36ba783abc9.png">

**Comment by kristynakitz** [comment]
fixed in the latest version
