### ISSUE TITLE
三星S6 连接上设备后在设备面板的移动设备连接上不显示设备屏幕

### ISSUE THREAD

**Issue by limzhang** [AirtestProject/AirtestIDE#60]

**Comment by rockywhisper** [comment]
@limzhang  你好，这是我们提供的 [兼容性机型列表](https://note.youdao.com/share/?id=fd9002a15aff3bf0e77da1b7415a6920&type=note#/)

看到Galaxy S6在表内，请优先查看下IDE是否处于中文目录下，如果是，请移至英文目录下连接设备试试看。 :-)

**Comment by limzhang** [comment]
把IDE移到英文目录后显示屏幕了 谢谢
