### ISSUE TITLE
使用for循环报错

### ISSUE THREAD

**Issue by Tinklibo** [AirtestProject/AirtestIDE#601]
**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
使用for循环获取自节点，并打印，子节点共计11个，打印完成后报错

**复现步骤：**
![image](https://user-images.githubusercontent.com/33279933/68583720-e030a780-04b8-11ea-9d4e-6401366c8f3c.png)

**python 版本:** `python3.7

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)
![image](https://user-images.githubusercontent.com/33279933/68583752-f2aae100-04b8-11ea-9f79-41b9313067d5.png)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：
![image](https://user-images.githubusercontent.com/33279933/68583867-2f76d800-04b9-11ea-9c41-69776f7867c7.png)

**Comment by yimelia** [comment]
直接改成 for i in list1试试？

**Comment by Tinklibo** [comment]
改成for i in list1试试？也是报错
![image](https://user-images.githubusercontent.com/33279933/68723839-c98f6b00-05f4-11ea-9f84-764aa61d2571.png)

**Comment by Tinklibo** [comment]
for循环后断开链接了，但是我在后面再次加入device链接手机就没有报错了
![image](https://user-images.githubusercontent.com/33279933/68742217-923bb100-062a-11ea-9193-44cfee7d8ea5.png)
