### ISSUE TITLE
代码方式如何连接

### ISSUE THREAD

**Issue by donyu123** [AirtestProject/AirtestIDE#602]
![image](https://user-images.githubusercontent.com/50282691/68648639-d0b66a80-055b-11ea-8f74-e3bd297e5a80.png)

**Comment by yimelia** [comment]
请查阅文档 https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#2-windows

**Comment by primejava** [comment]
在pycharm里面使用代码连接,为什么没有在电脑上弹出手机界面的窗口

**Comment by yimelia** [comment]
@primejava 
在pycharm里用代码连当然不会有窗口。
想要看窗口请下载AirtestIDE。
