### ISSUE TITLE
macpro  catalina，打开app，docker出现两个图标

### ISSUE THREAD

**Issue by fantasy0410** [AirtestProject/AirtestIDE#603]
安装airtestIDE后，启动，docker栏出现两个图标
![image](https://user-images.githubusercontent.com/29134398/68741358-5dc6f580-0628-11ea-885d-ec20c8b1c4a1.png)

**Comment by yimelia** [comment]
是的，不是BUG，就是这样的。第二个图标是一个常驻的后台进程。
