### ISSUE TITLE
滑动操作过慢导致无法解锁手机

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#608]
需求是点亮屏幕，然后滑动解锁
在小米手机上使用是可以的，但是在一台华为手机上，有时候可以有时候不行，由于滑动操作过慢，然后屏幕又上锁了，导致后续无法操作

poco.device.wake()
poco.swipe([0.5,0.8],[0.5,0.2])

唤醒手机后，poco.swipe需要等很久才进行操作，以至于有时候屏幕又上锁了，还没有进行swipe操作
有没有办法可以解决这个问题？

**Comment by yimelia** [comment]
直接用swipe语句试一下，而不是poco.swipe
swipe([x1, y1], [x2, y2])
传入的是绝对坐标值

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/69203636-d590a500-0b7f-11ea-8836-7bbd3c0bf809.png)
这是我们测试的数据，用poco.swipe会比较慢一点

**Comment by CiaraCai** [comment]
> ![image](https://user-images.githubusercontent.com/6896468/69203636-d590a500-0b7f-11ea-8836-7bbd3c0bf809.png)
> 这是我们测试的数据，用poco.swipe会比较慢一点

我这边在使用AirtestIDE进行UI自动化的同时，进行性能数据采集。使用这方法后仍然滑动时发现滑动速度太慢而且不连续，无法进行FPS的测试。想请问一下有什么办法可以达到快速、连续滑动吗？ 谢谢。

**Comment by yimelia** [comment]
@CiaraCai 
连续滑动可以参考例子：https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#8

**Comment by CiaraCai** [comment]
好的 我尝试一下，谢谢～


 原始邮件 
发件人: yimelia<notifications@github.com>
收件人: AirtestProject/AirtestIDE<AirtestIDE@noreply.github.com>
抄送: Ciara<574944901@qq.com>; Mention<mention@noreply.github.com>
发送时间: 2020年3月23日(周一) 09:46
主题: Re: [AirtestProject/AirtestIDE] 滑动操作过慢导致无法解锁手机 (#608)


@CiaraCai
 连续滑动可以参考例子：https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#8
