### ISSUE TITLE
win10，分辨率：1920*1080，Airtest IED显示的很不清晰

### ISSUE THREAD

**Issue by yiran1990** [AirtestProject/AirtestIDE#609]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python2.7`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号:华为mate10，Android 9
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**

<img width="957" alt="AirtestIDE界面" src="https://user-images.githubusercontent.com/24261547/69122453-ce16c080-0ad9-11ea-89df-5a573e1161a9.png">

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/settings/1_ide_settings/#_4
