### ISSUE TITLE
AirtestIDE1.2.2的firebase无法打包

### ISSUE THREAD

**Issue by xiaozhu-hello** [AirtestProject/AirtestIDE#610]
bug及其步骤：

1、配置好jdk环境变量，并验证成功。
2、AirtestIDE-->Firebase
3、选择（1）Build  instrumentation Test Apk
直接跳转到到官方打包文档页面而导致无法正常打包。http://airtest.netease.com/docs/en/1_online_help/firebase_building.html
（2）选择Build Mutiple Script-->Choose  Script，然后点击确定，也是跳转到打包的官方说明文档页面而无法正常打包。
http://airtest.netease.com/docs/en/1_online_help/firebase_building.htm

python 版本:  python   3.7.2
操作系统:Windows10  64bit
JDK： 1.8.0_40
AirtestIDE版本号：1.2.2

**截图**
![Uploading image.png…]()

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/69127263-edffb180-0ae4-11ea-9a31-36e8d7710425.png)

如果反复跳转到文档页，说明环境没配置好

**Comment by xiaozhu-hello** [comment]
请问，JDK有版本要求吗
