### ISSUE TITLE
连接ip变动的手机

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#612]
脚本在服务器上运行，目前通过ip连接
但是由于功能测试需要，手机的代理会时常的变动，就是说ip会时常变动，是否还有其他方法可以稳定的连接上手机

这样在触发脚本运行时就可以不用去修改配置信息

**Comment by yimelia** [comment]
如果要问我们的话，回答将会是使用USB线。

**Comment by keltonxue** [comment]
脚本在服务器端运行的，usb识别不了
