### ISSUE TITLE
ubuntu16.04  安装完后，启动一直卡在login界面无法运行

### ISSUE THREAD

**Issue by lionpizzicato** [AirtestProject/AirtestIDE#615]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
安装完后，启动一直卡在login界面无法运行，
然后安装了openGL和openCV，
但是还是卡在login界面，
重装还是一样卡在login界面。

**复现步骤：**
sudo dpkg -i ./Downloads/AirtestIDE_2019-09-10_py3_ubuntu16-04.deb
运行 /usr/lib/AirtestIDE

**python 版本:** `Python 2.7.12`/`Python 3.5.2` 

**操作系统:** `ubuntu16.04 LTS`
图形：SVGA3D; build: RELEASE;  LLVM;
64 位

**手机设备信息:**
 - 手机型号:无
 - Android系统版本号:无
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：Version v1.2.2

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by lionpizzicato** [comment]
![iss](https://user-images.githubusercontent.com/39703544/69234687-b53a0800-0bca-11ea-8360-919eac673885.png)

**Comment by yimelia** [comment]
可以尝试参考一下windows版本里面的`兼容性模式启动.bat`里的脚本内容，即windows下面是：
```
set AIRTESTIDE_OPENGL=software
AirtestIDE.exe
```
在ubuntu下尝试改成下面内容，在命令行终端中运行：
```
export AIRTESTIDE_OPENGL=software
./usr/lib/AirtestIDE
```
看看是否有效

**Comment by lionpizzicato** [comment]
![iss2](https://user-images.githubusercontent.com/39703544/69236947-8eca9b80-0bcf-11ea-842d-2b375e0b1879.png)
一样，，

**Comment by yimelia** [comment]
可以试试把`AIRTESTIDE_OPENGL`的值设为`angle`，如果还是不行的话，可以考虑更新显卡驱动试试。
这个功能依赖于硬件，在部分虚拟机、显卡比较古老的机器上运行有问题，以及部分双显卡电脑在强制指定独显时也可以使用。
