### ISSUE TITLE
小米手机（mix2s）无法使用exists poco

### ISSUE THREAD

**Issue by bai1996** [AirtestProject/AirtestIDE#619]
### 小米平板（pad 4 plus）可以使用

**详细描述问题bug：**

- 安卓10无法在允许时无法使用
- 【usb调试，usb安装，usb调试（安全设置）】均已打开
- app可以打开，但是无法模拟点击用poco查找ui
- 同样的代码在安卓8.1（小米pad 4 plus）下可以使用，

**复现步骤：**

- 连接手机（安卓10）

- 使用一下方法`exists(..)，touch(..)，poco(..)`

- 就会报以下错

`
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'D:\\ProgramGreeFile\\AirtestIDE_2019-09-11_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']
`

- 按着路径查了没有此文件

![图片](https://user-images.githubusercontent.com/26263269/69473384-c5cac800-0dee-11ea-9d90-f20dbdff31c5.png)

**python 版本:** `python3.x`（IDE自带的环境）

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:小米mix2s
 - Android系统版本号: [Android 10]
 - MIUI版本号:[MIUI11 9.11.7 | 开发版]

- AirtestIDE版本号：1.2.2

**截屏**
![图片](https://user-images.githubusercontent.com/26263269/69473417-3d005c00-0def-11ea-9b83-d2c05f2d845b.png)
![图片](https://user-images.githubusercontent.com/26263269/69473418-3ffb4c80-0def-11ea-96af-1331e3c91981.png)
![图片](https://user-images.githubusercontent.com/26263269/69473420-41c51000-0def-11ea-98c5-6f897d43b378.png)

**Comment by yimelia** [comment]
Duplicate of https://github.com/AirtestProject/Airtest/issues/504
