### ISSUE TITLE
oppo R9S 连接AirtestIDE 点击 Connect 后报错

### ISSUE THREAD

**Issue by Contentment** [AirtestProject/AirtestIDE#62]
![image](https://user-images.githubusercontent.com/28555655/38499243-7ffd69a0-3c39-11e8-9738-2e02fcd39ba9.png)

**Comment by rockywhisper** [comment]
@Contentment  设备没有打开USB安装应用的权限吧，可以把AirtestIDE\airtest\core\android\static\apks里面的安装包手动安装进手机试试看？

**Comment by Contentment** [comment]
问题解决，多谢！R9S本身USB权限已经开启，只是还需要手机短信验证码，昨天没有注意。

**Comment by rockywhisper** [comment]
@Contentment  好的，我把issue关掉了哈。
