### ISSUE TITLE
mac 10.14.6版本 腾讯手游助手连接失败

### ISSUE THREAD

**Issue by hongbiangoal** [AirtestProject/AirtestIDE#621]
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
mac 10.14.6版本 腾讯手机助手连接失败
**复现步骤：**
mac 10.14.6版本 腾讯手机助手连接失败

**python 版本:** `python3.7`

**操作系统:** `mac 10.14.6`

**手机设备信息:**
 - 手机型号:
 - 腾讯手游助手1.0.6
可通过adb install安装软件

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.2

**截屏**
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 get-state
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 wait-for-device
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 shell getprop ro.build.version.sdk
Device:127.0.0.1:6555 updated <airtest.core.android.android.Android object at 0x129c9a438> -> <airtest.core.android.android.Android object at 0x12d294b38>
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 shell dumpsys display
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 shell dumpsys SurfaceFlinger ; echo ---$?---
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 shell getevent -p ; echo ---$?---
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
/Applications/AirtestIDE 2.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:6555 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/android_client.py", line 162, in loadConnectedPhones
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/android_phone.py", line 87, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/android_phone.py", line 192, in startFrameStream
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/snippet.py", line 104, in ready_func
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/rotation.py", line 91, in start
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/rotation.py", line 72, in _refresh_by_ow
ValueError: invalid literal for int() with base 10: b'java.io.UTFDataFormatException: bad byte at 17\r\n'

**Comment by yimelia** [comment]
请完整描述你遇到的问题

**Comment by hongbiangoal** [comment]
airtestide连接不上模拟器，打印的错误信息已附上

**Comment by hongbiangoal** [comment]
夜神的模拟器都可以正常连接的

**Comment by yimelia** [comment]
connect的下拉菜单勾选第二个选项，然后再进行连接。
