### ISSUE TITLE
text() 无法输入文字

### ISSUE THREAD

**Issue by egg10086** [AirtestProject/AirtestIDE#626]
**详细描述问题bug：**
text() 无法输入文字

**python 版本:** `python3.7`

**操作系统:** Windows10 64bit

- AirtestIDE版本号：v1.2.2

**截屏**

![image](https://user-images.githubusercontent.com/53043791/69705480-9e4a6700-1130-11ea-99f2-115da0bcfa99.png)

**Comment by dinghongyi** [comment]
有import其他库吗，比如Lackey？

**Comment by dinghongyi** [comment]
https://github.com/pywinauto/pywinauto/issues/419
https://github.com/glitchassassin/lackey/issues/65
应该是跟你import的其他库冲突了，可以试一下能不能换一些其他可用的库

**Comment by egg10086** [comment]
没有
from airtest.core.api import *
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
只用了这些

**Comment by dinghongyi** [comment]
可以试一下去掉其他的import单独只运行text('test')有没有问题。

**Comment by egg10086** [comment]
引入这个包就会报错from airtest_selenium.proxy import WebChrome

**Comment by dinghongyi** [comment]
https://airtest.doc.io.netease.com/IDEdocs/plugins/2_selenium/
可以试一下里面的send_keys()能不能达到你需要的效果？

**Comment by egg10086** [comment]
嗯，直接Chrome就可以。主要是用的airtestIDE自己生成的代码，有点懵
