### ISSUE TITLE
运行脚本使用Yosemite输入法

### ISSUE THREAD

**Issue by wqfff** [AirtestProject/AirtestIDE#627]
本人使用的是华为P20测试脚本无法拉起Yosemite输入法，Yosemite输入法弹不出来，就在屏幕底部显示一行Yosemite小字

**Comment by yimelia** [comment]
能看到小字就是成功了。

https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#airtesttext

![image](https://user-images.githubusercontent.com/6896468/69707195-3f86ec80-1134-11ea-9e4f-7333fb26f98e.png)

**Comment by wqfff** [comment]
我现在的场景是输入并搜索，正常搜索用的是输入法上的搜索按钮，换成Yosemite该如何用代码实现搜索呢？

**Comment by yimelia** [comment]
请点击上一个帖子里的文档链接，查看里面的内容，你的问题都在里面有解答。
