### ISSUE TITLE
AirTest IDE无法录制，脚本编辑窗黑屏

### ISSUE THREAD

**Issue by simeng1128** [AirtestProject/AirtestIDE#629]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述：
启动AirTest IDE后，登陆界面是黑屏，跳过登陆后，打开主界面，脚本编辑窗也是黑屏，没法录制，无任何内容显示。cmd下一直打印如下报错信息：
QQuickWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetSiblings

**复现步骤：**
每次启动必现

**python 版本:** `python3.6`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/9567378/69801709-d0cc9080-1212-11ea-8b32-b69ff17516ac.png)

**Comment by yimelia** [comment]
可以尝试双击文件夹里面的 `使用兼容性模式启动.bat` 来启动IDE

**Comment by simeng1128** [comment]
> 可以尝试双击文件夹里面的 `使用兼容性模式启动.bat` 来启动IDE

就用的兼容模式启动的，没什么用，一样的效果。issue的帖子我都翻了，相关的建议用了都没什么用

**Comment by yimelia** [comment]
能否发一下系统的配置和显卡型号？

**Comment by simeng1128** [comment]
系统配置：
![image](https://user-images.githubusercontent.com/9567378/69805108-f1004d80-121a-11ea-81bc-bd300ad8edb7.png)
显卡信息：
![image](https://user-images.githubusercontent.com/9567378/69805155-0d03ef00-121b-11ea-8d32-e9d8784d7e78.png)
