### ISSUE TITLE
AirtestIDE 能否考虑加一个单步调试脚本的功能，每次都要从头运行

### ISSUE THREAD

**Issue by Contentment** [AirtestProject/AirtestIDE#63]

**Comment by Meteorix** [comment]
你希望的是选中某一句运行吗？

**Comment by Meteorix** [comment]
好的，我们设计下这个功能

**Comment by Contentment** [comment]
预祝 Airtest Project  越来越强大！  前途不可限量

**Comment by rockywhisper** [comment]
@Contentment  Hi，我们本周的更新增加了脚本选中调试功能：
详见 [新版本更新文档](http://airtest.netease.com/changelog.html)

这个issue我先关掉啦~
