### ISSUE TITLE
关闭remote desktop时运行就识别不到元素

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#631]
1.脚本在服务器端运行，为WEB程序，通过remote desktop连接到服务器
2.现在发现只有在打开remote desktop时运行可以正常运行
3.但是如果我最小化remote desktop，或者关闭remote desktop时运行就识别不到元素
![error](https://user-images.githubusercontent.com/43715934/69839715-acfd5f00-1293-11ea-826c-e19c9eb22f1f.png)

**Comment by yimelia** [comment]
如果selenium不支持的话，我们就也不支持的。
