### ISSUE TITLE
remote desktop时运行就识别不到元素续

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#632]
请不要关闭这个问题，我发现不是selenium的问题，用selenium的语法是可以识别的，但是通过airtest截图的方式就在关闭remote desktop时无法识别

===========
1.脚本在服务器端运行，为WEB程序，通过remote desktop连接到服务器
2.现在发现只有在打开remote desktop时运行可以正常运行
3.但是如果我最小化remote desktop，或者关闭remote desktop时运行就识别不到元素
               --| 此时如果是通过selenium原生的语法时可以运行的例如通过xpath，没有任何问题
               --| 但是通过截图的方式，在关闭或者最小化remote desktop无法识别图片元素
==============
这是airtest的bug？

**Comment by keltonxue** [comment]
难道我需要开着remote desktop才可以运行脚本？这完全不合理，我们都是通过jenkins在晚上触发，服务器是开着的，只是现在没有在本地通过remote desktop连接上服务器，这样通过截图方式的脚本就没法运行

**Comment by yimelia** [comment]
Duplicate of #631 
selenium能识别到文本类的元素，airtest_selenium要用截图识别的话，必须要窗口非最小化，否则截不到图的。
按目前的实现方式，这个需求是确实没办法做到的。
