### ISSUE TITLE
新安装的airtest脚本无法运行

### ISSUE THREAD

**Issue by rleecn** [AirtestProject/AirtestIDE#633]
(**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件）

**详细描述问题bug：**
bug描述
执行脚本提示一个无关账户信息：
File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 78, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 257, in touch
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 78, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/cv.py", line 59, in loop_find
AttributeError: 'NoneType' object has no attribute 'snapshot'

**复现步骤：**
新安装应用，连接设备后，框选屏幕某区域设置touch动作，然后执行

**python 版本:** `python3.x`

**操作系统:** `MACOSX`

**手机设备信息:**
 - 手机型号:魅族p6p

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**截屏**

**Comment by yimelia** [comment]
这个提示的原因是没有连接设备，请先连上设备。
如果用的是命令行运行，请确保传入了类似`--device Android:///xxxx`的参数

**Comment by whf19911230** [comment]
我也遇到了这个问题，连接的夜神模拟器，确实连接上了设备，可以在IDE里操作模拟器。

**Comment by yimelia** [comment]
@whf19911230 
如果没有更进一步的信息，例如脚本内容、运行时的命令行、报错信息的话，我们没法帮忙定位问题。
目前只能猜测大概率是你用了.py脚本，然后没有在脚本里写上对应的Android连接字符串。
如果是模拟器的话，连接字符串里面还得写上?cap_method=JAVACAP
具体请查阅文档，如果是新手的话，建议先创建普通的.air脚本，熟悉了之后再自己写.py文件

**Comment by whf19911230** [comment]
复现步骤和这个问题的报告者是一模一样的，时直接在IDE里做的.air脚本。
脚本内容就是：
# -*- encoding=utf8 -*-
__author__ = "王鸿飞"

from airtest.core.api import *

auto_setup(__file__)
touch(Template(r"tpl1576554403995.png", record_pos=(-0.165, -0.013), resolution=(1600, 900)))

报错信息是：
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 58, in main
  File "app\widgets\code_runner\tracer.py", line 72, in run_pyfile
  File "E:\Program Files\airtest\AirtestIDE_2019-09-11_py3_win64\untitled.py", line 7, in <module>
    touch(Template(r"tpl1576554403995.png", record_pos=(-0.165, -0.013), resolution=(1600, 900)))
  File "airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "airtest\core\api.py", line 257, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "airtest\core\cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
AttributeError: 'NoneType' object has no attribute 'snapshot'
[Finished]

**Comment by yimelia** [comment]
@whf19911230 
贴一下你运行脚本时的命令行看看，怎么运行的？

**Comment by whf19911230** [comment]
@yimelia 
![BF9 PO200R1`W@KP9R)D89L](https://user-images.githubusercontent.com/42372552/70969932-12e14780-20d8-11ea-9473-b2e857e1e0ab.png)

**Comment by whf19911230** [comment]
@yimelia 
这是IDE运行时的截图
![7OUU_H{@34L%U1U (DXJLT7](https://user-images.githubusercontent.com/42372552/70970045-5d62c400-20d8-11ea-80f0-d0e9ec88c792.png)

**Comment by yimelia** [comment]
贴一下这个图里红框部分的内容：
![image](https://user-images.githubusercontent.com/6896468/70970285-eaa61880-20d8-11ea-99fc-0a7a6508d08a.png)
也就是说，点击运行脚本后，立刻出现的第一行log，它的内容是IDE用了什么命令行来运行你的脚本

**Comment by yimelia** [comment]
以及，你用了纯.py脚本来写的脚本，请参考文档：https://airtest.doc.io.netease.com/IDEdocs/record_script/create_script/#py 来编写，纯.py脚本需要自行定义各种参数的。

前面已经建议过了，如果是纯新手，建议先创建.air脚本，这样会简单一些，等熟悉了各项参数设定后再考虑换用.py脚本。

**Comment by whf19911230** [comment]
@yimelia 
"E:\Program Files\airtest\AirtestIDE_2019-09-11_py3_win64\AirtestIDE" pyrunner "E:\Program Files\airtest\AirtestIDE_2019-09-11_py3_win64\untitled.py" 
============================================================

[Start running..]

我并不知道我用的是.py脚本诶，我只是下载好IDE了就直接按照文档教程上的过程开始尝试一下toch操作了，那我去看看文档怎么创建.air脚本

**Comment by whf19911230** [comment]
@yimelia 
的确改成手动创建.air脚本就没有那个报错了，谢谢解答。
