### ISSUE TITLE
失败后继续执行的机制

### ISSUE THREAD

**Issue by keltonxue** [AirtestProject/AirtestIDE#636]
目前脚本在服务器执行，通过subprocess.Popen去运行airtest run命令来批量运行脚本

但是现在比如发生了异常，脚本就停止了，不会继续执行以后的脚本

airtest有没有机制去robotframework一样Run Keyword And Continue On Failure，就是失败后继续执行的机制

**Comment by keltonxue** [comment]
因为不可能在每一个地方都try。。。exception，是否有专门的机制来Continue On Failure

**Comment by keltonxue** [comment]
例如assert时候的报错

**Comment by yimelia** [comment]
目前暂时没有类似于Run Keyword And Continue On Failure的机制，不过实际上脚本调度是你自己写的，你可以直接在subprocess.Popen外层做一次try catch就行了吧，直接判定这个命令行运行失败之后就继续continue
