### ISSUE TITLE
pip install airtest报错，直接下载库，在本地安装也报错

### ISSUE THREAD

**Issue by weiyanfen** [AirtestProject/AirtestIDE#637]
**详细描述问题bug：**
pip install airtest报错，直接下载库，在本地安装也报错

**复现步骤：**
1、pip install airtest安装
2、下载airtest-1.1.1.tar.gz本地安装也报错

**python 版本:** `python3.7` 

**操作系统:** `Windows10 64bit`

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/9304677/70039017-24b0ee00-15f4-11ea-98c4-96fd4b864710.png)
![image](https://user-images.githubusercontent.com/9304677/70039044-31354680-15f4-11ea-9c26-0d92cdef97b8.png)
![image](https://user-images.githubusercontent.com/9304677/70039067-3abeae80-15f4-11ea-9866-955917463470.png)
![image](https://user-images.githubusercontent.com/9304677/70039078-41e5bc80-15f4-11ea-8da9-4cf9af387d56.png)

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#pip
