### ISSUE TITLE
MacOs 10.14.5 不支持版本V1.2.2

### ISSUE THREAD

**Issue by atomtong** [AirtestProject/AirtestIDE#639]
![image](https://user-images.githubusercontent.com/5134163/70219029-14794a00-177f-11ea-95df-f764bf6cbc3f.png)

(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**

* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
MacOs 10.14.5 不支持版本V1.2.2
**复现步骤：**
点击安装以后，并未启动成功

**python 版本:** `python3.x`
Python 2.7.12

**操作系统:** `MacOs 10.14.5`

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.2

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by EraChen233** [comment]
试一下用命令行启动
https://airtest.doc.io.netease.com/IDEdocs/getting_started/crash_abnormalProblem/#_1
![image](https://user-images.githubusercontent.com/5961185/70219352-a4b78f00-177f-11ea-8816-c225539a4796.png)

**Comment by atomtong** [comment]
使用命令行OK 但是会有一个登陆授权的引导。skipOK ，如果不skip 使用github账号并不能授权成功。
![image](https://user-images.githubusercontent.com/5134163/70220097-fad90200-1780-11ea-9c80-6d411758a66e.png)

**Comment by atomtong** [comment]
我估计非命令行也是这个流程卡主了

**Comment by yimelia** [comment]
非命令行和这个没有关系，这个已经到界面了。
登录失败的话可以考虑注册一个airlab的账户，用那个来登录。
mac下面第一次启动会闪退，第二次启动一般都是可以正常启动的，如果实在不行的话，可以考虑用命令行来启动。

**Comment by EraChen233** [comment]
好的，我们后面查一下
