### ISSUE TITLE
输入框的文本内容无法清除，使用text("")无法输入新的内容

### ISSUE THREAD

**Issue by MargaretLHP** [AirtestProject/AirtestIDE#64]
没有clear()函数可以清楚文本吗？
在未清除文本的情况下使用text("")输入新的内容不成功

**Comment by Contentment** [comment]
我也遇到了，我们的账号默认记住状态，使用Poco 不能删除被记住的账号

**Comment by yimelia** [comment]
可以用`keyevent`接口来清除文本，比如

```
for i in range(0, 10):
    keyevent("67")  # 67是删除
```

**Comment by adolli** [comment]
请问是andoird应用吗？

**Comment by NichoShi** [comment]
Android应用的EditText好像没有办法直接清空，也不能直接用set_text()

**Comment by adolli** [comment]
试试更新到最新的pocoui，sdk API 21以上的系统已经能直接通过 ui.set_text('')清空内容了。如果还不行的话那就是操作系统太深度定制了。
```
pip install -U pocoui
```

**Comment by rockywhisper** [comment]
@MargaretLHP  你好，请按照楼上同学的方法试验下，或者换一台设备试下。

issue暂时关闭了哈，如果遇到任何问题欢迎反馈 :-)
