### ISSUE TITLE
在airtest内部定义的函数，不知道为什么显示is not defined，已连接自己的python环境

### ISSUE THREAD

**Issue by kiritotonggu** [AirtestProject/AirtestIDE#642]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
Traceback (most recent call last):
  File "app\widgets\code_runner\run_manager.py", line 206, in my_exec
  File "<string>", line 3, in <module>
NameError: name 'image_2_text' is not defined
**复现步骤：**
def image_2_text(filename):
    image = Image.open(filename)
    string = pytesseract.image_to_string(image)
    try:
        strs = re.findall(r'\d{9}', string)
        if strs:
            print('唯一编号', strs[0])
            return strs[0]
    except Exception as e:
        raise e

def save_id(id_):
    print(id_)

snapshot(filename="F:\\anaconda\\envs\\py\\new.air\\picture\\ID6.jpg")
sleep(1)
id_ = image_2_text(filename="F:\\anaconda\\envs\\py\\new.air\\ID6.txt")
with open('C:\\Users\\think\\Desktop\\new.air\\num.txt', 'a+', encoding='utf-8') as f:
    f.write(id_)

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/44113463/70309245-093e2100-1848-11ea-9e16-1b0cb41b093f.png)

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/70309768-33441300-1849-11ea-9844-ef34c4eed655.png)
https://airtest.doc.io.netease.com/IDEdocs/record_script/create_script/#_2

**Comment by kiritotonggu** [comment]
但是原来的时候我是使用调用这个函数形式，然后是成功运行了脚本，但是后面不知道为什么又开始显示is not defined
