### ISSUE TITLE
使用 Airtest 导致 minicap 失效

### ISSUE THREAD

**Issue by Erimus-Koo** [AirtestProject/AirtestIDE#643]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

夜神模拟器，原本使用uiautomator2正常，用Airtest连接并调试之后，用回uiautomator2截屏全黑，很可能是minicap出问题了。

我看有好几个issue是小米的机器也发生了类似问题，会不会是Airtest初始化过程中造成的？希望能排查确认一下。

后续新建一个模拟，uiautomator2就可以正常可截图了。暂时不敢再连Airtest了。

**复现步骤：**

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号: 夜神模拟器
 - Android系统版本号: [5.1.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
1. 我们通常建议用模拟器时，选择`javacap`模式来连接，而不是用minicap，请参考[文档](https://airtest.doc.io.netease.com/IDEdocs/device_connection/3_emulator_connection/)
2. 你提的问题和小米的MIUI11以上版本黑屏的问题没有关联，小米的那个问题是因为系统底层接口发生改动，导致minicap无法截图。
3. 指令`adb shell rm /data/local/tmp/mini*`可以删除设备中缓存的minicap文件，删除后，安装airtest对设备的影响就还原了。Airtest用的minicap做了一点很小的修改，增加了一个参数，目前尚不清楚和uiautomator2使用的minicap区别有多大。你可以使用`use javacap`+`use adb orientation`两个选项来连接模拟器。

**Comment by Erimus-Koo** [comment]
反馈：第3点提到的指令有效，截图恢复正常。谢谢。
