### ISSUE TITLE
请问AirTest如何引用自定义py函数

### ISSUE THREAD

**Issue by micheryu** [AirtestProject/AirtestIDE#644]
我想引用这个文件夹下的一个py文件
![image](https://user-images.githubusercontent.com/46097932/70489450-c70e2b80-1b36-11ea-9bb5-5fe5339e3c1d.png)

**Comment by yimelia** [comment]
1. IDE是绿色版，更新版本时只需要重新下载zip包解压就能使用，因此最好不要在IDE目录里新建文件夹，否则很容易导致版本更新时还需要另外迁移你自己的文件。
2. 引用py文件和写普通py脚本没什么不同，`sys.path.append("父路径")` 然后 `from xx import xx`即可
