### ISSUE TITLE
小米6 无法连接airtest

### ISSUE THREAD

**Issue by yuchisu** [AirtestProject/AirtestIDE#645]
问题自查里已经测试过，RotationWatcher.apk也出现在开发者选项里。
手机之前是开发版，刚刚切换成稳定版，全新系统

打开IDE，连接手机usb，点击connect，然后一直黑屏，几秒后connection failed.

python 版本:python3.8.0

**操作系统:windows10

**手机设备信息:**
 - 手机型号:小米6
-miui11.0.2
 - Android系统版本号: Android 9

- AirtestIDE版本号：1.2.2

**截屏**
![Snipaste_2019-12-10_15-44-48](https://user-images.githubusercontent.com/15692084/70505875-069f3c80-1b64-11ea-81e5-ad994b88a34b.png)
![Snipaste_2019-12-10_15-36-10](https://user-images.githubusercontent.com/15692084/70505409-ed49c080-1b62-11ea-91e4-31d27f926fce.png)

**Comment by yimelia** [comment]
Duplicate of https://github.com/AirtestProject/Airtest/issues/633
