### ISSUE TITLE
自定义启动器不会标出当前正在运行的代码

### ISSUE THREAD

**Issue by nsyujian** [AirtestProject/AirtestIDE#646]
**详细描述问题bug：**
https://airtest.doc.io.netease.com/IDEdocs/airtest_framework/2_launcherpy/#id16
按照上面自定义启动器文档中的内容，添加了自定义启动器，按照文档中的描述应该会标出当前运行的代码，实际没有，重置自定义启动器后就会标出。

**复现步骤：**
安装上面文档中的内容设置自定义启动器就会重现

**python 版本:** `python3.7.4`

**操作系统:** `macOS 10.14.6`

**手机设备信息:**
 - 手机型号: 红米6
 - Android系统版本号: [e.g. Android 9.0]

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**Comment by yimelia** [comment]
是的，不会。
