### ISSUE TITLE
为啥下标 为3 会报错

### ISSUE THREAD

**Issue by donyu123** [AirtestProject/AirtestIDE#649]
![image](https://user-images.githubusercontent.com/50282691/70794729-4cb10600-1dd9-11ea-9fa2-520cc620b8de.png)
![image](https://user-images.githubusercontent.com/50282691/70794788-6fdbb580-1dd9-11ea-8a1a-6151734ccec1.png)

**Comment by yimelia** [comment]
自动生成的语句不一定靠谱，最好是人工改写一下，用更合理的方式去获取节点

**Comment by donyu123** [comment]
第二条语句是手写的   按道理说不应是下标【3】的语句能跑通吗    为什么是下标【1】   下标【1】的 元素不是当前这个"请输入密码"这个元素   而是他的父级          下标【3】是请输入密码  这个元素的位置

**Comment by yimelia** [comment]
不清楚，没有具体的软件和调试信息的话我也没办法debug，请自行解决。

**Comment by donyu123** [comment]
好的谢谢
