### ISSUE TITLE
导入AppRuntimeLogging后运行，提示无hunter_cli.device_output模块

### ISSUE THREAD

**Issue by Leonylzhao** [AirtestProject/AirtestIDE#65]
![default](https://user-images.githubusercontent.com/37897280/38669389-d1064e20-3e78-11e8-86a3-cc0b49c5bed3.png)

已经成功安装pocounit组件

**Comment by adolli** [comment]
请勿使用`pocounit.addons.hunter.runtime_logging.AppRuntimeLogging`，这个模块尚未外放。
