### ISSUE TITLE
使用命令行来生成报告时，--static_root 静态资源目录 参数不起作用

### ISSUE THREAD

**Issue by zwwtx** [AirtestProject/AirtestIDE#650]
**详细描述问题bug：**
bug描述
使用命令行来生成报告时，--static_root 静态资源目录 参数不起作用
**复现步骤：**
1、电脑连接夜神模拟器
2、用命令运行脚本后
3、生成运行结果报告的命令行：
airtest report D:/h_project\testcases\login_tc.air --log_root D:/h_project\test_reports\20191216111104_login_tc --lang zh --export D:/h_project\test_reports\20191216111104_login_tc --static_root http://192.168.10.222:901/cof/static --plugin poco.utils.airtest.report
4、如果去掉--static_root 静态资源目录 参数---该目录可以打开 其他人也可以打开，部署OK的，目录下面会有static文件夹，且报告格式正常
反之，无static文件夹，且报告格式异常
**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备信息:**
 - 夜神模拟器版本号:v_6.2.3.7
 - Android系统版本号:4.4.2

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**截屏**
![image](https://user-images.githubusercontent.com/44486186/70876959-9591d600-1ff6-11ea-8b24-5c192aebba53.png)
![image](https://user-images.githubusercontent.com/44486186/70877004-b9551c00-1ff6-11ea-99ed-3e6f694c27cf.png)
![image](https://user-images.githubusercontent.com/44486186/70877032-c8d46500-1ff6-11ea-8377-98df71a03727.png)

**Comment by EraChen233** [comment]
步骤能正常显示，js脚本加载正常并正确执行，说明生成报告的命令应该是没错的，static_root设置正确
![image](https://user-images.githubusercontent.com/5961185/70877135-3f716280-1ff7-11ea-9507-4d298e059c36.png)

看报告，问题出在样式文件没有加载成功
请自行检查样式文件，也就是css文件，地址是否正确，是否正常加载

**Comment by zwwtx** [comment]
你这个解答 我也知道 没实际解决问题 应付了事

**Comment by yimelia** [comment]
@zwwtx 
我们已经帮忙定位到了问题所在，但是没有你们的环境，不能去现场调试，也没有更多报错信息和详细信息，只能做到这么多了。
服务器和环境是你们的，我们只能保证我们提供的代码没有问题，具体使用过程中的问题需要你们根据实际情况来排查，我们没有办法上门帮忙调试，感谢理解。

如果你们感兴趣的话，可以了解一下我们的企业级私有化解决方案：https://airlab.163.com/b2b
这个是工程师可以上门服务的，并且提供了全套的软件+硬件方案，无需自行动手搭建，一站式解决你们的需求，有兴趣的话可以联系我们进行付费购买。

**Comment by zwwtx** [comment]
--static_root 静态资源目录 参数---该目录可以打开 其他人也可以打开，部署OK的
