### ISSUE TITLE
运行web测试报错

### ISSUE THREAD

**Issue by 1111111Aa** [AirtestProject/AirtestIDE#651]
**复现步骤：**
命令行python 运行web测试相关case

**python 版本:** `python3.7`

**操作系统:** `mac os`

谷歌浏览器

do not connect device
save log in '/Users/lihong/IdeaProjects/autotest-airtest-web/log/demo'
this is jpg path: /Users/lihong/IdeaProjects/autotest-airtest-web/log/demo/1576478291.jpg
/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py:1031: UserWarning: name used for saved screenshot does not match file type. It should end with a `.png` extension
  "type. It should end with a `.png` extension", UserWarning)
this is jpg path: /Users/lihong/IdeaProjects/autotest-airtest-web/log/demo/1576478291.jpg
----------------------------------------------------------------------
Ran 1 test in 5.909s

**Comment by yimelia** [comment]
UserWarning: name used for saved screenshot does not match file type. It should end with a .png extension
"type. It should end with a .png extension", UserWarning)

**Comment by 1111111Aa** [comment]
咋这么快就关了。。。 我看得懂字面意思，我是想问怎么解决。。。这个报错不影响case执行，但是影响看报告，生成的报告里没有截图。

**Comment by 1111111Aa** [comment]
我试了直接把jpg改完png，报告里也没显示出截图

**Comment by yimelia** [comment]
问题没有解释清楚，我们并不清楚你到底遇到的是什么问题，只能推测为你不明白这段报错的内容是什么意思。
airtest报告中，只支持airtest相关语句的截图，selenium原本的语句我们是不清楚的。
具体请参考 #652 中的回复。
