### ISSUE TITLE
python 命令行运行web测试case，生成的报告里没有截图的显示

### ISSUE THREAD

**Issue by 1111111Aa** [AirtestProject/AirtestIDE#652]
执行命令过程如下：
python -m airtest run air_case/demo.air --log log/demo
do not connect device
save log in 'log/demo'
this is jpg path: log/demo/1576480063.jpg
/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py:1031: UserWarning: name used for saved screenshot does not match file type. It should end with a `.png` extension
  "type. It should end with a `.png` extension", UserWarning)
this is jpg path: log/demo/1576480063.jpg
----------------------------------------------------------------------
Ran 1 test in 7.184s

OK

airtest report air_case/demo.air --log_root log/demo --outfile log/demo/log.html --lang zh
log/demo/log.html

**Comment by yimelia** [comment]
selenium和airtest_selenium是不一样的。
不知道你的脚本里内容是什么，具体的报告生成到底是什么样，缺失的是什么截图。
但是，airtest应该是只对新增加的几个截图selenium接口能够显示在报告中，原生的selenium的语句是不会整合进来的。

**Comment by yimelia** [comment]
Duplicate of #651

**Comment by 1111111Aa** [comment]
> selenium和airtest_selenium是不一样的。
> 不知道你的脚本里内容是什么，具体的报告生成到底是什么样，缺失的是什么截图。
> 但是，airtest应该是只对新增加的几个截图selenium接口能够显示在报告中，原生的selenium的语句是不会整合进来的。

就是跑个简单的case，熟悉下命令行执行case而已。 case如下：已经是最基础的case了。在airtestide里执行，步骤里有截图。 用python命令行执行一个截图都没有。
# -*- encoding=utf8 -*-
__author__ = "autotest"

from airtest.core.api import *

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from airtest_selenium.proxy import WebChrome
driver = WebChrome()
driver.implicitly_wait(20)


auto_setup(__file__)
driver.get("http://baidu.com")
driver.find_element_by_id("kw")
driver.find_element_by_id("kw").send_keys("明天天气",Keys.ENTER)
driver.close()

**Comment by yimelia** [comment]
@1111111Aa 
这样描述就知道你的情况了，可以参考文档的[这里](https://airtest.doc.io.netease.com/IDEdocs/about_report/Report_guidelines/#selenium)，在生成报告时加上参数就行了
