### ISSUE TITLE
小米8手机连接后点connect不展示手机界面，报ADB指令执行失败

### ISSUE THREAD

**Issue by sillybug** [AirtestProject/AirtestIDE#656]
1、ADB指令执行失败，可能需要修改部分手机设置才能使用，请访问[帮助文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html)查看如何设置。

2、链接手机后，手机出现问题，输入键盘消失了。

**Comment by yimelia** [comment]
请按照模板来提交问题，否则我们很难定位具体到底是什么问题导致的。
如果是MIUI11的话，暂时需要勾选use javacap才能看到屏幕画面。
如果是MIUI11且版本是android10的话，还需要勾选use adb touch，并且目前IDE在横屏下的adb touch还有点问题，需要等待下一个版本修复。

如果不是MIUI11，请参考文档中的小米手机的设置进行设置，https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4
