### ISSUE TITLE
opencv-contrib-python版本冲突

### ISSUE THREAD

**Issue by zwwtx** [AirtestProject/AirtestIDE#657]
**详细描述问题bug：**
bug描述
opencv-contrib-python版本冲突
**复现步骤：**
1、python3.7安装了最新版opencv-contrib-python
报错
![image](https://user-images.githubusercontent.com/44486186/71226715-ce43ef00-2317-11ea-97d2-8fbd5b2e691d.png)
2、
pip uninstall opencv-contrib-python
pip install opencv-contrib-python==3.4.2.17以及3.4.2.16
都会报错ImportError: DLL load failed: 找不到指定的模块。
![image](https://user-images.githubusercontent.com/44486186/71226759-f92e4300-2317-11ea-8ab8-abb7e0b07200.png)
![image](https://user-images.githubusercontent.com/44486186/71226777-0fd49a00-2318-11ea-8f9a-c26095252904.png)

![image](https://user-images.githubusercontent.com/44486186/71226771-09462280-2318-11ea-9a60-ee974d106918.png)
**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**Comment by yimelia** [comment]
python低于3.7才能安装opencv-contrib-python==3.2.0.7，你的是3.7版本，是装不了的，文档里写得很清楚了：
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#airtest

可以考虑看一下那个DLL文件缺失的问题。
