### ISSUE TITLE
web测试，浏览器滑动条 滑动不到底部

### ISSUE THREAD

**Issue by 1111111Aa** [AirtestProject/AirtestIDE#658]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
airtest selenium 不能拖动右侧滑动框到底部

**复现步骤：**

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`
 AirtestIDE版本号：1.2
滑动操作代码如下
driver.execute_script("window.scrollTo(0, document.body.scrollHeight)");

**Comment by yimelia** [comment]
可以看一下纯selenium是否也有这个问题？
我们是内嵌了一个selenium，如果有问题的话，可能需要报到selenium那边去

**Comment by tianyihuhu** [comment]
我也遇到同样的问题，在Airtest中添加了这段代码
js = "window.scrollTo(0, document.body.scrollHeight)" 
driver.execute_script(js)
页面没有滚到到底，然后直接使用pycharm编译器，同样引用对应的包，加入这两行代码，运行时界面就滚动到底了。
两个对比时，引用from airtest_selenium.proxy import WebChrome都是这个的driver对象，但是效果airtest就没有达到。
请您和您的团队帮忙看一下，谢谢您！
python版本是3.9.8，selenium版本为3.9.0
