### ISSUE TITLE
关于AirtestCase变量作用域问题，详见bug描述

### ISSUE THREAD

**Issue by shijianzhihu** [AirtestProject/AirtestIDE#659]
**详细描述问题bug：**
bug描述
1. 我自定义了启动器，并在setUp()方法中将公共变量加入到`self.scope`中，代码段如下：
```
class McCustomAirtestCase(AirtestCase):
    def setUp(self):
        self.scope["TIMEOUT"] = 5 
        super(McCustomAirtestCase, self).setUp()

if __name__ == '__main__':
    ap = runner_parser()
    args = ap.parse_args()
    run_script(args, McCustomAirtestCase)
````
2. 在实际运行单个脚本时，确实在脚本代码中可以直接使用`TIMEOUT`变量;
3. 但是如果我的脚本中又使用using()方法引入了一个在其他脚本中定义的方法（此方法也使用了TIMEOUT），此时再运行脚本就会提示TIMEOUT未定义，以下是代码：
```
print("TIMEOUT=",TIMEOUT)   # 这里可以正常打印结果

using('common.air')
from common import ptfTimeout

ptfTimeout()        # 这里就会报错 name 'TIMEOUT' is not defined
```
ptfTimeout定义如下：
```
def ptfTimeout():
    print(TIMEOUT)
```
AirtestIDE报错截图如下：
![](https://user-images.githubusercontent.com/26112446/71248662-619c1500-2356-11ea-85a7-1735af705482.png)

common.air中我定义了众多公共的方法，自定义启动器用于支持批量运行脚本以及设置一些全局属性值。
我该怎么做，才能不出现以上报错的情况呢？ 求翻牌求解答，Thanks！！！

**python 版本:** `python3.7.0`
**airtest 版本:** `1.1.0`
**操作系统:** `Windows7 64bit`

**Comment by yimelia** [comment]
这个问题可能会比较麻烦，AirtestCase那个启动器在脚本结构很复杂的情况下其实不太好用，我们一直想摒弃掉，所以后来才会重新添加了一个纯py脚本的运行方式（参考IDE创建脚本时的.py脚本生成的模板）。

我看了一下，scope的内容来自于globals()，`cls.scope = copy(globals())`，所以你可以考虑试一下在运行你的脚本前，先import common里的内容，把东西加载到你的globals()之后，再更新一下scope，确保在运行到using脚本的时候，里面能够读取到那个变量。
或者是考虑修改成global全局变量的写法，也许也可以。
我没有具体的脚本，也没试着运行过，这个只能作为参考，如果能够解决的话欢迎分享一下代码~
