### ISSUE TITLE
sony xz手机不能自动横屏（见图）

### ISSUE THREAD

**Issue by KingBob1250** [AirtestProject/AirtestIDE#66]
环境：
pc：win10 64bit
手机：型号：索尼 Xperia XZ（F8332），安卓版本：8.0.0

![img20180413_103053](https://user-images.githubusercontent.com/38338682/38713816-ce52e4a8-3f05-11e8-8b1b-f0e3fd65b939.png)

**Comment by rockywhisper** [comment]
@KingBob1250  好的，我们验证下问题，尽快解决。

**Comment by rockywhisper** [comment]
@KingBob1250 
Hi，经过对该手机进行检查后发现，初次连接时显示正常。只有在手机屏幕旋向发生变化时，画面显示会错位。

**问题原因：**
 - 经检查，这台手机上的RotationWatcher.apk安装异常（未知原因）

**解决方法：**
 - 手动删除该apk后，再次连接即正常，再未重现。


如果有后续问题随时联系，这个issue先关闭了哈~
