### ISSUE TITLE
小米8连接失败，报minicap server setup timeout

### ISSUE THREAD

**Issue by smilexiaotao** [AirtestProject/AirtestIDE#660]
这些配置都已经打开，但点击“connect”报下面的错误
![image](https://user-images.githubusercontent.com/42379528/71264336-d71bdb80-237e-11ea-8f0c-b982113475af.png)
![image](https://user-images.githubusercontent.com/42379528/71264363-ea2eab80-237e-11ea-9e24-b139c7a47cf6.png)

**Comment by yimelia** [comment]
Duplicate of #656 

请按照模板来提交问题，否则我们很难定位具体到底是什么问题导致的。
如果是MIUI11的话，暂时需要勾选use javacap才能看到屏幕画面。
如果是MIUI11且版本是android10的话，还需要勾选use adb touch，并且目前IDE在横屏下的adb touch还有点问题，需要等待下一个版本修复。

如果不是MIUI11，请参考文档中的小米手机的设置进行设置，https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4
