### ISSUE TITLE
airtestIDE  在 win7 上打开，脚本编辑区和log查看窗黑屏

### ISSUE THREAD

**Issue by 1111111Aa** [AirtestProject/AirtestIDE#662]
**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`
![11_00_30__12_26_2019](https://user-images.githubusercontent.com/57934161/71455260-29ba2500-27cf-11ea-882b-fbdd860a05b2.jpg)

**Comment by yimelia** [comment]
在部分机器上可能由于显卡兼容性问题，导致无法正确启动，或脚本编辑窗口无法编辑，可以双击目录下的兼容模式启动.bat文件来启动

**Comment by 1111111Aa** [comment]
> 在部分机器上可能由于显卡兼容性问题，导致无法正确启动，或脚本编辑窗口无法编辑，可以双击目录下的兼容模式启动.bat文件来启动

双击 .bat 启动后也是这样

**Comment by yimelia** [comment]
这个编辑窗口需要用到OPENGL，所以在一些比较老的旧机器上、部分虚拟机上、以及一些远程的云桌面上可能会有问题。
建议你编写脚本的时候可以在本地电脑，远程只做脚本运行。

右键用记事本可以打开IDE目录下的那个`兼容模式运行.bat`文件，可以看到里面的内容是这样的：
```
rem set AIRTESTIDE_OPENGL=angle
set AIRTESTIDE_OPENGL=software
AirtestIDE.exe
```
其中，可以考虑把第二行的 `set AIRTESTIDE_OPENGL=software`，改成 `set AIRTESTIDE_OPENGL=angle`，然后再运行试试，但是可能依然不能使用。

**Comment by 1111111Aa** [comment]
> 这个编辑窗口需要用到OPENGL，所以在一些比较老的旧机器上、部分虚拟机上、以及一些远程的云桌面上可能会有问题。
> 建议你编写脚本的时候可以在本地电脑，远程只做脚本运行。
> 
> 右键用记事本可以打开IDE目录下的那个`兼容模式运行.bat`文件，可以看到里面的内容是这样的：
> 
> ```
> rem set AIRTESTIDE_OPENGL=angle
> set AIRTESTIDE_OPENGL=software
> AirtestIDE.exe
> ```
> 
> 其中，可以考虑把第二行的 `set AIRTESTIDE_OPENGL=software`，改成 `set AIRTESTIDE_OPENGL=angle`，然后再运行试试，但是可能依然不能使用。

好的，了解了。谢谢
