### ISSUE TITLE
设计问题?

### ISSUE THREAD

**Issue by jekoie** [AirtestProject/AirtestIDE#664]
- 登陆界面提示不支持的web browser:
![][1]
  - PyQt5 QWebEngine是支持最新Chrome内核的啊, 用的是旧的?
  - 那个问号有什么用?  除掉吧( Qt::WindowFlags~Qt::WindowContextHelpButtonHint )

- 黑色背景后台框:
  - 还不如搞个窗口, 让用户自已选择是否显示日志
- 界面写的跟kivy似的, 界面没有Mac OS 类似的美感
- 窗口没有记忆功能(QSettings)
<sub>估记还有其它问题, 刚下载看看的.<sub>  

[1]: https://user-images.githubusercontent.com/6836400/71495424-9e04cf00-2888-11ea-8907-018dc7575aa5.png

**Comment by yimelia** [comment]
1. 我们不是用的最新版PyQt5
2. 问号的按钮感谢提出，后续会进行删除
3. 我们目前就是希望强制显示日志出来，方便排查问题
4. 界面设计问题我无法进行回应，对于美的感知每个人的观念不同，我们不能说我们的界面好看，但是在目前现有的人手和开发条件下我们只能尽力做到当前这样
5. 我们对于窗口布局有部分记忆功能，但是窗口大小没有。

**Comment by jekoie** [comment]
大众对网易要求比较高嘛, 希望这个平台能统一市场上混乱的自动化框架.
