### ISSUE TITLE
启动时报错，如何解决

### ISSUE THREAD

**Issue by wyuan652197552** [AirtestProject/AirtestIDE#666]
![avatar](http://qr61.cn/ocQwSG/qRcs8wj)

**Comment by yimelia** [comment]
图片不能显示，看不到具体是什么情况。
在部分机器上可能由于显卡兼容性问题，导致无法正确启动，或脚本编辑窗口无法编辑，可以双击目录下的兼容模式启动.bat文件来启动。
如果不是这个原因，请参考文档：https://airtest.doc.io.netease.com/IDEdocs/getting_started/crash_abnormalProblem/
