### ISSUE TITLE
Cannot build instrumentation apk from IDE, stuck at 15%- mac os

### ISSUE THREAD

**Issue by sushantoghosh** [AirtestProject/AirtestIDE#667]
Remove any following parts if does not have details about

**Describe the bug**
IDE Stuck at 15% while building firebase instrumentation apk
<img width="1680" alt="Screenshot 2019-12-27 at 12 53 57 PM" src="https://user-images.githubusercontent.com/20637464/71507001-082d6c00-28a9-11ea-9f9e-1182614aec4a.png">

**Screenshots**
A **screenshot** is strongly recommended. Please include both the AirtestIDE window and the **black console window**.

**To Reproduce**
1. Go to 'Firebase'
2. Click on 'Build Instrumentation test apk'

**Expected behaviour**
Instrumentation apk build, next steps after 100% completion was expected

**AirtestIDE version:** `1.2.2`

**Platform:** `Mac OS catalina`

**Smartphone (please complete the following information):**
N/A
**Additional context**
N/A

**Comment by yimelia** [comment]
hi @sushantoghosh 
Java is required to build Firebase plug-in one-click package, so you need to install JDK first (only JDK). 
https://docs.oracle.com/javase/10/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-F575EB4A-70D3-4AB4-A20E-DBE95171AB5F

**Comment by sushantoghosh** [comment]
hi @yimelia , 
I have jdk installed , 

[~]$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

let me know do I have to have the release signed apk in the .air folder before clicking the 'Build Instrumentation test apk' ?

**Comment by sushantoghosh** [comment]
this issue got fixed, after I copied the release apk in the .air folder. This was not mentioned anywhere in the documentation
