### ISSUE TITLE
使用软件会出现闪退的异常

### ISSUE THREAD

**Issue by Jiro1993** [AirtestProject/AirtestIDE#67]
打开程序后，点击windows窗口连接的“选定窗口”，程序就闪退，提示：No such file or directory;
我下载文件后是直接解压的，没有动过里面的文件，应该不会有丢失的情况。

**Comment by Jiro1993** [comment]
![qq 20180413103924](https://user-images.githubusercontent.com/38338846/38714587-8fc6d90c-3f09-11e8-8cef-a71d5f4225c2.png)
![qq 20180413104308](https://user-images.githubusercontent.com/38338846/38714595-92d05fc4-3f09-11e8-86a7-a24fe4743840.png)

**Comment by rockywhisper** [comment]
@Jiro1993  Hi，下午 [官网](http://airtest.netease.com) 上发布了新版本，问题已解决。
