### ISSUE TITLE
app横屏展示, IDE中没有横屏, 同时获取到的坐标和点击的坐标不符

### ISSUE THREAD

**Issue by duhongjun** [AirtestProject/AirtestIDE#671]
**详细描述问题bug：**
APP全屏(横屏), IDE中没有横过来, touch截图功能无法正常使用, 总是提示不在范围内, 同时通过wait获取到的图片坐标, 点击时位置不对

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `mac  osx 10.15.2`

**手机设备信息:**
 - 手机型号: iphone xs max 
 - iphone系统版本号: 10.12

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by EraChen233** [comment]
试一下更新最新的 AirtestIDE 和 iOS-Tagent

**Comment by duhongjun** [comment]
IDE版本1.2.2
ios-Tagent是前天clone的master分支
xcode版本11.3

你说的那两个我应该都是最新的

**Comment by duhongjun** [comment]
iOS | Xcode
-- | --
≥ 13 | 11.x
10.x-12.x | 10.x
≥ 9.3 | ≥ 9.3


我更新下ios 13试试

**Comment by duhongjun** [comment]
更新后 一切正常
