### ISSUE TITLE
IOS设备横屏下, touch截图区域不正确

### ISSUE THREAD

**Issue by duhongjun** [AirtestProject/AirtestIDE#676]
IOS设备横屏下, touch截图区域不正确, 如图
**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `mac os 10.15.2`

**手机设备信息:**
 - 手机型号: iphone xs max
 - Iphone系统版本号: [10.13]
 - xcode版本: 11.3

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**截屏**
录了个gif
![Dec-31-2019 17-13-12](https://user-images.githubusercontent.com/18900868/71616361-e148a000-2bf0-11ea-8e4f-2b1fedca7db7.gif)

可以看到, 当截取屏幕右侧时, 提示不在截图范围, 在截图范围内的, 截出来的图位置不对

**Comment by MJie46** [comment]
同样的问题

**Comment by EraChen233** [comment]
问题已复现，我们会尽快修复
ide 的 touch 截图功能，就是执行截图，然后把截图的文件名插入到脚本中。
现在如果要使用这个功能，可以自行截图，截图文件放到脚本文件夹中，然后在脚本中手动写入截图文件名。

**Comment by chanchifan** [comment]
这个问题又出现了，IDE 1.2.5
