### ISSUE TITLE
命令行运行出现：minicap.so': No such file or directory

### ISSUE THREAD

**Issue by yyuan2019** [AirtestProject/AirtestIDE#677]
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'D:\\Python\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']
cmd下运行文件出现的错误，是什么原因
之前曾经都调试好了的

**Comment by yimelia** [comment]
Duplicate of #504

Android10问题请参考 AirtestProject/Airtest#618

**Comment by yyuan2019** [comment]
谢谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 下午2:08
收件人:&nbsp;"AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;;
抄送:&nbsp;"羽沫"<935232710@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/AirtestIDE] 命令行运行出现：minicap.so': No such file or directory (#677)




Duplicate of #504
 
Android10问题请参考 AirtestProject/Airtest#618

**Comment by yyuan2019** [comment]
是安卓版本升级产生的问题
有什么办法解决吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yimelia"<notifications@github.com&gt;; 
发送时间: 2020年1月2日(星期四) 下午2:08
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;; 
抄送: "羽沫"<935232710@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AirtestProject/AirtestIDE] 命令行运行出现：minicap.so&#39;: No such file or directory (#677)




Duplicate of #504
 
Android10问题请参考 AirtestProject/Airtest#618

**Comment by yimelia** [comment]
一种是可以等待更新，我们最近将会更新版本来支持
一种是直接close airtest的dev分支下来试用当前的开发分支

**Comment by yyuan2019** [comment]
那我等候更新吧！
奇怪的是：我找个Android 9 的手机，结果在airtestIDE运行，代码里的poco(text=&nbsp; 都识别不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 下午2:19
收件人:&nbsp;"AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;;
抄送:&nbsp;"羽沫"<935232710@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/AirtestIDE] 命令行运行出现：minicap.so': No such file or directory (#677)




一种是可以等待更新，我们最近将会更新版本来支持
 一种是直接close airtest的dev分支下来试用当前的开发分支

**Comment by yyuan2019** [comment]
close airtest的dev分支
如何操作？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 下午2:19
收件人:&nbsp;"AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;;
抄送:&nbsp;"羽沫"<935232710@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/AirtestIDE] 命令行运行出现：minicap.so': No such file or directory (#677)




一种是可以等待更新，我们最近将会更新版本来支持
 一种是直接close airtest的dev分支下来试用当前的开发分支
