### ISSUE TITLE
小米6 Android版本7.1.1无法连接

### ISSUE THREAD

**Issue by fiona66** [AirtestProject/AirtestIDE#68]
1.小米6 Android版本7.1.1无法连接
2.MAC应用内Connect报错“Failed to execute ADB commands, please read [Docs](http://airtest.netease.com/docs/docs_AirtestIDE-en_US/3_faq/faq.html) for more help. Bug feedback [Click here](https://github.com/AirtestProject/AirtestIDE/issues)”
实际跳转：http://airtest.netease.com/docs/docs_AirtestIDE-en_US/3_faq/faq.html)%20for%20more%20help.%20Bug%20feedback%20%5BClick%20here%5D(https://github.com/AirtestProject/AirtestIDE/issues  地址404

**Comment by rockywhisper** [comment]
@fiona66  你好。

1、小米设备[需要打开一些开关](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id7)，请排查下“开发者选项”的相关设置。

2、Mac跳转问题我们后续修复下。

**Comment by rockywhisper** [comment]
@fiona66  Hi，第二个问题的修复下个版本0.0.14将会放出.

目前在IDE中文模式下跳转是正常的，语言模式切换： 
 - 中文版：下拉菜单  ``选项-语言``
 - 英文版： 下拉菜单  ``Options-Languages``

这个issues我先关闭了哈~
