### ISSUE TITLE
兼容模式启动，直接闪退,WIN10、DX12

### ISSUE THREAD

**Issue by xiangzirui** [AirtestProject/AirtestIDE#681]
**详细描述问题bug：**
bug描述

**复现步骤：**
兼容模式管理员角色启动，命令行直接闪退

**python 版本:**
 python3.6
**操作系统:** 
Windows10 64bit`

**其他相关信息补充**
在windows10上异常
- AirtestIDE版本号：
2019-09-11
**截屏**
![image](https://user-images.githubusercontent.com/49627024/71799953-af708700-3091-11ea-94b3-2f1ee45fe6b1.png)

**Comment by yimelia** [comment]
尝试先在IDE目录里面，shitf+鼠标右键来启动命令行，然后在命令行里面手工输入`CompatibilityMode.bat`，在闪退之后能够在命令行里留下log，把log发出来看看

**Comment by xiangzirui** [comment]
> 尝试先在IDE目录里面，shitf+鼠标右键来启动命令行，然后在命令行里面手工输入`CompatibilityMode.bat`，在闪退之后能够在命令行里留下log，把log发出来看看

仅出现：info:filter not set , use raven.filter.fullPassFilter instead  的信息

**Comment by yimelia** [comment]
截图出来看一下？

**Comment by xiangzirui** [comment]
> 截图出来看一下？

![image](https://user-images.githubusercontent.com/49627024/71800588-7afdca80-3093-11ea-8293-710f215c4623.png)

**Comment by yimelia** [comment]
估计是因为另外开启了一个窗口，log都在另外那个窗口里面，导致看不到了，可以直接在你的命令行窗口里面输这两行，看看在闪退后有什么新的内容：
![image](https://user-images.githubusercontent.com/6896468/71800820-142ce100-3094-11ea-8be8-1e56e24d09ff.png)
只输这两行就可以了

**Comment by xiangzirui** [comment]
> 估计是因为另外开启了一个窗口，log都在另外那个窗口里面，导致看不到了，可以直接在你的命令行窗口里面输这两行，看看在闪退后有什么新的内容：
> ![image](https://user-images.githubusercontent.com/6896468/71800820-142ce100-3094-11ea-8be8-1e56e24d09ff.png)
> 只输这两行就可以了

只输入这两行的错误信息与上面相同

**Comment by xiangzirui** [comment]
> 估计是因为另外开启了一个窗口，log都在另外那个窗口里面，导致看不到了，可以直接在你的命令行窗口里面输这两行，看看在闪退后有什么新的内容：
> ![image](https://user-images.githubusercontent.com/6896468/71800820-142ce100-3094-11ea-8be8-1e56e24d09ff.png)
> 只输这两行就可以了

你好 只输入这两行之后仍然直接停止工作，没有新的报错信息，但是重启电脑后可以正常打开进程了
