### ISSUE TITLE
通过AirtestIDE或者命令行运行脚本，如何调整日志级别？

### ISSUE THREAD

**Issue by shijianzhihu** [AirtestProject/AirtestIDE#684]
**详细描述问题bug：**
通过AirtestIDE或者命令行运行脚本，如何调整日志级别？

**复现步骤：**
1. 通过AirtestIDE (v1.2.2) 运行脚本，在这里设置了级别但是没有效果。
![image](https://user-images.githubusercontent.com/26112446/71944310-5f630300-31fe-11ea-8667-8aa2057fb346.png)
2. 如何在代码中设置日志级别？

**python 版本:** `python3.7.0`
**操作系统:** `Windows10 64bit`

**Comment by yimelia** [comment]
1. 选了级别之后再运行脚本
2. 参考 https://github.com/AirtestProject/Airtest/issues/562
