### ISSUE TITLE
win窗口连接选桌面后ide异常无法正常使用

### ISSUE THREAD

**Issue by JNBINW** [AirtestProject/AirtestIDE#686]
* 测试开发环境AirtestIDE使用问题（本软件）

**详细描述问题bug：**
win窗口选择桌面后IDE异常，win桌面全屏覆盖整个IDE画面，IDE无法使用，且无法关闭连接。

**复现步骤：**
1.打开AirtestIDE
2.Windows窗口连接>选定窗口>选择桌面

**python 版本:** `python3.8`

**操作系统:** `Windows10 64bit`

**其他相关信息补充**
- AirtestIDE版本号：1.2.2

**截屏**
![windows窗口选择桌面后异常无法退出](https://user-images.githubusercontent.com/13123283/72082643-6f343180-333b-11ea-9c8e-4fd02daa5d29.png)

**Comment by yimelia** [comment]
Duplicate of #687
