### ISSUE TITLE
如何解决remote desktop时运行就识别不到airtest截图这个问题

### ISSUE THREAD

**Issue by sugersmile** [AirtestProject/AirtestIDE#689]
脚本在服务器端运行，为WEB程序，通过remote desktop连接到服务器, 现发现不打开remote desktop无法识别到图,请问有没有什么曲线救国的方法解决这个airtest截图问题

**Comment by yimelia** [comment]
目前的窗口截图是必须要能够看得到窗口画面、并且窗口最前，暂时是还没有实现其他方案，或者你可以考虑迭代一下airtest/core/win/模块下的截图方法看看
