### ISSUE TITLE
Ubuntu18.04 IDE无法启动

### ISSUE THREAD

**Issue by birdidi** [AirtestProject/AirtestIDE#691]
OS参数：

- Ubuntu18.04
- Python3.6

`Info: filter not set, use raven.filter.FullPassFilter instead.
setting OPENGL=angle...
qt.qpa.gl: Choosing xcb gl-integration based on following priority
 ("xcb_glx", "xcb_egl")
qt.qpa.gl: Xcb GLX gl-integration created
qt.qpa.gl: Xcb GLX gl-integration successfully initialized
loading config from : ['/root/.local/share/AirtestIDE/AirtestIDE/user.json']
/bin/sh: 1: system_profiler: not found
Info: filter not set, use raven.filter.FullPassFilter instead.
queue size is: 10
[1:1:0100/000000.232923:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault (core dumped)
`

**Comment by yimelia** [comment]
兼容的版本号以文档写的16.04为准，暂时无法维护更多版本
