### ISSUE TITLE
夜神模拟器,连接成功后,content下拉菜单无法点击.

### ISSUE THREAD

**Issue by life-is-short-pythonn** [AirtestProject/AirtestIDE#692]
![image](https://user-images.githubusercontent.com/46018608/72675189-987f5b00-3abb-11ea-9399-7e8326c8e846.png)
无法点击,我吐了
![image](https://user-images.githubusercontent.com/46018608/72675194-aa60fe00-3abb-11ea-92c2-6f8cb9356aef.png)

**Comment by yimelia** [comment]
注意ADB status是offline，只有device状态才是可点的。offline的可能性有很多，可以自行百度下。

**Comment by life-is-short-pythonn** [comment]
我已经开启了模拟器usb调试了,但还是无法连接****
![image](https://user-images.githubusercontent.com/46018608/72676385-b3f26200-3acb-11ea-92d6-d9a4783f9f87.png)

**Comment by life-is-short-pythonn** [comment]
状态还是offline

**Comment by life-is-short-pythonn** [comment]
我使用手机还是不行会报错
![image](https://user-images.githubusercontent.com/46018608/72676514-e3559e80-3acc-11ea-8b88-6019bce397f7.png)
![image](https://user-images.githubusercontent.com/46018608/72676518-f1a3ba80-3acc-11ea-8765-2d9a2984fac3.png)
![48EF60A37051026C3BC2061224C61B18](https://user-images.githubusercontent.com/46018608/72676537-2b74c100-3acd-11ea-9765-442d0a3cc527.jpg)

**Comment by yimelia** [comment]
1. 首先，设备状态是offline，说明手机没连上，这个和IDE无关，需要你自行排查问题，可能是端口号填错了，或者是其他原因导致的，手机状态可以用`adb.exe devices`指令来查看，adb.exe如果你本地没有，在IDE的目录下也有一个可以用 `AirtestIDE\airtest\core\android\static\adb\windows`。

要一直排查问题，直到能够在命令行窗口中看到你的设备是device状态后，才能连接。

2. 第二个手机连不上的问题，既然有报错，最好把报错贴上来，否则不知道到底是什么问题。或者自行根据文档来排查：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/

如果安卓版本号是Android10，暂时还没有兼容，目前是连不了的
