### ISSUE TITLE
请问较大型的游戏是否支持poco，多个场景来回加载是否需要在每个场景camera挂脚本，有多个相机时挂在不同的相机下是否有影响

### ISSUE THREAD

**Issue by pxs1997** [AirtestProject/AirtestIDE#693]
我有一个游戏项目，有多个场景，每个场景下有两个camera
每个场景游戏组件较多
我在一个空项目中使用教程方法可以正确使用poco
但是我使用相同方法挂载在游戏项目中时却无法读取ui树
请问有哪些可能原因呢

**Comment by yimelia** [comment]
最好是能够提供更多信息，比如有没有相关的报错log，以及用的是poco什么类型。
接入的时候注意阅读文档，挂载在全局变量中，不要挂在那种切换场景就会被销毁的对象上，否则一旦切换场景就拿不到数据了
