### ISSUE TITLE
华为畅想7S, ADB能连，IDE不能连

### ISSUE THREAD

**Issue by AndyWjc** [AirtestProject/AirtestIDE#694]

**Comment by yimelia** [comment]
首先请阅读发帖时的模板，根据模板来填写问题描述，不发报错的话，完全无法排查具体是什么问题
其次，请查阅连接文档：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/
然后，如果是Android10，暂时还不能连，等待我们更新就行，就这两天会更新
