### ISSUE TITLE
OPPO手机调试密码输入场景，会触发系统的安全键盘，IDE必现失去手机连接

### ISSUE THREAD

**Issue by EgoistInory** [AirtestProject/AirtestIDE#695]
bug描述
OPPO A5手机调试密码输入场景，会触发系统的安全键盘，IDE必现失去手机连接

**操作系统:** 
`Windows10 64bit`

**手机设备信息:**
 - 手机型号:OPPO A5

**其他相关信息补充**
需要设置手机不响应密码输入时使用安全键盘

**Comment by yimelia** [comment]
参考这个：
![image](https://user-images.githubusercontent.com/6896468/72726322-04002000-3bc3-11ea-87bd-8c9036334ebd.png)
