### ISSUE TITLE
Windows10 系统下，使用touch函数仅仅将鼠标移到相应位置，没有执行按下左键的命令

### ISSUE THREAD

**Issue by ljq29** [AirtestProject/AirtestIDE#697]
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues

**详细描述问题bug：**
bug描述

**复现步骤：**
**python 版本:** `python3.x`

**操作系统:** `Windows10 64bit`

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.2

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
Duplicate #696 

1. 可以尝试用非嵌入的方式来连接windows窗口 https://airtest.doc.io.netease.com/tutorial/7_Windows_automated_testing/#_2

2. 如果点击时报错了，可以尝试用管理员模式启动IDE，然后再运行脚本，可能是因为没有权限点击

3. 如果还是不行，尝试用连接桌面的方式来跑脚本
