### ISSUE TITLE
1.2.3版本的AirtestIDE，使用adb运行测试脚本失败

### ISSUE THREAD

**Issue by UnReAlKiNg** [AirtestProject/AirtestIDE#702]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**
第一步，根据官网http://airtest.netease.com/docs/cn/8_plugins/1_firebase.html#id5，8.1.3运行测试脚本的描述，已将脚本文件打包成apk并安装到手机上；
第二步，提示用adb运行代码adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner，
使用IDE自带的android助手情况如图片1：
HWMHA:/ $ adb shell am instrumentadb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner
/system/bin/sh: <stdin>[1]: pport.test.runner.AndroidJUnitRunner: not found
HWMHA:/ $ 
使用windows cmd运行情况如下：
org.kivy.android.ExampleInstrumentedTest:
Error in launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
junit.framework.AssertionFailedError:
=================report error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 97, in test
  File "copy_app/airtest\cli\__main__.py", line 13, in main
  File "copy_app\airtest\report\report.py", line 385, in main
  File "copy_app\airtest\report\report.py", line 325, in report
  File "copy_app/airtest\cli\info.py", line 20, in get_script_info
IOError: [Errno 2] No such file or directory: '/data/data/com.netease.open.airbase/files/app/\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd.air/\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd.py'
=================report error end================

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:华为 mate9 MHA-AL00
 - Android系统版本号: [Android 9]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：v1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![图片1](https://user-images.githubusercontent.com/33448761/74301533-58e02200-4d8e-11ea-8454-091bd92e0b92.jpg)

![图片2](https://user-images.githubusercontent.com/33448761/74301534-5a114f00-4d8e-11ea-8f87-08164449ee6e.png)

**Comment by yimelia** [comment]
1. 图1的运行方式是错的，在你的windows命令行里运行就行，像图2那样
2. 脚本名字不要用中文
