### ISSUE TITLE
airtest内置函数使用问题

### ISSUE THREAD

**Issue by UnReAlKiNg** [AirtestProject/AirtestIDE#703]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues

**详细描述问题bug：**
bug描述：
airtest的函数中有一个assert_exists和assert_not_exists，然后根据官网的示例
![image](https://user-images.githubusercontent.com/33448761/75003146-cb918180-54a1-11ea-8aca-7d0d9bfa9a86.png)，
写了一个类似的代码，然后编译的时候提示语句错误

**复现步骤：**
我的代码1：
assert_not_exists(image.jpg,"界面显示结算成功")：  #image是屏幕截图
        xxx（这些是执行的代码）
然后编译的时候提示这一行（assert那一行）语句错误
然后根据左侧的函数参数的描述
我又改成
我的代码2：
assert_not_exists(image.jpg,msg="界面显示结算成功")：
        xxx（这些是执行的代码）
还是提示语句错误

是这个函数不能用作：假设这个图片存在，然后执行下述操作（或者假设图片不存在）吗？
还是我的参数不对？
**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:Huawei MHA-AL00
 - Android系统版本号: [Android 9]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：v1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
请贴出完整的报错信息，请把运行时的命令行、以及结果贴出来，我们需要看到明确的报错信息才能知道是什么样的“语句错误”

**Comment by yimelia** [comment]
以及：如果你在每一个assert_exists()语句后面加了冒号的话，那么这样的语法肯定是错误的。
建议先百度一下assert语句的定义和用途，或者关注我们官方公众号AirtestProject，查看这篇文章有更详细的用法示例：https://mp.weixin.qq.com/s/DEe-Emyi0hN0JZA83i1Wmg
