### ISSUE TITLE
 RotationWatcher.apk does not exists

### ISSUE THREAD

**Issue by bestkings** [AirtestProject/AirtestIDE#704]
**Describe the bug**
I'm trying setup remote to emulators but have problem. Working fine with remote to real phones 
In AirtestIDE: already stick Use Javacap, Use orientation, sure correct port remote
In emulators: already make On Deverloper, USB debugging, Verify apps over USB
Main problem: AirtestIDE\\airtest\\core\\android\\static\\apks\\RotationWatcher.apk' does not exists

**Screenshots**
![aaa](https://user-images.githubusercontent.com/5138174/75140359-503e0300-5721-11ea-8688-9146500801a1.png)

**Comment by yimelia** [comment]
You can try to install this rotationwatcher.apk manually
