### ISSUE TITLE
能否手动设置自带的touch（）等指令的执行次数与等待时间？

### ISSUE THREAD

**Issue by sakurua5** [AirtestProject/AirtestIDE#705]
有时候由于电脑的卡顿等原因，图片不能第一时间加载出来，以致图片加载出来时，系统已判定error并终止脚本。若我一个个地去设置wait（）实在太花时间，能否添加一些设置让这些指令在找到对象前能一直重复搜索？

**Comment by EraChen233** [comment]
https://airtest.doc.io.netease.com/IDEdocs/settings/2_script_settings/#find_timeout

**Comment by sakurua5** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Era Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 中午11:44
收件人:&nbsp;"AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;;
抄送:&nbsp;"雨中山林"<907610069@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/AirtestIDE] 能否手动设置自带的touch（）等指令的执行次数与等待时间？ (#705)




https://airtest.doc.io.netease.com/IDEdocs/settings/2_script_settings/#find_timeout
