### ISSUE TITLE
华为输入法键盘无法展现，呈现为黑屏。

### ISSUE THREAD

**Issue by waveboy800** [AirtestProject/AirtestIDE#71]

**Comment by rockywhisper** [comment]
@waveboy800  你好，能描述下具体重现过程吗？手机型号又是什么呢？

我这边使用华为手机测试，连接状态下打开华为输入法键盘，输入没遇到问题。

**Comment by rockywhisper** [comment]
@waveboy800  你好，在更多的华为手机上也没能重现。

我暂时把issues关闭了哈，如果仍有问题随时联系  :-)
