### ISSUE TITLE
airtest如何持续集成？

### ISSUE THREAD

**Issue by dzhiqin** [AirtestProject/AirtestIDE#710]
目前只有看到用命令行运行脚本的介绍，没有关于持续集成的介绍，能否详细说明一下？谢谢。

**Comment by EraChen233** [comment]
如果是自行实现，可以参考这个样例
https://github.com/AirtestProject/multi-device-runner
如果需要现成成品，可以联系我们，使用我们的私有化方案
https://airlab.163.com/b2b
