### ISSUE TITLE
Bat形式运行的能不能有具体的实例，大佬帮忙解决下~

### ISSUE THREAD

**Issue by Topi9999** [AirtestProject/AirtestIDE#72]
看文档里面的，复制进去实现不了，闪一下就退出了，能否对新人友好点。。。
复制IDEl里的路径倒是可以，但是太长了，还是希望能有个简单的实例学习
比如：airtest run XXXX.air --device Android://127.0.0.1:5037/1x526xbd --log "C:\User等路径“
   这个运行就闪一下,哪里需要引号什么的。。
python custom_launcher XXXX.air --device Android://127.0.0.1:5037/1x526xbd --log "C:\User等路径“
  也是不行，一定要
"E:\AirtestIDE_2018-04-11_11\AirtestIDE" runner "E:\
那就是调用IDE的了。。。麻烦给个可以用的示例，谢谢~~

**Comment by Meteorix** [comment]
@Topi9999 你好，我们希望尽量对新人友好，有哪里没写清楚的尽管提。

你现在需要的是直接用airtest运行脚本，而不用IDE对吧？
看起来你已经看过这里的[文档](http://airtest.readthedocs.io/zh_CN/latest/README_MORE.html#running-air-from-cli)了，所以我们要确认下“闪一下”的原因。
1. 确认你已经安装了最新的airtest：``pip install -U airtest``
1. 在cmd里面输入 ``airtest -h``，输出应该类似下面的截图
![image](https://user-images.githubusercontent.com/3805278/38799986-92f2dfc2-4198-11e8-973e-b9fe90887099.png)
1. 没问题的话，连上手机再输入 ``airtest run XXXX.air --device Android:///``

理论上这样就能跑起来了，如果有报错的话，直接截图贴到issue里面，这样我们才能知道问题出在哪~

**Comment by Topi9999** [comment]
![default](https://user-images.githubusercontent.com/38421083/38802286-99a10bb8-419e-11e8-81ec-66c5e8d10ace.jpg)
感谢大佬及时回复~~万分感谢~
是这样的，我装了python2 python3  pip  install -U airtest安装的时候报错了，好像opencv装在了pip2上了，3装不了，但是airtest -h 确实可以的，截图：
![-h](https://user-images.githubusercontent.com/38421083/38802371-d5754514-419e-11e8-9408-ad9bde7f9a44.jpg)
然后执行你回复的：
airtest run Login.air --device Android://127.0.0.1:5037/1e5260bd --log "C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\643212da37d42c57e5f6f63c52a4fdb6"
就是闪一下没了。。
闪的图：
![default](https://user-images.githubusercontent.com/38421083/38802516-3ce727da-419f-11e8-8036-472039b00934.jpg)
麻烦帮忙解决下哈，好开心你们及时回复~好想加入你们，跟你们学习~~

**Comment by Topi9999** [comment]
![poco](https://user-images.githubusercontent.com/38421083/38802702-c6ee2cc6-419f-11e8-86d3-647ab1332fe2.jpg)
文件名加了引号后，多执行了几句，瞬间截图下，看到了，好像是Poco库没有的问题，我们游戏貌似是用cocos2dx修改的引擎，用poco貌似不行，那我改下脚本把from poco去掉就可以了？我试下。。

**Comment by Meteorix** [comment]
@Topi9999 不用客气（在评论里用飘号显示不太对。。）

直接用pip2安装吧，卸载一次再安装
``pip uninstall airtest``
``pip install -U airtest``

确保安装正确后，去掉后面的``--log``，按以下命令行执行：
``airtest run XXXX.air --device Android:///``

**Comment by Topi9999** [comment]
@Meteorix 额 好的，我刚才试着去掉了poco 运行了一小会，又闪掉了，这个闪退的log去哪里可以看到吗？我都是靠截图看的。。   xxxx.air 需要加引号吧，我加引号貌似执行了几步。。。

**Comment by Topi9999** [comment]
![default](https://user-images.githubusercontent.com/38421083/38803373-96b40830-41a1-11e8-84a6-995938004064.jpg)
卸载重装后，走到图片索引就闪退了，之前的IDE命令可以用的bat，现在也用不了了，比用airtest闪的还快。。

**Comment by Meteorix** [comment]
@Topi9999 不应该闪退啊，你按`shift+鼠标邮件`，选择`在此处打开命令行`，然后输入命令，先不要在bat文件里面直接写

**Comment by Meteorix** [comment]
或者你在bat文件最后加一行`pause`

**Comment by rockywhisper** [comment]
@Topi9999 Hi，看到你的Login.air脚本第53行内容有点奇怪：
![image](https://user-images.githubusercontent.com/8188879/38806870-49e11d2a-41ad-11e8-9697-f48871f31309.png)

那行脚本是手动改成那样的吗..？

**Comment by Topi9999** [comment]
@rockywhisper  是的呀，这脚本写的= =试一下而已。。

**Comment by Topi9999** [comment]
@Meteorix 谢谢大神哈，我进IDE编辑了下airtest run可以了，脚本的问题。。
那比如我手动修改的 启动脚本custom_launcher.py 用airtest run 怎么写呢。。。
我试过
airtest custom_launcher.py run  XXXX.air --device Android  不行
airtest launcher custom_launcher.py  XXXX.air --device Android 也不行。。。

**Comment by Meteorix** [comment]
@Topi9999 后面有三个斜杠

```airtest run XXXX.air --device Android:///```

另外你如果不需要launcher，就不用launcher了，那块比较复杂，是封装一些高级特性

**Comment by Topi9999** [comment]
python custom_launcher.py run XXXX.air --device Android:///
就是说 自己封装了 launcher.py 就不能用airtest 了是吧。。。
我可能需要改下启动的文件，和结束的清理什么的。。所以还是有需要的。

**Comment by Meteorix** [comment]
对的，自己封装了就直接用```python custom_launcher.py```运行。

`airtest`命令相当于用模块启动，即：```python -m airtest```

**Comment by Topi9999** [comment]
@Meteorix 额 我只是根据教程改了启动文件的一点点内容，还是要靠airtest run 或者 AirtestIDE" runner 才可以吧。。
直接 python custom_launcher.py run XXXX.air --device Android:///   启动不了。。

**Comment by Topi9999** [comment]
@Meteorix 再次感谢大佬的及时回复，好有爱！

**Comment by Meteorix** [comment]
直接 python custom_launcher.py run XXXX.air --device Android:///

把报错贴进来把

**Comment by Meteorix** [comment]
你应该安装了airtest吧？是不是python2 3 的版本搞错了？

**Comment by Topi9999** [comment]
list图上传不了。。。
pythone2 安装了 airtest  
python3 没有安装
是不是怎么指定python2来运行。。现在好像输入python默认是3，输入python2 提示不是内部指令。。

**Comment by Meteorix** [comment]
已经启动对了，检查下你的脚本吧，剩下就是python层面的问题了，可以进一步学习python之后再用custom_launcher

**Comment by Topi9999** [comment]
@Meteorix 大佬，在IDE调用custom_launcher启动是正确的，用airtest run 也可以启动的脚本，怎么用python custom_launcher 就不行。。。

**Comment by Meteorix** [comment]
custom_launcher目前的文档还不是很完善，你的脚本错误可能还是python语法的问题。

这个issue我先关了，你在qq群问问，或者另开custom_launcher的issue把~
