### ISSUE TITLE
小米note3 连不上普通模式连不上IDE,选javacap模式能连上

### ISSUE THREAD

**Issue by professorss** [AirtestProject/AirtestIDE#720]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 9]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by professorss** [comment]
![QQ截图20200312155539](https://user-images.githubusercontent.com/45282768/76500105-e9d41700-647a-11ea-9170-fd074ffd7b71.jpg)
![QQ截图20200312155605](https://user-images.githubusercontent.com/45282768/76500136-f35d7f00-647a-11ea-913c-0c4de9420467.jpg)

**Comment by yimelia** [comment]
是的，MIUI11不支持minicap
