### ISSUE TITLE
提示获取不到子节点

### ISSUE THREAD

**Issue by Torres009** [AirtestProject/AirtestIDE#721]
![image](https://user-images.githubusercontent.com/10679031/76680929-2e50e580-6628-11ea-8a0c-d5abf87b9ef9.png)
。

**Comment by yimelia** [comment]
建议手工编写代码，而不是用自动生成。

**Comment by Torres009** [comment]
手工编写代码后调试成功，非常感谢你的帮助！

**Comment by Torres009** [comment]
> 建议手工编写代码，而不是用自动生成。

手工编写代码后调试成功，非常感谢你的帮助！
