### ISSUE TITLE
是用windows窗口连接的时候，某些游戏不兼容

### ISSUE THREAD

**Issue by xwh610379675** [AirtestProject/AirtestIDE#725]
**详细描述问题bug：**
用windows连接一些游戏时，屏幕界面会闪屏，无法测试
比如游戏问道，遇到几个游戏都是这样啦

**复现步骤：**
下载问道（游戏），调成百分之50的窗口比例大小
用airtest连接问道，缩小airtest窗口，或者移动，windows窗口无法会花屏

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**截屏**

[>](url
![微信图片_20200318184329](https://user-images.githubusercontent.com/40521885/76952661-628a1600-6948-11ea-98fe-1979c2d972d2.png)
![微信图片_20200318184329](https://user-images.githubusercontent.com/40521885/76952704-76357c80-6948-11ea-9873-1152ee6031c7.png)

)

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/device_connection/5_windows_connection/#2-windows
有些软件嵌入不了的话，可以考虑这个无嵌入的方式
