### ISSUE TITLE
连接不上华为手机设备

### ISSUE THREAD

**Issue by wangcaiyun912** [AirtestProject/AirtestIDE#730]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
之前一直是用这个手机连接的airtest，但是今天再次连接手机的时候，按照以往的调试程序连接不上设备。使用终端命令可以正确返回  设备号 devices，但是airtest有报错。

**复现步骤：**
1、打开airtest
2、打开手机开发者模式，允许USB调试，允许ADB调试。
3、在airtest上刷新adb，点击connect，log报错“airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'E:\\airtest\\AirtestIDE_2019-05-09_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']”

**python 版本:** `python3.x`
Python3.7
**操作系统:** `Windows7 64bit`
Windows7 64bit
**手机设备信息:**
 - 手机型号:  nova 5 Pro  SEL-AL10

 - Android系统版本号: [e.g. Android 8.1] Android 10
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：V1.2.1

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/61188898/77400476-35c17d00-6de6-11ea-94fc-6834836c345c.png)

**Comment by yimelia** [comment]
因为你升级了手机版本到android10，所以请将airtest和airtest-ide都更新到最新版本
