### ISSUE TITLE
adb连接手机问题

### ISSUE THREAD

**Issue by pengyanbing84** [AirtestProject/AirtestIDE#732]
无法连接安卓手机， 报错如下 Injecting to another application requires INJECT_EVENTS permission，
airtest.core.error.AirtestError: 'Installation Failure'
ADB指令执行失败，可能需要修改部分手机设置才能使用
Python3.7
安卓6.0.1，MIUI 9 8.4.28开发版 手机型号Redmi 4A，adb devices 可以获取手机设备号，但无法自动化控制手机。

**Comment by pengyanbing84** [comment]
补充一句， 手机已经开启开发者模式和USB调试

**Comment by yimelia** [comment]
1. 和IDE一起启动的黑色命令行窗口里面的log信息截图发出来看一下。
2. 检查一下手机里的“允许模拟点击位置”、“USB安装”、“USB调试(安全设置)”三个选项都是打开状态，大部分选项的开启需要插入SIM卡登录小米账号，请确认是否都开启了

**Comment by pengyanbing84** [comment]
已成功连接，请问使用那款手机做自动化测试比较好？




| |
pengyanbing84
邮箱：pengyanbing84@163.com
|

Signature is customized by Netease Mail Master

在2020年03月26日 10:53，yimelia 写道：

和IDE一起启动的黑色命令行窗口里面的log信息截图发出来看一下。
检查一下手机里的“允许模拟点击位置”、“USB安装”、“USB调试(安全设置)”三个选项都是打开状态，大部分选项的开启需要插入SIM卡登录小米账号，请确认是否都开启了

**Comment by pengyanbing84** [comment]
我还出现一个问题，手机通过USB连接电脑，第一次运行程序自动化测试手机没有问题，手机还是继续USB连接电脑没有断开，当隔一段时间允许程序自动化测试手机没有反应，但输入 adb devices 可以获取手机设备号，请问这是什么原因导致？




| |
pengyanbing84
邮箱：pengyanbing84@163.com
|

Signature is customized by Netease Mail Master

在2020年03月26日 10:56，pengyanbing84 写道：
已成功连接，请问使用那款手机做自动化测试比较好？




| |
pengyanbing84
邮箱：pengyanbing84@163.com
|

Signature is customized by Netease Mail Master

在2020年03月26日 10:53，yimelia 写道：

和IDE一起启动的黑色命令行窗口里面的log信息截图发出来看一下。
检查一下手机里的“允许模拟点击位置”、“USB安装”、“USB调试(安全设置)”三个选项都是打开状态，大部分选项的开启需要插入SIM卡登录小米账号，请确认是否都开启了

**Comment by yimelia** [comment]
> 当隔一段时间允许程序自动化测试手机没有反应，

看不明白你的问题，请清晰、明确地描述清楚你遇到的问题，比如脚本如何运行，如何没有反应，是否有报错，运行了什么脚本，是否使用了poco，脚本在哪里卡住

**Comment by pengyanbing84** [comment]
当第一次运行脚本控制手机没有问题，
问题是当隔一段时间之后运行脚本手机没有反应，脚本一直等待着手机却没有反应，但输入adb devices 可以获取当前连接手机的设备号，最终报错超时火没有找到元素，手机是通过USB一直连接电脑没有断开过




| |
pengyanbing84
邮箱：pengyanbing84@163.com
|

Signature is customized by Netease Mail Master

在2020年03月26日 11:04，yimelia 写道：

当隔一段时间允许程序自动化测试手机没有反应，

看不明白你的问题，请清晰、明确地描述清楚你遇到的问题，比如脚本如何运行，如何没有反应，是否有报错，运行了什么脚本，是否使用了poco，脚本在哪里卡住

**Comment by pengyanbing84** [comment]
你好，能给我连接多台手机的demo？
python3的示例




| |
pengyanbing84
邮箱：pengyanbing84@163.com
|

Signature is customized by Netease Mail Master

在2020年03月26日 11:44，yimelia 写道：

Closed #732.

**Comment by tester-xm** [comment]
真是蠢货，自己找呗
