### ISSUE TITLE
windows 10系统，airtest v1.2.3版中运行后点击报告生成，提示没有日志，报告生成不了

### ISSUE THREAD

**Issue by zhiqing0808** [AirtestProject/AirtestIDE#733]
windows 10系统，airtest v1.2.3版中运行后点击报告生成，提示没有日志，报告生成不了@纪云-网易游戏 
![image](https://user-images.githubusercontent.com/20992057/77872291-2b393480-7279-11ea-96db-b5fb4bba08a3.png)

**Comment by EraChen233** [comment]
https://airtest.doc.io.netease.com/tutorial/2_Airtest_introduction/#pythonairtest
