### ISSUE TITLE
APP调用软键盘时，keyevent输入无效

### ISSUE THREAD

**Issue by weiyanfen** [AirtestProject/AirtestIDE#742]
**详细描述问题bug：**
bug描述
APP调用软键盘时，keyevent输入无效

**复现步骤：**
1、到交易密码页面，会唤起软键盘
2、用keyevent无效，用touch也无效

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号: 华为Nova2
 - Android系统版本号: [e.g. Android 8.0]

- AirtestIDE版本号：1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
类似这种软键盘
![image](https://user-images.githubusercontent.com/9304677/78896109-8c93ab80-7aa2-11ea-997f-2b1eeffa5708.png)
![image](https://user-images.githubusercontent.com/9304677/78896178-a634f300-7aa2-11ea-9042-d2031f457f43.png)
![image](https://user-images.githubusercontent.com/9304677/78896213-b2b94b80-7aa2-11ea-8789-457d27d7ec1f.png)

**Comment by yimelia** [comment]
有些手机在密码界面有保护，可能在输入密码时无法截图，找一下手机设置里面有没有安全输入的选项，把它关掉就好了。
参考：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#textide

**Comment by weiyanfen** [comment]
已经关掉安全输入的选项，APP弹的是软键盘，有什么办法解决吗？

**Comment by yimelia** [comment]
android版本号是多少？
之前此类问题，都是直接关闭安全输入就可以了的

**Comment by weiyanfen** [comment]
Android 8.0.0
![image](https://user-images.githubusercontent.com/9304677/78959035-5266f000-7b1c-11ea-8a1f-c0371cbcc58b.png)
![image](https://user-images.githubusercontent.com/9304677/78959191-be495880-7b1c-11ea-876f-2cbcbcb85162.png)

**Comment by yimelia** [comment]
这个可能有点无能为力了，可能是银行APP升级了安全模块。。。
