### ISSUE TITLE
set_current多次切换手机后ui结构有误

### ISSUE THREAD

**Issue by laoff** [AirtestProject/AirtestIDE#746]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
unity打包的游戏app，设备A切换至设备B后再次切换回设备A时，ui结构还是设备B的。

**复现步骤：**
from airtest.core.api import connect_device
dev1=connect_device("Android://127.0.0.1:5037/设备A?cap_method=JAVACAP&&ori_method=ADBORI")
dev2=connect_device("Android://127.0.0.1:5037/设备B?cap_method=JAVACAP&&ori_method=ADBORI")
print(G.DEVICE_LIST)
set_current("设备A")
print("设备")
print(G.DEVICE)
poco("设备AUI控件").click()
time.sleep(3)
set_current("设备B")
print("设备")
print(G.DEVICE)
poco("设备BUI控件").click()
time.sleep(3)
set_current("设备A")
time.sleep(3)
print("设备")
print(G.DEVICE)
poco("设备A控件").click()
#poco(“设备B控件”).click()

**python 版本:** `python3.x`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号A:华为p9
 - Android系统版本号: [Android 7.0]
 - 手机型号B:vivo y66
 - Android系统版本号: [Android 6.0.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
切换至设备A后poco("设备A控件").click()报错找不到该控件，poco(“设备B控件”).click()成功执行。
- AirtestIDE版本号：v1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
请初始化2个不同的poco对象，参考：https://airtest.doc.io.netease.com/tutorial/5_Android_automated_testing_two/#poco

**Comment by laoff** [comment]
请问如何初始化两个不同的unitypoco
