### ISSUE TITLE
IDE显示图片只能在图片和代码在同一目录下才能展示

### ISSUE THREAD

**Issue by NanYeYe** [AirtestProject/AirtestIDE#749]
G.BASEDIR.append添加了图片目录，执行时可以找到图片
但是在IDE打开，只有图片和代码在同一目录下，才能展示出图片
![image](https://user-images.githubusercontent.com/11953895/79871452-f0a95e80-8416-11ea-8f3c-a2be730d8818.png)

**Comment by yimelia** [comment]
是的，IDE并不会去读取你的脚本内容并解析具体的图片路径在哪里
