### ISSUE TITLE
设备窗口选择一个大点的windows窗口后，左上角的功能按钮找不到了

### ISSUE THREAD

**Issue by GrokLuffy** [AirtestProject/AirtestIDE#75]
![mfyosv 21 l2jjrj9 1](https://user-images.githubusercontent.com/22125579/38862483-a1ea4838-4267-11e8-8b01-db4ca1da9d9f.png)

**Comment by rockywhisper** [comment]
@GrokLuffy  Hi，IDE嵌入窗口时会保持窗口的大小。
在嵌入超大窗口时，画面渲染可能会超出IDE边界，右上角功能按钮就被顶出显示范围了。

解决方法：
- 一般最大化IDE即可完整显示画面
- 将设备窗页面拖出IDE，也可以完整展示画面

**建议：**
- 嵌入前把目标窗口缩放到合理的大小。（否则嵌入后会挤压IDE其他功能窗的空间）

**Comment by rockywhisper** [comment]
这个issue暂时关闭了哈~
