### ISSUE TITLE
Mac上脚本编辑器和log面板都是白屏

### ISSUE THREAD

**Issue by CrisDeng** [AirtestProject/AirtestIDE#752]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
mac上脚本编辑器和log都是白屏

**复现步骤：**

**python 版本:** `python3.6`

**操作系统:** `10.15.4`
mac pro 2013 ，AMD FirePro D500 3 GB图形卡

**其他相关信息补充**
在iMac上显示正常，在Mac Pro显示异常
**AirtestIDE版本号**`1.2.3`

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/6908058/80081615-c4f8b680-8585-11ea-83a6-97233cd691e1.png)
![image](https://user-images.githubusercontent.com/6908058/80081625-c924d400-8585-11ea-8401-ce0d1b44bfda.png)

**Comment by yimelia** [comment]
在设置里有几个启动模式，可以切换一下，然后退出IDE再重新启动试试，看看有没有哪个选项是可以用的：
https://airtest.doc.io.netease.com/IDEdocs/settings/1_ide_settings/#_5

**Comment by CrisDeng** [comment]
选择了software模式正常显示了，之前我搜索了Airtest白屏出来的链接是以下文档，切换显卡无效。建议把模式修改的方法放在这个页面里面
https://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id3
