### ISSUE TITLE
AirtestIDE启动报错

### ISSUE THREAD

**Issue by DengDeJie** [AirtestProject/AirtestIDE#754]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
AirtestIDE启动报错，ImportError:DLL load failed:找不到指定模块。

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 32bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/37207425/80269227-38aed680-86e0-11ea-88e3-8bcc8710f7c5.png)

**Comment by yimelia** [comment]
在AirtestIDE解压后的目录中找到api-ms-win-downlevel-shlwapi-l1-1-0.dll和IEShims.dll两个DLL文件，将他们复制到C:\Windows\System32目录，然后再重新启动IDE试试看

**Comment by DengDeJie** [comment]
> 在AirtestIDE解压后的目录中找到api-ms-win-downlevel-shlwapi-l1-1-0.dll和IEShims.dll两个DLL文件，将他们复制到C:\Windows\System32目录，然后再重新启动IDE试试看


> 在AirtestIDE解压后的目录中找到api-ms-win-downlevel-shlwapi-l1-1-0.dll和IEShims.dll两个DLL文件，将他们复制到C:\Windows\System32目录，然后再重新启动IDE试试看

只找到IEShims.dll这个文件，api-ms-win-downlevel-shlwapi-l1-1-0.dll这个文件没有。

**Comment by DengDeJie** [comment]
> 在AirtestIDE解压后的目录中找到api-ms-win-downlevel-shlwapi-l1-1-0.dll和IEShims.dll两个DLL文件，将他们复制到C:\Windows\System32目录，然后再重新启动IDE试试看

只找到IEShims.dll，api-ms-win-downlevel-shlwapi-l1-1-0.dll这个文件找不到。

**Comment by yimelia** [comment]
把IEShims.dll放到system32目录 之后启动有效果吗？

**Comment by DengDeJie** [comment]
> 把IEShims.dll放到system32目录 之后启动有效果吗？

没有效果，和之前一样。

**Comment by yimelia** [comment]
另外那个dll可以直接百度获取到，搜索一个下载到system32目录看看

**Comment by DengDeJie** [comment]
> 另外那个dll可以直接百度获取到，搜索一个下载到system32目录看看

下载api-ms-win-downlevel-shlwapi-l1-1-0.dll放到system32目录下载，问题解决了，感谢！！！
