### ISSUE TITLE
执行 swipe() 滑动后，在执行self.poco(),程序直接不执行下去，一直停止

### ISSUE THREAD

**Issue by luzhisheng** [AirtestProject/AirtestIDE#755]
**详细描述问题bug：**
执行 swipe() 滑动后，在执行self.poco(),程序直接卡死

**复现步骤：**
打开app，进入列表页面，向下滑动，8次左右，在执行self.poco(),程序直接卡死

**python 版本:** `python3.7`

**操作系统:** `ubuntu 64bit`

**手机设备信息:**
 - 手机型号: 魅族魅蓝
 - Android系统版本号: [e.g. Android 5.1]

**其他相关信息补充**
- AirtestIDE版本号：

```# 获取手机的屏幕分辨率
        xy = self.poco.get_screen_size()
        x = xy[0]
        y = xy[1]

        for i in range(0, 5):
            swipe((0.5 * x, 0.75 * y), (0.5 * x, 0.2 * y), duration=1)
            sleep(3)

        if self.poco(resourceId="com.taobao.live:id/taolive_search_back_icon").exists():
            self.poco(resourceId="com.taobao.live:id/taolive_search_back_icon").click()
```

**截屏**

没有报错数据，一直卡这，我用手上下滑动没有问题，程序跑直接卡在 self.poco

**Comment by yimelia** [comment]
如果去掉swipe的操作，直接执行poco.exists和poco.click能否正常执行？
如果去掉前面的get_screen_size()，只是用swipe随意滑动几下，然后执行后面的poco.click，能否正常执行？

**Comment by luzhisheng** [comment]
这个和get_screen_size没有关系，我使用了self.poco.swipe()也是一样的效果，可能是手机问题，我换了手机就ok了
