### ISSUE TITLE
AirTest IDE 脚本编辑窗黑屏，无法查看&编辑脚本

### ISSUE THREAD

**Issue by GaoRenling** [AirtestProject/AirtestIDE#759]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
1、打开IDE，Login界面黑屏，点击skip跳过，进入客户端，脚本编辑框黑屏，打开某个脚本时也无法查看脚本，没办法编辑脚本，log查看框也不会显示任何信息
2、选项->设置，随便修改某个参数，点击确定，关闭IDE时，会报AirtestIDE Automation tools已停止工作

**复现步骤：**
每次启动必现

**python 版本:** `python2.7.17

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：
IDE V1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![login](https://user-images.githubusercontent.com/14307280/81166272-0b0e3b00-8fc6-11ea-868a-1c01e7681664.png)
![main](https://user-images.githubusercontent.com/14307280/81166275-0d709500-8fc6-11ea-8bd6-255e2f554d3a.png)
![未响应](https://user-images.githubusercontent.com/14307280/81166299-16f9fd00-8fc6-11ea-9a0d-22ffbbd71b99.png)

**Comment by GaoRenling** [comment]
兼容模式启动.bat，也无法解决，依然存在该问题

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/81245713-4c472f00-9048-11ea-9f7b-5797198bf479.png)
设置里面的兼容模式有几个选项，可以都选择一下然后重启IDE再看看有没有哪个选项是可以用的

**Comment by GaoRenling** [comment]
网上查了很多，方法也试了（如显卡兼容性、ide设置中兼容模式、删除缓存重新下载等），最终还是没解决我的问题。后来自己找到问题了，有点坑，原因如下：
之前用teamvier远程办公，被检测到时商业行为，不让用，只能用vpn远程连接，远程连接有增强演示16位，改为质量最高32位就可以了。

**Comment by takethegame** [comment]
mac 下有同样的问题。请问楼主能给出更详细的问题原因吗？teamview怎么和airTest ide 关联起来了呢？
