### ISSUE TITLE
poco(text='xxxxx').click()问题

### ISSUE THREAD

**Issue by Topi9999** [AirtestProject/AirtestIDE#76]
前面哪里看了个刘欣大大的视频，将的是 poco(text = "xxxx").click()
系统会生成 xxxx 的图片去检索手机画面中有没有匹配的图片，这个检索方法挺好用的。。
但是我们游戏poco貌似用不了，扩展不了sdk
想问下，touch(text = "123").click() 这个方法可以吗。。

**Comment by rockywhisper** [comment]
@Topi9999  你说的是touch(text="xxx")这种吧，这种方式使用限制比较大：
- 要求游戏内文字规整，字体大小一致
- 需要实现该字体的图片生成方法
- 字体背景不能有过多变化

建议你直接使用游戏内截图的方式来尝试下 :-)

另外，你们的游戏poco-sdk扩展遇到什么问题也可以跟我们沟通下哈。
