### ISSUE TITLE
华为mate 20 录屏api录制分辨率和实际屏幕大小不一致

### ISSUE THREAD

**Issue by zhanglei417** [AirtestProject/AirtestIDE#761]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
使用录屏api录制视频，华为mate20，录制后发现视频分辨率为2160x2160.实际应为2160x1080 
![image](https://user-images.githubusercontent.com/25195338/81407372-dd63f600-916d-11ea-9af3-dae9e2e1aa15.png)

**复现步骤：**
使用recorder录制：

from airtest.core.android.android import Recorder
from airtest.core.android.adb import ADB

Recorder(ADB('LKX7N17B22002803')).start_recording(5000)
sleep(10)
Recorder(ADB('LKX7N17B22002803')).stop_recording('tmp/2.mp4')

ADB后为设备号
录制后查看视频大小和分辨率不一致。

**python 版本:** `python3.7`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:华为mate20

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
录屏默认会是一个正方形屏幕，这样无需横竖屏切换，处理起来更方便一些
