### ISSUE TITLE
想请问下怎么修改全局的图像识别阈值。

### ISSUE THREAD

**Issue by 1111111Aa** [AirtestProject/AirtestIDE#766]
我在用例里 用ST.threshold 写并不生效

from airtest.core.api import *
ST.threshold=0.6
using("search_common.air")
import search_common

search_common.enter_into_firstpage()

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/airtest_framework/1_script_settings/#threshold_1

除了assert_exists这个接口，其他的都适用
