### ISSUE TITLE
pycharm中编辑的内容无法同步到AirtestIDE

### ISSUE THREAD

**Issue by allenchen77** [AirtestProject/AirtestIDE#768]
在pycharm中编辑内容：
![image](https://user-images.githubusercontent.com/43990916/81888498-06eca980-95d4-11ea-9fe1-086251ae8407.png)

在airtestide中未更新：
![image](https://user-images.githubusercontent.com/43990916/81888514-0ce28a80-95d4-11ea-89bf-287d58e025c2.png)

**Comment by yimelia** [comment]
不要同时开两个进程写同一个文件。
如果文件发生改动，IDE会不断通知你是否更新文件，很麻烦的。
