### ISSUE TITLE
连不上手机

### ISSUE THREAD

**Issue by jianghanfen** [AirtestProject/AirtestIDE#769]
连不上手机，报错如截图。
还有怎么判断驱动安装与否？

**python 版本:** `python3.6.0`

**操作系统:** `Windows7 64bit`

 - 手机型号:vivo Y66
 - Android系统版本号: Android 6.0.1

 - AirtestIDE版本号：1.2.3

![image](https://user-images.githubusercontent.com/39332638/82023728-434a0380-96c1-11ea-97de-f38ae8127f89.png)
![image](https://user-images.githubusercontent.com/39332638/82024074-cf5c2b00-96c1-11ea-9fc1-568a0461a1af.png)

**Comment by yimelia** [comment]
ADB指令执行的时候出现问题，需要排查一下，有可能是受到了其他的ADB进程的干扰，可以先退掉你系统上所有“手机助手”类的软件（并且确认系统进程里都完全kill掉了），然后参考教程的这里排查一下：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#adb

**Comment by jianghanfen** [comment]
已解决，把一个后台360的进程杀掉，重新安装了下驱动就好了，多谢
