### ISSUE TITLE
我想自动关闭wifi，再打开wifi，该怎么做？

### ISSUE THREAD

**Issue by chadwi** [AirtestProject/AirtestIDE#77]
查看了airtest的api，似乎没有。或者说，我如何调用安卓系统api？

**Comment by Meteorix** [comment]
你可能需要使用`adb shell`来做这件事，在airtest里面直接用[`shell`函数](https://github.com/AirtestProject/Airtest/blob/edf903941afee29d74a957318e26058eae330732/airtest/core/api.py#L99)

**Comment by chadwi** [comment]
@Meteorix 我看到有Airtest/airtest/core/android/adb.py 模块，但是没有用法，在哪里有范例？

**Comment by Meteorix** [comment]
```
from airtest.core.api import *

# 直接用shell函数
shell("ls") 

# 或者取到adb对象使用
device().adb.shell("ls")
```
至于如何关闭wifi，Google一下~

**Comment by chadwi** [comment]
@Meteorix thank you
