### ISSUE TITLE
港版三星s4连不上

### ISSUE THREAD

**Issue by luochaof** [AirtestProject/AirtestIDE#771]
测试开发环境AirtestIDE使用问题

详细描述问题bug：
与电脑连接模式为MTP,打开了USB调试,允许模拟位置,允许未知来源
airtestIDE可以识别手机,但不能连接(点connect报错)

复现步骤：1.用数据线将电脑与手机连接;
2.安装三星官方驱动;
3.如上(bug描述)所述,进行相关设置;
4.打开airtestIDE,在"移动设备连接"选项下,点击"刷新ADB",点击connect

python 版本: python3.7

操作系统: Windows7 64bit

手机设备信息:

    手机型号:三星港版S4(GT-I9500)
    Android系统版本号: Android 4.4

    AirtestIDE版本号：v1.2.3

截屏
![图片](https://user-images.githubusercontent.com/62126211/82110334-1dc80300-9770-11ea-8c7a-fcf55466556d.png)
![图片](https://user-images.githubusercontent.com/62126211/82110357-494aed80-9770-11ea-83ca-881a0b5e24f2.png)

**Comment by yimelia** [comment]
android4.4有可能版本太低了导致不兼容，可以试一下勾选了use javacap和use adb orientation两个选项后，再点击connect看看能否连上

**Comment by luochaof** [comment]
没有这两个选项,应该不是系统版本低的问题,S4出厂自带的是4.2系统,应该是机型问题.
问题不大,现在应该很少有人用这么老的机子,刚好没丢就拿来试试,结果发现了这么一个bug,顺带提一下.没想到这么快就得到回复了,修复了效益也低,还好另一个手机运行正常.
