### ISSUE TITLE
pip 安装python airtest第三方库，报error:No matching distribution found for opencv-contrib-python<=3.4.2.17 (from airtest)

### ISSUE THREAD

**Issue by solar-ln** [AirtestProject/AirtestIDE#774]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
![image](https://user-images.githubusercontent.com/59274383/82190523-b652b480-9923-11ea-84e9-4c8f4216f2ac.png)

**复现步骤：**

**python 版本:** `python3.8.3`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
目前暂时还没有支持到python3.8
