### ISSUE TITLE
红米Note5连接不上

### ISSUE THREAD

**Issue by mhwang7758** [AirtestProject/AirtestIDE#775]
点击connect后黑屏一会后退出

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4

**Comment by mhwang7758** [comment]
> https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4

勾选后解决了，谢谢
