### ISSUE TITLE
Function addition || 功能附加

### ISSUE THREAD

**Issue by MVoikolesco** [AirtestProject/AirtestIDE#777]
Due to the need that arises at the moment, I request that, if possible, the function be added to switch between applications during the test.
Example: I am testing an android software, this software depends on some responses from a simulator (bench), to communicate with the bench we use a program on windows.
it would be so that during the test it was possible to make the program exit the android extension and open the program from the bench.

**Comment by yimelia** [comment]
I am not quite sure what you mean, but this code may help:

```
dev1 = connect_deivce("Android:///")
touch((x, y))  # touch android screen
dev2 = connect_device("Windows:///123456")  # connect to a windows handle
touch((x2, y2))  # touch windows (x2, y2)
set_current(0)  # set current device to dev1
touch((x3, y3))  # touch android screen (x3, y3)

print(G.DEVICE_LIST)  # you can see two devices in the G.DEVICE_LIST
set_current(1)  # set current device to windows
```

**Comment by MVoikolesco** [comment]
It would be for the test, to switch between two programs, the android that was running, and a windows software that communicates with a simulator machine.
Would your script do that?
