### ISSUE TITLE
测试报告图片不显示

### ISSUE THREAD

**Issue by Thetesthero** [AirtestProject/AirtestIDE#78]
ide执行完毕之后，查看测试包括，当中的图片没有显示加载出来
![default](https://user-images.githubusercontent.com/38424754/38977119-f48ce65c-43e5-11e8-9a1a-34e0fce98922.png)
![default](https://user-images.githubusercontent.com/38424754/38977134-02d38f40-43e6-11e8-88b7-61dc7e28f5a0.png)

**Comment by rockywhisper** [comment]
@Thetesthero  Hi, 你好。

我从官网正常下载IDE，完全按照你的文件路径和脚本路径操作，生成报告时的指令如下：
![image](https://user-images.githubusercontent.com/8188879/38997940-27ddc0fe-4421-11e8-9750-0ef93448a97f.png)
报告生成也正常.

如果方便的话，可以打开报告文件夹：
![image](https://user-images.githubusercontent.com/8188879/38998284-ce98957c-4421-11e8-9e65-9e178c25d3b8.png)
把里面的log.txt文件的内容也贴出来看看（顺便看一下这个文件夹里面有没有成功生成屏幕截图文件）

**Comment by rockywhisper** [comment]
@Thetesthero  似乎使用火狐浏览器、IE浏览器时都会遇到显示问题。使用Chrome浏览器正常。
我们修复下报告的浏览器兼容性。

**Comment by rockywhisper** [comment]
@Thetesthero  Hi，你好，我们今天推出了新版本，这个问题应该已经修复。

下载链接： http://airtest.netease.com/changelog.html
欢迎下载使用，如果有任何问题可以随时反馈哈，感谢 : )

**Comment by yimelia** [comment]
火狐浏览器的图片无法显示问题已经修复，将在0.1.7版本发布，之前应该是忽略了该问题。
