### ISSUE TITLE
OPPO R17 android10 运行python3脚本 uid 2000 does not have android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by suzeyinhappyboy** [AirtestProject/AirtestIDE#781]
**详细描述问题bug：**
bug描述：OPPO R17 android10手机，airtest 和pocoui已经更新，输入法设置为Yosemite，运行python3脚本后，没有安装poco-service.apk，报错
airtest.core.error.AdbShellError: stdout[b''] stderr[b'Security exception: uid 2000 does not have android.permission.WRITE_SECURE_SETTINGS.\n\njava.lang.SecurityException: uid 2000 does not have android.permission.WRITE_SECURE_SETTINGS.\n\tat android.app.ContextImpl.enforce(ContextImpl.java:1951)\n\tat android.app.ContextImpl.enforceCallingPermission(ContextImpl.java:1969)\n\tat com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl.lambda$onCommand$0$InputMethodManagerService$ShellCommandImpl(InputMethodManagerService.java:4834)\n\tat com.android.server.inputmethod.-$$Lambda$InputMethodManagerService$ShellCommandImpl$DbZq_GIUJWcuMsIpw_Jz5jVT2-Y.accept(Unknown Source:4)\n\tat java.util.Arrays$ArrayList.forEach(Arrays.java:3805)\n\tat com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:4834)\n\tat android.os.ShellCommand.exec(ShellCommand.java:104)\n\tat com.android.server.inputmethod.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:4808)\n\tat android.os.Binder.shellCommand(Binder.java:881)\n\tat android.os.Binder.onTransact(Binder.java:765)\n\tat com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:433)\n\tat com.android.server.inputmethod.InputMethodManagerService.onTransact(InputMethodManagerService.java:1619)\n\tat com.android.server.inputmethod.ColorInputMethodManagerService.onTransact(ColorInputMethodManagerService.java:85)\n\tat android.os.Binder.execTransactInternal(Binder.java:1021)\n\tat android.os.Binder.execTransact(Binder.java:994)\n']

**复现步骤：**
输入法设置为Yosemite，运行测试脚本

**python 版本:** `python3.7`

**操作系统:** `mac最新版`

**手机设备信息:**
 - 手机型号:OPPO R17
 - Android系统版本号: [e.g. Android 10]
 - (别的信息)

**其他相关信息补充**
- AirtestIDE版本号：1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
设置里有个“禁止监控权限”的选项，勾选上之后再试试看？

**Comment by suzeyinhappyboy** [comment]
@yimelia 大佬厉害，这么设置就可以了。但升级Airtest后，就会报错：
ERROR: setUpClass (myutils.EditBaseTestCase.EditBaseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ios_ci_4/Library/Python/3.7/lib/python/site-packages/airtest/cli/runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "/Users/ios_ci_4/Library/Python/3.7/lib/python/site-packages/airtest/cli/runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root, args.compress)
AttributeError: 'Namespace' object has no attribute 'compress'

解决方法：
多加一个参数
组装参数
args = Namespace(device=dev, log=log_path, recording=None, compress=10, script=path)

**Comment by yimelia** [comment]
这个是因为上个版本的airtest更新加了个参数，如果你自己用了自己的launcher.py的话，需要在入口那里额外再传一个compress参数进去，默认值可以填70，这个是图像的压缩程度，如果希望把图片压缩得更小一些，可以填10.

**Comment by arkilis** [comment]
> 禁止监控权限

这个在哪里可以选？感谢
