### ISSUE TITLE
执行脚本时获取分辨率概率性不正确（3/10）

### ISSUE THREAD

**Issue by lingdu618** [AirtestProject/AirtestIDE#782]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
执行脚本时，获取到的手机分辨率与实际不符合，手机屏幕下方的控件不显示出来
bug描述
在IDE执行或者命令行执行均会出现读取到的分辨率与实际不符，手机屏幕下方的控件不显示出来，使用的图片识别都会执行失败
**复现步骤：**
width,height=device().get_current_resolution()
height1 = G.DEVICE.display_info['height']
width1 = G.DEVICE.display_info['width']
print(width,height)
print(width1,height1)
start_pt=(width/3, height*0.01)
end_pt=(width/3, height*0.75)
start_pt1=(width/3, height*0.8)
end_pt1=(width/3, height*0.05)
start_pt2=(width/3, height*0.3)
end_pt2=(width/3, height*0.75)
swipe(start_pt, end_pt)
sleep(2.0)
swipe(start_pt, end_pt)
sleep(2.0)
poco(text="超级截屏").click()
sleep(2.0)

touch(Template(r"tpl1587527817473.png", record_pos=(-0.231, -0.87), resolution=(1080, 2340)))
sleep(2.0)
touch(Template(r"tpl1587527927847.png", record_pos=(0.158, 0.331), resolution=(1080, 2340)))

**python 版本:** `python3.6.5`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:自研机
 - Android系统版本号: [Android 10]
 - (别的信息)
分辨率：1080*2340

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
zhen整体执行时概率性获取分辨率不正确
![image](https://user-images.githubusercontent.com/20736381/83386867-54637600-a41e-11ea-92cf-92c0afc22486.png)
单独选中执行获取分辨率正常
![image](https://user-images.githubusercontent.com/20736381/83386950-7a891600-a41e-11ea-9b8e-870641f021c6.png)

**Comment by yimelia** [comment]
手机型号是什么？
在IDE和脚本连接运行时是否有勾选use javacap等选项？发一下运行时的命令行出来看看？
可以尝试勾选use adb orientation选项之后再试试看

**Comment by lingdu618** [comment]
在IDE和脚本连接运行时没有勾选use javacap use adb orientation选项，
勾选use javacap use adb orientation选项后运行了几次都正常了 
一定要勾选才行么

**Comment by yimelia** [comment]
use javacap不用勾，另外一个use adb orientation可以考虑勾选。
可以提供一下你的设备型号给我们试试看

**Comment by lingdu618** [comment]
是自研出海外的机器，国内市场没有卖的 所以提供型号也没用

**Comment by yimelia** [comment]
那就可能是默认的检测横竖屏的方法不兼容导致的问题，后面可以勾选了use adb orientation来使用
