### ISSUE TITLE
Switch between programs automatically

### ISSUE THREAD

**Issue by MVoikolesco** [AirtestProject/AirtestIDE#786]
Good Morning.
I would like to know how I can make during my tests Airtest switch between programs using the same script, in an automated way.
Hypothetical Description: I am testing a telephone software via OTG cable, at a certain moment I would need airtest to switch to a computer software, to perform a single thing that I would need to be done at this very moment in the computer program.
Hypothetical Example: the Phone Software communicates with a database that is on the computer, in a test step, I would need airtest to switch from the program that is running on the phone to a program that is running on the computer to press a button in that computer program, but I don't know how to do this.
Can someone help me with this

**Comment by yimelia** [comment]
I'm not sure you fully understand what you mean, can you provide sample code to help us understand?

https://github.com/AirtestProject/AirtestIDE/issues/777#issuecomment-634390936
