### ISSUE TITLE
airtest 命令行能否带自定义参数

### ISSUE THREAD

**Issue by chadwi** [AirtestProject/AirtestIDE#79]
> airtest report -h
usage: airtest report [-h] [--outfile OUTFILE] [--static_root STATIC_ROOT]
                      [--log_root LOG_ROOT] [--record RECORD [RECORD ...]]
                      [--export EXPORT] [--lang LANG]
                      script

看这意思，是不能自定义参数带入程序吗？

**Comment by chadwi** [comment]
@Meteorix 我想把 airtest 结合到 jinkins 上面，所以想从命令行传入参数

**Comment by Meteorix** [comment]
@chadwi 完全可以，参考刚刚那个代码。你可以继承``AirtestCase``来自定义运行环境，修改``argparser``来自定义命令行。

**Comment by chadwi** [comment]
@Meteorix 好的，我研究一下
