### ISSUE TITLE
airtest连接iOS手机UI渲染树没有展示出来

### ISSUE THREAD

**Issue by gghhy** [AirtestProject/AirtestIDE#798]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
已经安装了pocoui，连接上了iOS真机，Poco Assistant 选了iOS，没有展示出来渲染树（试过一个安卓真机，可以展示出来）
**复现步骤：**
连接上iOS真机，Poco Assistant 选了iOS，渲染树没有出来

**python 版本:** `python3.x`
python 3.7.3
**操作系统:** `Windows7 64bit`
MacBook Air (13-inch, 2017)  10.13.6
**手机设备信息:**
 - 手机型号:iphoneXR 10
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：
xcode  10.1
airtest  v1.2.0
**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/45389209/84477405-230e6400-acc2-11ea-921c-716c92084ea2.png)

**Comment by WindyTouch** [comment]
我也遇到了这个问题，不知道是不是windows版本还没支持iOS的UI渲染树么

**Comment by yimelia** [comment]
可是图里选的是cocos-js类型啊
