### ISSUE TITLE
Rename "Build Firebase APK" 

### ISSUE THREAD

**Issue by nakhbari** [AirtestProject/AirtestIDE#8]
The APK that is being build is not limited to Firebase. It is actually an Android Instrumentation APK.

Expected Behavior: Menu item name to be 
`Firebase` > `Build Instrumentation Test APK`
or 
`Android` > `Build Instrumentation Test APK`

**Comment by zzldjkzxf** [comment]
@nakhbari . The latest IDE, it was renamed the first selection.

**Comment by adolli** [comment]
In the future, this function maybe move to `Tools` > `Deployment` > `Bundle as instrumentation test APK`, as AirtestIDE is major on creating test scripts and FTL is one of the ways to run the test. Do u think so?

**Comment by nakhbari** [comment]
Tools > Deployment > Bundle as instrumentation test APK

Seems like a lot of menus to find this option. Is there other options other than `Bundle as instrumentation test APK`?

**Comment by adolli** [comment]
It is a bit deep for this menu action. To be fully compatible with AirtestIDE plugin system, we can make it simple for now. Such as `Plugins` > `Bundle as instrumentation test APK...`.

**Comment by nakhbari** [comment]
I have to create a recorded video for GDC and think we should stick to one location for this option. Can whichever option is decided upon be implemented in tomorrow's build. I need to get the recording submitted soon.

**Comment by adolli** [comment]
The menu will keep the same as in your slide in weeks. In the future updates, the menu may be moved. I can also emphasize it in the CHANGELOG.
