### ISSUE TITLE
AirtestIDE 有什么环境变量用来确定是在编辑器环境下吗？

### ISSUE THREAD

**Issue by chadwi** [AirtestProject/AirtestIDE#80]
AirtestIDE 有什么环境变量用来确定是在编辑器环境下 或 airtest 命令行模式下？
另外咱们有没有 QQ群可以交流？

**Comment by adolli** [comment]
目前没有专门设置这样的环境变量来区分编辑器环境还是命令行环境，但是可以通过 `sys.argv[0]` 来判断。欢迎加入qq群437119175 参与讨论、意见、灌水。

**Comment by Meteorix** [comment]
恩，这是一个好建议，我们可以加一个标志

**Comment by yimelia** [comment]
@chadwi 你好，在`2018-05-08`之后发布的版本将增加一个名为airtestEnv的环境变量，用于判断是否是在IDE环境下运行：

```
import os
if os.environ.get("airtestEnv") == "IDE":
    print("AirtestIDE")
```
仅当在IDE下运行时，环境变量中才会被设置这个值
