### ISSUE TITLE
macOS Big Sur 11.0下AirtestIDE无法启动

### ISSUE THREAD

**Issue by naodeng** [AirtestProject/AirtestIDE#807]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
            macOS Big Sur 11.0下AirtestIDE无法启动
**复现步骤：**
macOS Big Sur 11.0下AirtestIDE无法启动

**操作系统:** `macOS Big Sur 11.0`

- AirtestIDE版本号：1.2.3

**Comment by HBoPRC** [comment]
可以参考官方文档:[使用命令行启动](https://airtest.doc.io.netease.com/IDEdocs/getting_started/crash_abnormalProblem/#_1)
```bash
cd /Applications/AirtestIDE.app/Contents/MacOS
./AirtestIDE
```

**Comment by naodeng** [comment]
ok
