### ISSUE TITLE
Deeplinux下无法启动

### ISSUE THREAD

**Issue by Jinnrry** [AirtestProject/AirtestIDE#813]
**详细描述问题bug：**
AirtestIDE无法启动，在命令行运行后错误提示为：

```
(base) jiangwei@jiangwei-PC:/usr/lib$ ./AirtestIDE 
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : ['/home/jiangwei/.local/share/AirtestIDE/AirtestIDE/user.json']
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
/bin/sh: 1: system_profiler: not found
Info: filter not set, use raven.filter.FullPassFilter instead.
queue size is: 10
[1:1:0100/000000.655534:ERROR:broker_posix.cc(41)] Invalid node channel message
段错误

```

**复现步骤：**
1、在https://airtest.netease.com/ 下载ubuntu版本的deb包
2、sudo dpkg -i AirtestIDE_2020-01-21_py3_ubuntu16-04.deb
3、点击图标发现没有任何响应
4、使用./AirtestIDE 命令行启动

**python 版本:** `python3.7`

**操作系统:** `Deeplinux 15.11`

**其他相关信息补充**

- AirtestIDE版本号：`1.2.4`

**截屏**

**Comment by yimelia** [comment]
过往的IDE版本中，我们只提供了ubuntu16.04版本的包，只有ubuntu16.04的系统能够使用，其他版本的ubuntu、其他版本的linux无法保证可用性，因为我们无法一一测试市面上所有的linux发行版。

非常抱歉的是，由于linux下使用IDE的用户占比太少，加上维护linux版本需要额外的人力和资源的投入，我们在最新1.2.4之后的版本暂时也不再提供ubuntu的打包版，但不意味着linux下无法使用airtest：可以在其他平台上使用IDE写脚本，调试运行通过后，依然可以放到linux下用python环境运行。
