### ISSUE TITLE
按钮在屏幕外就直接点击导致报错，如何实现等按钮进入屏幕内再进行点击

### ISSUE THREAD

**Issue by 161CM** [AirtestProject/AirtestIDE#821]
按钮是会移到屏幕外，需要的时候自动移进来，做UI自动化时老是直接在屏幕外点击那个按钮导致报错了。用了exists()也不行，实在想不到其他方法来实现等按钮进入屏幕内再点击了
while True:
    time.sleep(2.0)
    if poco("WaitBtn").exists():
        break
poco("WaitBtn").click()

    **raise InvalidOperationException('Click position out of screen. pos={}'.format(repr(pos)))
poco.exceptions.InvalidOperationException: Click position out of screen. pos=[1.11280394, 0.6882359]**

**Comment by yimelia** [comment]
如果是特定的按钮会这样，可以判断一下按钮的位置是否在屏幕内
poco里是百分比坐标，猜测你发出来的这个`pos=[1.11280394, 0.6882359]`有个值大于1了，所以可能在屏幕外面了。

可以参考文档：https://poco.readthedocs.io/zh_CN/latest/source/doc/poco-example/play_with_coordinate_system_and_local_positioning.html#play-with-coordinate-system-and-local-positioning

**Comment by 161CM** [comment]
> 如果是特定的按钮会这样，可以判断一下按钮的位置是否在屏幕内
> poco里是百分比坐标，猜测你发出来的这个`pos=[1.11280394, 0.6882359]`有个值大于1了，所以可能在屏幕外面了。
> 
> 可以参考文档：https://poco.readthedocs.io/zh_CN/latest/source/doc/poco-example/play_with_coordinate_system_and_local_positioning.html#play-with-coordinate-system-and-local-positioning

解决了，感谢。
