### ISSUE TITLE
老是提示NameError: name xx is not defined

### ISSUE THREAD

**Issue by 161CM** [AirtestProject/AirtestIDE#823]
![NN0~B6_ WALHKBWZIRKBQZU](https://user-images.githubusercontent.com/45941730/88747653-d1427000-d181-11ea-854a-16cd27f9826b.png)

![$ O{F{TFZI8@2N5Z3J%2NBK](https://user-images.githubusercontent.com/45941730/88747744-018a0e80-d182-11ea-9726-d1d12fe58834.png)

**Comment by yimelia** [comment]
右键运行选中代码，就是真的只运行了选中的代码，没选中变量的初始化语句就没运行到
