### ISSUE TITLE
Unity的ugui界面使用poco的时候，如果按钮偏移，控件点击不准确，除非在（0，0）坐标

### ISSUE THREAD

**Issue by bingo423** [AirtestProject/AirtestIDE#824]
**详细描述问题bug：**
Unity的ugui界面使用poco的时候，如果按钮偏移，控件点击不准确，除非在（0，0）坐标

**复现步骤：**
创建一个ugui的button，挂载canvas下，简单实现以下点击效果；canvas的各种设置问题都一样，就不贴图了

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.5
-Unity版本号2018.4.12

**截屏**
![image](https://user-images.githubusercontent.com/6705839/89281458-b5a50100-d67c-11ea-9c92-a1faf8d78930.png)
![image](https://user-images.githubusercontent.com/6705839/89281482-bd64a580-d67c-11ea-8f08-b9ce6a9a6ef4.png)
![image](https://user-images.githubusercontent.com/6705839/89281493-c35a8680-d67c-11ea-97f0-18eb39a6ff65.png)

**Comment by bingo423** [comment]
经证实，是刘海屏的问题，测试设备是2200x1080，而游戏是根据1920x1080适配的，看看怎么配置能解决我的测试问题

**Comment by yimelia** [comment]
可以参考一下这个：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#3
