### ISSUE TITLE
点击无效

### ISSUE THREAD

**Issue by hanxinghen1992** [AirtestProject/AirtestIDE#825]
脚本运行没有报错，报告里也显示正常点击了，但实际上并没有进入到“游戏”这个选项里是怎么回事？
![QQ图片20200805132048](https://user-images.githubusercontent.com/69232430/89374617-7f1fc280-d71e-11ea-9b4a-1e61a008cb1d.png)

**Comment by yimelia** [comment]
windows由于一些权限、以及软件类型的限制，可能导致点击不一定生效。
可能的解决方案：
- 不用窗口嵌入，在设置里选无嵌入模式，然后再连接windows窗口
- IDE启动的时候注意选管理员身份启动，然后再运行脚本
