### ISSUE TITLE
pocoservice 崩溃问题

### ISSUE THREAD

**Issue by huluxin** [AirtestProject/AirtestIDE#826]
bug描述
 最近版本升级后在运行测试脚本时pocoservice 崩溃特别频繁，脚本还是原来脚本，现在总是出问题。
**复现步骤：**

**python 版本:** `python3.7.2`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:红米note 8
 - Android系统版本号: Android 9
- AirtestIDE版本号：1.2.5
**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
图一
![image](https://user-images.githubusercontent.com/196540/89758533-a14c8280-db1a-11ea-9462-92a316067e0b.png)
图二
![image](https://user-images.githubusercontent.com/196540/89761039-271efc80-db20-11ea-9fb9-edba6e00cea5.png)

**Comment by yimelia** [comment]
新版本的pocoservice和poco都没有任何改动，建议排查其他环境方面的原因
