### ISSUE TITLE
更新到1.2.4-1.2.5版本后 Run selected code 没反应，过段时间超时

### ISSUE THREAD

**Issue by 1987skywalker** [AirtestProject/AirtestIDE#838]
**详细描述问题bug：**
更新到1.2.5版本后 Run selected code
[DEBUG][Start debugging...]
没反应，然后超时。同样代码在1.2.3版本一直正常

**复现步骤：**
选中代码右击Run selected code

**python 版本:** `python3.x`

**操作系统:** `mac OS 10.14.6`

**手机设备信息:**
 - 手机型号:
 - iOS 12.4

**其他相关信息补充**
- AirtestIDE版本号：1.2.5

**Comment by yimelia** [comment]
我这里没有遇到类似问题，无法重现，请提供更多信息后再reopen此单
