### ISSUE TITLE
请问怎样才可以调用.py文件，然后运行调用的.py文件的代码

### ISSUE THREAD

**Issue by yebinhuang** [AirtestProject/AirtestIDE#839]
> 
如: 有4个文件
第一个文件：device.yaml
Android:
  platformName: Android
  deviceName: '127.0.0.1:7555'
  appPackage: 'com.tencent.mm' # apk包名
  appActivity: ''

----------------------------------

第二个文件：util.py(备注：封装驱动)
import yaml
from airtest.core.api import *
from page.main_page import MainPage

class App:
    config = yaml.safe_load(open('../config/device.yaml', 'r', encoding='utf-8'))['Android']

    @classmethod
    def start(cls):
        connect_device("Android://127.0.0.1:5037/{}".format(cls.config['deviceName']))
        start_app(cls.config["appPackage"])
        logger = logging.getLogger("airtest")
        logger.setLevel(logging.ERROR)
        return MainPage

    @ classmethod
    def quit(cls):
        time.sleep(5)
        start_app(cls.config["appPackage"])

---------------------------------------
第三个文件  test_page01.py
# 移动端
# -*- coding: utf-8 -*-
import unittest

from airtest.core.api import *

from page.test_util import App

class TestZhiXue(unittest.TestCase):

    @classmethod
    def setUpClass(cls) -> None:
        cls.main_page = App.start()
        print(cls.main_page)

    # stop_app('com.tencent.mm')
    @classmethod
    def tearDownClass(cls) -> None:
        pass

    # 注销，微信未认证认证
    def test_002(self):
        # 搜索框
        sleep(5)
        self.main_page.poco("com.tencent.mm:id/f8y").click()
        # 搜索输入框
        sleep()
        self.main_page.poco("com.tencent.mm:id/bhn").set_text("")
        # 搜索“xxx”
        self.main_page.poco("com.tencent.mm:id/bhn").set_text("xxx")
        # 点击xxx公众号
        self.main_page.poco("com.tencent.mm:id/gbv").click()
        # 调用注销
        from utils.app_utils import Utils
        Utils().user_cancel()--------调用文件4

-----------------------------
第四文件   app_utils.py

# 移动端
# -*- coding: utf-8 -*-
from airtest.core.api import *

from page.test_util import App

# 注销用户
class Utils:
    def __init__(self):
        self.poco = App.start()

    def user_cancel(self):
        # poco = Test().hhh()
        # 点击输入按钮
        self.poco.poco(wait("com.tencent.mm:id/aly")).click()
        # 输入“注销”
        self.poco.poco("com.tencent.mm:id/g78").click()
        text("注销")

**Comment by yimelia** [comment]
不清楚你想问什么，代码类问题可以自行调试解决
