### ISSUE TITLE
魅族 PRO7 PLUS 兼容问题

### ISSUE THREAD

**Issue by lazydao** [AirtestProject/AirtestIDE#84]
在运行报告中看到定位坐标是对的，但实际操作点击的时候点击的错误的位置（打开开发者选项里的“显示点按操作反馈”可确定）

**Comment by rockywhisper** [comment]
@lazydao  好的，我们查证下问题。

**Comment by rockywhisper** [comment]
@lazydao  你好，这台设备minitouch支持有点问题，给minitouch开发者提了 [issues](https://github.com/openstf/minitouch/issues/28) ，看起来是比较容易修复的。

可以暂时先换台设备测试，也可以使用 [Mumu模拟器](http://mumu.163.com/) 进行 [测试](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/3_emulator_connection.html#id3)

**Comment by rockywhisper** [comment]
@lazydao  Hi，minitouch开发者本周对 [issues](https://github.com/openstf/minitouch/issues/28) 进行了修复，AirtestIDE下个版本将会外放修改。（预计版本号：2018-5-8_16）
