### ISSUE TITLE
IDE是打包内置了一个airtest吗？

### ISSUE THREAD

**Issue by Dawnnnnnn** [AirtestProject/AirtestIDE#846]
**详细描述问题bug：**
我修改了AirtestIDE.exe同目录下的airtest文件夹中的api.py文件，但重启后好像没有生效，所以想问一下IDE是否使用的并不是同目录下的airtest？或者是我哪里的操作有问题吗？

如果是上面所说的情况，那么有什么方法更改IDE使用的airtest？

**操作系统:** `Windows10 64bit`

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#pythonexeairtestide
