### ISSUE TITLE
红米7A无法连接

### ISSUE THREAD

**Issue by ethahae** [AirtestProject/AirtestIDE#847]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
红米7A连接不上

**复现步骤：**
一部7A, 登录小米账号, 打开usb调试+usb安装+USB调试(安全设置), 在airtest里刷新出adb device时尝试连接

**python 版本:** `python2.7.10`

**操作系统:** `macOS Mojave 10.14.3 (18D109) 64bit`

**手机设备信息:**
 - 手机型号: 红米7A
 - Android系统版本号: [e.g. Android 9]
 - MIUI 11.0.6

**其他相关信息补充**
https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4 描述的内容已经开启
- AirtestIDE版本号：
v1.2.5
**截屏**
![image](https://user-images.githubusercontent.com/5284466/95875142-46e2d300-0da4-11eb-97ff-c4050e2d5638.png)
![image](https://user-images.githubusercontent.com/5284466/95875676-d8524500-0da4-11eb-91cf-a9dfc665352e.png)
![image](https://user-images.githubusercontent.com/5284466/95875684-dbe5cc00-0da4-11eb-8194-572afb2781aa.png)

logs:

/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 wait-for-device
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell getprop ro.build.version.sdk
Device:002a68340207 updated <airtest.core.android.android.Android object at 0x13173af98> -> <airtest.core.android.android.Android object at 0x131744d68>
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell ls /data/local/tmp/minicap
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell ls /data/local/tmp/minicap.so
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
version:6
skip install minicap
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell dumpsys window displays
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell pm path jp.co.cyberagent.stf.rotationwatcher
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-S6Qq_6FBgSa3p7EDzisUrw==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell dumpsys window windows
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 forward --no-rebind tcp:15390 localabstract:minicap_15390
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 002a68340207 shell dumpsys window displays
Failed to execute ADB commands, please read [Docs](https://airtest.doc.io.netease.com/en/IDEdocs/device_connection/2_android_faq/)

**Comment by yimelia** [comment]
尝试勾选use javacap之后再连接试试

**Comment by ethahae** [comment]
勾选 use javacap后解决(会装一个叫yosemite的app)
能说明一下
javacap, adb oxxxxxx ,adb  touch 的区别吗, 我没看到文档哪里有讲, 谢谢
