### ISSUE TITLE
使用install()方法进行安装时，没法处理MIUI安装确认弹窗事件，导致安装失败。

### ISSUE THREAD

**Issue by ElesG** [AirtestProject/AirtestIDE#85]
使用install()方法进行安装时，没法处理MIUI安装确认弹窗事件，导致安装失败。
MIUI使用adb安装apk的时候，会弹出一个是否确认安装的弹窗，本来想通过捕获并点击的方式去兼容这个确认安装的弹窗，但是发现在执行过程中，需要等到install()执行返回结果才能执行下一个点击操作，那么就会导致执行过程里面出现安装确认弹窗时无法绕过的现象。
![image](https://user-images.githubusercontent.com/7394262/39114651-0c2f7246-4712-11e8-898e-9f8260b82465.png)

希望能够在install()方法添加一些方法，可以捕捉处理这类系统弹窗的。

**Comment by Meteorix** [comment]
@ElesG 这个由于各家安卓系统的定制太多了，不太好统一处理，你先自行用脚本处理吧，比如：
```

device().adb.push("xxx.apk", "/data/local/tmp/")
proc = device().adb.start_cmd("pm install /data/local/tmp/xxx.apk")

###  用airtest处理弹框
# touch("弹框")

proc.wait()

```

另外这个是airtest的问题，可以提到airtest的issue里  ：)

**Comment by chadwi** [comment]
@ElesG 这是手机设置的问题，关闭 安装提示，百度一下

**Comment by ElesG** [comment]
@Meteorix 试了一下，发现用`start_cmd()`这个方法没法执行`pm install /data/local/tmp/xxx.apk`这个命令，拉起安装的弹窗，但是log中没有显示报错。直接在终端执行`adb shell pm install /data/local/tmp/xxx.apk`是会唤起安装弹窗的。是我的实现方法有问题吗？在手机上是确定有对应的包的。

**Comment by Meteorix** [comment]
oh，应该用`start_shell`

这两个函数返回的是subprocess.Popen对象，可以 `proc.communicate()`看看stdout/stderr

**Comment by ElesG** [comment]
@chadwi 恩恩，这也是一个方法，我担心不是每个系统能够这样关闭弹窗，所以还是想了解下如果遇到无法绕过的弹窗怎么解决。

**Comment by ElesG** [comment]
@Meteorix 对的！得到了解决~谢谢大佬！
