### ISSUE TITLE
unity项目接入后（UGUI项目），大部分界面下，Poco辅助窗UI渲染树刷新频繁（每秒刷新1次），导致选不中某个UI控件

### ISSUE THREAD

**Issue by sa96102088** [AirtestProject/AirtestIDE#858]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

(重要！根据问题类型选择分类)
 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
*测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
unity项目接入后（UGUI项目），大部分界面下Poco辅助窗UI渲染树刷新频繁（每秒刷新1次），导致选不中某个UI控件。我不清楚是我们项目本身的问题还是其他问题。（难道是UGUI一直在进行rebuild类似的操作？）这种刷新频繁的界面难道是动态的UI特效导致的？
**复现步骤：**
就正常游戏链接IDE后，点击Poco辅助窗的unity选项，UI渲染树出现了信息后，从登陆界面进入游戏后，就一直频繁刷新渲染树。

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - 华为mate10 ALP-AL00: [Android 8.1]

**其他相关信息补充**
- AirtestIDE版本号：v1.2.6

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![111111](https://user-images.githubusercontent.com/29347146/98226390-eb65c880-1f90-11eb-909d-498a34faff2c.png)
![111111111](https://user-images.githubusercontent.com/29347146/98226395-ed2f8c00-1f90-11eb-8075-3f2511c947d6.png)

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/record_script/3_poco_assistant/#31
可以点最左边的锁定按钮临时锁定UI树
