### ISSUE TITLE
ADB Status 一直为 unauthorized，无法连接

### ISSUE THREAD

**Issue by qq8954321a** [AirtestProject/AirtestIDE#870]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述：ADB Status 一直为 unauthorized，无法连接

**复现步骤：**
插入了vivo oppo 的手机，status 直接显示 unauthorized，点击connect无反应无法连接

**python 版本: python3.7

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:vivo z3x
 - Android系统版本号:  Android 9
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.2

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/50578947/100495372-130e1200-3186-11eb-9a22-b6652083644d.png)

**Comment by yimelia** [comment]
要先在手机上面点同意才可以用ADB连
