### ISSUE TITLE
AirtestIDE软件启动不成功

### ISSUE THREAD

**Issue by toli2020** [AirtestProject/AirtestIDE#871]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
AirtestIDE软件启动不成功

**复现步骤：**
1.双击，AirtestIDE.exe 或 兼容模式启动.bat。
2.cmd，运行AirtestIDE.exe 或 兼容模式启动.bat。

**python 版本:**
 python3.6.7

**操作系统:** 
Windows7 64bit

**手机设备信息:**
和手机无关。多个测试手机在其他电脑可以链接成功，在我的电脑打不开IDE

**其他相关信息补充**
(在其他笔记本电脑上运行异常 。)
特此说明：之前是能打开IDE，在IDE界面里识别不到手机（怀疑此问题和我的电脑或系统有关）。
然后就百度一通，安装了dxwebsetup.exe   DirectX。结果搞大了，现在连IDE也打不开了。

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/75239664/100578089-847fc900-331c-11eb-9f0e-73020317c1a2.png)
![image](https://user-images.githubusercontent.com/75239664/100578108-8c3f6d80-331c-11eb-8316-6351db94d068.png)

**Comment by fishfish-yu** [comment]
1.更新电脑显卡
2.尝试使用兼容模式启动
3.尝试删除loading config.....目录下的json文件，再重启IDE
