### ISSUE TITLE
MI 10 连接后，没有显示device screen 界面

### ISSUE THREAD

**Issue by wanglinfen** [AirtestProject/AirtestIDE#879]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
1. 设备显示在移动设备连接列表，点击connect按钮，log 查看窗没有日志
2. MI 10 连接后，等了很久，没有显示device screen 界面

**复现步骤：**
step1.  电脑通过USB 连接小米10， 移动设备连接列表显示设备device状态
step2. 点击connect 按钮

**手机设备信息:**
 - 手机型号:  mi 10

- AirtestIDE版本号：v1.2.6

**截屏**
![image](https://user-images.githubusercontent.com/48945663/102441404-2ada0700-405d-11eb-84e1-e739877f041e.png)

**Comment by yimelia** [comment]
勾选use javacap
