### ISSUE TITLE
Multiple Instrumentation Tests

### ISSUE THREAD

**Issue by nakhbari** [AirtestProject/AirtestIDE#9]
Right now creating a single test works well. If I wanted to create a test for scenario A and another for scenario B, I would have to create a new Instrumentation test for each of these scripts.

Possible Solution:
Allow for users to select the scripts they want to include in the Android Instrumentation APK. This way a user can include multiple tests in their APK.

In the test APK we can run these multiple scripts using the @Parameterized annotation. This will create a new test case for each script and we can perform a cleanup after each script is complete.

**Comment by adolli** [comment]
I am considering to integrate multiple testcases under unittest framework.

**Comment by zzldjkzxf** [comment]
@nakhbari .  It's difficult to add a instrument test function dynamically.  But we can run multiple scripts on python layer. Now I add a new button below the Firebase Menu.  User can add multiple scripts into test APK and these scripts would be ran orderly. Every script would have report respecIively. But these scripts would be ran in one instrument test  function. It's ok?

**Comment by nakhbari** [comment]
Sure we can do this for now.
I think we can add separate instrumentation tests dynamically fairly easily. I have done this before. Let me send you an email.

**Comment by zzldjkzxf** [comment]
@nakhbari.  On the latest IDE, we can build multiple scripts. And I test it on FTL, it seems that worked well. You can try it, or let Fang have a try and give some advices to us.
