### ISSUE TITLE
三星S8+链接成功后，通过IDE点击错位

### ISSUE THREAD

**Issue by Enderyu** [AirtestProject/AirtestIDE#90]
三星S8+链接成功后，通过IDE点击错位

**Comment by rockywhisper** [comment]
@Enderyu  有截图吗，是否画面显示不全？  [可以把分辨率设置为WQHD](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id7)

**Comment by rockywhisper** [comment]
@Enderyu 这个issues暂时关闭了哈，有问题随时联系。
