### ISSUE TITLE
自定义函数添加@logwrap后，报错TypeError: can't pickle mappingproxy objects

### ISSUE THREAD

**Issue by zjnshu** [AirtestProject/AirtestIDE#903]
* 测试开发环境问题（本软件）

**详细描述问题bug：**
bug描述：自定义方法添加@logwrap后，报错TypeError: can't pickle mappingproxy objects
想要在测试报告中记录自定义函数中使用的参数（图片），自定义函数添加@logwrap后，报错TypeError: can't pickle mappingproxy objects

**python 版本:** `python3.6`

**操作系统:** `Windows10 64bit`

**截屏**
![image](https://user-images.githubusercontent.com/26788872/107003756-40032480-67c8-11eb-81da-a6ad27fffdb1.png)
![image](https://user-images.githubusercontent.com/26788872/107004019-9f613480-67c8-11eb-9d71-4f65701d5d98.png)

![image](https://user-images.githubusercontent.com/26788872/107003975-8f495500-67c8-11eb-9db4-5e5d97b5e33e.png)

**Comment by yimelia** [comment]
猜测是因为你的参数对象不是一个普通的对象，是你自己定义的，所以需要额外再做一下处理才能让它成为一个能够被`json.dump`的对象。参考一下airtest文件夹里的`logwraper.py`文件，里面有一个`_dumper`就是做了这件事，需要对它进行一些扩展。
