### ISSUE TITLE
打包测试Apk报错：NotADirectoryError: [WinError 267] 目录名称无效

### ISSUE THREAD

**Issue by cjh0613** [AirtestProject/AirtestIDE#904]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* - [x] 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述：

**复现步骤：**使用管理员身份运行`AirtestIDE`，新建`.py`纯 Python（高级用户），代码可以正常运行，放置于`E:\\GitHub\\python-cs\\20210204\\airtest\\cs.py`，使用`Firebase`菜单的`打包测试Apk`，进度条卡住并报错：

```
Traceback (most recent call last):
  File "plugins/firebase_plugin\build.py", line 99, in run
  File "plugins/firebase_plugin\build.py", line 65, in copy_files
  File "shutil.py", line 315, in copytree
NotADirectoryError: [WinError 267] 目录名称无效。: 'E:\\GitHub\\python-cs\\20210204\\airtest\\cs.py'
```

**python 版本:** `python3.8`，安装于`C:\Program Files (x86)\Python38-32`

**操作系统:** `Windows10 64bit`

不涉及：

```
**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)
```

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.6

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/25498029/107305548-26aaf280-6abe-11eb-9c18-33ee0da509c0.png)

**Comment by cjh0613** [comment]
？

**Comment by yimelia** [comment]
这个功能不完善，未来我们将从IDE中移除
