### ISSUE TITLE
在windows7系统中无法打开IDE，cmd窗口总提示“Failed to create D3D shaders”

### ISSUE THREAD

**Issue by ElesG** [AirtestProject/AirtestIDE#91]
环境参数：
windows 7 64位
已安装python2.7.9

安装版本：0.0.14

报错日志：
![image](https://user-images.githubusercontent.com/7394262/39234153-0a136e7e-48a5-11e8-881d-5977b42644d4.png)

**Comment by rockywhisper** [comment]
@ElesG  你好，在FAQ中有对应的 [解决方案](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/1_ide_crash.html#id3) 哈.

**Comment by ElesG** [comment]
@rockywhisper 非常感谢！

**Comment by rockywhisper** [comment]
@ElesG  这个issues先关闭了哈~    :-)
