### ISSUE TITLE
Airtest升级到1.2.8后，连接安卓手机后，devices窗口未能渲染出手机画面。

### ISSUE THREAD

**Issue by Octzxx** [AirtestProject/AirtestIDE#915]
**详细描述问题bug：**
Airtest升级到1.2.8后，连接安卓手机后，devices窗口未能渲染出手机画面（经过vivo和小米手机尝试，都无法显示手机画面，升级前版本=1.2.6，手机画面渲染正常）

**复现步骤：**
前置条件（现有一个airtest1.2.6）
1.从现有版本升级到1.2.8版本
2.打开devices窗口，点击connect，窗口无反应
3.查看log窗口，无日志更新
4.查看UI渲染树，可以看到对应内容
5.再次点击connect，窗口短暂渲染出手机画面后，立即消失

**python 版本:** `python3.8.5`

**操作系统:** `MacOS 10.15.7`

**手机设备信息:**
 - 手机型号:vivo X30
 - Android系统版本号:  Android 10
 - (别的信息)

**其他相关信息补充**
ps:录屏文件过大无法上传，详情看图片。
- AirtestIDE版本号：1.2.8

**截屏**
![image](https://user-images.githubusercontent.com/79882050/109579698-605aa080-7b34-11eb-8158-5ace0305de4f.png)

**Comment by Octzxx** [comment]
![image](https://user-images.githubusercontent.com/79882050/109580735-0ce95200-7b36-11eb-81c8-bca8a2a5553a.png)

**Comment by yimelia** [comment]
手机型号是什么？

**Comment by Octzxx** [comment]
hello，我觉得这个和手机型号是不是没啥关系。我把那个连接手机的时候那个黑屏兼容那个选项取消勾选后，就好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yimelia"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午2:13
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;; 
抄送: "Apollo"<958937672@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AirtestProject/AirtestIDE] Airtest升级到1.2.8后，连接安卓手机后，devices窗口未能渲染出手机画面。 (#915)





 
手机型号是什么？

**Comment by yimelia** [comment]
正常情况下不需要勾选选项，直接连手机即可
但是我们想看一下是什么型号手机有这种勾选了反而连不上的问题

**Comment by Octzxx** [comment]
好滴，我这是vivo X30，红米K30都有这个现象。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yimelia"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午2:28
收件人: "AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;; 
抄送: "Apollo"<958937672@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AirtestProject/AirtestIDE] Airtest升级到1.2.8后，连接安卓手机后，devices窗口未能渲染出手机画面。 (#915)





 
正常情况下不需要勾选选项，直接连手机即可
 但是我们想看一下是什么型号手机有这种勾选了反而连不上的问题
