### ISSUE TITLE
希望Linux平台的支持

### ISSUE THREAD

**Issue by lizaifang** [AirtestProject/AirtestIDE#92]

**Comment by Meteorix** [comment]
是希望在linux桌面上测试Android？还是测试linux桌面软件？

**Comment by lizaifang** [comment]
是希望这个IDE能在Linux桌面上能用，测试Android就可以了。放出个版本

**Comment by Meteorix** [comment]
![image](https://user-images.githubusercontent.com/3805278/39283384-891363a0-4940-11e8-9863-8226fd0a1fe3.png)

我们正在搞这个~目前用py3+qt5搞了个版本，正在解决打包问题，可能要晚些时候才会放出

**Comment by lizaifang** [comment]
好的，很期待， 谢谢你们的努力

**Comment by kigkrazy** [comment]
谢谢你们的努力

**Comment by rockywhisper** [comment]
@lizaifang @kigkrazy  Hi，我们今天推出了新版本，其中包括Ubuntu16.04安装包。

下载链接： http://airtest.netease.com/changelog.html
欢迎下载使用，如果有任何问题可以随时反馈哈，感谢 : )
