### ISSUE TITLE
自定义Python版本支持 3.9.2

### ISSUE THREAD

**Issue by TinyZzh** [AirtestProject/AirtestIDE#927]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

1. 设置python版本为3.9.2
2. 启动脚本报错 No module named 'airtest'

**python 版本:** `python3.x`

python版本为3.9.2

**操作系统:** `Windows7 64bit`

win 10

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/5763397/113082388-f1dd3100-920c-11eb-96e9-c0019fd593cc.png)

![image](https://user-images.githubusercontent.com/5763397/113082452-11745980-920d-11eb-8c69-0dd8e882771f.png)

**Comment by yimelia** [comment]
需要在你本地环境中安装，见 https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#python

**Comment by TinyZzh** [comment]
本地环境安装之后。numpy版本降低到1.19，导致vs code代码补全功能失效了。
