### ISSUE TITLE
软件界面工作不正常

### ISSUE THREAD

**Issue by ZhongMin044** [AirtestProject/AirtestIDE#93]
版本：0.0.14。问题主要有：1）设备窗口悬浮时会变很大，而且还不能缩小；2）设备窗口如果在其它窗口并列，设备窗口也太大，导致脚本编辑窗口只有一小条。想调整中间的窗口分割线，该分割线无法拖动；

**Comment by rockywhisper** [comment]
@ZhongMin044  Hi，看到你的界面相关的问题。  :grinning:  
- **关于设备窗口缩放：**
    - 连接 移动设备/模拟器 时，设备窗是可以自由缩放大小的 ；
    - 嵌入Windows窗口时，目前窗口嵌入后是固定大小的（出于图像识别的测试方案考虑），所以嵌入前请将窗口缩放到合适大小，否则可能挤压其他功能窗口。

- **调节中间窗口分割线异常：**
    - 仍是嵌入窗口固定大小的设定导致的，建议嵌入前适当缩小窗口。

**Comment by rockywhisper** [comment]
@ZhongMin044  Hi，v0.0.15版本中，“选项”-“设置”:
![image](https://user-images.githubusercontent.com/8188879/39612548-0d9db8b6-4f93-11e8-9f10-68354391817f.png)

然后进行窗口选定时，就可以不执行嵌入进行脚本录制运行了。

**Comment by ZhongMin044** [comment]
Very good.

Thanks.
