### ISSUE TITLE
我修改了AirTest的api.py代码，请问怎样在IDE中调用它？

### ISSUE THREAD

**Issue by Using1174** [AirtestProject/AirtestIDE#94]
我在`cv.py`和`api.py`内添加了`KEEP_CAPTURE()`方法，将截图保存在内存，希望多次`exist`判断时能够优化效率，而不是每次都去手机上截图获取。
但是，修改的源代码无法使用IDE加载，运行时会报“KEEP_CAPTURE()”没有定义的错误，请问我要怎么修改才能让IDE识别新增加的方法呢？

**Comment by adolli** [comment]
你可以把你定义的`KEEP_CAPTURE`方法卸载脚本文件里

**Comment by Using1174** [comment]
实现这个`KEEP_CAPTURE`方法需要修改`cv.py`文件里的`loop_find`的机制，我没有办法在外部实现。

**Comment by adolli** [comment]
IDE里内置了airtest模块，要换成你自定义的模块的话，在设置面板里，将你的自定义airtest的路径加到sys.path那一栏。 以下代码可验证airtest模块是否替换成功
```python
import airtest
print(airtest)
```

**Comment by Using1174** [comment]
![image](https://user-images.githubusercontent.com/16488261/39423839-6d90368a-4ca6-11e8-99cd-c69d8740da9e.png)

![image](https://user-images.githubusercontent.com/16488261/39423823-5c85591a-4ca6-11e8-86cf-e65a2db700fe.png)
请问是这样吗？

**Comment by adolli** [comment]
试试路径里的斜杠双写。我拉一个专业的人过来解答这个问题。 @rockywhisper

**Comment by Using1174** [comment]
我试了双斜杠，也不行

**Comment by adolli** [comment]
那麻烦稍等下负责这个模块的人来解答了

**Comment by yimelia** [comment]
目前应该暂时还没办法在IDE里面修改airtest的引用，只能改poco的，想要使用自己的airtest暂时只能用命令行运行的方式来使用，我们后续会尽快出一个解决方案来解决这个问题

**Comment by Using1174** [comment]
好，那等更新再用了。
