### ISSUE TITLE
连接ios设备时提示Error connecting to device: No such file or directory，需要重新构建wda到设备上(设备上有wda)

### ISSUE THREAD

**Issue by Im-coco** [AirtestProject/AirtestIDE#942]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
wda连接ios设备时提示：Error connecting to device: No such file or directory

**复现步骤：**
通过xcode product->test ,wda到ios设备上后（当前xcode运行中），iproxy 转发端口后，ios设备可以连接到电脑，
断开ios设备连接再重新连接时提示【Error connecting to device: No such file or directory】，需再次用xocde 重新product->test后才可连接

**python 版本:** `python3.8`

**操作系统:** `macos 10.15.7`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)
iphone 7 ios 12.3（多个版本都试过）

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.9

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![image](https://user-images.githubusercontent.com/55836395/116983042-2f494880-acfc-11eb-8d9b-15e418b73905.png)

**Comment by yimelia** [comment]
是的，必须保持xcode连接才可以

**Comment by Im-coco** [comment]
好的谢谢
