### ISSUE TITLE
请问有计划iOS会支持swipe_along这个方法吗？

### ISSUE THREAD

**Issue by rtp1236** [AirtestProject/AirtestIDE#943]
请问有计划iOS会支持swipe_along这个方法吗？
请问有计划iOS会支持swipe_along这个方法吗？
请问有计划iOS会支持swipe_along这个方法吗？

**Comment by yimelia** [comment]
如果后续wda那边开放了相关接口的话，我们会想办法加上，目前是没有

**Comment by rtp1236** [comment]
> 如果后续wda那边开放了相关接口的话，我们会想办法加上，目前是没有

再请问一下，iOS现在swipe最多支持三个坐标点，后续有计划多加几个坐标点么?项目里有个画圆的控件,iOS目前没办法实现...
