### ISSUE TITLE
Connected to the window in non-embedded mode

### ISSUE THREAD

**Issue by xiaokai521** [AirtestProject/AirtestIDE#953]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述:
连接windows窗口提示Connected to the window in non-embedded mode，试了很多窗口都如此
![image](https://user-images.githubusercontent.com/84714145/119338307-6d65d680-bcc2-11eb-9140-f5e9a97c9154.png)

**复现步骤：**

**python 版本:** `python3.x&python2 都有装`

**操作系统:** `Windows10 64bit`

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.9

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by Captain-yan** [comment]
我也是同样问题，windows7就正常使用

**Comment by yimelia** [comment]
这是我们专门提供的无嵌入模式的功能， 这是正常的提示
https://airtest.doc.io.netease.com/IDEdocs/3.2device_connection/5_windows_connection/
