### ISSUE TITLE
Memory 會一直上升

### ISSUE THREAD

**Issue by ayumi760405** [AirtestProject/AirtestIDE#955]
bug描述:

AirtestIDE 打開未使用下Memory 使用量會一直上升

<img width="825" alt="截圖 2021-05-27 下午6 58 31" src="https://user-images.githubusercontent.com/28735340/119815552-43a8eb80-bf1e-11eb-84c4-466db0267a9e.png">

**python 版本:** `python3.8`

**操作系统:** `MacOS Big Sur (11.2.3（20D91）)`

- AirtestIDE版本号： 1.2.9

<img width="486" alt="截圖 2021-05-27 下午7 00 53" src="https://user-images.githubusercontent.com/28735340/119815699-676c3180-bf1e-11eb-9240-174e06361f68.png">

**Comment by ayumi760405** [comment]
放置一個晚上後增長到30GB
<img width="841" alt="截圖 2021-05-28 上午9 17 22" src="https://user-images.githubusercontent.com/28735340/119915648-8954cb00-bf95-11eb-8181-13b2aa5d34c6.png">

**Comment by yimelia** [comment]
抱歉，这是一个比较严重的BUG，在手机直接拔掉USB线后会导致这个问题，我们目前已经修复，但是希望能跟其他的修改一起外放，所以暂时还没有发布新版本，最近一段时间可能要先注意不做这样的操作，非常抱歉

**Comment by ayumi760405** [comment]
好的, 謝謝
