### ISSUE TITLE
如何连接ios

### ISSUE THREAD

**Issue by wangwencheng888** [AirtestProject/AirtestIDE#96]
看到新版本上有连接ios APP connection 了，但是如何操作连接上去呢就一个空白的输入框看不明白啊

**Comment by rockywhisper** [comment]
@wangwencheng888   你好，可以参考下 [iOS连接文档](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/1_quick_start/5_ios_connection.html)
