### ISSUE TITLE
IOS手机如何切换设备

### ISSUE THREAD

**Issue by duyongchao1234** [AirtestProject/AirtestIDE#960]
![{91B487E6-6056-479A-CC48-15BCFD6BE697}](https://user-images.githubusercontent.com/59679136/121285086-5bb23f00-c910-11eb-9172-a721237d9bf7.jpg)
可以看出用set_current函数并没有切换苹果手机

**Comment by yimelia** [comment]
并看不出任何问题。
你把同一个LIST打印了两遍。

**Comment by duyongchao1234** [comment]
已经解决了谢谢
