### ISSUE TITLE
华为手机连接成功，不能调用adb命令

### ISSUE THREAD

**Issue by feixu88** [AirtestProject/AirtestIDE#969]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
IDE连接手机成功，也能执行操作的touch等命令
执行adb 命令报错,错误代码
[15:18:05][DEBUG]<airtest.core.android.adb> D:\tools\Python3.7\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 6HJ4C19927016561 shell ls
Traceback (most recent call last):
  File "D:\tools\Python3.7\lib\site-packages\airtest\core\android\adb.py", line 374, in shell
    out = self.raw_shell(cmd)
  File "D:\tools\Python3.7\lib\site-packages\airtest\core\android\adb.py", line 332, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "D:\tools\Python3.7\lib\site-packages\airtest\core\android\adb.py", line 197, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b'3rdmodem\r\n3rdmodemnvm\r\n3rdmodemnvmbkp\r\nacct\r\napex\r\nbin\r\nbugreports\r\ncache\r\nconfig\r\ncust\r\nd\r\ndata\r\ndebug_ramdisk\r\ndefault.prop\r\ndev\r\neng\r\netc\r\nhw_product\r\nlog\r\nmnt\r\nodm\r\noem\r\npatch_hw\r\npreas\r\npreavs\r\npreload\r\nprets\r\npretvs\r\nproc\r\nproduct\r\nproduct_services\r\nres\r\nsbin\r\nsdcard\r\nsplash2\r\nstorage\r\nsys\r\nsystem\r\nvendor\r\nversion\r\n'] stderr[b'ls: ./fstab.zram1024m: Permission denied\r\nls: ./fstab.zram1280m: Permission denied\r\nls: ./fstab.zram1536m: Permission denied\r\nls: ./fstab.zram2240m: Permission denied\r\nls: ./fstab.zram256m: Permission denied\r\nls: ./fstab.zram2800m: Permission denied\r\nls: ./fstab.zram4096m: Permission denied\r\nls: ./fstab.zram512m: Permission denied\r\nls: ./fstab.zram6144m: Permission denied\r\nls: ./fstab.zram768m: Permission denied\r\nls: ./fstab.zram8192m: Permission denied\r\nls: ./init: Permission denied\r\nls: ./init.environ.rc: Permission denied\r\nls: ./init.mygote64.rc: Permission denied\r\nls: ./init.rc: Permission denied\r\nls: ./init.usb.configfs.rc: Permission denied\r\nls: ./init.usb.rc: Permission denied\r\nls: ./init.zygote32.rc: Permission denied\r\nls: ./init.zygote64_32.rc: Permission denied\r\nls: ./metadata: Permission denied\r\nls: ./modem_log: Permission denied\r\nls: ./resetFactory.cfg: Permission denied\r\nls: ./sec_storage: Permission denied\r\nls: ./ueventd.rc: Permission denied\r\nls: ./verity_key: Permission denied\r\n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\WorkSpace\WeakNetwork\run.py", line 16, in <module>
    shell("ls")
  File "D:\tools\Python3.7\lib\site-packages\airtest\utils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "D:\tools\Python3.7\lib\site-packages\airtest\core\api.py", line 167, in shell
    return G.DEVICE.shell(cmd)
  File "D:\tools\Python3.7\lib\site-packages\airtest\core\android\android.py", line 309, in shell
    return self.adb.shell(*args, **kwargs)
  File "D:\tools\Python3.7\lib\site-packages\airtest\core\android\adb.py", line 376, in shell
    raise AdbShellError(err.stdout, err.stderr)
airtest.core.error.AdbShellError: stdout[b'3rdmodem\r\n3rdmodemnvm\r\n3rdmodemnvmbkp\r\nacct\r\napex\r\nbin\r\nbugreports\r\ncache\r\nconfig\r\ncust\r\nd\r\ndata\r\ndebug_ramdisk\r\ndefault.prop\r\ndev\r\neng\r\netc\r\nhw_product\r\nlog\r\nmnt\r\nodm\r\noem\r\npatch_hw\r\npreas\r\npreavs\r\npreload\r\nprets\r\npretvs\r\nproc\r\nproduct\r\nproduct_services\r\nres\r\nsbin\r\nsdcard\r\nsplash2\r\nstorage\r\nsys\r\nsystem\r\nvendor\r\nversion\r\n'] stderr[b'ls: ./fstab.zram1024m: Permission denied\r\nls: ./fstab.zram1280m: Permission denied\r\nls: ./fstab.zram1536m: Permission denied\r\nls: ./fstab.zram2240m: Permission denied\r\nls: ./fstab.zram256m: Permission denied\r\nls: ./fstab.zram2800m: Permission denied\r\nls: ./fstab.zram4096m: Permission denied\r\nls: ./fstab.zram512m: Permission denied\r\nls: ./fstab.zram6144m: Permission denied\r\nls: ./fstab.zram768m: Permission denied\r\nls: ./fstab.zram8192m: Permission denied\r\nls: ./init: Permission denied\r\nls: ./init.environ.rc: Permission denied\r\nls: ./init.mygote64.rc: Permission denied\r\nls: ./init.rc: Permission denied\r\nls: ./init.usb.configfs.rc: Permission denied\r\nls: ./init.usb.rc: Permission denied\r\nls: ./init.zygote32.rc: Permission denied\r\nls: ./init.zygote64_32.rc: Permission denied\r\nls: ./metadata: Permission denied\r\nls: ./modem_log: Permission denied\r\nls: ./resetFactory.cfg: Permission denied\r\nls: ./sec_storage: Permission denied\r\nls: ./ueventd.rc: Permission denied\r\nls: ./verity_key: Permission denied\r\n']
[Finished]
华为手机的三个权限都开了
1.输入法设置中，取消安全输入
2.开发者选项->监控ADB安装应用取消，打开仅充电模式下允许调试
3.权限监控->设置->自动配置权限

**复现步骤：**

**python 版本:** `python3.7`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:华为 nova 5pro
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
![image](https://user-images.githubusercontent.com/86401869/123222113-30c80d80-d502-11eb-83fb-91d85eddd622.png)

**Comment by markhuang3310** [comment]
指令有執行成功只是回傳值不為 0. (adb shell 使用者的權限無法訪問部分資料夾)
可以改善的方向
1. 給使用者帶入 check_return_code 參數決定是否檢查 return code
2. 回傳 return code 與 stdout, stderr 給使用者決定處理方式

WAR:
可以將 shell("ls") 替換為
```
cmd = "ls"
def war_shell():
    proc = G.DEVICE.start_cmd(cmd)
    stdout, stderr = proc.communicate()
    stdout = stdout.decode("utf-8")
    stderr = stderr.decode("utf-8")
    return proc.returncode, stdout, stderr 

war_shell("ls")
```
