### ISSUE TITLE
请问为什么无法设置“wait”函数里面的一些参数？

### ISSUE THREAD

**Issue by plzplx** [AirtestProject/AirtestIDE#99]
![qq 20180508102943](https://user-images.githubusercontent.com/39073765/39734643-cff46b3e-52aa-11e8-8a3b-ebcdbf799124.png)
![qq 20180508103030](https://user-images.githubusercontent.com/39073765/39734645-d11825a0-52aa-11e8-8e10-e52b8a3eff78.png)

**Comment by rockywhisper** [comment]
@plzplx 只是没有显示出来提示词，但是可用的哈，可以试验一下。

**Comment by plzplx** [comment]
![qq 20180508104847](https://user-images.githubusercontent.com/39073765/39735252-5d312062-52ad-11e8-9101-75d619e3480d.png)
请问这个的意思是不是查找“系统应用”，每1秒查找一次，10秒后找不到则执行touch“文件管理器”；

![qq 20180508105207](https://user-images.githubusercontent.com/39073765/39735367-d9ac2f38-52ad-11e8-8ae1-6cf143cab53c.png)
为什么执行脚本的时候会先去执行touch“文件管理器”呢？

**Comment by plzplx** [comment]
@rockywhisper Hi

**Comment by yimelia** [comment]
@plzplx 不是的，intervalfunc的作用是“当一次查找不成功后，尝试执行这个intervalfunc”，而不是查找10秒失败后才执行它。

以及直接写 intervalfunc=touch() 这样是不行的，应该直接把对应的func作为参数传给它，而不是直接传一整个语句，举个例子可以这样写：

```
def test():
    touch(图片)
wait(图片, timeout=10, intervalfunc=test)
```

**Comment by plzplx** [comment]
@yimelia 感谢解惑。
