### ISSUE TITLE
1.2.11版本连接安卓手机后，点击到APP登录页面时会自动断开连接

### ISSUE THREAD

**Issue by FantasticJiang** [AirtestProject/AirtestIDE#999]
**bug描述**
1.2.11版本AirtestIDE连接**安卓手机**后，在淘宝、天猫、闲鱼、京东等（目前发现）APP的测试过程中，点到**登录页面**时会自动断开连接。
目前发现存在问题的机型有：小米10S，一加9R

**复现步骤：**
1. AirtestIDE连接小米10S
2. 打开淘宝（未登录状态）
3. 点击底部菜单栏的“消息”（未登录状态点击“消息”会自动跳转到登录）

**python 版本:** `python3.7.8`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号: 小米10S  MIUI 12.5.7稳定版、一加9R ColorOS 11.2
 - Android系统版本号: Android 11

**Comment by wangdayecoding** [comment]
小米10页发现了，也是1.2.11版

**Comment by yimelia** [comment]
关掉手机的安全键盘（或安全输入）选项后再试试
